// Code generated by tools/bindgen. DO NOT EDIT.
//
// Source: MacOSX26.2.sdk (Xcode 26.2), target arm64-apple-macos26.0
// Frameworks: Foundation, UserNotifications
//
// Regenerate with: tools/bindgen/regen.sh

//go:build darwin

package usernotifications

// UNAuthorizationOptions is the ObjC enum UNAuthorizationOptions (unsigned long).
type UNAuthorizationOptions uint

const (
	UNAuthorizationOptionBadge                           UNAuthorizationOptions = 1
	UNAuthorizationOptionSound                           UNAuthorizationOptions = 2
	UNAuthorizationOptionAlert                           UNAuthorizationOptions = 4
	UNAuthorizationOptionCarPlay                         UNAuthorizationOptions = 8
	UNAuthorizationOptionCriticalAlert                   UNAuthorizationOptions = 16
	UNAuthorizationOptionProvidesAppNotificationSettings UNAuthorizationOptions = 32
	UNAuthorizationOptionProvisional                     UNAuthorizationOptions = 64
	UNAuthorizationOptionAnnouncement                    UNAuthorizationOptions = 128
	UNAuthorizationOptionTimeSensitive                   UNAuthorizationOptions = 256
)

// UNAuthorizationStatus is the ObjC enum UNAuthorizationStatus (long).
type UNAuthorizationStatus int

const (
	UNAuthorizationStatusNotDetermined UNAuthorizationStatus = 0
	UNAuthorizationStatusDenied        UNAuthorizationStatus = 1
	UNAuthorizationStatusAuthorized    UNAuthorizationStatus = 2
	UNAuthorizationStatusProvisional   UNAuthorizationStatus = 3
	UNAuthorizationStatusEphemeral     UNAuthorizationStatus = 4
)

// UNNotificationPresentationOptions is the ObjC enum UNNotificationPresentationOptions (unsigned long).
type UNNotificationPresentationOptions uint

const (
	UNNotificationPresentationOptionBadge  UNNotificationPresentationOptions = 1
	UNNotificationPresentationOptionSound  UNNotificationPresentationOptions = 2
	UNNotificationPresentationOptionAlert  UNNotificationPresentationOptions = 4
	UNNotificationPresentationOptionList   UNNotificationPresentationOptions = 8
	UNNotificationPresentationOptionBanner UNNotificationPresentationOptions = 16
)
