// Code generated by tools/bindgen. DO NOT EDIT.
//
// Source: MacOSX26.2.sdk (Xcode 26.2), target arm64-apple-macos26.0
// Frameworks: Foundation, UserNotifications
//
// Regenerate with: tools/bindgen/regen.sh

//go:build darwin

package usernotifications

import "github.com/ebitengine/purego/objc"

// NSDate an opaque handle for the ObjC class NSDate (NSObject subclass).
// Only the identity crosses: no method of NSDate is on the allowlist.
type NSDate struct{ objc.ID }

// NSDateClass is the class object of NSDate.
type NSDateClass struct{ objc.Class }

// GetNSDateClass looks the class up in the ObjC runtime.
func GetNSDateClass() NSDateClass { return NSDateClass{objc.GetClass("NSDate")} }
