// Code generated by tools/bindgen. DO NOT EDIT.
//
// Source: MacOSX26.2.sdk (Xcode 26.2), target arm64-apple-macos26.0
// Frameworks: Foundation, UserNotifications
//
// Regenerate with: tools/bindgen/regen.sh

//go:build darwin

package usernotifications

import "github.com/ebitengine/purego/objc"

// NSSet an opaque handle for the ObjC class NSSet (NSObject subclass).
// Only the identity crosses: no method of NSSet is on the allowlist.
type NSSet struct{ objc.ID }

// NSSetClass is the class object of NSSet.
type NSSetClass struct{ objc.Class }

// GetNSSetClass looks the class up in the ObjC runtime.
func GetNSSetClass() NSSetClass { return NSSetClass{objc.GetClass("NSSet")} }
