// Code generated by tools/bindgen. DO NOT EDIT.
//
// Source: MacOSX26.2.sdk (Xcode 26.2), target arm64-apple-macos26.0
// Frameworks: Foundation, UserNotifications
//
// Regenerate with: tools/bindgen/regen.sh

//go:build darwin

package usernotifications

import "github.com/ebitengine/purego/objc"

// Selectors, registered once at package init.
var (
	selActionIdentifier                                    = objc.RegisterName("actionIdentifier")
	selAddNotificationRequestWithCompletionHandler         = objc.RegisterName("addNotificationRequest:withCompletionHandler:")
	selAlloc                                               = objc.RegisterName("alloc")
	selAttachments                                         = objc.RegisterName("attachments")
	selAuthorizationStatus                                 = objc.RegisterName("authorizationStatus")
	selBody                                                = objc.RegisterName("body")
	selCategoryIdentifier                                  = objc.RegisterName("categoryIdentifier")
	selContent                                             = objc.RegisterName("content")
	selContentByUpdatingWithProviderError                  = objc.RegisterName("contentByUpdatingWithProvider:error:")
	selCurrentNotificationCenter                           = objc.RegisterName("currentNotificationCenter")
	selDate                                                = objc.RegisterName("date")
	selDelegate                                            = objc.RegisterName("delegate")
	selFilterCriteria                                      = objc.RegisterName("filterCriteria")
	selGetDeliveredNotificationsWithCompletionHandler      = objc.RegisterName("getDeliveredNotificationsWithCompletionHandler:")
	selGetNotificationCategoriesWithCompletionHandler      = objc.RegisterName("getNotificationCategoriesWithCompletionHandler:")
	selGetNotificationSettingsWithCompletionHandler        = objc.RegisterName("getNotificationSettingsWithCompletionHandler:")
	selGetPendingNotificationRequestsWithCompletionHandler = objc.RegisterName("getPendingNotificationRequestsWithCompletionHandler:")
	selIdentifier                                          = objc.RegisterName("identifier")
	selLaunchImageName                                     = objc.RegisterName("launchImageName")
	selNotification                                        = objc.RegisterName("notification")
	selProvidesAppNotificationSettings                     = objc.RegisterName("providesAppNotificationSettings")
	selRelevanceScore                                      = objc.RegisterName("relevanceScore")
	selRemoveAllDeliveredNotifications                     = objc.RegisterName("removeAllDeliveredNotifications")
	selRemoveAllPendingNotificationRequests                = objc.RegisterName("removeAllPendingNotificationRequests")
	selRemoveDeliveredNotificationsWithIdentifiers         = objc.RegisterName("removeDeliveredNotificationsWithIdentifiers:")
	selRemovePendingNotificationRequestsWithIdentifiers    = objc.RegisterName("removePendingNotificationRequestsWithIdentifiers:")
	selRequest                                             = objc.RegisterName("request")
	selRequestAuthorizationWithOptionsCompletionHandler    = objc.RegisterName("requestAuthorizationWithOptions:completionHandler:")
	selRequestWithIdentifierContentTrigger                 = objc.RegisterName("requestWithIdentifier:content:trigger:")
	selSetAttachments                                      = objc.RegisterName("setAttachments:")
	selSetBadgeCountWithCompletionHandler                  = objc.RegisterName("setBadgeCount:withCompletionHandler:")
	selSetBody                                             = objc.RegisterName("setBody:")
	selSetCategoryIdentifier                               = objc.RegisterName("setCategoryIdentifier:")
	selSetDelegate                                         = objc.RegisterName("setDelegate:")
	selSetFilterCriteria                                   = objc.RegisterName("setFilterCriteria:")
	selSetLaunchImageName                                  = objc.RegisterName("setLaunchImageName:")
	selSetNotificationCategories                           = objc.RegisterName("setNotificationCategories:")
	selSetRelevanceScore                                   = objc.RegisterName("setRelevanceScore:")
	selSetSound                                            = objc.RegisterName("setSound:")
	selSetSubtitle                                         = objc.RegisterName("setSubtitle:")
	selSetSummaryArgument                                  = objc.RegisterName("setSummaryArgument:")
	selSetSummaryArgumentCount                             = objc.RegisterName("setSummaryArgumentCount:")
	selSetTargetContentIdentifier                          = objc.RegisterName("setTargetContentIdentifier:")
	selSetThreadIdentifier                                 = objc.RegisterName("setThreadIdentifier:")
	selSetTitle                                            = objc.RegisterName("setTitle:")
	selSetUserInfo                                         = objc.RegisterName("setUserInfo:")
	selSound                                               = objc.RegisterName("sound")
	selSubtitle                                            = objc.RegisterName("subtitle")
	selSummaryArgument                                     = objc.RegisterName("summaryArgument")
	selSummaryArgumentCount                                = objc.RegisterName("summaryArgumentCount")
	selSupportsContentExtensions                           = objc.RegisterName("supportsContentExtensions")
	selTargetContentIdentifier                             = objc.RegisterName("targetContentIdentifier")
	selThreadIdentifier                                    = objc.RegisterName("threadIdentifier")
	selTitle                                               = objc.RegisterName("title")
	selTrigger                                             = objc.RegisterName("trigger")
	selUserInfo                                            = objc.RegisterName("userInfo")
)
