// Code generated by tools/bindgen. DO NOT EDIT.
//
// Source: MacOSX26.2.sdk (Xcode 26.2), target arm64-apple-macos26.0
// Frameworks: Foundation, UserNotifications
//
// Regenerate with: tools/bindgen/regen.sh

//go:build darwin

package usernotifications

import "github.com/ebitengine/purego/objc"

// UNNotification wraps the ObjC class UNNotification (NSObject subclass).
type UNNotification struct{ objc.ID }

// UNNotificationClass is the class object of UNNotification.
type UNNotificationClass struct{ objc.Class }

// GetUNNotificationClass looks the class up in the ObjC runtime.
func GetUNNotificationClass() UNNotificationClass {
	return UNNotificationClass{objc.GetClass("UNNotification")}
}

// Alloc allocates an uninitialized UNNotification (-[NSObject alloc]).
func (c UNNotificationClass) Alloc() UNNotification {
	return UNNotification{objc.ID(c.Class).Send(selAlloc)}
}

// Date reads the UNNotification property date.
func (o UNNotification) Date() NSDate {
	return NSDate{o.ID.Send(selDate)}
}

// Request reads the UNNotification property request.
func (o UNNotification) Request() UNNotificationRequest {
	return UNNotificationRequest{o.ID.Send(selRequest)}
}
