// Code generated by tools/bindgen. DO NOT EDIT.
//
// Source: MacOSX26.2.sdk (Xcode 26.2), target arm64-apple-macos26.0
// Frameworks: Foundation, UserNotifications
//
// Regenerate with: tools/bindgen/regen.sh

//go:build darwin

package usernotifications

import (
	"github.com/adriaanm/wata/go-pkgs/appleptt/objcrt"
	"github.com/ebitengine/purego/objc"
)

// UNNotificationContent wraps the ObjC class UNNotificationContent (NSObject subclass).
type UNNotificationContent struct{ objc.ID }

// UNNotificationContentClass is the class object of UNNotificationContent.
type UNNotificationContentClass struct{ objc.Class }

// GetUNNotificationContentClass looks the class up in the ObjC runtime.
func GetUNNotificationContentClass() UNNotificationContentClass {
	return UNNotificationContentClass{objc.GetClass("UNNotificationContent")}
}

// Alloc allocates an uninitialized UNNotificationContent (-[NSObject alloc]).
func (c UNNotificationContentClass) Alloc() UNNotificationContent {
	return UNNotificationContent{objc.ID(c.Class).Send(selAlloc)}
}

// Attachments reads the UNNotificationContent property attachments.
func (o UNNotificationContent) Attachments() NSArray {
	return NSArray{o.ID.Send(selAttachments)}
}

// Body reads the UNNotificationContent property body.
func (o UNNotificationContent) Body() string {
	return objcrt.GoString(o.ID.Send(selBody))
}

// CategoryIdentifier reads the UNNotificationContent property categoryIdentifier.
func (o UNNotificationContent) CategoryIdentifier() string {
	return objcrt.GoString(o.ID.Send(selCategoryIdentifier))
}

// FilterCriteria reads the UNNotificationContent property filterCriteria.
func (o UNNotificationContent) FilterCriteria() string {
	return objcrt.GoString(o.ID.Send(selFilterCriteria))
}

// LaunchImageName reads the UNNotificationContent property launchImageName.
func (o UNNotificationContent) LaunchImageName() string {
	return objcrt.GoString(o.ID.Send(selLaunchImageName))
}

// RelevanceScore reads the UNNotificationContent property relevanceScore.
func (o UNNotificationContent) RelevanceScore() float64 {
	return objc.Send[float64](o.ID, selRelevanceScore)
}

// Sound reads the UNNotificationContent property sound.
func (o UNNotificationContent) Sound() UNNotificationSound {
	return UNNotificationSound{o.ID.Send(selSound)}
}

// Subtitle reads the UNNotificationContent property subtitle.
func (o UNNotificationContent) Subtitle() string {
	return objcrt.GoString(o.ID.Send(selSubtitle))
}

// SummaryArgument — The argument to be inserted in the summary for this notification.
func (o UNNotificationContent) SummaryArgument() string {
	return objcrt.GoString(o.ID.Send(selSummaryArgument))
}

// SummaryArgumentCount — A number that indicates how many items in the summary are represented in the summary.
// For example if a podcast app sends one notification for 3 new episodes in a show,
// the argument should be the name of the show and the count should be 3.
// Default is 1 and cannot be 0.
func (o UNNotificationContent) SummaryArgumentCount() uint {
	return objc.Send[uint](o.ID, selSummaryArgumentCount)
}

// TargetContentIdentifier reads the UNNotificationContent property targetContentIdentifier.
func (o UNNotificationContent) TargetContentIdentifier() string {
	return objcrt.GoString(o.ID.Send(selTargetContentIdentifier))
}

// ThreadIdentifier reads the UNNotificationContent property threadIdentifier.
func (o UNNotificationContent) ThreadIdentifier() string {
	return objcrt.GoString(o.ID.Send(selThreadIdentifier))
}

// Title reads the UNNotificationContent property title.
func (o UNNotificationContent) Title() string {
	return objcrt.GoString(o.ID.Send(selTitle))
}

// UserInfo reads the UNNotificationContent property userInfo.
func (o UNNotificationContent) UserInfo() NSDictionary {
	return NSDictionary{o.ID.Send(selUserInfo)}
}

// ContentByUpdatingWithProviderError — Contextualizes your UNNotificationContent object with other Apple SDK objects conforming to UNNotificationContentProviding. This will specialize the notification and decorate its look and behavior accordingly. For example, the notification will be treated as a message with an avatar and be promoted to the top of notification center if the object passed in is a valid INSendMessageIntent<UNNotificationContentProviding>. This throws an error with a UNErrorCode found in UNError.h if the UNNotificationContentProviding object is invalid. A valid UNNotificationContent result should not be mutated and be passed directly to UNUserNotificationCenter.
// This should be called in the UNNotificationServiceExtension in didReceiveNotificationRequest:withContentHandler: and the returned UNNotificationContent should be passed to the contentHandler for incoming push notifications.
func (o UNNotificationContent) ContentByUpdatingWithProviderError(provider objc.ID) (UNNotificationContent, error) {
	var errOut objcrt.ErrOut
	ret := o.ID.Send(selContentByUpdatingWithProviderError, provider, errOut.Ptr())
	return UNNotificationContent{ret}, errOut.Err()
}
