// Code generated by tools/bindgen. DO NOT EDIT.
//
// Source: MacOSX26.2.sdk (Xcode 26.2), target arm64-apple-macos26.0
// Frameworks: Foundation, UserNotifications
//
// Regenerate with: tools/bindgen/regen.sh

//go:build darwin

package usernotifications

import "github.com/ebitengine/purego/objc"

// UNNotificationAttachment an opaque handle for the ObjC class UNNotificationAttachment (NSObject subclass).
// Only the identity crosses: no method of UNNotificationAttachment is on the allowlist.
type UNNotificationAttachment struct{ objc.ID }

// UNNotificationAttachmentClass is the class object of UNNotificationAttachment.
type UNNotificationAttachmentClass struct{ objc.Class }

// GetUNNotificationAttachmentClass looks the class up in the ObjC runtime.
func GetUNNotificationAttachmentClass() UNNotificationAttachmentClass {
	return UNNotificationAttachmentClass{objc.GetClass("UNNotificationAttachment")}
}
