// Code generated by tools/bindgen. DO NOT EDIT.
//
// Source: MacOSX26.2.sdk (Xcode 26.2), target arm64-apple-macos26.0
// Frameworks: Foundation, UserNotifications
//
// Regenerate with: tools/bindgen/regen.sh

//go:build darwin

package usernotifications

import (
	"github.com/adriaanm/wata/go-pkgs/appleptt/objcrt"
	"github.com/ebitengine/purego/objc"
)

// UNUserNotificationCenter wraps the ObjC class UNUserNotificationCenter (NSObject subclass).
type UNUserNotificationCenter struct{ objc.ID }

// UNUserNotificationCenterClass is the class object of UNUserNotificationCenter.
type UNUserNotificationCenterClass struct{ objc.Class }

// GetUNUserNotificationCenterClass looks the class up in the ObjC runtime.
func GetUNUserNotificationCenterClass() UNUserNotificationCenterClass {
	return UNUserNotificationCenterClass{objc.GetClass("UNUserNotificationCenter")}
}

// Alloc allocates an uninitialized UNUserNotificationCenter (-[NSObject alloc]).
func (c UNUserNotificationCenterClass) Alloc() UNUserNotificationCenter {
	return UNUserNotificationCenter{objc.ID(c.Class).Send(selAlloc)}
}

// Delegate reads the UNUserNotificationCenter property delegate.
func (o UNUserNotificationCenter) Delegate() objc.ID {
	return o.ID.Send(selDelegate)
}

// SetDelegate writes the UNUserNotificationCenter property delegate.
func (o UNUserNotificationCenter) SetDelegate(v objc.ID) {
	o.ID.Send(selSetDelegate, v)
}

// SupportsContentExtensions reads the UNUserNotificationCenter property supportsContentExtensions.
func (o UNUserNotificationCenter) SupportsContentExtensions() bool {
	return objc.Send[bool](o.ID, selSupportsContentExtensions)
}

// AddNotificationRequestWithCompletionHandler calls -[UNUserNotificationCenter addNotificationRequest:withCompletionHandler:].
func (o UNUserNotificationCenter) AddNotificationRequestWithCompletionHandler(request UNNotificationRequest, completionHandler func(error)) {
	blockCompletionHandler := objc.NewBlock(func(_ objc.Block, a0 objc.ID) {
		completionHandler(objcrt.GoError(a0))
	})
	defer blockCompletionHandler.Release()
	o.ID.Send(selAddNotificationRequestWithCompletionHandler, request.ID, blockCompletionHandler)
}

// GetDeliveredNotificationsWithCompletionHandler calls -[UNUserNotificationCenter getDeliveredNotificationsWithCompletionHandler:].
func (o UNUserNotificationCenter) GetDeliveredNotificationsWithCompletionHandler(completionHandler func(NSArray)) {
	blockCompletionHandler := objc.NewBlock(func(_ objc.Block, a0 objc.ID) {
		completionHandler(NSArray{a0})
	})
	defer blockCompletionHandler.Release()
	o.ID.Send(selGetDeliveredNotificationsWithCompletionHandler, blockCompletionHandler)
}

// GetNotificationCategoriesWithCompletionHandler calls -[UNUserNotificationCenter getNotificationCategoriesWithCompletionHandler:].
func (o UNUserNotificationCenter) GetNotificationCategoriesWithCompletionHandler(completionHandler func(NSSet)) {
	blockCompletionHandler := objc.NewBlock(func(_ objc.Block, a0 objc.ID) {
		completionHandler(NSSet{a0})
	})
	defer blockCompletionHandler.Release()
	o.ID.Send(selGetNotificationCategoriesWithCompletionHandler, blockCompletionHandler)
}

// GetNotificationSettingsWithCompletionHandler calls -[UNUserNotificationCenter getNotificationSettingsWithCompletionHandler:].
func (o UNUserNotificationCenter) GetNotificationSettingsWithCompletionHandler(completionHandler func(UNNotificationSettings)) {
	blockCompletionHandler := objc.NewBlock(func(_ objc.Block, a0 objc.ID) {
		completionHandler(UNNotificationSettings{a0})
	})
	defer blockCompletionHandler.Release()
	o.ID.Send(selGetNotificationSettingsWithCompletionHandler, blockCompletionHandler)
}

// GetPendingNotificationRequestsWithCompletionHandler calls -[UNUserNotificationCenter getPendingNotificationRequestsWithCompletionHandler:].
func (o UNUserNotificationCenter) GetPendingNotificationRequestsWithCompletionHandler(completionHandler func(NSArray)) {
	blockCompletionHandler := objc.NewBlock(func(_ objc.Block, a0 objc.ID) {
		completionHandler(NSArray{a0})
	})
	defer blockCompletionHandler.Release()
	o.ID.Send(selGetPendingNotificationRequestsWithCompletionHandler, blockCompletionHandler)
}

// RemoveAllDeliveredNotifications calls -[UNUserNotificationCenter removeAllDeliveredNotifications].
func (o UNUserNotificationCenter) RemoveAllDeliveredNotifications() {
	o.ID.Send(selRemoveAllDeliveredNotifications)
}

// RemoveAllPendingNotificationRequests calls -[UNUserNotificationCenter removeAllPendingNotificationRequests].
func (o UNUserNotificationCenter) RemoveAllPendingNotificationRequests() {
	o.ID.Send(selRemoveAllPendingNotificationRequests)
}

// RemoveDeliveredNotificationsWithIdentifiers calls -[UNUserNotificationCenter removeDeliveredNotificationsWithIdentifiers:].
func (o UNUserNotificationCenter) RemoveDeliveredNotificationsWithIdentifiers(identifiers NSArray) {
	o.ID.Send(selRemoveDeliveredNotificationsWithIdentifiers, identifiers.ID)
}

// RemovePendingNotificationRequestsWithIdentifiers calls -[UNUserNotificationCenter removePendingNotificationRequestsWithIdentifiers:].
func (o UNUserNotificationCenter) RemovePendingNotificationRequestsWithIdentifiers(identifiers NSArray) {
	o.ID.Send(selRemovePendingNotificationRequestsWithIdentifiers, identifiers.ID)
}

// RequestAuthorizationWithOptionsCompletionHandler calls -[UNUserNotificationCenter requestAuthorizationWithOptions:completionHandler:].
func (o UNUserNotificationCenter) RequestAuthorizationWithOptionsCompletionHandler(options UNAuthorizationOptions, completionHandler func(bool, error)) {
	blockCompletionHandler := objc.NewBlock(func(_ objc.Block, a0 bool, a1 objc.ID) {
		completionHandler(a0, objcrt.GoError(a1))
	})
	defer blockCompletionHandler.Release()
	o.ID.Send(selRequestAuthorizationWithOptionsCompletionHandler, uint(options), blockCompletionHandler)
}

// SetBadgeCountWithCompletionHandler calls -[UNUserNotificationCenter setBadgeCount:withCompletionHandler:].
func (o UNUserNotificationCenter) SetBadgeCountWithCompletionHandler(newBadgeCount int, completionHandler func(error)) {
	blockCompletionHandler := objc.NewBlock(func(_ objc.Block, a0 objc.ID) {
		completionHandler(objcrt.GoError(a0))
	})
	defer blockCompletionHandler.Release()
	o.ID.Send(selSetBadgeCountWithCompletionHandler, newBadgeCount, blockCompletionHandler)
}

// SetNotificationCategories calls -[UNUserNotificationCenter setNotificationCategories:].
func (o UNUserNotificationCenter) SetNotificationCategories(categories NSSet) {
	o.ID.Send(selSetNotificationCategories, categories.ID)
}

// CurrentNotificationCenter calls +[UNUserNotificationCenter currentNotificationCenter].
func (c UNUserNotificationCenterClass) CurrentNotificationCenter() UNUserNotificationCenter {
	return UNUserNotificationCenter{objc.ID(c.Class).Send(selCurrentNotificationCenter)}
}
