// Code generated by tools/bindgen. DO NOT EDIT.
//
// Source: tools/bindgen/fixtures
//
// Regenerate with: tools/bindgen/regen.sh

//go:build darwin

package fixture

import "github.com/ebitengine/purego/objc"

// Selectors, registered once at package init.
var (
	selAlloc          = objc.RegisterName("alloc")
	selBoxAt          = objc.RegisterName("boxAt:")
	selContentSize    = objc.RegisterName("contentSize")
	selRangeOfSize    = objc.RegisterName("rangeOfSize:")
	selSetContentSize = objc.RegisterName("setContentSize:")
)
