// Code generated by tools/bindgen. DO NOT EDIT.
//
// Source: tools/bindgen/fixtures
//
// Regenerate with: tools/bindgen/regen.sh

//go:build darwin

package fixture

import "github.com/ebitengine/purego/objc"

// WFGeom wraps the ObjC class WFGeom (NSObject subclass).
type WFGeom struct{ objc.ID }

// WFGeomClass is the class object of WFGeom.
type WFGeomClass struct{ objc.Class }

// GetWFGeomClass looks the class up in the ObjC runtime.
func GetWFGeomClass() WFGeomClass { return WFGeomClass{objc.GetClass("WFGeom")} }

// Alloc allocates an uninitialized WFGeom (-[NSObject alloc]).
func (c WFGeomClass) Alloc() WFGeom { return WFGeom{objc.ID(c.Class).Send(selAlloc)} }

// ContentSize — A struct-valued read/write property.
func (o WFGeom) ContentSize() WFSize {
	return objc.Send[WFSize](o.ID, selContentSize)
}

// SetContentSize writes the WFGeom property contentSize.
func (o WFGeom) SetContentSize(v WFSize) {
	o.ID.Send(selSetContentSize, v)
}

// BoxAt — A nested struct returned by value (24 bytes: indirect on arm64).
func (o WFGeom) BoxAt(index uint) WFBox {
	return objc.Send[WFBox](o.ID, selBoxAt, index)
}

// RangeOfSize — A struct argument and a struct return.
func (o WFGeom) RangeOfSize(size WFSize) WFRange {
	return objc.Send[WFRange](o.ID, selRangeOfSize, size)
}
