// Code generated by tools/bindgen. DO NOT EDIT.
//
// Source: MacOSX26.2.sdk (Xcode 26.2), target arm64-apple-macos26.0
// Frameworks: Foundation, AVFAudio
//
// Regenerate with: tools/bindgen/regen.sh

//go:build darwin

package avfaudio

import (
	"github.com/adriaanm/wata/go-pkgs/appleptt/objcrt"
	"github.com/ebitengine/purego/objc"
)

// AVAudioNode wraps the ObjC class AVAudioNode (NSObject subclass).
type AVAudioNode struct{ objc.ID }

// AVAudioNodeClass is the class object of AVAudioNode.
type AVAudioNodeClass struct{ objc.Class }

// GetAVAudioNodeClass looks the class up in the ObjC runtime.
func GetAVAudioNodeClass() AVAudioNodeClass { return AVAudioNodeClass{objc.GetClass("AVAudioNode")} }

// Alloc allocates an uninitialized AVAudioNode (-[NSObject alloc]).
func (c AVAudioNodeClass) Alloc() AVAudioNode { return AVAudioNode{objc.ID(c.Class).Send(selAlloc)} }

// Engine reads the AVAudioNode property engine.
func (o AVAudioNode) Engine() AVAudioEngine {
	return AVAudioEngine{o.ID.Send(selEngine)}
}

// LastRenderTime reads the AVAudioNode property lastRenderTime.
func (o AVAudioNode) LastRenderTime() AVAudioTime {
	return AVAudioTime{o.ID.Send(selLastRenderTime)}
}

// Latency reads the AVAudioNode property latency.
func (o AVAudioNode) Latency() float64 {
	return objc.Send[float64](o.ID, selLatency)
}

// NumberOfInputs reads the AVAudioNode property numberOfInputs.
func (o AVAudioNode) NumberOfInputs() uint {
	return objc.Send[uint](o.ID, selNumberOfInputs)
}

// NumberOfOutputs reads the AVAudioNode property numberOfOutputs.
func (o AVAudioNode) NumberOfOutputs() uint {
	return objc.Send[uint](o.ID, selNumberOfOutputs)
}

// OutputPresentationLatency reads the AVAudioNode property outputPresentationLatency.
func (o AVAudioNode) OutputPresentationLatency() float64 {
	return objc.Send[float64](o.ID, selOutputPresentationLatency)
}

// InputFormatForBus — ! @method inputFormatForBus:
// @abstract Obtain an input bus's format.
func (o AVAudioNode) InputFormatForBus(bus uint) AVAudioFormat {
	return AVAudioFormat{o.ID.Send(selInputFormatForBus, bus)}
}

// InstallTapOnBusBufferSizeFormatBlock calls -[AVAudioNode installTapOnBus:bufferSize:format:block:].
func (o AVAudioNode) InstallTapOnBusBufferSizeFormatBlock(bus uint, bufferSize uint32, format AVAudioFormat, tapBlock func(AVAudioPCMBuffer, AVAudioTime)) {
	blockTapBlock := objc.NewBlock(func(_ objc.Block, a0 objc.ID, a1 objc.ID) {
		tapBlock(AVAudioPCMBuffer{a0}, AVAudioTime{a1})
	})
	defer blockTapBlock.Release()
	o.ID.Send(selInstallTapOnBusBufferSizeFormatBlock, bus, bufferSize, format.ID, blockTapBlock)
}

// NameForInputBus — !	@method nameForInputBus:
// @abstract Return the name of an input bus.
func (o AVAudioNode) NameForInputBus(bus uint) string {
	return objcrt.GoString(o.ID.Send(selNameForInputBus, bus))
}

// NameForOutputBus — !	@method nameForOutputBus:
// @abstract Return the name of an output bus.
func (o AVAudioNode) NameForOutputBus(bus uint) string {
	return objcrt.GoString(o.ID.Send(selNameForOutputBus, bus))
}

// OutputFormatForBus — ! @method outputFormatForBus:
// @abstract Obtain an output bus's format.
func (o AVAudioNode) OutputFormatForBus(bus uint) AVAudioFormat {
	return AVAudioFormat{o.ID.Send(selOutputFormatForBus, bus)}
}

// RemoveTapOnBus calls -[AVAudioNode removeTapOnBus:].
func (o AVAudioNode) RemoveTapOnBus(bus uint) {
	o.ID.Send(selRemoveTapOnBus, bus)
}

// Reset — ! @method reset
// @abstract Clear a unit's previous processing state.
func (o AVAudioNode) Reset() {
	o.ID.Send(selReset)
}
