// Code generated by tools/bindgen. DO NOT EDIT.
//
// Source: MacOSX26.2.sdk (Xcode 26.2), target arm64-apple-macos26.0
// Frameworks: Foundation, AVFAudio
//
// Regenerate with: tools/bindgen/regen.sh

//go:build darwin

package avfaudio

import "github.com/ebitengine/purego/objc"

// AVAudioPlayerNode wraps the ObjC class AVAudioPlayerNode (AVAudioNode subclass).
type AVAudioPlayerNode struct{ objc.ID }

// AVAudioPlayerNodeClass is the class object of AVAudioPlayerNode.
type AVAudioPlayerNodeClass struct{ objc.Class }

// GetAVAudioPlayerNodeClass looks the class up in the ObjC runtime.
func GetAVAudioPlayerNodeClass() AVAudioPlayerNodeClass {
	return AVAudioPlayerNodeClass{objc.GetClass("AVAudioPlayerNode")}
}

// Alloc allocates an uninitialized AVAudioPlayerNode (-[NSObject alloc]).
func (c AVAudioPlayerNodeClass) Alloc() AVAudioPlayerNode {
	return AVAudioPlayerNode{objc.ID(c.Class).Send(selAlloc)}
}

// Playing — !	@property playing
// @abstract Indicates whether or not the player is playing.
func (o AVAudioPlayerNode) Playing() bool {
	return objc.Send[bool](o.ID, selIsPlaying)
}

// Init calls -[AVAudioPlayerNode init].
func (o AVAudioPlayerNode) Init() AVAudioPlayerNode {
	return AVAudioPlayerNode{o.ID.Send(selInit)}
}

// NodeTimeForPlayerTime — !	@method nodeTimeForPlayerTime:
// @abstract
// Convert from player time to node time.
// @param playerTime
// a time relative to the player's start time
// @return
// a node time
// @discussion
// This method and its inverse `playerTimeForNodeTime:` are discussed in the
// introduction to this class.
// If the player is not playing when this method is called, nil is returned.
func (o AVAudioPlayerNode) NodeTimeForPlayerTime(playerTime AVAudioTime) AVAudioTime {
	return AVAudioTime{o.ID.Send(selNodeTimeForPlayerTime, playerTime.ID)}
}

// Pause — ! @method pause
// @abstract Pause playback.
// @discussion
// The player's sample time does not advance while the node is paused.
// Note that pausing or stopping all the players connected to an engine does not pause or stop
// the engine or the underlying hardware. The engine must be explicitly paused or stopped for
// the hardware to stop.
func (o AVAudioPlayerNode) Pause() {
	o.ID.Send(selPause)
}

// Play — !	@method play
// @abstract Start or resume playback immediately.
// @discussion
// equivalent to playAtTime:nil
func (o AVAudioPlayerNode) Play() {
	o.ID.Send(selPlay)
}

// PlayAtTime — !	@method playAtTime:
// @abstract Start or resume playback at a specific time.
// @param when
// the node time at which to start or resume playback. nil signifies "now".
// @discussion
// This node is initially paused. Requests to play buffers or file segments are enqueued, and
// any necessary decoding begins immediately. Playback does not begin, however, until the player
// has started playing, via this method.
// Note that providing an AVAudioTime which is past (before lastRenderTime) will cause the
// player to begin playback immediately.
// E.g. To start a player X seconds in future:
// <pre>
// // start engine and player
// NSError *nsErr = nil;
// [_engine startAndReturnError:&nsErr];
// if (!nsErr) {
// const float kStartDelayTime = 0.5; // sec
// AVAudioFormat *outputFormat = [_player outputFormatForBus:0];
// AVAudioFramePosition startSampleTime = _player.lastRenderTime.sampleTime + kStartDelayTime * outputFormat.sampleRate;
// AVAudioTime *startTime = [AVAudioTime timeWithSampleTime:startSampleTime atRate:outputFormat.sampleRate];
// [_player playAtTime:startTime];
// }
// </pre>
func (o AVAudioPlayerNode) PlayAtTime(when AVAudioTime) {
	o.ID.Send(selPlayAtTime, when.ID)
}

// PlayerTimeForNodeTime — !	@method playerTimeForNodeTime:
// @abstract
// Convert from node time to player time.
// @param nodeTime
// a node time
// @return
// a time relative to the player's start time
// @discussion
// This method and its inverse `nodeTimeForPlayerTime:` are discussed in the
// introduction to this class.
// If the player is not playing when this method is called, nil is returned.
func (o AVAudioPlayerNode) PlayerTimeForNodeTime(nodeTime AVAudioTime) AVAudioTime {
	return AVAudioTime{o.ID.Send(selPlayerTimeForNodeTime, nodeTime.ID)}
}

// PrepareWithFrameCount — ! @method prepareWithFrameCount:
// @abstract Prepares previously scheduled file regions or buffers for playback.
// @param frameCount
// The number of sample frames of data to be prepared before returning.
func (o AVAudioPlayerNode) PrepareWithFrameCount(frameCount uint32) {
	o.ID.Send(selPrepareWithFrameCount, frameCount)
}

// ScheduleBufferCompletionHandler — ! @method scheduleBuffer:completionHandler:
// @abstract Schedule playing samples from an AVAudioBuffer.
// @param buffer
// the buffer to play
// @param completionHandler
// called after the buffer has been consumed by the player or the player is stopped. may be nil.
// @discussion
// Schedules the buffer to be played following any previously scheduled commands.
// It is possible for the completionHandler to be called before rendering begins
// or before the buffer is played completely.
func (o AVAudioPlayerNode) ScheduleBufferCompletionHandler(buffer AVAudioPCMBuffer, completionHandler func()) {
	blockCompletionHandler := objc.NewBlock(func(_ objc.Block) {
		completionHandler()
	})
	defer blockCompletionHandler.Release()
	o.ID.Send(selScheduleBufferCompletionHandler, buffer.ID, blockCompletionHandler)
}

// Stop — !	@method stop
// @abstract Clear all of the node's previously scheduled events and stop playback.
// @discussion
// All of the node's previously scheduled events are cleared, including any that are in the
// middle of playing. The node's sample time (and therefore the times to which new events are
// to be scheduled) is reset to 0, and will not proceed until the node is started again (via
// play or playAtTime).
// Note that pausing or stopping all the players connected to an engine does not pause or stop
// the engine or the underlying hardware. The engine must be explicitly paused or stopped for
// the hardware to stop.
func (o AVAudioPlayerNode) Stop() {
	o.ID.Send(selStop)
}
