// Code generated by tools/bindgen. DO NOT EDIT.
//
// Source: MacOSX26.2.sdk (Xcode 26.2), target arm64-apple-macos26.0
// Frameworks: Foundation, AVFAudio
//
// Regenerate with: tools/bindgen/regen.sh

//go:build darwin

package avfaudio

import "github.com/ebitengine/purego/objc"

// AVAudioInputNode an opaque handle for the ObjC class AVAudioInputNode (AVAudioIONode subclass).
// Only the identity crosses: no method of AVAudioInputNode is on the allowlist.
type AVAudioInputNode struct{ objc.ID }

// AVAudioInputNodeClass is the class object of AVAudioInputNode.
type AVAudioInputNodeClass struct{ objc.Class }

// GetAVAudioInputNodeClass looks the class up in the ObjC runtime.
func GetAVAudioInputNodeClass() AVAudioInputNodeClass {
	return AVAudioInputNodeClass{objc.GetClass("AVAudioInputNode")}
}
