// Code generated by tools/bindgen. DO NOT EDIT.
//
// Source: MacOSX26.2.sdk (Xcode 26.2), target arm64-apple-macos26.0
// Frameworks: Foundation, AVFAudio
//
// Regenerate with: tools/bindgen/regen.sh

//go:build darwin

package avfaudio

import "github.com/ebitengine/purego/objc"

// AVAudioTime an opaque handle for the ObjC class AVAudioTime (NSObject subclass).
// Only the identity crosses: no method of AVAudioTime is on the allowlist.
type AVAudioTime struct{ objc.ID }

// AVAudioTimeClass is the class object of AVAudioTime.
type AVAudioTimeClass struct{ objc.Class }

// GetAVAudioTimeClass looks the class up in the ObjC runtime.
func GetAVAudioTimeClass() AVAudioTimeClass { return AVAudioTimeClass{objc.GetClass("AVAudioTime")} }
