// Code generated by tools/bindgen. DO NOT EDIT.
//
// Source: MacOSX26.2.sdk (Xcode 26.2), target arm64-apple-macos26.0
// Frameworks: Foundation, AVFAudio
//
// Regenerate with: tools/bindgen/regen.sh

//go:build darwin

package avfaudio

import "github.com/ebitengine/purego/objc"

// AVAudioPCMBuffer wraps the ObjC class AVAudioPCMBuffer (AVAudioBuffer subclass).
type AVAudioPCMBuffer struct{ objc.ID }

// AVAudioPCMBufferClass is the class object of AVAudioPCMBuffer.
type AVAudioPCMBufferClass struct{ objc.Class }

// GetAVAudioPCMBufferClass looks the class up in the ObjC runtime.
func GetAVAudioPCMBufferClass() AVAudioPCMBufferClass {
	return AVAudioPCMBufferClass{objc.GetClass("AVAudioPCMBuffer")}
}

// Alloc allocates an uninitialized AVAudioPCMBuffer (-[NSObject alloc]).
func (c AVAudioPCMBufferClass) Alloc() AVAudioPCMBuffer {
	return AVAudioPCMBuffer{objc.ID(c.Class).Send(selAlloc)}
}

// FrameCapacity — ! @property frameCapacity
// @abstract
// The buffer's capacity, in audio sample frames.
func (o AVAudioPCMBuffer) FrameCapacity() uint32 {
	return objc.Send[uint32](o.ID, selFrameCapacity)
}

// FrameLength — !	@property frameLength
// @abstract The current number of valid sample frames in the buffer.
// @discussion
// You may modify the length of the buffer as part of an operation that modifies its contents.
// The length must be less than or equal to the frameCapacity. Modifying frameLength will update
// the mDataByteSize in each of the underlying AudioBufferList's AudioBuffer's correspondingly,
// and vice versa. Note that in the case of deinterleaved formats, mDataByteSize will refers
// the size of one channel's worth of audio samples.
func (o AVAudioPCMBuffer) FrameLength() uint32 {
	return objc.Send[uint32](o.ID, selFrameLength)
}

// SetFrameLength writes the AVAudioPCMBuffer property frameLength.
func (o AVAudioPCMBuffer) SetFrameLength(v uint32) {
	o.ID.Send(selSetFrameLength, v)
}

// Stride — !	@property stride
// @abstract The buffer's number of interleaved channels.
// @discussion
// Useful in conjunction with floatChannelData etc.
func (o AVAudioPCMBuffer) Stride() uint {
	return objc.Send[uint](o.ID, selStride)
}

// InitWithPCMFormatFrameCapacity — !	@method initWithPCMFormat:frameCapacity:
// @abstract Initialize a buffer that is to contain PCM audio samples.
// @param format
// The format of the PCM audio to be contained in the buffer.
// @param frameCapacity
// The capacity of the buffer in PCM sample frames.
// @discussion
// An exception is raised if the format is not PCM.
// Returns nil in the following cases:
// - if the format has zero bytes per frame (format.streamDescription->mBytesPerFrame == 0)
// - if the buffer byte capacity (frameCapacity * format.streamDescription->mBytesPerFrame)
// cannot be represented by an uint32_t
func (o AVAudioPCMBuffer) InitWithPCMFormatFrameCapacity(format AVAudioFormat, frameCapacity uint32) AVAudioPCMBuffer {
	return AVAudioPCMBuffer{o.ID.Send(selInitWithPCMFormatFrameCapacity, format.ID, frameCapacity)}
}
