// Code generated by tools/bindgen. DO NOT EDIT.
//
// Source: MacOSX26.2.sdk (Xcode 26.2), target arm64-apple-macos26.0
// Frameworks: Foundation, AVFAudio
//
// Regenerate with: tools/bindgen/regen.sh

//go:build darwin

package avfaudio

import (
	"github.com/adriaanm/wata/go-pkgs/appleptt/objcrt"
	"github.com/ebitengine/purego/objc"
)

// AVAudioEngine wraps the ObjC class AVAudioEngine (NSObject subclass).
type AVAudioEngine struct{ objc.ID }

// AVAudioEngineClass is the class object of AVAudioEngine.
type AVAudioEngineClass struct{ objc.Class }

// GetAVAudioEngineClass looks the class up in the ObjC runtime.
func GetAVAudioEngineClass() AVAudioEngineClass {
	return AVAudioEngineClass{objc.GetClass("AVAudioEngine")}
}

// Alloc allocates an uninitialized AVAudioEngine (-[NSObject alloc]).
func (c AVAudioEngineClass) Alloc() AVAudioEngine {
	return AVAudioEngine{objc.ID(c.Class).Send(selAlloc)}
}

// AutoShutdownEnabled — ! @property autoShutdownEnabled
// @abstract
// When auto shutdown is enabled, the engine can start and stop the audio hardware dynamically,
// to conserve power. This is the enforced behavior on watchOS and can be optionally enabled on
// other platforms.
// To conserve power, it is advised that the client pause/stop the engine when not in use.
// But when auto shutdown is enabled, the engine will stop the audio hardware if it was running
// idle for a certain duration, and restart it later when required.
// Note that, because this operation is dynamic, it may affect the start times of the source
// nodes (e.g. `AVAudioPlayerNode`), if the engine has to resume from its shutdown state.
// On watchOS, auto shutdown is always enabled. On other platforms, it is disabled by
// default, but the client can enable it if needed.
// This property is applicable only when the engine is rendering to/from an audio device. If
// the value is changed when the engine is in manual rendering mode, it will take effect
// whenever the engine is switched to render to/from the audio device.
func (o AVAudioEngine) AutoShutdownEnabled() bool {
	return objc.Send[bool](o.ID, selIsAutoShutdownEnabled)
}

// SetAutoShutdownEnabled writes the AVAudioEngine property autoShutdownEnabled.
func (o AVAudioEngine) SetAutoShutdownEnabled(v bool) {
	o.ID.Send(selSetAutoShutdownEnabled, v)
}

// InputNode — ! @property inputNode
// @abstract
// The engine's singleton input node.
// Audio input is performed via an input node. The engine creates a singleton on demand when
// this property is first accessed. To receive input, connect another node from the output of
// the input node, or create a recording tap on it.
// When the engine is rendering to/from an audio device, the AVAudioSesssion category and/or
// availability of hardware determine whether an app can perform input. Check for the input node's
// input format (i.e. hardware format) for non-zero sample rate and channel count to see if input is enabled.
// Trying to perform input through the input node when it is not enabled or available will
// cause the engine to throw an error (when possible) or an exception.
// Note that if the engine has at any point previously had its inputNode enabled and permission to
// record was granted, then any time the engine is running, the mic-in-use indicator will appear.
// For applications which may need to dynamically switch between output-only and input-output
// modes, it may be advantageous to use two engine instances.
// In manual rendering mode, the input node can be used to synchronously supply data to
// the engine while it is rendering (see
// `AVAudioInputNode(setManualRenderingInputPCMFormat:inputBlock:)`.
func (o AVAudioEngine) InputNode() AVAudioInputNode {
	return AVAudioInputNode{o.ID.Send(selInputNode)}
}

// IsInManualRenderingMode — ! @property isInManualRenderingMode
// @abstract
// Whether or not the engine is operating in manual rendering mode, i.e. not connected
// to an audio device and rendering in response to the requests from the client
func (o AVAudioEngine) IsInManualRenderingMode() bool {
	return objc.Send[bool](o.ID, selIsInManualRenderingMode)
}

// MainMixerNode — ! @property mainMixerNode
// @abstract
// The engine's optional singleton main mixer node.
// The engine will construct a singleton main mixer and connect it to the outputNode on demand,
// when this property is first accessed. You can then connect additional nodes to the mixer.
// If the client has never explicitly set the connection format between the mainMixerNode and
// the outputNode, the engine will always set/update the format to track the format of the outputNode
// on (re)start, even after an AVAudioEngineConfigurationChangeNotification.
// Otherwise, it's the client's responsibility to set/update this connection format after an
// AVAudioEngineConfigurationChangeNotification.
// By default, the mixer's output format (sample rate and channel count) will track the format
// of the output node. You may however make the connection explicitly with a different format.
func (o AVAudioEngine) MainMixerNode() AVAudioMixerNode {
	return AVAudioMixerNode{o.ID.Send(selMainMixerNode)}
}

// ManualRenderingFormat — ! @property manualRenderingFormat
// @abstract
// The render format of the engine in manual rendering mode.
// Querying this property when the engine is not in manual rendering mode will return an
// invalid format, with zero sample rate and channel count.
func (o AVAudioEngine) ManualRenderingFormat() AVAudioFormat {
	return AVAudioFormat{o.ID.Send(selManualRenderingFormat)}
}

// ManualRenderingMaximumFrameCount — ! @property manualRenderingMaximumFrameCount
// @abstract
// The maximum number of PCM sample frames the engine can produce in any single render call in
// the manual rendering mode.
// Querying this property when the engine is not in manual rendering mode will return zero.
func (o AVAudioEngine) ManualRenderingMaximumFrameCount() uint32 {
	return objc.Send[uint32](o.ID, selManualRenderingMaximumFrameCount)
}

// ManualRenderingSampleTime — ! @property manualRenderingSampleTime
// @abstract
// Indicates where the engine is on its render timeline in manual rendering mode.
// The timeline in manual rendering mode starts at a sample time of zero, and is in terms
// of the render format's sample rate. Resetting the engine (see `reset`) will reset the
// timeline back to zero.
func (o AVAudioEngine) ManualRenderingSampleTime() int64 {
	return objc.Send[int64](o.ID, selManualRenderingSampleTime)
}

// OutputNode — ! @property outputNode
// @abstract
// The engine's singleton output node.
// Audio output is performed via an output node. The engine creates a singleton on demand when
// this property is first accessed. Connect another node to the input of the output node, or
// obtain a mixer that is connected there by default, using the "mainMixerNode" property.
// When the engine is rendering to/from an audio device, the AVAudioSesssion category and/or
// availability of hardware determine whether an app can perform output. Check the output
// format of output node (i.e. hardware format) for non-zero sample rate and channel count to
// see if output is enabled.
// Trying to perform output through the output node when it is not enabled or available will
// cause the engine to throw an error (when possible) or an exception.
// In manual rendering mode, the output format of the output node will determine the
// render format of the engine. It can be changed through
// `enableManualRenderingMode:format:maximumFrameCount:error:`.
func (o AVAudioEngine) OutputNode() AVAudioOutputNode {
	return AVAudioOutputNode{o.ID.Send(selOutputNode)}
}

// Running — ! @property running
// @abstract
// The engine's running state.
func (o AVAudioEngine) Running() bool {
	return objc.Send[bool](o.ID, selIsRunning)
}

// AttachNode — !	@method attachNode:
// @abstract
// Take ownership of a new node.
// @param node
// The node to be attached to the engine.
// To support the instantiation of arbitrary AVAudioNode subclasses, instances are created
// externally to the engine, but are not usable until they are attached to the engine via
// this method. Thus the idiom, without ARC, is:
// ```
// // when building engine:
// AVAudioNode *_player;	// member of controller class (for example)
// ...
// _player = [[AVAudioPlayerNode alloc] init];
// [engine attachNode: _player];
// ...
// // when destroying engine (without ARC)
// [_player release];
// ```
func (o AVAudioEngine) AttachNode(node AVAudioNode) {
	o.ID.Send(selAttachNode, node.ID)
}

// ConnectToFormat — !	@method connect:to:format:
// @abstract
// Establish a connection between two nodes
// This calls connect:to:fromBus:toBus:format: using bus 0 on the source node,
// and bus 0 on the destination node, except in the case of a destination which is a mixer,
// in which case the destination is the mixer's nextAvailableInputBus.
func (o AVAudioEngine) ConnectToFormat(node1 AVAudioNode, node2 AVAudioNode, format AVAudioFormat) {
	o.ID.Send(selConnectToFormat, node1.ID, node2.ID, format.ID)
}

// ConnectToFromBusToBusFormat — ! @method connect:to:fromBus:toBus:format:
// @abstract
// Establish a connection between two nodes.
// @param node1
// The source node
// @param node2
// The destination node
// @param bus1
// The output bus on the source node
// @param bus2
// The input bus on the destination node
// @param format
// If non-nil, the format of the source node's output bus is set to this
// format. In all cases, the format of the destination node's input bus is set to
// match that of the source node's output bus.
// Nodes have input and output buses (AVAudioNodeBus). Use this method to establish
// one-to-one connections betweeen nodes. Connections made using this method are always
// one-to-one, never one-to-many or many-to-one.
// Note that any pre-existing connection(s) involving the source's output bus or the
// destination's input bus will be broken.
func (o AVAudioEngine) ConnectToFromBusToBusFormat(node1 AVAudioNode, node2 AVAudioNode, bus1 uint, bus2 uint, format AVAudioFormat) {
	o.ID.Send(selConnectToFromBusToBusFormat, node1.ID, node2.ID, bus1, bus2, format.ID)
}

// ConnectToConnectionPointsFromBusFormat — ! @method connect:toConnectionPoints:fromBus:format:
// @abstract
// Establish connections between a source node and multiple destination nodes.
// @param sourceNode
// The source node
// @param destNodes
// An array of AVAudioConnectionPoint objects specifying destination
// nodes and busses
// @param sourceBus
// The output bus on source node
// @param format
// If non-nil, the format of the source node's output bus is set to this
// format. In all cases, the format of the destination nodes' input bus is set to
// match that of the source node's output bus
// Use this method to establish connections from a source node to multiple destination nodes.
// Connections made using this method are either one-to-one (when a single destination
// connection is specified) or one-to-many (when multiple connections are specified), but
// never many-to-one.
// To incrementally add a new connection to a source node, use this method with an array
// of AVAudioConnectionPoint objects comprising of pre-existing connections (obtained from
// `outputConnectionPointsForNode:outputBus:`) and the new connection.
// Note that any pre-existing connection involving the destination's input bus will be
// broken. And, any pre-existing connection on source node which is not a part of the
// specified destination connection array will also be broken.
// Also note that when the output of a node is split into multiple paths, all the paths
// must render at the same rate until they reach a common mixer.
// In other words, starting from the split node until the common mixer node where all split
// paths terminate, you cannot have:
// - any AVAudioUnitTimeEffect
// - any sample rate conversion
func (o AVAudioEngine) ConnectToConnectionPointsFromBusFormat(sourceNode AVAudioNode, destNodes NSArray, sourceBus uint, format AVAudioFormat) {
	o.ID.Send(selConnectToConnectionPointsFromBusFormat, sourceNode.ID, destNodes.ID, sourceBus, format.ID)
}

// DetachNode — !	@method detachNode:
// @abstract
// Detach a node previously attached to the engine.
// If necessary, the engine will safely disconnect the node before detaching it.
func (o AVAudioEngine) DetachNode(node AVAudioNode) {
	o.ID.Send(selDetachNode, node.ID)
}

// DisableManualRenderingMode — !	@method disableManualRenderingMode
// @abstract
// Set the engine to render to/from an audio device.
// When disabling the manual rendering mode, the engine:
// 1. Stops and resets itself (see `stop` and `reset`).
// 2. Switches the output/input nodes to render to/from an audio device. Their input and
// output formats may change.
// 3. Removes any taps previously installed on the input and output nodes.
// 4. Maintains all the engine connections as is.
// Calling this method when the engine is already rendering to/from an audio device has no
// effect.
func (o AVAudioEngine) DisableManualRenderingMode() {
	o.ID.Send(selDisableManualRenderingMode)
}

// DisconnectMIDIFrom — ! @method disconnectMIDI:from:
// @abstract
// Remove a MIDI connection between two nodes.
// @param sourceNode
// The node whose MIDI output is to be disconnected.
// @param destinationNode
// The node whose MIDI input is to be disconnected.
// If a tap block is installed on the source node, it will be removed when the last
// connection from the source node is removed.
func (o AVAudioEngine) DisconnectMIDIFrom(sourceNode AVAudioNode, destinationNode AVAudioNode) {
	o.ID.Send(selDisconnectMIDIFrom, sourceNode.ID, destinationNode.ID)
}

// DisconnectMIDIFromNodes — ! @method disconnectMIDI:fromNodes:
// @abstract
// Remove a MIDI connection between one source node and multiple destination nodes.
// @param sourceNode
// The node whose MIDI output is to be disconnected.
// @param destinationNodes
// An array of AVAudioNodes specifying nodes whose MIDI input is to be disconnected.
// If a tap block is installed on the source node, it will be removed when the last
// connection from the source node is removed.
func (o AVAudioEngine) DisconnectMIDIFromNodes(sourceNode AVAudioNode, destinationNodes NSArray) {
	o.ID.Send(selDisconnectMIDIFromNodes, sourceNode.ID, destinationNodes.ID)
}

// DisconnectMIDIInput — ! @method disconnectMIDIInput:
// @abstract
// Disconnects all input MIDI connections of this node.
// @param node
// The node whose MIDI input is to be disconnected.
func (o AVAudioEngine) DisconnectMIDIInput(node AVAudioNode) {
	o.ID.Send(selDisconnectMIDIInput, node.ID)
}

// DisconnectMIDIOutput — ! @method disconnectMIDIOutput:
// @abstract
// Disconnects all output MIDI connections of this node.
// @param node
// The node whose MIDI outputs are to be disconnected.
func (o AVAudioEngine) DisconnectMIDIOutput(node AVAudioNode) {
	o.ID.Send(selDisconnectMIDIOutput, node.ID)
}

// DisconnectNodeInput — !	@method disconnectNodeInput:
// @abstract
// Remove a connection between two nodes.
// @param node
// The node whose inputs are to be disconnected
// Connections are broken on each of the node's input busses.
func (o AVAudioEngine) DisconnectNodeInput(node AVAudioNode) {
	o.ID.Send(selDisconnectNodeInput, node.ID)
}

// DisconnectNodeInputBus — ! @method disconnectNodeInput:bus:
// @abstract
// Remove a connection between two nodes.
// @param node
// The node whose input is to be disconnected
// @param bus
// The destination's input bus to disconnect
func (o AVAudioEngine) DisconnectNodeInputBus(node AVAudioNode, bus uint) {
	o.ID.Send(selDisconnectNodeInputBus, node.ID, bus)
}

// DisconnectNodeOutput — !	@method disconnectNodeOutput:
// @abstract
// Remove a connection between two nodes.
// @param node
// The node whose outputs are to be disconnected
// Connections are broken on each of the node's output busses.
func (o AVAudioEngine) DisconnectNodeOutput(node AVAudioNode) {
	o.ID.Send(selDisconnectNodeOutput, node.ID)
}

// DisconnectNodeOutputBus — ! @method disconnectNodeOutput:bus:
// @abstract
// Remove a connection between two nodes.
// @param node
// The node whose output is to be disconnected
// @param bus
// The source's output bus to disconnect
func (o AVAudioEngine) DisconnectNodeOutputBus(node AVAudioNode, bus uint) {
	o.ID.Send(selDisconnectNodeOutputBus, node.ID, bus)
}

// Init — ! @method init
// @abstract
// Initialize a new engine.
// On creation, the engine is by default connected to an audio device and automatically renders
// in realtime. It can be configured to operate in manual rendering mode through
// `enableManualRenderingMode:format:maximumFrameCount:error:`.
func (o AVAudioEngine) Init() AVAudioEngine {
	return AVAudioEngine{o.ID.Send(selInit)}
}

// InputConnectionPointForNodeInputBus — ! @method inputConnectionPointForNode:inputBus:
// @abstract
// Get connection information on a node's input bus.
// @param node
// The node whose input connection is being queried.
// @param bus
// The node's input bus on which the connection is being queried.
// @return
// An AVAudioConnectionPoint object with connection information on the node's
// specified input bus.
// Connections are always one-to-one or one-to-many, never many-to-one.
// Returns nil if there is no connection on the node's specified input bus.
func (o AVAudioEngine) InputConnectionPointForNodeInputBus(node AVAudioNode, bus uint) AVAudioConnectionPoint {
	return AVAudioConnectionPoint{o.ID.Send(selInputConnectionPointForNodeInputBus, node.ID, bus)}
}

// OutputConnectionPointsForNodeOutputBus — ! @method outputConnectionPointsForNode:outputBus:
// @abstract
// Get connection information on a node's output bus.
// @param node
// The node whose output connections are being queried.
// @param bus
// The node's output bus on which connections are being queried.
// @return
// An array of AVAudioConnectionPoint objects with connection information on the node's
// specified output bus.
// Connections are always one-to-one or one-to-many, never many-to-one.
// Returns an empty array if there are no connections on the node's specified output bus.
func (o AVAudioEngine) OutputConnectionPointsForNodeOutputBus(node AVAudioNode, bus uint) NSArray {
	return NSArray{o.ID.Send(selOutputConnectionPointsForNodeOutputBus, node.ID, bus)}
}

// Pause — !	@method pause
// @abstract
// Pause the engine.
// When the engine is rendering to/from an audio device, stops the audio hardware and the flow
// of audio through the engine. When operating in this mode, it is recommended that the engine
// be paused or stopped (as applicable) when not in use, to minimize power consumption.
// Pausing the engine does not deallocate the resources allocated by prepare. Resume the
// engine by invoking start again.
func (o AVAudioEngine) Pause() {
	o.ID.Send(selPause)
}

// Prepare — !	@method prepare
// @abstract
// Prepare the engine for starting.
// This method preallocates many of the resources the engine requires in order to start.
// Use it to responsively start audio input or output.
// On AVAudioSession supported platforms, this method may cause the audio session to be implicitly activated. Activating the audio session (implicitly or explicitly) may cause other audio sessions to be interrupted or ducked depending on the session's configuration. It is recommended to configure and activate the app's audio session before preparing the engine.
// See https://developer.apple.com/library/archive/documentation/Audio/Conceptual/AudioSessionProgrammingGuide/Introduction/Introduction.html for details.
func (o AVAudioEngine) Prepare() {
	o.ID.Send(selPrepare)
}

// Reset — !	@method reset
// @abstract reset
// Reset all of the nodes in the engine.
// This will reset all of the nodes in the engine. This is useful, for example, for silencing
// reverb and delay tails.
// In manual rendering mode, the render timeline is reset to a sample time of zero.
func (o AVAudioEngine) Reset() {
	o.ID.Send(selReset)
}

// StartAndReturnError — ! @method startAndReturnError:
// @abstract
// Start the engine.
// @return
// YES for success
// Calls prepare if it has not already been called since stop.
// When the engine is rendering to/from an audio device, starts the audio hardware via the
// AVAudioInputNode and/or AVAudioOutputNode instances in the engine. Audio begins to flow
// through the engine.
// Reasons for potential failure to start in this mode include:
// 1. There is problem in the structure of the graph. Input can't be routed to output or to a
// recording tap through converter type nodes.
// 2. An AVAudioSession error.
// 3. The driver failed to start the hardware.
// In manual rendering mode, prepares the engine to render when requested by the client.
// On AVAudioSession supported platforms, this method may cause the audio session to be implicitly activated. It is recommended to configure and activate the app's audio session before starting the engine. For more information, see the `prepare` method above.
func (o AVAudioEngine) StartAndReturnError() (bool, error) {
	var errOut objcrt.ErrOut
	ret := objc.Send[bool](o.ID, selStartAndReturnError, errOut.Ptr())
	return ret, errOut.Err()
}

// Stop — ! @method stop
// @abstract
// When the engine is rendering to/from an audio device, stops the audio hardware and the
// engine. When operating in this mode, it is recommended that the engine be paused or stopped
// (as applicable) when not in use, to minimize power consumption.
// Stopping the engine releases the resources allocated by prepare.
func (o AVAudioEngine) Stop() {
	o.ID.Send(selStop)
}
