// Code generated by tools/bindgen. DO NOT EDIT.
//
// Source: MacOSX26.2.sdk (Xcode 26.2), target arm64-apple-macos26.0
// Frameworks: Foundation, AVFAudio
//
// Regenerate with: tools/bindgen/regen.sh

//go:build darwin

package avfaudio

import "github.com/ebitengine/purego/objc"

// AVAudioConnectionPoint an opaque handle for the ObjC class AVAudioConnectionPoint (NSObject subclass).
// Only the identity crosses: no method of AVAudioConnectionPoint is on the allowlist.
type AVAudioConnectionPoint struct{ objc.ID }

// AVAudioConnectionPointClass is the class object of AVAudioConnectionPoint.
type AVAudioConnectionPointClass struct{ objc.Class }

// GetAVAudioConnectionPointClass looks the class up in the ObjC runtime.
func GetAVAudioConnectionPointClass() AVAudioConnectionPointClass {
	return AVAudioConnectionPointClass{objc.GetClass("AVAudioConnectionPoint")}
}
