// Code generated by tools/bindgen. DO NOT EDIT.
//
// Source: MacOSX26.2.sdk (Xcode 26.2), target arm64-apple-macos26.0
// Frameworks: Foundation, AVFAudio
//
// Regenerate with: tools/bindgen/regen.sh

//go:build darwin

package avfaudio

import "github.com/ebitengine/purego/objc"

// AVAudioMixerNode an opaque handle for the ObjC class AVAudioMixerNode (AVAudioNode subclass).
// Only the identity crosses: no method of AVAudioMixerNode is on the allowlist.
type AVAudioMixerNode struct{ objc.ID }

// AVAudioMixerNodeClass is the class object of AVAudioMixerNode.
type AVAudioMixerNodeClass struct{ objc.Class }

// GetAVAudioMixerNodeClass looks the class up in the ObjC runtime.
func GetAVAudioMixerNodeClass() AVAudioMixerNodeClass {
	return AVAudioMixerNodeClass{objc.GetClass("AVAudioMixerNode")}
}
