// Code generated by tools/bindgen. DO NOT EDIT.
//
// Source: MacOSX26.2.sdk (Xcode 26.2), target arm64-apple-macos26.0
// Frameworks: Foundation, AVFAudio
//
// Regenerate with: tools/bindgen/regen.sh

//go:build darwin

package avfaudio

import "github.com/ebitengine/purego/objc"

// AVAudioOutputNode an opaque handle for the ObjC class AVAudioOutputNode (AVAudioIONode subclass).
// Only the identity crosses: no method of AVAudioOutputNode is on the allowlist.
type AVAudioOutputNode struct{ objc.ID }

// AVAudioOutputNodeClass is the class object of AVAudioOutputNode.
type AVAudioOutputNodeClass struct{ objc.Class }

// GetAVAudioOutputNodeClass looks the class up in the ObjC runtime.
func GetAVAudioOutputNodeClass() AVAudioOutputNodeClass {
	return AVAudioOutputNodeClass{objc.GetClass("AVAudioOutputNode")}
}
