// Code generated by tools/bindgen. DO NOT EDIT.
//
// Source: MacOSX26.2.sdk (Xcode 26.2), target arm64-apple-macos26.0
// Frameworks: Foundation, AVFAudio
//
// Regenerate with: tools/bindgen/regen.sh

//go:build darwin

package avfaudio

import "github.com/ebitengine/purego/objc"

// AVAudioChannelLayout an opaque handle for the ObjC class AVAudioChannelLayout (NSObject subclass).
// Only the identity crosses: no method of AVAudioChannelLayout is on the allowlist.
type AVAudioChannelLayout struct{ objc.ID }

// AVAudioChannelLayoutClass is the class object of AVAudioChannelLayout.
type AVAudioChannelLayoutClass struct{ objc.Class }

// GetAVAudioChannelLayoutClass looks the class up in the ObjC runtime.
func GetAVAudioChannelLayoutClass() AVAudioChannelLayoutClass {
	return AVAudioChannelLayoutClass{objc.GetClass("AVAudioChannelLayout")}
}
