// Code generated by tools/bindgen. DO NOT EDIT.
//
// Source: MacOSX26.2.sdk (Xcode 26.2), target arm64-apple-macos26.0
// Frameworks: Foundation, AVFAudio
//
// Regenerate with: tools/bindgen/regen.sh

//go:build darwin

package avfaudio

import "github.com/ebitengine/purego/objc"

// AVAudioIONode an opaque handle for the ObjC class AVAudioIONode (AVAudioNode subclass).
// Only the identity crosses: no method of AVAudioIONode is on the allowlist.
type AVAudioIONode struct{ objc.ID }

// AVAudioIONodeClass is the class object of AVAudioIONode.
type AVAudioIONodeClass struct{ objc.Class }

// GetAVAudioIONodeClass looks the class up in the ObjC runtime.
func GetAVAudioIONodeClass() AVAudioIONodeClass {
	return AVAudioIONodeClass{objc.GetClass("AVAudioIONode")}
}
