// Code generated by tools/bindgen. DO NOT EDIT.
//
// Source: MacOSX26.2.sdk (Xcode 26.2), target arm64-apple-macos26.0
// Frameworks: Foundation, AVFAudio
//
// Regenerate with: tools/bindgen/regen.sh

//go:build darwin

package avfaudio

// AVAudioCommonFormat is the ObjC enum AVAudioCommonFormat (unsigned long).
type AVAudioCommonFormat uint

const (
	AVAudioOtherFormat      AVAudioCommonFormat = 0
	AVAudioPCMFormatFloat32 AVAudioCommonFormat = 1
	AVAudioPCMFormatFloat64 AVAudioCommonFormat = 2
	AVAudioPCMFormatInt16   AVAudioCommonFormat = 3
	AVAudioPCMFormatInt32   AVAudioCommonFormat = 4
)
