// Code generated by tools/bindgen. DO NOT EDIT.
//
// Source: MacOSX26.2.sdk (Xcode 26.2), target arm64-apple-macos26.0
// Frameworks: Foundation, AVFAudio
//
// Regenerate with: tools/bindgen/regen.sh

//go:build darwin

package avfaudio

import "github.com/ebitengine/purego/objc"

// NSError an opaque handle for the ObjC class NSError (NSObject subclass).
// Only the identity crosses: no method of NSError is on the allowlist.
type NSError struct{ objc.ID }

// NSErrorClass is the class object of NSError.
type NSErrorClass struct{ objc.Class }

// GetNSErrorClass looks the class up in the ObjC runtime.
func GetNSErrorClass() NSErrorClass { return NSErrorClass{objc.GetClass("NSError")} }
