// Code generated by tools/bindgen. DO NOT EDIT.
//
// Source: iPhoneSimulator26.2.sdk (Xcode 26.2), target arm64-apple-ios26.2-simulator
// Frameworks: Foundation, UIKit
//
// Regenerate with: tools/bindgen/regen.sh

//go:build darwin

package uikit

// UIViewContentMode is the ObjC enum UIViewContentMode (long).
type UIViewContentMode int

const (
	UIViewContentModeScaleToFill     UIViewContentMode = 0
	UIViewContentModeScaleAspectFit  UIViewContentMode = 1
	UIViewContentModeScaleAspectFill UIViewContentMode = 2
	UIViewContentModeRedraw          UIViewContentMode = 3
	UIViewContentModeCenter          UIViewContentMode = 4
	UIViewContentModeTop             UIViewContentMode = 5
	UIViewContentModeBottom          UIViewContentMode = 6
	UIViewContentModeLeft            UIViewContentMode = 7
	UIViewContentModeRight           UIViewContentMode = 8
	UIViewContentModeTopLeft         UIViewContentMode = 9
	UIViewContentModeTopRight        UIViewContentMode = 10
	UIViewContentModeBottomLeft      UIViewContentMode = 11
	UIViewContentModeBottomRight     UIViewContentMode = 12
)
