// Code generated by tools/bindgen. DO NOT EDIT.
//
// Source: iPhoneSimulator26.2.sdk (Xcode 26.2), target arm64-apple-ios26.2-simulator
// Frameworks: Foundation, UIKit
//
// Regenerate with: tools/bindgen/regen.sh

//go:build darwin

package uikit

import (
	"github.com/adriaanm/wata/go-pkgs/appleptt/objcrt"
	"github.com/ebitengine/purego/objc"
)

// NSArray — NSOrderedCollectionDifference.h
// Copyright (c) 2017-2019, Apple Inc. All rights reserved.
type NSArray struct{ objc.ID }

// NSArrayClass is the class object of NSArray.
type NSArrayClass struct{ objc.Class }

// GetNSArrayClass looks the class up in the ObjC runtime.
func GetNSArrayClass() NSArrayClass { return NSArrayClass{objc.GetClass("NSArray")} }

// Alloc allocates an uninitialized NSArray (-[NSObject alloc]).
func (c NSArrayClass) Alloc() NSArray { return NSArray{objc.ID(c.Class).Send(selAlloc)} }

// Count reads the NSArray property count.
func (o NSArray) Count() uint {
	return objc.Send[uint](o.ID, selCount)
}

// ArrayByAddingObject calls -[NSArray arrayByAddingObject:].
func (o NSArray) ArrayByAddingObject(anObject objc.ID) NSArray {
	return NSArray{o.ID.Send(selArrayByAddingObject, anObject)}
}

// ArrayByAddingObjectsFromArray calls -[NSArray arrayByAddingObjectsFromArray:].
func (o NSArray) ArrayByAddingObjectsFromArray(otherArray NSArray) NSArray {
	return NSArray{o.ID.Send(selArrayByAddingObjectsFromArray, otherArray.ID)}
}

// ComponentsJoinedByString calls -[NSArray componentsJoinedByString:].
func (o NSArray) ComponentsJoinedByString(separator string) string {
	return objcrt.GoString(o.ID.Send(selComponentsJoinedByString, objcrt.NSString(separator)))
}

// ContainsObject calls -[NSArray containsObject:].
func (o NSArray) ContainsObject(anObject objc.ID) bool {
	return objc.Send[bool](o.ID, selContainsObject, anObject)
}

// DescriptionWithLocale calls -[NSArray descriptionWithLocale:].
func (o NSArray) DescriptionWithLocale(locale objc.ID) string {
	return objcrt.GoString(o.ID.Send(selDescriptionWithLocale, locale))
}

// DescriptionWithLocaleIndent calls -[NSArray descriptionWithLocale:indent:].
func (o NSArray) DescriptionWithLocaleIndent(locale objc.ID, level uint) string {
	return objcrt.GoString(o.ID.Send(selDescriptionWithLocaleIndent, locale, level))
}

// FirstObjectCommonWithArray calls -[NSArray firstObjectCommonWithArray:].
func (o NSArray) FirstObjectCommonWithArray(otherArray NSArray) objc.ID {
	return o.ID.Send(selFirstObjectCommonWithArray, otherArray.ID)
}

// IndexOfObject calls -[NSArray indexOfObject:].
func (o NSArray) IndexOfObject(anObject objc.ID) uint {
	return objc.Send[uint](o.ID, selIndexOfObject, anObject)
}

// IndexOfObjectIdenticalTo calls -[NSArray indexOfObjectIdenticalTo:].
func (o NSArray) IndexOfObjectIdenticalTo(anObject objc.ID) uint {
	return objc.Send[uint](o.ID, selIndexOfObjectIdenticalTo, anObject)
}

// Init calls -[NSArray init].
func (o NSArray) Init() NSArray {
	return NSArray{o.ID.Send(selInit)}
}

// InitWithArray calls -[NSArray initWithArray:].
func (o NSArray) InitWithArray(array NSArray) NSArray {
	return NSArray{o.ID.Send(selInitWithArray, array.ID)}
}

// InitWithArrayCopyItems calls -[NSArray initWithArray:copyItems:].
func (o NSArray) InitWithArrayCopyItems(array NSArray, flag bool) NSArray {
	return NSArray{o.ID.Send(selInitWithArrayCopyItems, array.ID, flag)}
}

// InitWithObjects calls -[NSArray initWithObjects:].
func (o NSArray) InitWithObjects(firstObj objc.ID) NSArray {
	return NSArray{o.ID.Send(selInitWithObjects, firstObj)}
}

// IsEqualToArray calls -[NSArray isEqualToArray:].
func (o NSArray) IsEqualToArray(otherArray NSArray) bool {
	return objc.Send[bool](o.ID, selIsEqualToArray, otherArray.ID)
}

// MakeObjectsPerformSelector calls -[NSArray makeObjectsPerformSelector:].
func (o NSArray) MakeObjectsPerformSelector(aSelector objc.SEL) {
	o.ID.Send(selMakeObjectsPerformSelector, aSelector)
}

// MakeObjectsPerformSelectorWithObject calls -[NSArray makeObjectsPerformSelector:withObject:].
func (o NSArray) MakeObjectsPerformSelectorWithObject(aSelector objc.SEL, argument objc.ID) {
	o.ID.Send(selMakeObjectsPerformSelectorWithObject, aSelector, argument)
}

// ObjectAtIndex calls -[NSArray objectAtIndex:].
func (o NSArray) ObjectAtIndex(index uint) objc.ID {
	return o.ID.Send(selObjectAtIndex, index)
}

// ObjectAtIndexedSubscript calls -[NSArray objectAtIndexedSubscript:].
func (o NSArray) ObjectAtIndexedSubscript(idx uint) objc.ID {
	return o.ID.Send(selObjectAtIndexedSubscript, idx)
}

// PathsMatchingExtensions calls -[NSArray pathsMatchingExtensions:].
func (o NSArray) PathsMatchingExtensions(filterTypes NSArray) NSArray {
	return NSArray{o.ID.Send(selPathsMatchingExtensions, filterTypes.ID)}
}

// SetValueForKey — Invoke -setValue:forKey: on each of the receiver's elements.
func (o NSArray) SetValueForKey(value objc.ID, key string) {
	o.ID.Send(selSetValueForKey, value, objcrt.NSString(key))
}

// SortedArrayUsingDescriptors calls -[NSArray sortedArrayUsingDescriptors:].
func (o NSArray) SortedArrayUsingDescriptors(sortDescriptors NSArray) NSArray {
	return NSArray{o.ID.Send(selSortedArrayUsingDescriptors, sortDescriptors.ID)}
}

// SortedArrayUsingSelector calls -[NSArray sortedArrayUsingSelector:].
func (o NSArray) SortedArrayUsingSelector(comparator objc.SEL) NSArray {
	return NSArray{o.ID.Send(selSortedArrayUsingSelector, comparator)}
}

// ValueForKey — Return an array containing the results of invoking -valueForKey: on each of the receiver's elements. The returned array will contain NSNull elements for each instance of -valueForKey: returning nil.
func (o NSArray) ValueForKey(key string) objc.ID {
	return o.ID.Send(selValueForKey, objcrt.NSString(key))
}

// Array calls +[NSArray array].
func (c NSArrayClass) Array() NSArray {
	return NSArray{objc.ID(c.Class).Send(selArray)}
}

// ArrayWithArray calls +[NSArray arrayWithArray:].
func (c NSArrayClass) ArrayWithArray(array NSArray) NSArray {
	return NSArray{objc.ID(c.Class).Send(selArrayWithArray, array.ID)}
}

// ArrayWithObject calls +[NSArray arrayWithObject:].
func (c NSArrayClass) ArrayWithObject(anObject objc.ID) NSArray {
	return NSArray{objc.ID(c.Class).Send(selArrayWithObject, anObject)}
}

// ArrayWithObjects calls +[NSArray arrayWithObjects:].
func (c NSArrayClass) ArrayWithObjects(firstObj objc.ID) NSArray {
	return NSArray{objc.ID(c.Class).Send(selArrayWithObjects, firstObj)}
}
