// Code generated by tools/bindgen. DO NOT EDIT.
//
// Source: iPhoneSimulator26.2.sdk (Xcode 26.2), target arm64-apple-ios26.2-simulator
// Frameworks: Foundation, UIKit
//
// Regenerate with: tools/bindgen/regen.sh

//go:build darwin

package uikit

import (
	"github.com/adriaanm/wata/go-pkgs/appleptt/objcrt"
	"github.com/ebitengine/purego/objc"
)

// UIApplication wraps the ObjC class UIApplication (UIResponder subclass).
type UIApplication struct{ objc.ID }

// UIApplicationClass is the class object of UIApplication.
type UIApplicationClass struct{ objc.Class }

// GetUIApplicationClass looks the class up in the ObjC runtime.
func GetUIApplicationClass() UIApplicationClass {
	return UIApplicationClass{objc.GetClass("UIApplication")}
}

// Alloc allocates an uninitialized UIApplication (-[NSObject alloc]).
func (c UIApplicationClass) Alloc() UIApplication {
	return UIApplication{objc.ID(c.Class).Send(selAlloc)}
}

// ApplicationIconBadgeNumber reads the UIApplication property applicationIconBadgeNumber.
func (o UIApplication) ApplicationIconBadgeNumber() int {
	return objc.Send[int](o.ID, selApplicationIconBadgeNumber)
}

// SetApplicationIconBadgeNumber writes the UIApplication property applicationIconBadgeNumber.
func (o UIApplication) SetApplicationIconBadgeNumber(v int) {
	o.ID.Send(selSetApplicationIconBadgeNumber, v)
}

// ApplicationSupportsShakeToEdit reads the UIApplication property applicationSupportsShakeToEdit.
func (o UIApplication) ApplicationSupportsShakeToEdit() bool {
	return objc.Send[bool](o.ID, selApplicationSupportsShakeToEdit)
}

// SetApplicationSupportsShakeToEdit writes the UIApplication property applicationSupportsShakeToEdit.
func (o UIApplication) SetApplicationSupportsShakeToEdit(v bool) {
	o.ID.Send(selSetApplicationSupportsShakeToEdit, v)
}

// BackgroundTimeRemaining reads the UIApplication property backgroundTimeRemaining.
func (o UIApplication) BackgroundTimeRemaining() float64 {
	return objc.Send[float64](o.ID, selBackgroundTimeRemaining)
}

// Delegate reads the UIApplication property delegate.
func (o UIApplication) Delegate() objc.ID {
	return o.ID.Send(selDelegate)
}

// SetDelegate writes the UIApplication property delegate.
func (o UIApplication) SetDelegate(v objc.ID) {
	o.ID.Send(selSetDelegate, v)
}

// IdleTimerDisabled reads the UIApplication property idleTimerDisabled.
func (o UIApplication) IdleTimerDisabled() bool {
	return objc.Send[bool](o.ID, selIsIdleTimerDisabled)
}

// SetIdleTimerDisabled writes the UIApplication property idleTimerDisabled.
func (o UIApplication) SetIdleTimerDisabled(v bool) {
	o.ID.Send(selSetIdleTimerDisabled, v)
}

// IgnoringInteractionEvents reads the UIApplication property ignoringInteractionEvents.
func (o UIApplication) IgnoringInteractionEvents() bool {
	return objc.Send[bool](o.ID, selIsIgnoringInteractionEvents)
}

// KeyWindow reads the UIApplication property keyWindow.
func (o UIApplication) KeyWindow() UIWindow {
	return UIWindow{o.ID.Send(selKeyWindow)}
}

// NetworkActivityIndicatorVisible reads the UIApplication property networkActivityIndicatorVisible.
func (o UIApplication) NetworkActivityIndicatorVisible() bool {
	return objc.Send[bool](o.ID, selIsNetworkActivityIndicatorVisible)
}

// SetNetworkActivityIndicatorVisible writes the UIApplication property networkActivityIndicatorVisible.
func (o UIApplication) SetNetworkActivityIndicatorVisible(v bool) {
	o.ID.Send(selSetNetworkActivityIndicatorVisible, v)
}

// PreferredContentSizeCategory reads the UIApplication property preferredContentSizeCategory.
func (o UIApplication) PreferredContentSizeCategory() string {
	return objcrt.GoString(o.ID.Send(selPreferredContentSizeCategory))
}

// ProtectedDataAvailable reads the UIApplication property protectedDataAvailable.
func (o UIApplication) ProtectedDataAvailable() bool {
	return objc.Send[bool](o.ID, selIsProtectedDataAvailable)
}

// ProximitySensingEnabled reads the UIApplication property proximitySensingEnabled.
func (o UIApplication) ProximitySensingEnabled() bool {
	return objc.Send[bool](o.ID, selIsProximitySensingEnabled)
}

// SetProximitySensingEnabled writes the UIApplication property proximitySensingEnabled.
func (o UIApplication) SetProximitySensingEnabled(v bool) {
	o.ID.Send(selSetProximitySensingEnabled, v)
}

// StatusBarFrame reads the UIApplication property statusBarFrame.
func (o UIApplication) StatusBarFrame() CGRect {
	return objc.Send[CGRect](o.ID, selStatusBarFrame)
}

// StatusBarHidden reads the UIApplication property statusBarHidden.
func (o UIApplication) StatusBarHidden() bool {
	return objc.Send[bool](o.ID, selIsStatusBarHidden)
}

// StatusBarOrientationAnimationDuration reads the UIApplication property statusBarOrientationAnimationDuration.
func (o UIApplication) StatusBarOrientationAnimationDuration() float64 {
	return objc.Send[float64](o.ID, selStatusBarOrientationAnimationDuration)
}

// SupportsMultipleScenes reads the UIApplication property supportsMultipleScenes.
func (o UIApplication) SupportsMultipleScenes() bool {
	return objc.Send[bool](o.ID, selSupportsMultipleScenes)
}

// Windows reads the UIApplication property windows.
func (o UIApplication) Windows() NSArray {
	return NSArray{o.ID.Send(selWindows)}
}

// SharedApplication reads the UIApplication class property sharedApplication.
func (c UIApplicationClass) SharedApplication() UIApplication {
	return UIApplication{objc.ID(c.Class).Send(selSharedApplication)}
}

// BeginIgnoringInteractionEvents calls -[UIApplication beginIgnoringInteractionEvents].
func (o UIApplication) BeginIgnoringInteractionEvents() {
	o.ID.Send(selBeginIgnoringInteractionEvents)
}

// BeginReceivingRemoteControlEvents calls -[UIApplication beginReceivingRemoteControlEvents].
func (o UIApplication) BeginReceivingRemoteControlEvents() {
	o.ID.Send(selBeginReceivingRemoteControlEvents)
}

// CancelAllLocalNotifications calls -[UIApplication cancelAllLocalNotifications].
func (o UIApplication) CancelAllLocalNotifications() {
	o.ID.Send(selCancelAllLocalNotifications)
}

// ClearKeepAliveTimeout calls -[UIApplication clearKeepAliveTimeout].
func (o UIApplication) ClearKeepAliveTimeout() {
	o.ID.Send(selClearKeepAliveTimeout)
}

// CompleteStateRestoration calls -[UIApplication completeStateRestoration].
func (o UIApplication) CompleteStateRestoration() {
	o.ID.Send(selCompleteStateRestoration)
}

// EndBackgroundTask calls -[UIApplication endBackgroundTask:].
func (o UIApplication) EndBackgroundTask(identifier uint) {
	o.ID.Send(selEndBackgroundTask, identifier)
}

// EndIgnoringInteractionEvents calls -[UIApplication endIgnoringInteractionEvents].
func (o UIApplication) EndIgnoringInteractionEvents() {
	o.ID.Send(selEndIgnoringInteractionEvents)
}

// EndReceivingRemoteControlEvents calls -[UIApplication endReceivingRemoteControlEvents].
func (o UIApplication) EndReceivingRemoteControlEvents() {
	o.ID.Send(selEndReceivingRemoteControlEvents)
}

// ExtendStateRestoration calls -[UIApplication extendStateRestoration].
func (o UIApplication) ExtendStateRestoration() {
	o.ID.Send(selExtendStateRestoration)
}

// IgnoreSnapshotOnNextApplicationLaunch calls -[UIApplication ignoreSnapshotOnNextApplicationLaunch].
func (o UIApplication) IgnoreSnapshotOnNextApplicationLaunch() {
	o.ID.Send(selIgnoreSnapshotOnNextApplicationLaunch)
}

// RegisterForRemoteNotifications calls -[UIApplication registerForRemoteNotifications].
func (o UIApplication) RegisterForRemoteNotifications() {
	o.ID.Send(selRegisterForRemoteNotifications)
}

// SetAlternateIconNameCompletionHandler calls -[UIApplication setAlternateIconName:completionHandler:].
func (o UIApplication) SetAlternateIconNameCompletionHandler(alternateIconName string, completionHandler func(error)) {
	blockCompletionHandler := objc.NewBlock(func(_ objc.Block, a0 objc.ID) {
		completionHandler(objcrt.GoError(a0))
	})
	defer blockCompletionHandler.Release()
	o.ID.Send(selSetAlternateIconNameCompletionHandler, objcrt.NSString(alternateIconName), blockCompletionHandler)
}

// SetKeepAliveTimeoutHandler calls -[UIApplication setKeepAliveTimeout:handler:].
func (o UIApplication) SetKeepAliveTimeoutHandler(timeout float64, keepAliveHandler func()) bool {
	blockKeepAliveHandler := objc.NewBlock(func(_ objc.Block) {
		keepAliveHandler()
	})
	defer blockKeepAliveHandler.Release()
	return objc.Send[bool](o.ID, selSetKeepAliveTimeoutHandler, timeout, blockKeepAliveHandler)
}

// SetMinimumBackgroundFetchInterval — ! The system guarantees that it will not wake up your application for a background fetch more
// frequently than the interval provided. Set to UIApplicationBackgroundFetchIntervalMinimum to be
// woken as frequently as the system desires, or to UIApplicationBackgroundFetchIntervalNever (the
// default) to never be woken for a background fetch.
// This setter will have no effect unless your application has the "fetch"
// UIBackgroundMode. See the UIApplicationDelegate method
// `application:performFetchWithCompletionHandler:` for more.
func (o UIApplication) SetMinimumBackgroundFetchInterval(minimumBackgroundFetchInterval float64) {
	o.ID.Send(selSetMinimumBackgroundFetchInterval, minimumBackgroundFetchInterval)
}

// SetNewsstandIconImage calls -[UIApplication setNewsstandIconImage:].
func (o UIApplication) SetNewsstandIconImage(image UIImage) {
	o.ID.Send(selSetNewsstandIconImage, image.ID)
}

// SetStatusBarHiddenAnimated calls -[UIApplication setStatusBarHidden:animated:].
func (o UIApplication) SetStatusBarHiddenAnimated(hidden bool, animated bool) {
	o.ID.Send(selSetStatusBarHiddenAnimated, hidden, animated)
}

// UnregisterForRemoteNotifications calls -[UIApplication unregisterForRemoteNotifications].
func (o UIApplication) UnregisterForRemoteNotifications() {
	o.ID.Send(selUnregisterForRemoteNotifications)
}

// RegisterObjectForStateRestorationRestorationIdentifier calls +[UIApplication registerObjectForStateRestoration:restorationIdentifier:].
func (c UIApplicationClass) RegisterObjectForStateRestorationRestorationIdentifier(object objc.ID, restorationIdentifier string) {
	objc.ID(c.Class).Send(selRegisterObjectForStateRestorationRestorationIdentifier, object, objcrt.NSString(restorationIdentifier))
}
