// Code generated by tools/bindgen. DO NOT EDIT.
//
// Source: iPhoneSimulator26.2.sdk (Xcode 26.2), target arm64-apple-ios26.2-simulator
// Frameworks: Foundation, UIKit
//
// Regenerate with: tools/bindgen/regen.sh

//go:build darwin

package uikit

import (
	"github.com/adriaanm/wata/go-pkgs/appleptt/objcrt"
	"github.com/ebitengine/purego/objc"
)

// UIColor wraps the ObjC class UIColor (NSObject subclass).
type UIColor struct{ objc.ID }

// UIColorClass is the class object of UIColor.
type UIColorClass struct{ objc.Class }

// GetUIColorClass looks the class up in the ObjC runtime.
func GetUIColorClass() UIColorClass { return UIColorClass{objc.GetClass("UIColor")} }

// Alloc allocates an uninitialized UIColor (-[NSObject alloc]).
func (c UIColorClass) Alloc() UIColor { return UIColor{objc.ID(c.Class).Send(selAlloc)} }

// LinearExposure — The linear brightness multiplier that was applied when generating this color. Colors created with an exposure by UIColor create CGColors that are tagged with a contentHeadroom value. While CGColors created without a contentHeadroom tag will return 0 from CGColorGetHeadroom, UIColors generated in a similar fashion return a linearExposure of 1.0.
func (o UIColor) LinearExposure() float64 {
	return objc.Send[float64](o.ID, selLinearExposure)
}

// StandardDynamicRangeColor — In some cases it is useful to recover the color that was base SDR color that was exposed to generate the given HDR color. If a color's `linearExposure` is >1, then this will return the base SDR color.
func (o UIColor) StandardDynamicRangeColor() UIColor {
	return UIColor{o.ID.Send(selStandardDynamicRangeColor)}
}

// BlackColor reads the UIColor class property blackColor.
func (c UIColorClass) BlackColor() UIColor {
	return UIColor{objc.ID(c.Class).Send(selBlackColor)}
}

// BlueColor reads the UIColor class property blueColor.
func (c UIColorClass) BlueColor() UIColor {
	return UIColor{objc.ID(c.Class).Send(selBlueColor)}
}

// BrownColor reads the UIColor class property brownColor.
func (c UIColorClass) BrownColor() UIColor {
	return UIColor{objc.ID(c.Class).Send(selBrownColor)}
}

// ClearColor reads the UIColor class property clearColor.
func (c UIColorClass) ClearColor() UIColor {
	return UIColor{objc.ID(c.Class).Send(selClearColor)}
}

// CyanColor reads the UIColor class property cyanColor.
func (c UIColorClass) CyanColor() UIColor {
	return UIColor{objc.ID(c.Class).Send(selCyanColor)}
}

// DarkGrayColor reads the UIColor class property darkGrayColor.
func (c UIColorClass) DarkGrayColor() UIColor {
	return UIColor{objc.ID(c.Class).Send(selDarkGrayColor)}
}

// DarkTextColor reads the UIColor class property darkTextColor.
func (c UIColorClass) DarkTextColor() UIColor {
	return UIColor{objc.ID(c.Class).Send(selDarkTextColor)}
}

// GrayColor reads the UIColor class property grayColor.
func (c UIColorClass) GrayColor() UIColor {
	return UIColor{objc.ID(c.Class).Send(selGrayColor)}
}

// GreenColor reads the UIColor class property greenColor.
func (c UIColorClass) GreenColor() UIColor {
	return UIColor{objc.ID(c.Class).Send(selGreenColor)}
}

// GroupTableViewBackgroundColor — groupTableViewBackgroundColor is now the same as systemGroupedBackgroundColor.
func (c UIColorClass) GroupTableViewBackgroundColor() UIColor {
	return UIColor{objc.ID(c.Class).Send(selGroupTableViewBackgroundColor)}
}

// LabelColor — Foreground colors for static text and related elements.
func (c UIColorClass) LabelColor() UIColor {
	return UIColor{objc.ID(c.Class).Send(selLabelColor)}
}

// LightGrayColor reads the UIColor class property lightGrayColor.
func (c UIColorClass) LightGrayColor() UIColor {
	return UIColor{objc.ID(c.Class).Send(selLightGrayColor)}
}

// LightTextColor — lightTextColor is always light, and darkTextColor is always dark, regardless of the current UIUserInterfaceStyle.
// When possible, we recommend using `labelColor` and its variants, instead.
func (c UIColorClass) LightTextColor() UIColor {
	return UIColor{objc.ID(c.Class).Send(selLightTextColor)}
}

// LinkColor — Foreground color for standard system links.
func (c UIColorClass) LinkColor() UIColor {
	return UIColor{objc.ID(c.Class).Send(selLinkColor)}
}

// MagentaColor reads the UIColor class property magentaColor.
func (c UIColorClass) MagentaColor() UIColor {
	return UIColor{objc.ID(c.Class).Send(selMagentaColor)}
}

// OpaqueSeparatorColor reads the UIColor class property opaqueSeparatorColor.
func (c UIColorClass) OpaqueSeparatorColor() UIColor {
	return UIColor{objc.ID(c.Class).Send(selOpaqueSeparatorColor)}
}

// OrangeColor reads the UIColor class property orangeColor.
func (c UIColorClass) OrangeColor() UIColor {
	return UIColor{objc.ID(c.Class).Send(selOrangeColor)}
}

// PlaceholderTextColor — Foreground color for placeholder text in controls or text fields or text views.
func (c UIColorClass) PlaceholderTextColor() UIColor {
	return UIColor{objc.ID(c.Class).Send(selPlaceholderTextColor)}
}

// PurpleColor reads the UIColor class property purpleColor.
func (c UIColorClass) PurpleColor() UIColor {
	return UIColor{objc.ID(c.Class).Send(selPurpleColor)}
}

// QuaternaryLabelColor reads the UIColor class property quaternaryLabelColor.
func (c UIColorClass) QuaternaryLabelColor() UIColor {
	return UIColor{objc.ID(c.Class).Send(selQuaternaryLabelColor)}
}

// QuaternarySystemFillColor — quaternarySystemFillColor is appropriate for filling large areas containing complex content.
// Example: Expanded table cells.
func (c UIColorClass) QuaternarySystemFillColor() UIColor {
	return UIColor{objc.ID(c.Class).Send(selQuaternarySystemFillColor)}
}

// RedColor reads the UIColor class property redColor.
func (c UIColorClass) RedColor() UIColor {
	return UIColor{objc.ID(c.Class).Send(selRedColor)}
}

// ScrollViewTexturedBackgroundColor reads the UIColor class property scrollViewTexturedBackgroundColor.
func (c UIColorClass) ScrollViewTexturedBackgroundColor() UIColor {
	return UIColor{objc.ID(c.Class).Send(selScrollViewTexturedBackgroundColor)}
}

// SecondaryLabelColor reads the UIColor class property secondaryLabelColor.
func (c UIColorClass) SecondaryLabelColor() UIColor {
	return UIColor{objc.ID(c.Class).Send(selSecondaryLabelColor)}
}

// SecondarySystemBackgroundColor reads the UIColor class property secondarySystemBackgroundColor.
func (c UIColorClass) SecondarySystemBackgroundColor() UIColor {
	return UIColor{objc.ID(c.Class).Send(selSecondarySystemBackgroundColor)}
}

// SecondarySystemFillColor — secondarySystemFillColor is appropriate for filling medium-size shapes.
// Example: The background of a switch.
func (c UIColorClass) SecondarySystemFillColor() UIColor {
	return UIColor{objc.ID(c.Class).Send(selSecondarySystemFillColor)}
}

// SecondarySystemGroupedBackgroundColor reads the UIColor class property secondarySystemGroupedBackgroundColor.
func (c UIColorClass) SecondarySystemGroupedBackgroundColor() UIColor {
	return UIColor{objc.ID(c.Class).Send(selSecondarySystemGroupedBackgroundColor)}
}

// SeparatorColor — Foreground colors for separators (thin border or divider lines).
// `separatorColor` may be partially transparent, so it can go on top of any content.
// `opaqueSeparatorColor` is intended to look similar, but is guaranteed to be opaque, so it will
// completely cover anything behind it. Depending on the situation, you may need one or the other.
func (c UIColorClass) SeparatorColor() UIColor {
	return UIColor{objc.ID(c.Class).Send(selSeparatorColor)}
}

// SystemBackgroundColor — We provide two design systems (also known as "stacks") for structuring an iOS app's backgrounds.
// Each stack has three "levels" of background colors. The first color is intended to be the
// main background, farthest back. Secondary and tertiary colors are layered on top
// of the main background, when appropriate.
// Inside of a discrete piece of UI, choose a stack, then use colors from that stack.
// We do not recommend mixing and matching background colors between stacks.
// The foreground colors above are designed to work in both stacks.
// 1. systemBackground
// Use this stack for views with standard table views, and designs which have a white
// primary background in light mode.
func (c UIColorClass) SystemBackgroundColor() UIColor {
	return UIColor{objc.ID(c.Class).Send(selSystemBackgroundColor)}
}

// SystemBlueColor reads the UIColor class property systemBlueColor.
func (c UIColorClass) SystemBlueColor() UIColor {
	return UIColor{objc.ID(c.Class).Send(selSystemBlueColor)}
}

// SystemBrownColor reads the UIColor class property systemBrownColor.
func (c UIColorClass) SystemBrownColor() UIColor {
	return UIColor{objc.ID(c.Class).Send(selSystemBrownColor)}
}

// SystemCyanColor reads the UIColor class property systemCyanColor.
func (c UIColorClass) SystemCyanColor() UIColor {
	return UIColor{objc.ID(c.Class).Send(selSystemCyanColor)}
}

// SystemFillColor — Fill colors for UI elements.
// These are meant to be used over the background colors, since their alpha component is less than 1.
// systemFillColor is appropriate for filling thin and small shapes.
// Example: The track of a slider.
func (c UIColorClass) SystemFillColor() UIColor {
	return UIColor{objc.ID(c.Class).Send(selSystemFillColor)}
}

// SystemGray2Color — The numbered variations, systemGray2 through systemGray6, are grays which increasingly
// trend away from systemGray and in the direction of systemBackgroundColor.
// In UIUserInterfaceStyleLight: systemGray2 is slightly lighter than systemGray.
// systemGray3 is lighter than that, and so on.
// In UIUserInterfaceStyleDark:  systemGray2 is slightly darker than systemGray.
// systemGray3 is darker than that, and so on.
func (c UIColorClass) SystemGray2Color() UIColor {
	return UIColor{objc.ID(c.Class).Send(selSystemGray2Color)}
}

// SystemGray3Color reads the UIColor class property systemGray3Color.
func (c UIColorClass) SystemGray3Color() UIColor {
	return UIColor{objc.ID(c.Class).Send(selSystemGray3Color)}
}

// SystemGray4Color reads the UIColor class property systemGray4Color.
func (c UIColorClass) SystemGray4Color() UIColor {
	return UIColor{objc.ID(c.Class).Send(selSystemGray4Color)}
}

// SystemGray5Color reads the UIColor class property systemGray5Color.
func (c UIColorClass) SystemGray5Color() UIColor {
	return UIColor{objc.ID(c.Class).Send(selSystemGray5Color)}
}

// SystemGray6Color reads the UIColor class property systemGray6Color.
func (c UIColorClass) SystemGray6Color() UIColor {
	return UIColor{objc.ID(c.Class).Send(selSystemGray6Color)}
}

// SystemGrayColor — Shades of gray. systemGray is the base gray color.
func (c UIColorClass) SystemGrayColor() UIColor {
	return UIColor{objc.ID(c.Class).Send(selSystemGrayColor)}
}

// SystemGreenColor reads the UIColor class property systemGreenColor.
func (c UIColorClass) SystemGreenColor() UIColor {
	return UIColor{objc.ID(c.Class).Send(selSystemGreenColor)}
}

// SystemGroupedBackgroundColor — 2. systemGroupedBackground
// Use this stack for views with grouped content, such as grouped tables and
// platter-based designs. These are like grouped table views, but you may use these
// colors in places where a table view wouldn't make sense.
func (c UIColorClass) SystemGroupedBackgroundColor() UIColor {
	return UIColor{objc.ID(c.Class).Send(selSystemGroupedBackgroundColor)}
}

// SystemIndigoColor reads the UIColor class property systemIndigoColor.
func (c UIColorClass) SystemIndigoColor() UIColor {
	return UIColor{objc.ID(c.Class).Send(selSystemIndigoColor)}
}

// SystemMintColor reads the UIColor class property systemMintColor.
func (c UIColorClass) SystemMintColor() UIColor {
	return UIColor{objc.ID(c.Class).Send(selSystemMintColor)}
}

// SystemOrangeColor reads the UIColor class property systemOrangeColor.
func (c UIColorClass) SystemOrangeColor() UIColor {
	return UIColor{objc.ID(c.Class).Send(selSystemOrangeColor)}
}

// SystemPinkColor reads the UIColor class property systemPinkColor.
func (c UIColorClass) SystemPinkColor() UIColor {
	return UIColor{objc.ID(c.Class).Send(selSystemPinkColor)}
}

// SystemPurpleColor reads the UIColor class property systemPurpleColor.
func (c UIColorClass) SystemPurpleColor() UIColor {
	return UIColor{objc.ID(c.Class).Send(selSystemPurpleColor)}
}

// SystemRedColor — Some colors that are used by system elements and applications.
// These return named colors whose values may vary between different contexts and releases.
// Do not make assumptions about the color spaces or actual colors used.
func (c UIColorClass) SystemRedColor() UIColor {
	return UIColor{objc.ID(c.Class).Send(selSystemRedColor)}
}

// SystemTealColor reads the UIColor class property systemTealColor.
func (c UIColorClass) SystemTealColor() UIColor {
	return UIColor{objc.ID(c.Class).Send(selSystemTealColor)}
}

// SystemYellowColor reads the UIColor class property systemYellowColor.
func (c UIColorClass) SystemYellowColor() UIColor {
	return UIColor{objc.ID(c.Class).Send(selSystemYellowColor)}
}

// TertiaryLabelColor reads the UIColor class property tertiaryLabelColor.
func (c UIColorClass) TertiaryLabelColor() UIColor {
	return UIColor{objc.ID(c.Class).Send(selTertiaryLabelColor)}
}

// TertiarySystemBackgroundColor reads the UIColor class property tertiarySystemBackgroundColor.
func (c UIColorClass) TertiarySystemBackgroundColor() UIColor {
	return UIColor{objc.ID(c.Class).Send(selTertiarySystemBackgroundColor)}
}

// TertiarySystemFillColor — tertiarySystemFillColor is appropriate for filling large shapes.
// Examples: Input fields, search bars, buttons.
func (c UIColorClass) TertiarySystemFillColor() UIColor {
	return UIColor{objc.ID(c.Class).Send(selTertiarySystemFillColor)}
}

// TertiarySystemGroupedBackgroundColor reads the UIColor class property tertiarySystemGroupedBackgroundColor.
func (c UIColorClass) TertiarySystemGroupedBackgroundColor() UIColor {
	return UIColor{objc.ID(c.Class).Send(selTertiarySystemGroupedBackgroundColor)}
}

// TintColor — This color represents the tint color of a view.
// Like other dynamic colors, UIColor.tintColor relies on UITraitCollection.currentTraitCollection
// being set to a view's trait collection when it is used, so that it can resolve to that view's
// tint color. If you use UIColor.tintColor outside a view's context, and do not resolve it
// manually with a view's trait collection, it will return the system default tint color.
// Setting UIColor.tintColor directly to a view's tintColor property behaves the same as setting nil.
// However, you cannot set a custom dynamic color (e.g. using +[UIColor colorWithDynamicProvider:])
// that can resolve to UIColor.tintColor to a view's tintColor property.
func (c UIColorClass) TintColor() UIColor {
	return UIColor{objc.ID(c.Class).Send(selTintColor)}
}

// UnderPageBackgroundColor reads the UIColor class property underPageBackgroundColor.
func (c UIColorClass) UnderPageBackgroundColor() UIColor {
	return UIColor{objc.ID(c.Class).Send(selUnderPageBackgroundColor)}
}

// ViewFlipsideBackgroundColor reads the UIColor class property viewFlipsideBackgroundColor.
func (c UIColorClass) ViewFlipsideBackgroundColor() UIColor {
	return UIColor{objc.ID(c.Class).Send(selViewFlipsideBackgroundColor)}
}

// WhiteColor reads the UIColor class property whiteColor.
func (c UIColorClass) WhiteColor() UIColor {
	return UIColor{objc.ID(c.Class).Send(selWhiteColor)}
}

// YellowColor reads the UIColor class property yellowColor.
func (c UIColorClass) YellowColor() UIColor {
	return UIColor{objc.ID(c.Class).Send(selYellowColor)}
}

// ColorByApplyingContentHeadroom — Reinterpret the color by applying a new `contentHeadroom` without changing the color components. Changing the `contentHeadroom` redefines the color relative to a different peak white, changing its behavior under tone mapping and the result of calling `standardDynamicRangeColor`. The new color will have a `contentHeadroom` >= 1.0.
func (o UIColor) ColorByApplyingContentHeadroom(contentHeadroom float64) UIColor {
	return UIColor{o.ID.Send(selColorByApplyingContentHeadroom, contentHeadroom)}
}

// ColorWithAlphaComponent calls -[UIColor colorWithAlphaComponent:].
func (o UIColor) ColorWithAlphaComponent(alpha float64) UIColor {
	return UIColor{o.ID.Send(selColorWithAlphaComponent, alpha)}
}

// InitWithDisplayP3RedGreenBlueAlpha calls -[UIColor initWithDisplayP3Red:green:blue:alpha:].
func (o UIColor) InitWithDisplayP3RedGreenBlueAlpha(displayP3Red float64, green float64, blue float64, alpha float64) UIColor {
	return UIColor{o.ID.Send(selInitWithDisplayP3RedGreenBlueAlpha, displayP3Red, green, blue, alpha)}
}

// InitWithHueSaturationBrightnessAlpha calls -[UIColor initWithHue:saturation:brightness:alpha:].
func (o UIColor) InitWithHueSaturationBrightnessAlpha(hue float64, saturation float64, brightness float64, alpha float64) UIColor {
	return UIColor{o.ID.Send(selInitWithHueSaturationBrightnessAlpha, hue, saturation, brightness, alpha)}
}

// InitWithPatternImage calls -[UIColor initWithPatternImage:].
func (o UIColor) InitWithPatternImage(image UIImage) UIColor {
	return UIColor{o.ID.Send(selInitWithPatternImage, image.ID)}
}

// InitWithRedGreenBlueAlpha calls -[UIColor initWithRed:green:blue:alpha:].
func (o UIColor) InitWithRedGreenBlueAlpha(red float64, green float64, blue float64, alpha float64) UIColor {
	return UIColor{o.ID.Send(selInitWithRedGreenBlueAlpha, red, green, blue, alpha)}
}

// InitWithRedGreenBlueAlphaExposure — Generates an HDR color by applying an exposure to the SDR color defined by the red, green, and blue components. The `red`, `green`, and `blue` components have a nominal range of [0..1], `exposure` is a value >= 0. To produce an HDR color, we process the given color in a linear color space, multiplying component values by `2^exposure`. The produced color will have a `contentHeadroom` equal to the linearized exposure value. Each whole value of exposure produces a color that is twice as bright.
func (o UIColor) InitWithRedGreenBlueAlphaExposure(red float64, green float64, blue float64, alpha float64, exposure float64) UIColor {
	return UIColor{o.ID.Send(selInitWithRedGreenBlueAlphaExposure, red, green, blue, alpha, exposure)}
}

// InitWithRedGreenBlueAlphaLinearExposure — Generates an HDR color by applying an exposure to the SDR color defined by the red, green, and blue components. The `red`, `green`, and `blue` components have a nominal range of [0..1], `linearExposure` is a value >= 1. To produce an HDR color, we process the given color in a linear color space, multiplying component values by `linearExposure `. The produced color will have a `contentHeadroom` equal to `linearExposure`. Each doubling of `linearExposure` produces a color that is twice as bright.
func (o UIColor) InitWithRedGreenBlueAlphaLinearExposure(red float64, green float64, blue float64, alpha float64, linearExposure float64) UIColor {
	return UIColor{o.ID.Send(selInitWithRedGreenBlueAlphaLinearExposure, red, green, blue, alpha, linearExposure)}
}

// InitWithWhiteAlpha calls -[UIColor initWithWhite:alpha:].
func (o UIColor) InitWithWhiteAlpha(white float64, alpha float64) UIColor {
	return UIColor{o.ID.Send(selInitWithWhiteAlpha, white, alpha)}
}

// Set calls -[UIColor set].
func (o UIColor) Set() {
	o.ID.Send(selSet)
}

// SetFill calls -[UIColor setFill].
func (o UIColor) SetFill() {
	o.ID.Send(selSetFill)
}

// SetStroke calls -[UIColor setStroke].
func (o UIColor) SetStroke() {
	o.ID.Send(selSetStroke)
}

// ColorNamed calls +[UIColor colorNamed:].
func (c UIColorClass) ColorNamed(name string) UIColor {
	return UIColor{objc.ID(c.Class).Send(selColorNamed, objcrt.NSString(name))}
}

// ColorWithDisplayP3RedGreenBlueAlpha calls +[UIColor colorWithDisplayP3Red:green:blue:alpha:].
func (c UIColorClass) ColorWithDisplayP3RedGreenBlueAlpha(displayP3Red float64, green float64, blue float64, alpha float64) UIColor {
	return UIColor{objc.ID(c.Class).Send(selColorWithDisplayP3RedGreenBlueAlpha, displayP3Red, green, blue, alpha)}
}

// ColorWithHueSaturationBrightnessAlpha calls +[UIColor colorWithHue:saturation:brightness:alpha:].
func (c UIColorClass) ColorWithHueSaturationBrightnessAlpha(hue float64, saturation float64, brightness float64, alpha float64) UIColor {
	return UIColor{objc.ID(c.Class).Send(selColorWithHueSaturationBrightnessAlpha, hue, saturation, brightness, alpha)}
}

// ColorWithPatternImage calls +[UIColor colorWithPatternImage:].
func (c UIColorClass) ColorWithPatternImage(image UIImage) UIColor {
	return UIColor{objc.ID(c.Class).Send(selColorWithPatternImage, image.ID)}
}

// ColorWithRedGreenBlueAlpha calls +[UIColor colorWithRed:green:blue:alpha:].
func (c UIColorClass) ColorWithRedGreenBlueAlpha(red float64, green float64, blue float64, alpha float64) UIColor {
	return UIColor{objc.ID(c.Class).Send(selColorWithRedGreenBlueAlpha, red, green, blue, alpha)}
}

// ColorWithRedGreenBlueAlphaExposure calls +[UIColor colorWithRed:green:blue:alpha:exposure:].
func (c UIColorClass) ColorWithRedGreenBlueAlphaExposure(red float64, green float64, blue float64, alpha float64, exposure float64) UIColor {
	return UIColor{objc.ID(c.Class).Send(selColorWithRedGreenBlueAlphaExposure, red, green, blue, alpha, exposure)}
}

// ColorWithRedGreenBlueAlphaLinearExposure calls +[UIColor colorWithRed:green:blue:alpha:linearExposure:].
func (c UIColorClass) ColorWithRedGreenBlueAlphaLinearExposure(red float64, green float64, blue float64, alpha float64, linearExposure float64) UIColor {
	return UIColor{objc.ID(c.Class).Send(selColorWithRedGreenBlueAlphaLinearExposure, red, green, blue, alpha, linearExposure)}
}

// ColorWithWhiteAlpha calls +[UIColor colorWithWhite:alpha:].
func (c UIColorClass) ColorWithWhiteAlpha(white float64, alpha float64) UIColor {
	return UIColor{objc.ID(c.Class).Send(selColorWithWhiteAlpha, white, alpha)}
}
