// Code generated by tools/bindgen. DO NOT EDIT.
//
// Source: iPhoneSimulator26.2.sdk (Xcode 26.2), target arm64-apple-ios26.2-simulator
// Frameworks: Foundation, UIKit
//
// Regenerate with: tools/bindgen/regen.sh

//go:build darwin

package uikit

import (
	"github.com/adriaanm/wata/go-pkgs/appleptt/objcrt"
	"github.com/ebitengine/purego/objc"
)

// UIFont wraps the ObjC class UIFont (NSObject subclass).
type UIFont struct{ objc.ID }

// UIFontClass is the class object of UIFont.
type UIFontClass struct{ objc.Class }

// GetUIFontClass looks the class up in the ObjC runtime.
func GetUIFontClass() UIFontClass { return UIFontClass{objc.GetClass("UIFont")} }

// Alloc allocates an uninitialized UIFont (-[NSObject alloc]).
func (c UIFontClass) Alloc() UIFont { return UIFont{objc.ID(c.Class).Send(selAlloc)} }

// Ascender reads the UIFont property ascender.
func (o UIFont) Ascender() float64 {
	return objc.Send[float64](o.ID, selAscender)
}

// CapHeight reads the UIFont property capHeight.
func (o UIFont) CapHeight() float64 {
	return objc.Send[float64](o.ID, selCapHeight)
}

// Descender reads the UIFont property descender.
func (o UIFont) Descender() float64 {
	return objc.Send[float64](o.ID, selDescender)
}

// FamilyName reads the UIFont property familyName.
func (o UIFont) FamilyName() string {
	return objcrt.GoString(o.ID.Send(selFamilyName))
}

// FontName reads the UIFont property fontName.
func (o UIFont) FontName() string {
	return objcrt.GoString(o.ID.Send(selFontName))
}

// Leading reads the UIFont property leading.
func (o UIFont) Leading() float64 {
	return objc.Send[float64](o.ID, selLeading)
}

// LineHeight reads the UIFont property lineHeight.
func (o UIFont) LineHeight() float64 {
	return objc.Send[float64](o.ID, selLineHeight)
}

// PointSize reads the UIFont property pointSize.
func (o UIFont) PointSize() float64 {
	return objc.Send[float64](o.ID, selPointSize)
}

// XHeight reads the UIFont property xHeight.
func (o UIFont) XHeight() float64 {
	return objc.Send[float64](o.ID, selXHeight)
}

// ButtonFontSize reads the UIFont class property buttonFontSize.
func (c UIFontClass) ButtonFontSize() float64 {
	return objc.Send[float64](objc.ID(c.Class), selButtonFontSize)
}

// DefaultFontSize reads the UIFont class property defaultFontSize.
func (c UIFontClass) DefaultFontSize() float64 {
	return objc.Send[float64](objc.ID(c.Class), selDefaultFontSize)
}

// FamilyNames reads the UIFont class property familyNames.
func (c UIFontClass) FamilyNames() NSArray {
	return NSArray{objc.ID(c.Class).Send(selFamilyNames)}
}

// LabelFontSize reads the UIFont class property labelFontSize.
func (c UIFontClass) LabelFontSize() float64 {
	return objc.Send[float64](objc.ID(c.Class), selLabelFontSize)
}

// SmallSystemFontSize reads the UIFont class property smallSystemFontSize.
func (c UIFontClass) SmallSystemFontSize() float64 {
	return objc.Send[float64](objc.ID(c.Class), selSmallSystemFontSize)
}

// SystemFontSize reads the UIFont class property systemFontSize.
func (c UIFontClass) SystemFontSize() float64 {
	return objc.Send[float64](objc.ID(c.Class), selSystemFontSize)
}

// SystemMinimumFontSize reads the UIFont class property systemMinimumFontSize.
func (c UIFontClass) SystemMinimumFontSize() float64 {
	return objc.Send[float64](objc.ID(c.Class), selSystemMinimumFontSize)
}

// FontWithSize calls -[UIFont fontWithSize:].
func (o UIFont) FontWithSize(fontSize float64) UIFont {
	return UIFont{o.ID.Send(selFontWithSize, fontSize)}
}

// BoldSystemFontOfSize calls +[UIFont boldSystemFontOfSize:].
func (c UIFontClass) BoldSystemFontOfSize(fontSize float64) UIFont {
	return UIFont{objc.ID(c.Class).Send(selBoldSystemFontOfSize, fontSize)}
}

// FontNamesForFamilyName calls +[UIFont fontNamesForFamilyName:].
func (c UIFontClass) FontNamesForFamilyName(familyName string) NSArray {
	return NSArray{objc.ID(c.Class).Send(selFontNamesForFamilyName, objcrt.NSString(familyName))}
}

// FontWithNameSize calls +[UIFont fontWithName:size:].
func (c UIFontClass) FontWithNameSize(fontName string, fontSize float64) UIFont {
	return UIFont{objc.ID(c.Class).Send(selFontWithNameSize, objcrt.NSString(fontName), fontSize)}
}

// ItalicSystemFontOfSize calls +[UIFont italicSystemFontOfSize:].
func (c UIFontClass) ItalicSystemFontOfSize(fontSize float64) UIFont {
	return UIFont{objc.ID(c.Class).Send(selItalicSystemFontOfSize, fontSize)}
}

// MonospacedDigitSystemFontOfSizeWeight calls +[UIFont monospacedDigitSystemFontOfSize:weight:].
func (c UIFontClass) MonospacedDigitSystemFontOfSizeWeight(fontSize float64, weight float64) UIFont {
	return UIFont{objc.ID(c.Class).Send(selMonospacedDigitSystemFontOfSizeWeight, fontSize, weight)}
}

// MonospacedSystemFontOfSizeWeight — Returns current default monospaced font for system UI. Clients of this API should be aware that the monospaced system font has a similar coverage of default system UI font, which includes Latin and common symbols used for displaying text like source code. For the characters it does not cover, the substituted fonts are usually not the same width as the monospaced system font, they can be wider, narrower, or variable. To ensure fixed advances in text layout, clients can consider using string attributes like UIFontDescriptorFixedAdvanceAttribute.
func (c UIFontClass) MonospacedSystemFontOfSizeWeight(fontSize float64, weight float64) UIFont {
	return UIFont{objc.ID(c.Class).Send(selMonospacedSystemFontOfSizeWeight, fontSize, weight)}
}

// PreferredFontForTextStyle calls +[UIFont preferredFontForTextStyle:].
func (c UIFontClass) PreferredFontForTextStyle(style string) UIFont {
	return UIFont{objc.ID(c.Class).Send(selPreferredFontForTextStyle, objcrt.NSString(style))}
}

// SystemFontOfSize calls +[UIFont systemFontOfSize:].
func (c UIFontClass) SystemFontOfSize(fontSize float64) UIFont {
	return UIFont{objc.ID(c.Class).Send(selSystemFontOfSize, fontSize)}
}

// SystemFontOfSizeWeight calls +[UIFont systemFontOfSize:weight:].
func (c UIFontClass) SystemFontOfSizeWeight(fontSize float64, weight float64) UIFont {
	return UIFont{objc.ID(c.Class).Send(selSystemFontOfSizeWeight, fontSize, weight)}
}

// SystemFontOfSizeWeightWidth — Returns an instance with the specified weight and width. Width values are declared in UIFontDescriptor.h.
func (c UIFontClass) SystemFontOfSizeWeightWidth(fontSize float64, weight float64, width float64) UIFont {
	return UIFont{objc.ID(c.Class).Send(selSystemFontOfSizeWeightWidth, fontSize, weight, width)}
}
