// Code generated by tools/bindgen. DO NOT EDIT.
//
// Source: iPhoneSimulator26.2.sdk (Xcode 26.2), target arm64-apple-ios26.2-simulator
// Frameworks: Foundation, UIKit
//
// Regenerate with: tools/bindgen/regen.sh

//go:build darwin

package uikit

import "github.com/ebitengine/purego/objc"

// UIImageView wraps the ObjC class UIImageView (UIView subclass).
type UIImageView struct{ objc.ID }

// UIImageViewClass is the class object of UIImageView.
type UIImageViewClass struct{ objc.Class }

// GetUIImageViewClass looks the class up in the ObjC runtime.
func GetUIImageViewClass() UIImageViewClass { return UIImageViewClass{objc.GetClass("UIImageView")} }

// Alloc allocates an uninitialized UIImageView (-[NSObject alloc]).
func (c UIImageViewClass) Alloc() UIImageView { return UIImageView{objc.ID(c.Class).Send(selAlloc)} }

// AdjustsImageWhenAncestorFocused reads the UIImageView property adjustsImageWhenAncestorFocused.
func (o UIImageView) AdjustsImageWhenAncestorFocused() bool {
	return objc.Send[bool](o.ID, selAdjustsImageWhenAncestorFocused)
}

// SetAdjustsImageWhenAncestorFocused writes the UIImageView property adjustsImageWhenAncestorFocused.
func (o UIImageView) SetAdjustsImageWhenAncestorFocused(v bool) {
	o.ID.Send(selSetAdjustsImageWhenAncestorFocused, v)
}

// Animating reads the UIImageView property animating.
func (o UIImageView) Animating() bool {
	return objc.Send[bool](o.ID, selIsAnimating)
}

// AnimationDuration reads the UIImageView property animationDuration.
func (o UIImageView) AnimationDuration() float64 {
	return objc.Send[float64](o.ID, selAnimationDuration)
}

// SetAnimationDuration writes the UIImageView property animationDuration.
func (o UIImageView) SetAnimationDuration(v float64) {
	o.ID.Send(selSetAnimationDuration, v)
}

// AnimationImages reads the UIImageView property animationImages.
func (o UIImageView) AnimationImages() NSArray {
	return NSArray{o.ID.Send(selAnimationImages)}
}

// SetAnimationImages writes the UIImageView property animationImages.
func (o UIImageView) SetAnimationImages(v NSArray) {
	o.ID.Send(selSetAnimationImages, v.ID)
}

// AnimationRepeatCount reads the UIImageView property animationRepeatCount.
func (o UIImageView) AnimationRepeatCount() int {
	return objc.Send[int](o.ID, selAnimationRepeatCount)
}

// SetAnimationRepeatCount writes the UIImageView property animationRepeatCount.
func (o UIImageView) SetAnimationRepeatCount(v int) {
	o.ID.Send(selSetAnimationRepeatCount, v)
}

// Highlighted reads the UIImageView property highlighted.
func (o UIImageView) Highlighted() bool {
	return objc.Send[bool](o.ID, selIsHighlighted)
}

// SetHighlighted writes the UIImageView property highlighted.
func (o UIImageView) SetHighlighted(v bool) {
	o.ID.Send(selSetHighlighted, v)
}

// HighlightedAnimationImages reads the UIImageView property highlightedAnimationImages.
func (o UIImageView) HighlightedAnimationImages() NSArray {
	return NSArray{o.ID.Send(selHighlightedAnimationImages)}
}

// SetHighlightedAnimationImages writes the UIImageView property highlightedAnimationImages.
func (o UIImageView) SetHighlightedAnimationImages(v NSArray) {
	o.ID.Send(selSetHighlightedAnimationImages, v.ID)
}

// HighlightedImage reads the UIImageView property highlightedImage.
func (o UIImageView) HighlightedImage() UIImage {
	return UIImage{o.ID.Send(selHighlightedImage)}
}

// SetHighlightedImage writes the UIImageView property highlightedImage.
func (o UIImageView) SetHighlightedImage(v UIImage) {
	o.ID.Send(selSetHighlightedImage, v.ID)
}

// Image reads the UIImageView property image.
func (o UIImageView) Image() UIImage {
	return UIImage{o.ID.Send(selImage)}
}

// SetImage writes the UIImageView property image.
func (o UIImageView) SetImage(v UIImage) {
	o.ID.Send(selSetImage, v.ID)
}

// MasksFocusEffectToContents reads the UIImageView property masksFocusEffectToContents.
func (o UIImageView) MasksFocusEffectToContents() bool {
	return objc.Send[bool](o.ID, selMasksFocusEffectToContents)
}

// SetMasksFocusEffectToContents writes the UIImageView property masksFocusEffectToContents.
func (o UIImageView) SetMasksFocusEffectToContents(v bool) {
	o.ID.Send(selSetMasksFocusEffectToContents, v)
}

// OverlayContentView reads the UIImageView property overlayContentView.
func (o UIImageView) OverlayContentView() UIView {
	return UIView{o.ID.Send(selOverlayContentView)}
}

// TintColor reads the UIImageView property tintColor.
func (o UIImageView) TintColor() UIColor {
	return UIColor{o.ID.Send(selTintColor)}
}

// SetTintColor writes the UIImageView property tintColor.
func (o UIImageView) SetTintColor(v UIColor) {
	o.ID.Send(selSetTintColor, v.ID)
}

// UserInteractionEnabled reads the UIImageView property userInteractionEnabled.
func (o UIImageView) UserInteractionEnabled() bool {
	return objc.Send[bool](o.ID, selIsUserInteractionEnabled)
}

// SetUserInteractionEnabled writes the UIImageView property userInteractionEnabled.
func (o UIImageView) SetUserInteractionEnabled(v bool) {
	o.ID.Send(selSetUserInteractionEnabled, v)
}

// InitWithImage calls -[UIImageView initWithImage:].
func (o UIImageView) InitWithImage(image UIImage) UIImageView {
	return UIImageView{o.ID.Send(selInitWithImage, image.ID)}
}

// InitWithImageHighlightedImage calls -[UIImageView initWithImage:highlightedImage:].
func (o UIImageView) InitWithImageHighlightedImage(image UIImage, highlightedImage UIImage) UIImageView {
	return UIImageView{o.ID.Send(selInitWithImageHighlightedImage, image.ID, highlightedImage.ID)}
}

// RemoveAllSymbolEffects — Removes all symbol effects from the image view with default options and animation.
func (o UIImageView) RemoveAllSymbolEffects() {
	o.ID.Send(selRemoveAllSymbolEffects)
}

// StartAnimating calls -[UIImageView startAnimating].
func (o UIImageView) StartAnimating() {
	o.ID.Send(selStartAnimating)
}

// StopAnimating calls -[UIImageView stopAnimating].
func (o UIImageView) StopAnimating() {
	o.ID.Send(selStopAnimating)
}
