// Code generated by tools/bindgen. DO NOT EDIT.
//
// Source: iPhoneSimulator26.2.sdk (Xcode 26.2), target arm64-apple-ios26.2-simulator
// Frameworks: Foundation, UIKit
//
// Regenerate with: tools/bindgen/regen.sh

//go:build darwin

package uikit

import (
	"github.com/adriaanm/wata/go-pkgs/appleptt/objcrt"
	"github.com/ebitengine/purego/objc"
)

// UILabel wraps the ObjC class UILabel (UIView subclass).
type UILabel struct{ objc.ID }

// UILabelClass is the class object of UILabel.
type UILabelClass struct{ objc.Class }

// GetUILabelClass looks the class up in the ObjC runtime.
func GetUILabelClass() UILabelClass { return UILabelClass{objc.GetClass("UILabel")} }

// Alloc allocates an uninitialized UILabel (-[NSObject alloc]).
func (c UILabelClass) Alloc() UILabel { return UILabel{objc.ID(c.Class).Send(selAlloc)} }

// AdjustsFontSizeToFitWidth reads the UILabel property adjustsFontSizeToFitWidth.
func (o UILabel) AdjustsFontSizeToFitWidth() bool {
	return objc.Send[bool](o.ID, selAdjustsFontSizeToFitWidth)
}

// SetAdjustsFontSizeToFitWidth writes the UILabel property adjustsFontSizeToFitWidth.
func (o UILabel) SetAdjustsFontSizeToFitWidth(v bool) {
	o.ID.Send(selSetAdjustsFontSizeToFitWidth, v)
}

// AdjustsLetterSpacingToFitWidth reads the UILabel property adjustsLetterSpacingToFitWidth.
func (o UILabel) AdjustsLetterSpacingToFitWidth() bool {
	return objc.Send[bool](o.ID, selAdjustsLetterSpacingToFitWidth)
}

// SetAdjustsLetterSpacingToFitWidth writes the UILabel property adjustsLetterSpacingToFitWidth.
func (o UILabel) SetAdjustsLetterSpacingToFitWidth(v bool) {
	o.ID.Send(selSetAdjustsLetterSpacingToFitWidth, v)
}

// AllowsDefaultTighteningForTruncation reads the UILabel property allowsDefaultTighteningForTruncation.
func (o UILabel) AllowsDefaultTighteningForTruncation() bool {
	return objc.Send[bool](o.ID, selAllowsDefaultTighteningForTruncation)
}

// SetAllowsDefaultTighteningForTruncation writes the UILabel property allowsDefaultTighteningForTruncation.
func (o UILabel) SetAllowsDefaultTighteningForTruncation(v bool) {
	o.ID.Send(selSetAllowsDefaultTighteningForTruncation, v)
}

// Enabled reads the UILabel property enabled.
func (o UILabel) Enabled() bool {
	return objc.Send[bool](o.ID, selIsEnabled)
}

// SetEnabled writes the UILabel property enabled.
func (o UILabel) SetEnabled(v bool) {
	o.ID.Send(selSetEnabled, v)
}

// EnablesMarqueeWhenAncestorFocused reads the UILabel property enablesMarqueeWhenAncestorFocused.
func (o UILabel) EnablesMarqueeWhenAncestorFocused() bool {
	return objc.Send[bool](o.ID, selEnablesMarqueeWhenAncestorFocused)
}

// SetEnablesMarqueeWhenAncestorFocused writes the UILabel property enablesMarqueeWhenAncestorFocused.
func (o UILabel) SetEnablesMarqueeWhenAncestorFocused(v bool) {
	o.ID.Send(selSetEnablesMarqueeWhenAncestorFocused, v)
}

// Font reads the UILabel property font.
func (o UILabel) Font() UIFont {
	return UIFont{o.ID.Send(selFont)}
}

// SetFont writes the UILabel property font.
func (o UILabel) SetFont(v UIFont) {
	o.ID.Send(selSetFont, v.ID)
}

// Highlighted reads the UILabel property highlighted.
func (o UILabel) Highlighted() bool {
	return objc.Send[bool](o.ID, selIsHighlighted)
}

// SetHighlighted writes the UILabel property highlighted.
func (o UILabel) SetHighlighted(v bool) {
	o.ID.Send(selSetHighlighted, v)
}

// HighlightedTextColor reads the UILabel property highlightedTextColor.
func (o UILabel) HighlightedTextColor() UIColor {
	return UIColor{o.ID.Send(selHighlightedTextColor)}
}

// SetHighlightedTextColor writes the UILabel property highlightedTextColor.
func (o UILabel) SetHighlightedTextColor(v UIColor) {
	o.ID.Send(selSetHighlightedTextColor, v.ID)
}

// MinimumFontSize reads the UILabel property minimumFontSize.
func (o UILabel) MinimumFontSize() float64 {
	return objc.Send[float64](o.ID, selMinimumFontSize)
}

// SetMinimumFontSize writes the UILabel property minimumFontSize.
func (o UILabel) SetMinimumFontSize(v float64) {
	o.ID.Send(selSetMinimumFontSize, v)
}

// MinimumScaleFactor reads the UILabel property minimumScaleFactor.
func (o UILabel) MinimumScaleFactor() float64 {
	return objc.Send[float64](o.ID, selMinimumScaleFactor)
}

// SetMinimumScaleFactor writes the UILabel property minimumScaleFactor.
func (o UILabel) SetMinimumScaleFactor(v float64) {
	o.ID.Send(selSetMinimumScaleFactor, v)
}

// NumberOfLines reads the UILabel property numberOfLines.
func (o UILabel) NumberOfLines() int {
	return objc.Send[int](o.ID, selNumberOfLines)
}

// SetNumberOfLines writes the UILabel property numberOfLines.
func (o UILabel) SetNumberOfLines(v int) {
	o.ID.Send(selSetNumberOfLines, v)
}

// PreferredMaxLayoutWidth reads the UILabel property preferredMaxLayoutWidth.
func (o UILabel) PreferredMaxLayoutWidth() float64 {
	return objc.Send[float64](o.ID, selPreferredMaxLayoutWidth)
}

// SetPreferredMaxLayoutWidth writes the UILabel property preferredMaxLayoutWidth.
func (o UILabel) SetPreferredMaxLayoutWidth(v float64) {
	o.ID.Send(selSetPreferredMaxLayoutWidth, v)
}

// ShadowColor reads the UILabel property shadowColor.
func (o UILabel) ShadowColor() UIColor {
	return UIColor{o.ID.Send(selShadowColor)}
}

// SetShadowColor writes the UILabel property shadowColor.
func (o UILabel) SetShadowColor(v UIColor) {
	o.ID.Send(selSetShadowColor, v.ID)
}

// ShadowOffset reads the UILabel property shadowOffset.
func (o UILabel) ShadowOffset() CGSize {
	return objc.Send[CGSize](o.ID, selShadowOffset)
}

// SetShadowOffset writes the UILabel property shadowOffset.
func (o UILabel) SetShadowOffset(v CGSize) {
	o.ID.Send(selSetShadowOffset, v)
}

// ShowsExpansionTextWhenTruncated — Indicates whether expansion text will be shown when the view is too small to show all the contents. Defaults to NO.
func (o UILabel) ShowsExpansionTextWhenTruncated() bool {
	return objc.Send[bool](o.ID, selShowsExpansionTextWhenTruncated)
}

// SetShowsExpansionTextWhenTruncated writes the UILabel property showsExpansionTextWhenTruncated.
func (o UILabel) SetShowsExpansionTextWhenTruncated(v bool) {
	o.ID.Send(selSetShowsExpansionTextWhenTruncated, v)
}

// Text reads the UILabel property text.
func (o UILabel) Text() string {
	return objcrt.GoString(o.ID.Send(selText))
}

// SetText writes the UILabel property text.
func (o UILabel) SetText(v string) {
	o.ID.Send(selSetText, objcrt.NSString(v))
}

// TextColor reads the UILabel property textColor.
func (o UILabel) TextColor() UIColor {
	return UIColor{o.ID.Send(selTextColor)}
}

// SetTextColor writes the UILabel property textColor.
func (o UILabel) SetTextColor(v UIColor) {
	o.ID.Send(selSetTextColor, v.ID)
}

// UserInteractionEnabled reads the UILabel property userInteractionEnabled.
func (o UILabel) UserInteractionEnabled() bool {
	return objc.Send[bool](o.ID, selIsUserInteractionEnabled)
}

// SetUserInteractionEnabled writes the UILabel property userInteractionEnabled.
func (o UILabel) SetUserInteractionEnabled(v bool) {
	o.ID.Send(selSetUserInteractionEnabled, v)
}

// DrawTextInRect calls -[UILabel drawTextInRect:].
func (o UILabel) DrawTextInRect(rect CGRect) {
	o.ID.Send(selDrawTextInRect, rect)
}

// TextRectForBoundsLimitedToNumberOfLines calls -[UILabel textRectForBounds:limitedToNumberOfLines:].
func (o UILabel) TextRectForBoundsLimitedToNumberOfLines(bounds CGRect, numberOfLines int) CGRect {
	return objc.Send[CGRect](o.ID, selTextRectForBoundsLimitedToNumberOfLines, bounds, numberOfLines)
}
