// Code generated by tools/bindgen. DO NOT EDIT.
//
// Source: iPhoneSimulator26.2.sdk (Xcode 26.2), target arm64-apple-ios26.2-simulator
// Frameworks: Foundation, UIKit
//
// Regenerate with: tools/bindgen/regen.sh

//go:build darwin

package uikit

import "github.com/ebitengine/purego/objc"

// UIScreen wraps the ObjC class UIScreen (NSObject subclass).
type UIScreen struct{ objc.ID }

// UIScreenClass is the class object of UIScreen.
type UIScreenClass struct{ objc.Class }

// GetUIScreenClass looks the class up in the ObjC runtime.
func GetUIScreenClass() UIScreenClass { return UIScreenClass{objc.GetClass("UIScreen")} }

// Alloc allocates an uninitialized UIScreen (-[NSObject alloc]).
func (c UIScreenClass) Alloc() UIScreen { return UIScreen{objc.ID(c.Class).Send(selAlloc)} }

// ApplicationFrame reads the UIScreen property applicationFrame.
func (o UIScreen) ApplicationFrame() CGRect {
	return objc.Send[CGRect](o.ID, selApplicationFrame)
}

// AvailableModes reads the UIScreen property availableModes.
func (o UIScreen) AvailableModes() NSArray {
	return NSArray{o.ID.Send(selAvailableModes)}
}

// Bounds reads the UIScreen property bounds.
func (o UIScreen) Bounds() CGRect {
	return objc.Send[CGRect](o.ID, selBounds)
}

// Brightness reads the UIScreen property brightness.
func (o UIScreen) Brightness() float64 {
	return objc.Send[float64](o.ID, selBrightness)
}

// SetBrightness writes the UIScreen property brightness.
func (o UIScreen) SetBrightness(v float64) {
	o.ID.Send(selSetBrightness, v)
}

// CalibratedLatency reads the UIScreen property calibratedLatency.
func (o UIScreen) CalibratedLatency() float64 {
	return objc.Send[float64](o.ID, selCalibratedLatency)
}

// Captured reads the UIScreen property captured.
func (o UIScreen) Captured() bool {
	return objc.Send[bool](o.ID, selIsCaptured)
}

// CurrentEDRHeadroom reads the UIScreen property currentEDRHeadroom.
func (o UIScreen) CurrentEDRHeadroom() float64 {
	return objc.Send[float64](o.ID, selCurrentEDRHeadroom)
}

// FocusedView reads the UIScreen property focusedView.
func (o UIScreen) FocusedView() UIView {
	return UIView{o.ID.Send(selFocusedView)}
}

// MaximumFramesPerSecond reads the UIScreen property maximumFramesPerSecond.
func (o UIScreen) MaximumFramesPerSecond() int {
	return objc.Send[int](o.ID, selMaximumFramesPerSecond)
}

// MirroredScreen reads the UIScreen property mirroredScreen.
func (o UIScreen) MirroredScreen() UIScreen {
	return UIScreen{o.ID.Send(selMirroredScreen)}
}

// NativeBounds reads the UIScreen property nativeBounds.
func (o UIScreen) NativeBounds() CGRect {
	return objc.Send[CGRect](o.ID, selNativeBounds)
}

// NativeScale reads the UIScreen property nativeScale.
func (o UIScreen) NativeScale() float64 {
	return objc.Send[float64](o.ID, selNativeScale)
}

// PotentialEDRHeadroom reads the UIScreen property potentialEDRHeadroom.
func (o UIScreen) PotentialEDRHeadroom() float64 {
	return objc.Send[float64](o.ID, selPotentialEDRHeadroom)
}

// Scale reads the UIScreen property scale.
func (o UIScreen) Scale() float64 {
	return objc.Send[float64](o.ID, selScale)
}

// SupportsFocus reads the UIScreen property supportsFocus.
func (o UIScreen) SupportsFocus() bool {
	return objc.Send[bool](o.ID, selSupportsFocus)
}

// WantsSoftwareDimming reads the UIScreen property wantsSoftwareDimming.
func (o UIScreen) WantsSoftwareDimming() bool {
	return objc.Send[bool](o.ID, selWantsSoftwareDimming)
}

// SetWantsSoftwareDimming writes the UIScreen property wantsSoftwareDimming.
func (o UIScreen) SetWantsSoftwareDimming(v bool) {
	o.ID.Send(selSetWantsSoftwareDimming, v)
}

// MainScreen reads the UIScreen class property mainScreen.
func (c UIScreenClass) MainScreen() UIScreen {
	return UIScreen{objc.ID(c.Class).Send(selMainScreen)}
}

// Screens reads the UIScreen class property screens.
func (c UIScreenClass) Screens() NSArray {
	return NSArray{objc.ID(c.Class).Send(selScreens)}
}

// SnapshotViewAfterScreenUpdates calls -[UIScreen snapshotViewAfterScreenUpdates:].
func (o UIScreen) SnapshotViewAfterScreenUpdates(afterUpdates bool) UIView {
	return UIView{o.ID.Send(selSnapshotViewAfterScreenUpdates, afterUpdates)}
}
