// Code generated by tools/bindgen. DO NOT EDIT.
//
// Source: iPhoneSimulator26.2.sdk (Xcode 26.2), target arm64-apple-ios26.2-simulator
// Frameworks: Foundation, UIKit
//
// Regenerate with: tools/bindgen/regen.sh

//go:build darwin

package uikit

import "github.com/ebitengine/purego/objc"

// UIViewController an opaque handle for the ObjC class UIViewController (UIResponder subclass).
// Only the identity crosses: no method of UIViewController is on the allowlist.
type UIViewController struct{ objc.ID }

// UIViewControllerClass is the class object of UIViewController.
type UIViewControllerClass struct{ objc.Class }

// GetUIViewControllerClass looks the class up in the ObjC runtime.
func GetUIViewControllerClass() UIViewControllerClass {
	return UIViewControllerClass{objc.GetClass("UIViewController")}
}
