// Code generated by tools/bindgen. DO NOT EDIT.
//
// Source: tools/bindgen/fixtures
//
// Regenerate with: tools/bindgen/regen.sh

//go:build darwin

package fixture

import (
	"github.com/adriaanm/wata/go-pkgs/appleptt/objcrt"
	"github.com/ebitengine/purego/objc"
)

// WFChannel wraps the ObjC class WFChannel (NSObject subclass).
type WFChannel struct{ objc.ID }

// WFChannelClass is the class object of WFChannel.
type WFChannelClass struct{ objc.Class }

// GetWFChannelClass looks the class up in the ObjC runtime.
func GetWFChannelClass() WFChannelClass { return WFChannelClass{objc.GetClass("WFChannel")} }

// Alloc allocates an uninitialized WFChannel (-[NSObject alloc]).
func (c WFChannelClass) Alloc() WFChannel { return WFChannel{objc.ID(c.Class).Send(selAlloc)} }

// Active reads the WFChannel property active.
func (o WFChannel) Active() bool {
	return objc.Send[bool](o.ID, selActive)
}

// SetActive writes the WFChannel property active.
func (o WFChannel) SetActive(v bool) {
	o.ID.Send(selSetActive, v)
}

// Hidden reads the WFChannel property hidden.
func (o WFChannel) Hidden() bool {
	return objc.Send[bool](o.ID, selIsHidden)
}

// SetHidden writes the WFChannel property hidden.
func (o WFChannel) SetHidden(v bool) {
	o.ID.Send(selSetHiddenFlag, v)
}

// Name — What the channel is called.
func (o WFChannel) Name() string {
	return objcrt.GoString(o.ID.Send(selName))
}

// Running reads the WFChannel property running.
func (o WFChannel) Running() bool {
	return objc.Send[bool](o.ID, selIsRunning)
}

// SharedChannel — A class property: the accessor is on the metaclass.
func (c WFChannelClass) SharedChannel() WFChannel {
	return WFChannel{objc.ID(c.Class).Send(selSharedChannel)}
}
