// Code generated by tools/bindgen. DO NOT EDIT.
//
// Source: tools/bindgen/fixtures
//
// Regenerate with: tools/bindgen/regen.sh

//go:build darwin

package fixture

import "github.com/ebitengine/purego/objc"

// NSData an opaque handle for the ObjC class NSData (NSObject subclass).
// Only the identity crosses: no method of NSData is on the allowlist.
type NSData struct{ objc.ID }

// NSDataClass is the class object of NSData.
type NSDataClass struct{ objc.Class }

// GetNSDataClass looks the class up in the ObjC runtime.
func GetNSDataClass() NSDataClass { return NSDataClass{objc.GetClass("NSData")} }
