// Code generated by tools/bindgen. DO NOT EDIT.
//
// Source: tools/bindgen/fixtures
//
// Regenerate with: tools/bindgen/regen.sh

//go:build darwin

package fixture

import "github.com/ebitengine/purego/objc"

// Selectors, registered once at package init.
var (
	selAlloc             = objc.RegisterName("alloc")
	selDescribe          = objc.RegisterName("describe")
	selInit              = objc.RegisterName("init")
	selInitWithNameCount = objc.RegisterName("initWithName:count:")
	selIsReady           = objc.RegisterName("isReady")
	selPayload           = objc.RegisterName("payload")
	selThing             = objc.RegisterName("thing")
)
