// Code generated by tools/bindgen. DO NOT EDIT.
//
// Source: tools/bindgen/fixtures
//
// Regenerate with: tools/bindgen/regen.sh

//go:build darwin

package fixture

import (
	"github.com/adriaanm/wata/go-pkgs/appleptt/objcrt"
	"github.com/ebitengine/purego/objc"
)

// WFThing — A thing, for testing object-returning methods.
type WFThing struct{ objc.ID }

// WFThingClass is the class object of WFThing.
type WFThingClass struct{ objc.Class }

// GetWFThingClass looks the class up in the ObjC runtime.
func GetWFThingClass() WFThingClass { return WFThingClass{objc.GetClass("WFThing")} }

// Alloc allocates an uninitialized WFThing (-[NSObject alloc]).
func (c WFThingClass) Alloc() WFThing { return WFThing{objc.ID(c.Class).Send(selAlloc)} }

// Describe calls -[WFThing describe].
func (o WFThing) Describe() string {
	return objcrt.GoString(o.ID.Send(selDescribe))
}

// Init calls -[WFThing init].
func (o WFThing) Init() WFThing {
	return WFThing{o.ID.Send(selInit)}
}

// InitWithNameCount — Names the thing.
func (o WFThing) InitWithNameCount(name string, count int) WFThing {
	return WFThing{o.ID.Send(selInitWithNameCount, objcrt.NSString(name), count)}
}

// IsReady calls -[WFThing isReady].
func (o WFThing) IsReady() bool {
	return objc.Send[bool](o.ID, selIsReady)
}

// Payload calls -[WFThing payload].
func (o WFThing) Payload() NSData {
	return NSData{o.ID.Send(selPayload)}
}

// Thing calls +[WFThing thing].
func (c WFThingClass) Thing() WFThing {
	return WFThing{objc.ID(c.Class).Send(selThing)}
}
