#!/usr/bin/env python3
"""Build the irohnet-ffi Rust staticlib and stage it where the cgo
directives expect it (clib/<archdir>/libirohnet_ffi.a).

    ./mklib.py            # host (darwin): cargo build --release -> clib/darwin/
    ./mklib.py arm        # device (armv7 musl, the BQ268)     -> clib/linux_arm/
    ./mklib.py ios        # iPhone   (aarch64-apple-ios)       -> clib/ios/
    ./mklib.py ios-sim    # simulator(aarch64-apple-ios-sim)   -> clib/ios_sim/

The two Apple cross-builds need no zig and no linker work — a staticlib is
not linked here, and Xcode's clang is the C toolchain cargo picks up. NOTHING
CONSUMES THEM YET (plan 0034 stops at the archive; the Go-side iOS cgo stanza
belongs with the client that links it), so the only check they can carry is
build provenance — which this script asserts itself: the archive's ARCH
(`lipo -archs`) AND its Mach-O PLATFORM. The platform half is the one that
matters: `aarch64-apple-ios` and `aarch64-apple-ios-sim` produce arm64
archives that are indistinguishable by arch and NOT interchangeable, so an
arch-only check passes a simulator lib on its way into a device build.

clib/ is a build artifact (gitignored); re-run to regenerate. The iroh
version is pinned by rust/Cargo.lock (committed) — every build is --locked.

The arm cross-build needs rustup (for the armv7-unknown-linux-musleabihf
std, installed on first run) and zig (the C cross-toolchain the audio
module's mklibs.sh already uses — ring's C sources ride it here). cargo and
rustc are resolved through `rustup which` rather than PATH: a distro rustc
earlier on PATH has no cross std, and `rustup run` does not reliably win the
PATH race. cc-rs passes clang-style `--target=<triple>` flags that zig
rejects (zig names the arch `arm`, not `armv7`), so the generated cc wrapper
strips them and pins zig's own `-target`.

NB (same trap as go-pkgs/audio): Go's build cache does not see .a changes —
after rebuilding the lib, build the consuming binary with `go build -a` or
clean the cache.
"""

import os
import shutil
import subprocess
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
RUST = HERE / "rust"

RUST_TARGET = "armv7-unknown-linux-musleabihf"
ZIG_TARGET = "arm-linux-musleabihf"

CC_WRAPPER = """#!/bin/sh
# Generated by mklib.py: zig as the armv7-musl cross cc for cargo's C deps.
# Drop clang-style --target= (zig's arch spelling differs); zig -target rules.
args=""
for a in "$@"; do
  case "$a" in --target=*) ;; *) args="$args \\"$a\\"" ;; esac
done
eval exec zig cc -target {zig_target} $args
"""

AR_WRAPPER = """#!/bin/sh
# Generated by mklib.py: zig's llvm-ar for the cross archive steps.
exec zig ar "$@"
"""


def rustup_which(tool: str) -> str:
    r = subprocess.run(["rustup", "which", tool], capture_output=True, text=True)
    if r.returncode != 0:
        sys.exit(f"[mklib] rustup which {tool} failed (rustup required for the arm cross-build): {r.stderr.strip()}")
    return r.stdout.strip()


def build_host() -> Path:
    subprocess.run(["cargo", "build", "--release", "--locked"], cwd=RUST, check=True)
    return RUST / "target" / "release" / "libirohnet_ffi.a"


def build_arm() -> Path:
    if shutil.which("zig") is None:
        sys.exit("[mklib] zig not installed (the C cross-toolchain; ring's C sources need it)")
    cargo = rustup_which("cargo")
    rustc = rustup_which("rustc")
    installed = subprocess.run(
        ["rustup", "target", "list", "--installed"], capture_output=True, text=True, check=True
    ).stdout.split()
    if RUST_TARGET not in installed:
        subprocess.run(["rustup", "target", "add", RUST_TARGET], check=True)
    tooldir = HERE / "clib" / "cross-tools"
    tooldir.mkdir(parents=True, exist_ok=True)
    cc = tooldir / "cc-arm"
    ar = tooldir / "ar-arm"
    cc.write_text(CC_WRAPPER.format(zig_target=ZIG_TARGET))
    ar.write_text(AR_WRAPPER)
    cc.chmod(0o755)
    ar.chmod(0o755)
    env_target = RUST_TARGET.replace("-", "_")
    env = {
        **os.environ,
        "RUSTC": rustc,
        f"CC_{env_target}": str(cc),
        f"AR_{env_target}": str(ar),
    }
    subprocess.run(
        [cargo, "build", "--release", "--locked", "--target", RUST_TARGET],
        cwd=RUST, env=env, check=True,
    )
    return RUST / "target" / RUST_TARGET / "release" / "libirohnet_ffi.a"


# The Apple cross targets: (rust triple, clib subdir, expected arch, expected
# Mach-O platform as `otool -l` spells it in LC_BUILD_VERSION).
APPLE = {
    "ios": ("aarch64-apple-ios", "ios", "arm64", "IOS"),
    "ios-sim": ("aarch64-apple-ios-sim", "ios_sim", "arm64", "IOSSIMULATOR"),
}


def build_apple(name: str) -> Path:
    triple, _, _, _ = APPLE[name]
    if shutil.which("xcrun") is None:
        sys.exit("[mklib] xcrun not found (the Apple cross-builds need the Xcode command line tools)")
    cargo = rustup_which("cargo")
    rustc = rustup_which("rustc")
    installed = subprocess.run(
        ["rustup", "target", "list", "--installed"], capture_output=True, text=True, check=True
    ).stdout.split()
    if triple not in installed:
        subprocess.run(["rustup", "target", "add", triple], check=True)
    subprocess.run(
        [cargo, "build", "--release", "--locked", "--target", triple],
        cwd=RUST, env={**os.environ, "RUSTC": rustc}, check=True,
    )
    return RUST / "target" / triple / "release" / "libirohnet_ffi.a"


def archive_archs(lib: Path) -> set:
    out = subprocess.run(["lipo", "-archs", str(lib)], capture_output=True, text=True, check=True)
    return set(out.stdout.split())


# LC_BUILD_VERSION platform values. otool prints the NUMBER on some toolchains
# and the name on others, so both spellings are normalized to one name here.
PLATFORM_NAMES = {
    "1": "MACOS", "2": "IOS", "3": "TVOS", "4": "WATCHOS", "5": "BRIDGEOS",
    "6": "MACCATALYST", "7": "IOSSIMULATOR", "8": "TVOSSIMULATOR",
    "9": "WATCHOSSIMULATOR", "10": "DRIVERKIT", "11": "VISIONOS",
    "12": "VISIONOSSIMULATOR",
}


def archive_platforms(lib: Path) -> set:
    """the Mach-O platforms the archive's members were built for, out of their
    LC_BUILD_VERSION load commands. `otool -l` walks every member; the platform
    lines are all we keep. An archive built for one target reports exactly one
    platform — anything else is the mix-up this check exists to catch."""
    out = subprocess.run(["otool", "-l", str(lib)], capture_output=True, text=True, check=True)
    plats = set()
    for line in out.stdout.splitlines():
        f = line.split()
        if len(f) == 2 and f[0] == "platform":
            plats.add(PLATFORM_NAMES.get(f[1], f[1].upper()))
    return plats


def assert_apple(name: str, lib: Path) -> None:
    _, _, want_arch, want_plat = APPLE[name]
    archs = archive_archs(lib)
    if archs != {want_arch}:
        sys.exit(f"[mklib] {name}: wrong architecture: want {{{want_arch}}}, got {archs or '{}'}")
    plats = archive_platforms(lib)
    if plats != {want_plat}:
        # The failure worth designing against: a device build carrying
        # simulator objects (or the reverse) has the RIGHT arch and links into
        # the wrong product, so arch alone would call this green.
        sys.exit(f"[mklib] {name}: wrong Mach-O platform: want {{{want_plat}}}, got {plats or '{}'}")
    print(f"[mklib] {name}: arch {want_arch}, Mach-O platform {want_plat} — OK")


def main() -> int:
    arch = sys.argv[1] if len(sys.argv) > 1 else "host"
    if arch == "host":
        lib, archdir = build_host(), "darwin"
    elif arch == "arm":
        lib, archdir = build_arm(), "linux_arm"
    elif arch in APPLE:
        lib = build_apple(arch)
        assert_apple(arch, lib)
        archdir = APPLE[arch][1]
    else:
        sys.exit(f"[mklib] unknown arch {arch!r} (want: host | arm | ios | ios-sim)")
    out = HERE / "clib" / archdir
    out.mkdir(parents=True, exist_ok=True)
    shutil.copy2(lib, out / lib.name)
    size_mb = lib.stat().st_size / (1024 * 1024)
    print(f"[mklib] {out / lib.name} ({size_mb:.1f} MB)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
