// Command hellopt is the PushToTalk hello: the smallest thing that proves the
// generated bindings drive Apple's PushToTalk framework from Go.
//
// It builds as a C archive (-buildmode=c-archive) and the ObjC shell in ../ios
// calls the exported functions. Everything below the C boundary is Go:
// PTChannelManager, both delegates and the channel descriptor come from
// go-pkgs/appleptt, generated by tools/bindgen, dispatched through purego.
//
// The framework only exists on iOS hardware — the simulator has no PushToTalk
// service — so this binary is meaningful only on a device. See ../README.md.
package main

import "C"

import (
	"strings"
	"sync"
	"time"

	pt "github.com/adriaanm/wata/go-pkgs/appleptt"
	"github.com/adriaanm/wata/go-pkgs/appleptt/objcrt"
	"github.com/ebitengine/purego/objc"
)

// The one channel this hello joins. A real client would derive the UUID from
// the wata room it belongs to; here it is a constant so two devices running
// the hello land in the same channel.
const (
	channelUUID = "1F2E3D4C-5B6A-4798-8695-A4B3C2D1E0F0"
	channelName = "wata hello"
)

var (
	mu      sync.Mutex
	lines   []string
	manager pt.PTChannelManager
	joined  bool
)

func note(format string, args ...any) {
	mu.Lock()
	defer mu.Unlock()
	msg := format
	if len(args) > 0 {
		msg = sprintf(format, args...)
	}
	lines = append(lines, time.Now().Format("15:04:05")+" "+msg)
}

func sprintf(format string, args ...any) string {
	// Kept trivial on purpose: this binary has no business formatting much.
	var b strings.Builder
	rest := format
	for _, a := range args {
		i := strings.Index(rest, "%s")
		if i < 0 {
			break
		}
		b.WriteString(rest[:i])
		switch v := a.(type) {
		case string:
			b.WriteString(v)
		case error:
			b.WriteString(v.Error())
		default:
			b.WriteString("?")
		}
		rest = rest[i+2:]
	}
	b.WriteString(rest)
	return b.String()
}

func uuid() pt.NSUUID {
	return pt.GetNSUUIDClass().Alloc().InitWithUUIDString(channelUUID)
}

func descriptor() pt.PTChannelDescriptor {
	return pt.GetPTChannelDescriptorClass().Alloc().InitWithNameImage(channelName, pt.UIImage{})
}

//export HelloBoot
func HelloBoot() {
	note("boot: asking the system for a channel manager")

	delegate := pt.NewPTChannelManagerDelegate(pt.PTChannelManagerDelegate{
		ChannelManagerDidJoinChannelWithUUIDReason: func(
			_ pt.PTChannelManager, _ pt.NSUUID, reason pt.PTChannelJoinReason) {
			mu.Lock()
			joined = true
			mu.Unlock()
			note("joined the channel (reason %s)", reasonName(reason))
		},
		ChannelManagerDidLeaveChannelWithUUIDReason: func(
			_ pt.PTChannelManager, _ pt.NSUUID, _ pt.PTChannelLeaveReason) {
			mu.Lock()
			joined = false
			mu.Unlock()
			note("left the channel")
		},
		ChannelManagerFailedToJoinChannelWithUUIDError: func(
			_ pt.PTChannelManager, _ pt.NSUUID, err error) {
			note("join failed: %s", err)
		},
		ChannelManagerChannelUUIDDidBeginTransmittingFromSource: func(
			_ pt.PTChannelManager, _ pt.NSUUID, _ pt.PTChannelTransmitRequestSource) {
			note("transmitting")
		},
		ChannelManagerChannelUUIDDidEndTransmittingFromSource: func(
			_ pt.PTChannelManager, _ pt.NSUUID, _ pt.PTChannelTransmitRequestSource) {
			note("stopped transmitting")
		},
		ChannelManagerFailedToBeginTransmittingInChannelWithUUIDError: func(
			_ pt.PTChannelManager, _ pt.NSUUID, err error) {
			note("transmit failed: %s", err)
		},
		// The system hands the app a configured, activated audio session for the
		// duration of a transmission. Capturing from it is the next milestone
		// (go-pkgs/audio); the hello only proves the handoff happens.
		ChannelManagerDidActivateAudioSession: func(_ pt.PTChannelManager, s pt.AVAudioSession) {
			note("audio session activated: %s", describe(s.ID))
		},
		ChannelManagerDidDeactivateAudioSession: func(pt.PTChannelManager, pt.AVAudioSession) {
			note("audio session deactivated")
		},
		ChannelManagerReceivedEphemeralPushToken: func(_ pt.PTChannelManager, token pt.NSData) {
			note("ephemeral push token: %s bytes", itoa(len(objcrt.GoBytes(token.ID))))
		},
	})

	restoration := pt.NewPTChannelRestorationDelegate(pt.PTChannelRestorationDelegate{
		ChannelDescriptorForRestoredChannelUUID: func(pt.NSUUID) pt.PTChannelDescriptor {
			note("the system restored the channel")
			return descriptor()
		},
	})

	pt.GetPTChannelManagerClass().ChannelManagerWithDelegateRestorationDelegateCompletionHandler(
		delegate, restoration, func(m pt.PTChannelManager, err error) {
			if err != nil {
				note("no channel manager: %s", err)
				return
			}
			mu.Lock()
			manager = m
			mu.Unlock()
			note("channel manager ready")
		})
}

//export HelloJoin
func HelloJoin() {
	m, ok := current()
	if !ok {
		return
	}
	note("requesting to join")
	m.RequestJoinChannelWithUUIDDescriptor(uuid(), descriptor())
}

//export HelloTalk
func HelloTalk() {
	m, ok := current()
	if !ok {
		return
	}
	note("requesting to transmit")
	m.RequestBeginTransmittingWithChannelUUID(uuid())
}

//export HelloStopTalk
func HelloStopTalk() {
	m, ok := current()
	if !ok {
		return
	}
	m.StopTransmittingWithChannelUUID(uuid())
}

//export HelloLeave
func HelloLeave() {
	m, ok := current()
	if !ok {
		return
	}
	m.LeaveChannelWithUUID(uuid())
}

// HelloLog returns the event log. The caller owns the string and must free it.
//
//export HelloLog
func HelloLog() *C.char {
	mu.Lock()
	defer mu.Unlock()
	return C.CString(strings.Join(lines, "\n"))
}

func current() (pt.PTChannelManager, bool) {
	mu.Lock()
	defer mu.Unlock()
	if manager.ID == 0 {
		lines = append(lines, "no channel manager yet")
		return manager, false
	}
	return manager, true
}

func describe(id objc.ID) string {
	if id == 0 {
		return "<nil>"
	}
	return objcrt.GoString(id.Send(objc.RegisterName("description")))
}

func reasonName(r pt.PTChannelJoinReason) string {
	if r == pt.PTChannelJoinReasonChannelRestoration {
		return "restoration"
	}
	return "request"
}

func itoa(n int) string {
	if n == 0 {
		return "0"
	}
	var buf [20]byte
	i := len(buf)
	for n > 0 {
		i--
		buf[i] = byte('0' + n%10)
		n /= 10
	}
	return string(buf[i:])
}

func main() {}
