// Code generated by tools/bindgen. DO NOT EDIT.
//
// Source: MacOSX26.2.sdk (Xcode 26.2), target arm64-apple-macos26.0
// Frameworks: Foundation, AppKit
//
// Regenerate with: tools/bindgen/regen.sh

//go:build darwin

package appkit

// NSApplicationActivationPolicy is the ObjC enum NSApplicationActivationPolicy (long).
type NSApplicationActivationPolicy int

const (
	NSApplicationActivationPolicyRegular    NSApplicationActivationPolicy = 0
	NSApplicationActivationPolicyAccessory  NSApplicationActivationPolicy = 1
	NSApplicationActivationPolicyProhibited NSApplicationActivationPolicy = 2
)

// NSBackingStoreType is the ObjC enum NSBackingStoreType (unsigned long).
type NSBackingStoreType uint

const (
	NSBackingStoreRetained    NSBackingStoreType = 0
	NSBackingStoreNonretained NSBackingStoreType = 1
	NSBackingStoreBuffered    NSBackingStoreType = 2
)

// NSBoxType is the ObjC enum NSBoxType (unsigned long).
type NSBoxType uint

const (
	NSBoxPrimary   NSBoxType = 0
	NSBoxSeparator NSBoxType = 2
	NSBoxCustom    NSBoxType = 4
)

// NSEventModifierFlags is the ObjC enum NSEventModifierFlags (unsigned long).
type NSEventModifierFlags uint

const (
	NSEventModifierFlagCapsLock                   NSEventModifierFlags = 65536
	NSEventModifierFlagShift                      NSEventModifierFlags = 131072
	NSEventModifierFlagControl                    NSEventModifierFlags = 262144
	NSEventModifierFlagOption                     NSEventModifierFlags = 524288
	NSEventModifierFlagCommand                    NSEventModifierFlags = 1048576
	NSEventModifierFlagNumericPad                 NSEventModifierFlags = 2097152
	NSEventModifierFlagHelp                       NSEventModifierFlags = 4194304
	NSEventModifierFlagFunction                   NSEventModifierFlags = 8388608
	NSEventModifierFlagDeviceIndependentFlagsMask NSEventModifierFlags = 4294901760
)

// NSEventType is the ObjC enum NSEventType (unsigned long).
type NSEventType uint

const (
	NSEventTypeLeftMouseDown      NSEventType = 1
	NSEventTypeLeftMouseUp        NSEventType = 2
	NSEventTypeRightMouseDown     NSEventType = 3
	NSEventTypeRightMouseUp       NSEventType = 4
	NSEventTypeMouseMoved         NSEventType = 5
	NSEventTypeLeftMouseDragged   NSEventType = 6
	NSEventTypeRightMouseDragged  NSEventType = 7
	NSEventTypeMouseEntered       NSEventType = 8
	NSEventTypeMouseExited        NSEventType = 9
	NSEventTypeKeyDown            NSEventType = 10
	NSEventTypeKeyUp              NSEventType = 11
	NSEventTypeFlagsChanged       NSEventType = 12
	NSEventTypeAppKitDefined      NSEventType = 13
	NSEventTypeSystemDefined      NSEventType = 14
	NSEventTypeApplicationDefined NSEventType = 15
	NSEventTypePeriodic           NSEventType = 16
	NSEventTypeCursorUpdate       NSEventType = 17
	NSEventTypeScrollWheel        NSEventType = 22
	NSEventTypeTabletPoint        NSEventType = 23
	NSEventTypeTabletProximity    NSEventType = 24
	NSEventTypeOtherMouseDown     NSEventType = 25
	NSEventTypeOtherMouseUp       NSEventType = 26
	NSEventTypeOtherMouseDragged  NSEventType = 27
	NSEventTypeGesture            NSEventType = 29
	NSEventTypeMagnify            NSEventType = 30
	NSEventTypeSwipe              NSEventType = 31
	NSEventTypeRotate             NSEventType = 18
	NSEventTypeBeginGesture       NSEventType = 19
	NSEventTypeEndGesture         NSEventType = 20
	NSEventTypeSmartMagnify       NSEventType = 32
	NSEventTypeQuickLook          NSEventType = 33
	NSEventTypePressure           NSEventType = 34
	NSEventTypeDirectTouch        NSEventType = 37
	NSEventTypeChangeMode         NSEventType = 38
	NSEventTypeMouseCancelled     NSEventType = 40
)

// NSImageScaling is the ObjC enum NSImageScaling (unsigned long).
type NSImageScaling uint

const (
	NSImageScaleProportionallyDown     NSImageScaling = 0
	NSImageScaleAxesIndependently      NSImageScaling = 1
	NSImageScaleNone                   NSImageScaling = 2
	NSImageScaleProportionallyUpOrDown NSImageScaling = 3
	NSScaleProportionally              NSImageScaling = 0
	NSScaleToFit                       NSImageScaling = 1
	NSScaleNone                        NSImageScaling = 2
)

// NSTitlePosition is the ObjC enum NSTitlePosition (unsigned long).
type NSTitlePosition uint

const (
	NSNoTitle     NSTitlePosition = 0
	NSAboveTop    NSTitlePosition = 1
	NSAtTop       NSTitlePosition = 2
	NSBelowTop    NSTitlePosition = 3
	NSAboveBottom NSTitlePosition = 4
	NSAtBottom    NSTitlePosition = 5
	NSBelowBottom NSTitlePosition = 6
)

// NSWindowOrderingMode is the ObjC enum NSWindowOrderingMode (long).
type NSWindowOrderingMode int

const (
	NSWindowAbove NSWindowOrderingMode = 1
	NSWindowBelow NSWindowOrderingMode = -1
	NSWindowOut   NSWindowOrderingMode = 0
)

// NSWindowStyleMask is the ObjC enum NSWindowStyleMask (unsigned long).
type NSWindowStyleMask uint

const (
	NSWindowStyleMaskBorderless             NSWindowStyleMask = 0
	NSWindowStyleMaskTitled                 NSWindowStyleMask = 1
	NSWindowStyleMaskClosable               NSWindowStyleMask = 2
	NSWindowStyleMaskMiniaturizable         NSWindowStyleMask = 4
	NSWindowStyleMaskResizable              NSWindowStyleMask = 8
	NSWindowStyleMaskTexturedBackground     NSWindowStyleMask = 256
	NSWindowStyleMaskUnifiedTitleAndToolbar NSWindowStyleMask = 4096
	NSWindowStyleMaskFullScreen             NSWindowStyleMask = 16384
	NSWindowStyleMaskFullSizeContentView    NSWindowStyleMask = 32768
	NSWindowStyleMaskUtilityWindow          NSWindowStyleMask = 16
	NSWindowStyleMaskDocModalWindow         NSWindowStyleMask = 64
	NSWindowStyleMaskNonactivatingPanel     NSWindowStyleMask = 128
	NSWindowStyleMaskHUDWindow              NSWindowStyleMask = 8192
)
