// Code generated by tools/bindgen. DO NOT EDIT.
//
// Source: MacOSX26.2.sdk (Xcode 26.2), target arm64-apple-macos26.0
// Frameworks: Foundation, AppKit
//
// Regenerate with: tools/bindgen/regen.sh

//go:build darwin

package appkit

import "github.com/ebitengine/purego"

// The frameworks whose classes this package binds, loaded at package
// init: objc.GetClass sees only what is already in the process, and a
// pure-Go binary links no framework. Dlopen is idempotent and cheap.
func init() {
	_, _ = purego.Dlopen("/System/Library/Frameworks/AppKit.framework/AppKit",
		purego.RTLD_GLOBAL|purego.RTLD_LAZY)
}
