// Code generated by tools/bindgen. DO NOT EDIT.
//
// Source: MacOSX26.2.sdk (Xcode 26.2), target arm64-apple-macos26.0
// Frameworks: Foundation, AppKit
//
// Regenerate with: tools/bindgen/regen.sh

//go:build darwin

package appkit

import (
	"github.com/adriaanm/wata/go-pkgs/appleptt/objcrt"
	"github.com/ebitengine/purego/objc"
)

// NSBox wraps the ObjC class NSBox (NSView subclass).
type NSBox struct{ objc.ID }

// NSBoxClass is the class object of NSBox.
type NSBoxClass struct{ objc.Class }

// GetNSBoxClass looks the class up in the ObjC runtime.
func GetNSBoxClass() NSBoxClass { return NSBoxClass{objc.GetClass("NSBox")} }

// Alloc allocates an uninitialized NSBox (-[NSObject alloc]).
func (c NSBoxClass) Alloc() NSBox { return NSBox{objc.ID(c.Class).Send(selAlloc)} }

// BorderColor — For boxType == NSBoxCustom: Get and set the border color the box. The default value is +[NSColor secondaryLabelColor], and may vary release-to-release.
func (o NSBox) BorderColor() NSColor {
	return NSColor{o.ID.Send(selBorderColor)}
}

// SetBorderColor writes the NSBox property borderColor.
func (o NSBox) SetBorderColor(v NSColor) {
	o.ID.Send(selSetBorderColor, v.ID)
}

// BorderRect reads the NSBox property borderRect.
func (o NSBox) BorderRect() CGRect {
	return objc.Send[CGRect](o.ID, selBorderRect)
}

// BorderWidth — For boxType == NSBoxCustom: Get and set the border width of the box. The default value is 1.0.
func (o NSBox) BorderWidth() float64 {
	return objc.Send[float64](o.ID, selBorderWidth)
}

// SetBorderWidth writes the NSBox property borderWidth.
func (o NSBox) SetBorderWidth(v float64) {
	o.ID.Send(selSetBorderWidth, v)
}

// BoxType reads the NSBox property boxType.
func (o NSBox) BoxType() NSBoxType {
	return NSBoxType(objc.Send[uint](o.ID, selBoxType))
}

// SetBoxType writes the NSBox property boxType.
func (o NSBox) SetBoxType(v NSBoxType) {
	o.ID.Send(selSetBoxType, uint(v))
}

// ContentView — Get and set the content view for the box. Note that subviews added to the NSBox will be really added as subviews of the contentView.
func (o NSBox) ContentView() NSView {
	return NSView{o.ID.Send(selContentView)}
}

// SetContentView writes the NSBox property contentView.
func (o NSBox) SetContentView(v NSView) {
	o.ID.Send(selSetContentView, v.ID)
}

// ContentViewMargins reads the NSBox property contentViewMargins.
func (o NSBox) ContentViewMargins() CGSize {
	return objc.Send[CGSize](o.ID, selContentViewMargins)
}

// SetContentViewMargins writes the NSBox property contentViewMargins.
func (o NSBox) SetContentViewMargins(v CGSize) {
	o.ID.Send(selSetContentViewMargins, v)
}

// CornerRadius — For boxType == NSBoxCustom: Get and set the corner radius of the box. The default value is 0.0 (no corner radius).
func (o NSBox) CornerRadius() float64 {
	return objc.Send[float64](o.ID, selCornerRadius)
}

// SetCornerRadius writes the NSBox property cornerRadius.
func (o NSBox) SetCornerRadius(v float64) {
	o.ID.Send(selSetCornerRadius, v)
}

// FillColor — For boxType == NSBoxCustom: Get and set the fill (background) color the box. The default value is NSColor.clearColor.
func (o NSBox) FillColor() NSColor {
	return NSColor{o.ID.Send(selFillColor)}
}

// SetFillColor writes the NSBox property fillColor.
func (o NSBox) SetFillColor(v NSColor) {
	o.ID.Send(selSetFillColor, v.ID)
}

// Title reads the NSBox property title.
func (o NSBox) Title() string {
	return objcrt.GoString(o.ID.Send(selTitle))
}

// SetTitle writes the NSBox property title.
func (o NSBox) SetTitle(v string) {
	o.ID.Send(selSetTitle, objcrt.NSString(v))
}

// TitleCell reads the NSBox property titleCell.
func (o NSBox) TitleCell() objc.ID {
	return o.ID.Send(selTitleCell)
}

// TitleFont reads the NSBox property titleFont.
func (o NSBox) TitleFont() NSFont {
	return NSFont{o.ID.Send(selTitleFont)}
}

// SetTitleFont writes the NSBox property titleFont.
func (o NSBox) SetTitleFont(v NSFont) {
	o.ID.Send(selSetTitleFont, v.ID)
}

// TitlePosition reads the NSBox property titlePosition.
func (o NSBox) TitlePosition() NSTitlePosition {
	return NSTitlePosition(objc.Send[uint](o.ID, selTitlePosition))
}

// SetTitlePosition writes the NSBox property titlePosition.
func (o NSBox) SetTitlePosition(v NSTitlePosition) {
	o.ID.Send(selSetTitlePosition, uint(v))
}

// TitleRect reads the NSBox property titleRect.
func (o NSBox) TitleRect() CGRect {
	return objc.Send[CGRect](o.ID, selTitleRect)
}

// Transparent — Transparent boxes do not draw anything.  Subview drawing is unaffected.  The 'transparent' property corresponds to the binding 'NSTransparentBinding'.
func (o NSBox) Transparent() bool {
	return objc.Send[bool](o.ID, selIsTransparent)
}

// SetTransparent writes the NSBox property transparent.
func (o NSBox) SetTransparent(v bool) {
	o.ID.Send(selSetTransparent, v)
}

// SetFrameFromContentFrame calls -[NSBox setFrameFromContentFrame:].
func (o NSBox) SetFrameFromContentFrame(contentFrame CGRect) {
	o.ID.Send(selSetFrameFromContentFrame, contentFrame)
}

// SetTitleWithMnemonic — Mnemonics are deprecated in 10.8. Historically they have not done anything. For compatibility, this method still calls setTitle: with the ampersand stripped from it.
func (o NSBox) SetTitleWithMnemonic(stringWithAmpersand string) {
	o.ID.Send(selSetTitleWithMnemonic, objcrt.NSString(stringWithAmpersand))
}

// SizeToFit calls -[NSBox sizeToFit].
func (o NSBox) SizeToFit() {
	o.ID.Send(selSizeToFit)
}
