// Code generated by tools/bindgen. DO NOT EDIT.
//
// Source: MacOSX26.2.sdk (Xcode 26.2), target arm64-apple-macos26.0
// Frameworks: Foundation, AppKit
//
// Regenerate with: tools/bindgen/regen.sh

//go:build darwin

package appkit

import (
	"github.com/adriaanm/wata/go-pkgs/appleptt/objcrt"
	"github.com/ebitengine/purego/objc"
)

// NSButton wraps the ObjC class NSButton (NSControl subclass).
type NSButton struct{ objc.ID }

// NSButtonClass is the class object of NSButton.
type NSButtonClass struct{ objc.Class }

// GetNSButtonClass looks the class up in the ObjC runtime.
func GetNSButtonClass() NSButtonClass { return NSButtonClass{objc.GetClass("NSButton")} }

// Alloc allocates an uninitialized NSButton (-[NSObject alloc]).
func (c NSButtonClass) Alloc() NSButton { return NSButton{objc.ID(c.Class).Send(selAlloc)} }

// AllowsMixedState reads the NSButton property allowsMixedState.
func (o NSButton) AllowsMixedState() bool {
	return objc.Send[bool](o.ID, selAllowsMixedState)
}

// SetAllowsMixedState writes the NSButton property allowsMixedState.
func (o NSButton) SetAllowsMixedState(v bool) {
	o.ID.Send(selSetAllowsMixedState, v)
}

// AlternateImage reads the NSButton property alternateImage.
func (o NSButton) AlternateImage() NSImage {
	return NSImage{o.ID.Send(selAlternateImage)}
}

// SetAlternateImage writes the NSButton property alternateImage.
func (o NSButton) SetAlternateImage(v NSImage) {
	o.ID.Send(selSetAlternateImage, v.ID)
}

// AlternateTitle reads the NSButton property alternateTitle.
func (o NSButton) AlternateTitle() string {
	return objcrt.GoString(o.ID.Send(selAlternateTitle))
}

// SetAlternateTitle writes the NSButton property alternateTitle.
func (o NSButton) SetAlternateTitle(v string) {
	o.ID.Send(selSetAlternateTitle, objcrt.NSString(v))
}

// BezelColor reads the NSButton property bezelColor.
func (o NSButton) BezelColor() NSColor {
	return NSColor{o.ID.Send(selBezelColor)}
}

// SetBezelColor writes the NSButton property bezelColor.
func (o NSButton) SetBezelColor(v NSColor) {
	o.ID.Send(selSetBezelColor, v.ID)
}

// Bordered reads the NSButton property bordered.
func (o NSButton) Bordered() bool {
	return objc.Send[bool](o.ID, selIsBordered)
}

// SetBordered writes the NSButton property bordered.
func (o NSButton) SetBordered(v bool) {
	o.ID.Send(selSetBordered, v)
}

// ContentTintColor reads the NSButton property contentTintColor.
func (o NSButton) ContentTintColor() NSColor {
	return NSColor{o.ID.Send(selContentTintColor)}
}

// SetContentTintColor writes the NSButton property contentTintColor.
func (o NSButton) SetContentTintColor(v NSColor) {
	o.ID.Send(selSetContentTintColor, v.ID)
}

// HasDestructiveAction reads the NSButton property hasDestructiveAction.
func (o NSButton) HasDestructiveAction() bool {
	return objc.Send[bool](o.ID, selHasDestructiveAction)
}

// SetHasDestructiveAction writes the NSButton property hasDestructiveAction.
func (o NSButton) SetHasDestructiveAction(v bool) {
	o.ID.Send(selSetHasDestructiveAction, v)
}

// Image reads the NSButton property image.
func (o NSButton) Image() NSImage {
	return NSImage{o.ID.Send(selImage)}
}

// SetImage writes the NSButton property image.
func (o NSButton) SetImage(v NSImage) {
	o.ID.Send(selSetImage, v.ID)
}

// ImageHugsTitle reads the NSButton property imageHugsTitle.
func (o NSButton) ImageHugsTitle() bool {
	return objc.Send[bool](o.ID, selImageHugsTitle)
}

// SetImageHugsTitle writes the NSButton property imageHugsTitle.
func (o NSButton) SetImageHugsTitle(v bool) {
	o.ID.Send(selSetImageHugsTitle, v)
}

// ImageScaling reads the NSButton property imageScaling.
func (o NSButton) ImageScaling() NSImageScaling {
	return NSImageScaling(objc.Send[uint](o.ID, selImageScaling))
}

// SetImageScaling writes the NSButton property imageScaling.
func (o NSButton) SetImageScaling(v NSImageScaling) {
	o.ID.Send(selSetImageScaling, uint(v))
}

// KeyEquivalent reads the NSButton property keyEquivalent.
func (o NSButton) KeyEquivalent() string {
	return objcrt.GoString(o.ID.Send(selKeyEquivalent))
}

// SetKeyEquivalent writes the NSButton property keyEquivalent.
func (o NSButton) SetKeyEquivalent(v string) {
	o.ID.Send(selSetKeyEquivalent, objcrt.NSString(v))
}

// KeyEquivalentModifierMask reads the NSButton property keyEquivalentModifierMask.
func (o NSButton) KeyEquivalentModifierMask() NSEventModifierFlags {
	return NSEventModifierFlags(objc.Send[uint](o.ID, selKeyEquivalentModifierMask))
}

// SetKeyEquivalentModifierMask writes the NSButton property keyEquivalentModifierMask.
func (o NSButton) SetKeyEquivalentModifierMask(v NSEventModifierFlags) {
	o.ID.Send(selSetKeyEquivalentModifierMask, uint(v))
}

// MaxAcceleratorLevel reads the NSButton property maxAcceleratorLevel.
func (o NSButton) MaxAcceleratorLevel() int {
	return objc.Send[int](o.ID, selMaxAcceleratorLevel)
}

// SetMaxAcceleratorLevel writes the NSButton property maxAcceleratorLevel.
func (o NSButton) SetMaxAcceleratorLevel(v int) {
	o.ID.Send(selSetMaxAcceleratorLevel, v)
}

// ShowsBorderOnlyWhileMouseInside reads the NSButton property showsBorderOnlyWhileMouseInside.
func (o NSButton) ShowsBorderOnlyWhileMouseInside() bool {
	return objc.Send[bool](o.ID, selShowsBorderOnlyWhileMouseInside)
}

// SetShowsBorderOnlyWhileMouseInside writes the NSButton property showsBorderOnlyWhileMouseInside.
func (o NSButton) SetShowsBorderOnlyWhileMouseInside(v bool) {
	o.ID.Send(selSetShowsBorderOnlyWhileMouseInside, v)
}

// SpringLoaded reads the NSButton property springLoaded.
func (o NSButton) SpringLoaded() bool {
	return objc.Send[bool](o.ID, selIsSpringLoaded)
}

// SetSpringLoaded writes the NSButton property springLoaded.
func (o NSButton) SetSpringLoaded(v bool) {
	o.ID.Send(selSetSpringLoaded, v)
}

// State reads the NSButton property state.
func (o NSButton) State() int {
	return objc.Send[int](o.ID, selState)
}

// SetState writes the NSButton property state.
func (o NSButton) SetState(v int) {
	o.ID.Send(selSetState, v)
}

// Title reads the NSButton property title.
func (o NSButton) Title() string {
	return objcrt.GoString(o.ID.Send(selTitle))
}

// SetTitle writes the NSButton property title.
func (o NSButton) SetTitle(v string) {
	o.ID.Send(selSetTitle, objcrt.NSString(v))
}

// Transparent reads the NSButton property transparent.
func (o NSButton) Transparent() bool {
	return objc.Send[bool](o.ID, selIsTransparent)
}

// SetTransparent writes the NSButton property transparent.
func (o NSButton) SetTransparent(v bool) {
	o.ID.Send(selSetTransparent, v)
}

// CompressWithPrioritizedCompressionOptions calls -[NSButton compressWithPrioritizedCompressionOptions:].
func (o NSButton) CompressWithPrioritizedCompressionOptions(prioritizedOptions NSArray) {
	o.ID.Send(selCompressWithPrioritizedCompressionOptions, prioritizedOptions.ID)
}

// Highlight calls -[NSButton highlight:].
func (o NSButton) Highlight(flag bool) {
	o.ID.Send(selHighlight, flag)
}

// MinimumSizeWithPrioritizedCompressionOptions calls -[NSButton minimumSizeWithPrioritizedCompressionOptions:].
func (o NSButton) MinimumSizeWithPrioritizedCompressionOptions(prioritizedOptions NSArray) CGSize {
	return objc.Send[CGSize](o.ID, selMinimumSizeWithPrioritizedCompressionOptions, prioritizedOptions.ID)
}

// PerformKeyEquivalent calls -[NSButton performKeyEquivalent:].
func (o NSButton) PerformKeyEquivalent(key NSEvent) bool {
	return objc.Send[bool](o.ID, selPerformKeyEquivalent, key.ID)
}

// SetNextState calls -[NSButton setNextState].
func (o NSButton) SetNextState() {
	o.ID.Send(selSetNextState)
}

// SetPeriodicDelayInterval calls -[NSButton setPeriodicDelay:interval:].
func (o NSButton) SetPeriodicDelayInterval(delay float32, interval float32) {
	o.ID.Send(selSetPeriodicDelayInterval, delay, interval)
}

// SetTitleWithMnemonic calls -[NSButton setTitleWithMnemonic:].
func (o NSButton) SetTitleWithMnemonic(stringWithAmpersand string) {
	o.ID.Send(selSetTitleWithMnemonic, objcrt.NSString(stringWithAmpersand))
}

// ButtonWithImageTargetAction — !
// Creates a standard push button with the provided image. Set the image's accessibilityDescription property to ensure accessibility for this control.
// @param image The image to display in the body of the button.
// @param target The target object that receives action messages from the control.
// @param action The action message sent by the control.
// @return An initialized button object.
func (c NSButtonClass) ButtonWithImageTargetAction(image NSImage, target objc.ID, action objc.SEL) NSButton {
	return NSButton{objc.ID(c.Class).Send(selButtonWithImageTargetAction, image.ID, target, action)}
}

// ButtonWithTitleImageTargetAction — !
// Creates a standard push button with a title and image.
// @param title The localized title string that is displayed on the button.
// @param image The image that is displayed alongside the title. In left-to-right localizations, the image is displayed to the left of the title. In right-to-left localizations, it is displayed to the right.
// @param target The target object that receives action messages from the control.
// @param action The action message sent by the control.
// @return An initialized button object.
func (c NSButtonClass) ButtonWithTitleImageTargetAction(title string, image NSImage, target objc.ID, action objc.SEL) NSButton {
	return NSButton{objc.ID(c.Class).Send(selButtonWithTitleImageTargetAction, objcrt.NSString(title), image.ID, target, action)}
}

// ButtonWithTitleTargetAction — !
// Creates a standard push button with the provided title.
// @param title The localized title string that is displayed on the button.
// @param target The target object that receives action messages from the control.
// @param action The action message sent by the control.
// @return An initialized button object.
func (c NSButtonClass) ButtonWithTitleTargetAction(title string, target objc.ID, action objc.SEL) NSButton {
	return NSButton{objc.ID(c.Class).Send(selButtonWithTitleTargetAction, objcrt.NSString(title), target, action)}
}

// CheckboxWithTitleTargetAction — !
// Creates a standard checkbox with the provided title.
// @param title The localized title string that is displayed alongside the checkbox.
// @param target The target object that receives action messages from the control.
// @param action The action message sent by the control.
// @return An initialized button object.
func (c NSButtonClass) CheckboxWithTitleTargetAction(title string, target objc.ID, action objc.SEL) NSButton {
	return NSButton{objc.ID(c.Class).Send(selCheckboxWithTitleTargetAction, objcrt.NSString(title), target, action)}
}

// RadioButtonWithTitleTargetAction — !
// Creates a standard radio button with the provided title.
// @param title The localized title string that is displayed alongside the radio button.
// @param target The target object that receives action messages from the control.
// @param action The action message sent by the control.
// @return An initialized button object.
func (c NSButtonClass) RadioButtonWithTitleTargetAction(title string, target objc.ID, action objc.SEL) NSButton {
	return NSButton{objc.ID(c.Class).Send(selRadioButtonWithTitleTargetAction, objcrt.NSString(title), target, action)}
}
