// Code generated by tools/bindgen. DO NOT EDIT.
//
// Source: MacOSX26.2.sdk (Xcode 26.2), target arm64-apple-macos26.0
// Frameworks: Foundation, AppKit
//
// Regenerate with: tools/bindgen/regen.sh

//go:build darwin

package appkit

import (
	"github.com/adriaanm/wata/go-pkgs/appleptt/objcrt"
	"github.com/ebitengine/purego/objc"
)

// NSBundle wraps the ObjC class NSBundle (NSObject subclass).
type NSBundle struct{ objc.ID }

// NSBundleClass is the class object of NSBundle.
type NSBundleClass struct{ objc.Class }

// GetNSBundleClass looks the class up in the ObjC runtime.
func GetNSBundleClass() NSBundleClass { return NSBundleClass{objc.GetClass("NSBundle")} }

// Alloc allocates an uninitialized NSBundle (-[NSObject alloc]).
func (c NSBundleClass) Alloc() NSBundle { return NSBundle{objc.ID(c.Class).Send(selAlloc)} }

// BuiltInPlugInsPath reads the NSBundle property builtInPlugInsPath.
func (o NSBundle) BuiltInPlugInsPath() string {
	return objcrt.GoString(o.ID.Send(selBuiltInPlugInsPath))
}

// BundleIdentifier — Methods for obtaining various information about a bundle.
func (o NSBundle) BundleIdentifier() string {
	return objcrt.GoString(o.ID.Send(selBundleIdentifier))
}

// BundlePath reads the NSBundle property bundlePath.
func (o NSBundle) BundlePath() string {
	return objcrt.GoString(o.ID.Send(selBundlePath))
}

// DevelopmentLocalization reads the NSBundle property developmentLocalization.
func (o NSBundle) DevelopmentLocalization() string {
	return objcrt.GoString(o.ID.Send(selDevelopmentLocalization))
}

// ExecutableArchitectures reads the NSBundle property executableArchitectures.
func (o NSBundle) ExecutableArchitectures() NSArray {
	return NSArray{o.ID.Send(selExecutableArchitectures)}
}

// ExecutablePath reads the NSBundle property executablePath.
func (o NSBundle) ExecutablePath() string {
	return objcrt.GoString(o.ID.Send(selExecutablePath))
}

// InfoDictionary reads the NSBundle property infoDictionary.
func (o NSBundle) InfoDictionary() NSDictionary {
	return NSDictionary{o.ID.Send(selInfoDictionary)}
}

// Loaded reads the NSBundle property loaded.
func (o NSBundle) Loaded() bool {
	return objc.Send[bool](o.ID, selIsLoaded)
}

// Localizations reads the NSBundle property localizations.
func (o NSBundle) Localizations() NSArray {
	return NSArray{o.ID.Send(selLocalizations)}
}

// LocalizedInfoDictionary reads the NSBundle property localizedInfoDictionary.
func (o NSBundle) LocalizedInfoDictionary() NSDictionary {
	return NSDictionary{o.ID.Send(selLocalizedInfoDictionary)}
}

// PreferredLocalizations — Methods for dealing with localizations.
func (o NSBundle) PreferredLocalizations() NSArray {
	return NSArray{o.ID.Send(selPreferredLocalizations)}
}

// PrincipalClass reads the NSBundle property principalClass.
func (o NSBundle) PrincipalClass() objc.Class {
	return objc.Send[objc.Class](o.ID, selPrincipalClass)
}

// PrivateFrameworksPath reads the NSBundle property privateFrameworksPath.
func (o NSBundle) PrivateFrameworksPath() string {
	return objcrt.GoString(o.ID.Send(selPrivateFrameworksPath))
}

// ResourcePath reads the NSBundle property resourcePath.
func (o NSBundle) ResourcePath() string {
	return objcrt.GoString(o.ID.Send(selResourcePath))
}

// SharedFrameworksPath reads the NSBundle property sharedFrameworksPath.
func (o NSBundle) SharedFrameworksPath() string {
	return objcrt.GoString(o.ID.Send(selSharedFrameworksPath))
}

// SharedSupportPath reads the NSBundle property sharedSupportPath.
func (o NSBundle) SharedSupportPath() string {
	return objcrt.GoString(o.ID.Send(selSharedSupportPath))
}

// AllBundles reads the NSBundle class property allBundles.
func (c NSBundleClass) AllBundles() NSArray {
	return NSArray{objc.ID(c.Class).Send(selAllBundles)}
}

// AllFrameworks reads the NSBundle class property allFrameworks.
func (c NSBundleClass) AllFrameworks() NSArray {
	return NSArray{objc.ID(c.Class).Send(selAllFrameworks)}
}

// MainBundle — Methods for creating or retrieving bundle instances.
func (c NSBundleClass) MainBundle() NSBundle {
	return NSBundle{objc.ID(c.Class).Send(selMainBundle)}
}

// URLsForResourcesWithExtensionSubdirectory calls -[NSBundle URLsForResourcesWithExtension:subdirectory:].
func (o NSBundle) URLsForResourcesWithExtensionSubdirectory(ext string, subpath string) NSArray {
	return NSArray{o.ID.Send(selURLsForResourcesWithExtensionSubdirectory, objcrt.NSString(ext), objcrt.NSString(subpath))}
}

// URLsForResourcesWithExtensionSubdirectoryLocalization calls -[NSBundle URLsForResourcesWithExtension:subdirectory:localization:].
func (o NSBundle) URLsForResourcesWithExtensionSubdirectoryLocalization(ext string, subpath string, localizationName string) NSArray {
	return NSArray{o.ID.Send(selURLsForResourcesWithExtensionSubdirectoryLocalization, objcrt.NSString(ext), objcrt.NSString(subpath), objcrt.NSString(localizationName))}
}

// ClassNamed calls -[NSBundle classNamed:].
func (o NSBundle) ClassNamed(className string) objc.Class {
	return objc.Send[objc.Class](o.ID, selClassNamed, objcrt.NSString(className))
}

// ImageForResource calls -[NSBundle imageForResource:].
func (o NSBundle) ImageForResource(name string) NSImage {
	return NSImage{o.ID.Send(selImageForResource, objcrt.NSString(name))}
}

// InitWithPath calls -[NSBundle initWithPath:].
func (o NSBundle) InitWithPath(path string) NSBundle {
	return NSBundle{o.ID.Send(selInitWithPath, objcrt.NSString(path))}
}

// Load — Methods for loading and unloading bundles.
func (o NSBundle) Load() bool {
	return objc.Send[bool](o.ID, selLoad)
}

// LoadAndReturnError calls -[NSBundle loadAndReturnError:].
func (o NSBundle) LoadAndReturnError() (bool, error) {
	var errOut objcrt.ErrOut
	ret := objc.Send[bool](o.ID, selLoadAndReturnError, errOut.Ptr())
	return ret, errOut.Err()
}

// LocalizedStringForKeyValueTable — Methods for retrieving localized strings.
func (o NSBundle) LocalizedStringForKeyValueTable(key string, value string, tableName string) string {
	return objcrt.GoString(o.ID.Send(selLocalizedStringForKeyValueTable, objcrt.NSString(key), objcrt.NSString(value), objcrt.NSString(tableName)))
}

// LocalizedStringForKeyValueTableLocalizations — Look up a localized string given a list of available localizations.
// - Parameters:
// - key: The key for the localized string to retrieve.
// - value: A default value to return if a localized string for “key“ cannot be found.
// - tableName: The name of the strings file to search. If `nil`, the method uses tables in `Localizable.strings`.
// - localizations: An array of BCP 47 language codes corresponding to available localizations. Bundle compares the array against its available localizations, and uses the best result to retrieve the localized string. If empty, we treat it as no localization is available, and may return a fallback.
// - Returns: A localized version of the string designated by “key“ in table “tableName“.
func (o NSBundle) LocalizedStringForKeyValueTableLocalizations(key string, value string, tableName string, localizations NSArray) string {
	return objcrt.GoString(o.ID.Send(selLocalizedStringForKeyValueTableLocalizations, objcrt.NSString(key), objcrt.NSString(value), objcrt.NSString(tableName), localizations.ID))
}

// ObjectForInfoDictionaryKey calls -[NSBundle objectForInfoDictionaryKey:].
func (o NSBundle) ObjectForInfoDictionaryKey(key string) objc.ID {
	return o.ID.Send(selObjectForInfoDictionaryKey, objcrt.NSString(key))
}

// PathForAuxiliaryExecutable calls -[NSBundle pathForAuxiliaryExecutable:].
func (o NSBundle) PathForAuxiliaryExecutable(executableName string) string {
	return objcrt.GoString(o.ID.Send(selPathForAuxiliaryExecutable, objcrt.NSString(executableName)))
}

// PathForImageResource calls -[NSBundle pathForImageResource:].
func (o NSBundle) PathForImageResource(name string) string {
	return objcrt.GoString(o.ID.Send(selPathForImageResource, objcrt.NSString(name)))
}

// PathForResourceOfType calls -[NSBundle pathForResource:ofType:].
func (o NSBundle) PathForResourceOfType(name string, ext string) string {
	return objcrt.GoString(o.ID.Send(selPathForResourceOfType, objcrt.NSString(name), objcrt.NSString(ext)))
}

// PathForResourceOfTypeInDirectory calls -[NSBundle pathForResource:ofType:inDirectory:].
func (o NSBundle) PathForResourceOfTypeInDirectory(name string, ext string, subpath string) string {
	return objcrt.GoString(o.ID.Send(selPathForResourceOfTypeInDirectory, objcrt.NSString(name), objcrt.NSString(ext), objcrt.NSString(subpath)))
}

// PathForResourceOfTypeInDirectoryForLocalization calls -[NSBundle pathForResource:ofType:inDirectory:forLocalization:].
func (o NSBundle) PathForResourceOfTypeInDirectoryForLocalization(name string, ext string, subpath string, localizationName string) string {
	return objcrt.GoString(o.ID.Send(selPathForResourceOfTypeInDirectoryForLocalization, objcrt.NSString(name), objcrt.NSString(ext), objcrt.NSString(subpath), objcrt.NSString(localizationName)))
}

// PathForSoundResource — May return nil if no file found
func (o NSBundle) PathForSoundResource(name string) string {
	return objcrt.GoString(o.ID.Send(selPathForSoundResource, objcrt.NSString(name)))
}

// PathsForResourcesOfTypeInDirectory calls -[NSBundle pathsForResourcesOfType:inDirectory:].
func (o NSBundle) PathsForResourcesOfTypeInDirectory(ext string, subpath string) NSArray {
	return NSArray{o.ID.Send(selPathsForResourcesOfTypeInDirectory, objcrt.NSString(ext), objcrt.NSString(subpath))}
}

// PathsForResourcesOfTypeInDirectoryForLocalization calls -[NSBundle pathsForResourcesOfType:inDirectory:forLocalization:].
func (o NSBundle) PathsForResourcesOfTypeInDirectoryForLocalization(ext string, subpath string, localizationName string) NSArray {
	return NSArray{o.ID.Send(selPathsForResourcesOfTypeInDirectoryForLocalization, objcrt.NSString(ext), objcrt.NSString(subpath), objcrt.NSString(localizationName))}
}

// PreflightAndReturnError calls -[NSBundle preflightAndReturnError:].
func (o NSBundle) PreflightAndReturnError() (bool, error) {
	var errOut objcrt.ErrOut
	ret := objc.Send[bool](o.ID, selPreflightAndReturnError, errOut.Ptr())
	return ret, errOut.Err()
}

// PreservationPriorityForTag calls -[NSBundle preservationPriorityForTag:].
func (o NSBundle) PreservationPriorityForTag(tag string) float64 {
	return objc.Send[float64](o.ID, selPreservationPriorityForTag, objcrt.NSString(tag))
}

// Unload calls -[NSBundle unload].
func (o NSBundle) Unload() bool {
	return objc.Send[bool](o.ID, selUnload)
}

// BundleForClass calls +[NSBundle bundleForClass:].
func (c NSBundleClass) BundleForClass(aClass objc.Class) NSBundle {
	return NSBundle{objc.ID(c.Class).Send(selBundleForClass, aClass)}
}

// BundleWithIdentifier calls +[NSBundle bundleWithIdentifier:].
func (c NSBundleClass) BundleWithIdentifier(identifier string) NSBundle {
	return NSBundle{objc.ID(c.Class).Send(selBundleWithIdentifier, objcrt.NSString(identifier))}
}

// BundleWithPath calls +[NSBundle bundleWithPath:].
func (c NSBundleClass) BundleWithPath(path string) NSBundle {
	return NSBundle{objc.ID(c.Class).Send(selBundleWithPath, objcrt.NSString(path))}
}

// LoadNibNamedOwner calls +[NSBundle loadNibNamed:owner:].
func (c NSBundleClass) LoadNibNamedOwner(nibName string, owner objc.ID) bool {
	return objc.Send[bool](objc.ID(c.Class), selLoadNibNamedOwner, objcrt.NSString(nibName), owner)
}

// PathForResourceOfTypeInDirectory calls +[NSBundle pathForResource:ofType:inDirectory:].
func (c NSBundleClass) PathForResourceOfTypeInDirectory(name string, ext string, bundlePath string) string {
	return objcrt.GoString(objc.ID(c.Class).Send(selPathForResourceOfTypeInDirectory, objcrt.NSString(name), objcrt.NSString(ext), objcrt.NSString(bundlePath)))
}

// PathsForResourcesOfTypeInDirectory calls +[NSBundle pathsForResourcesOfType:inDirectory:].
func (c NSBundleClass) PathsForResourcesOfTypeInDirectory(ext string, bundlePath string) NSArray {
	return NSArray{objc.ID(c.Class).Send(selPathsForResourcesOfTypeInDirectory, objcrt.NSString(ext), objcrt.NSString(bundlePath))}
}

// PreferredLocalizationsFromArray calls +[NSBundle preferredLocalizationsFromArray:].
func (c NSBundleClass) PreferredLocalizationsFromArray(localizationsArray NSArray) NSArray {
	return NSArray{objc.ID(c.Class).Send(selPreferredLocalizationsFromArray, localizationsArray.ID)}
}

// PreferredLocalizationsFromArrayForPreferences calls +[NSBundle preferredLocalizationsFromArray:forPreferences:].
func (c NSBundleClass) PreferredLocalizationsFromArrayForPreferences(localizationsArray NSArray, preferencesArray NSArray) NSArray {
	return NSArray{objc.ID(c.Class).Send(selPreferredLocalizationsFromArrayForPreferences, localizationsArray.ID, preferencesArray.ID)}
}
