// Code generated by tools/bindgen. DO NOT EDIT.
//
// Source: MacOSX26.2.sdk (Xcode 26.2), target arm64-apple-macos26.0
// Frameworks: Foundation, AppKit
//
// Regenerate with: tools/bindgen/regen.sh

//go:build darwin

package appkit

import (
	"github.com/adriaanm/wata/go-pkgs/appleptt/objcrt"
	"github.com/ebitengine/purego/objc"
)

// NSControl wraps the ObjC class NSControl (NSView subclass).
type NSControl struct{ objc.ID }

// NSControlClass is the class object of NSControl.
type NSControlClass struct{ objc.Class }

// GetNSControlClass looks the class up in the ObjC runtime.
func GetNSControlClass() NSControlClass { return NSControlClass{objc.GetClass("NSControl")} }

// Alloc allocates an uninitialized NSControl (-[NSObject alloc]).
func (c NSControlClass) Alloc() NSControl { return NSControl{objc.ID(c.Class).Send(selAlloc)} }

// Action reads the NSControl property action.
func (o NSControl) Action() objc.SEL {
	return objc.Send[objc.SEL](o.ID, selAction)
}

// SetAction writes the NSControl property action.
func (o NSControl) SetAction(v objc.SEL) {
	o.ID.Send(selSetAction, v)
}

// AllowsExpansionToolTips reads the NSControl property allowsExpansionToolTips.
func (o NSControl) AllowsExpansionToolTips() bool {
	return objc.Send[bool](o.ID, selAllowsExpansionToolTips)
}

// SetAllowsExpansionToolTips writes the NSControl property allowsExpansionToolTips.
func (o NSControl) SetAllowsExpansionToolTips(v bool) {
	o.ID.Send(selSetAllowsExpansionToolTips, v)
}

// Continuous reads the NSControl property continuous.
func (o NSControl) Continuous() bool {
	return objc.Send[bool](o.ID, selIsContinuous)
}

// SetContinuous writes the NSControl property continuous.
func (o NSControl) SetContinuous(v bool) {
	o.ID.Send(selSetContinuous, v)
}

// DoubleValue reads the NSControl property doubleValue.
func (o NSControl) DoubleValue() float64 {
	return objc.Send[float64](o.ID, selDoubleValue)
}

// SetDoubleValue writes the NSControl property doubleValue.
func (o NSControl) SetDoubleValue(v float64) {
	o.ID.Send(selSetDoubleValue, v)
}

// Enabled reads the NSControl property enabled.
func (o NSControl) Enabled() bool {
	return objc.Send[bool](o.ID, selIsEnabled)
}

// SetEnabled writes the NSControl property enabled.
func (o NSControl) SetEnabled(v bool) {
	o.ID.Send(selSetEnabled, v)
}

// FloatValue reads the NSControl property floatValue.
func (o NSControl) FloatValue() float32 {
	return objc.Send[float32](o.ID, selFloatValue)
}

// SetFloatValue writes the NSControl property floatValue.
func (o NSControl) SetFloatValue(v float32) {
	o.ID.Send(selSetFloatValue, v)
}

// Font reads the NSControl property font.
func (o NSControl) Font() NSFont {
	return NSFont{o.ID.Send(selFont)}
}

// SetFont writes the NSControl property font.
func (o NSControl) SetFont(v NSFont) {
	o.ID.Send(selSetFont, v.ID)
}

// Highlighted reads the NSControl property highlighted.
func (o NSControl) Highlighted() bool {
	return objc.Send[bool](o.ID, selIsHighlighted)
}

// SetHighlighted writes the NSControl property highlighted.
func (o NSControl) SetHighlighted(v bool) {
	o.ID.Send(selSetHighlighted, v)
}

// IgnoresMultiClick reads the NSControl property ignoresMultiClick.
func (o NSControl) IgnoresMultiClick() bool {
	return objc.Send[bool](o.ID, selIgnoresMultiClick)
}

// SetIgnoresMultiClick writes the NSControl property ignoresMultiClick.
func (o NSControl) SetIgnoresMultiClick(v bool) {
	o.ID.Send(selSetIgnoresMultiClick, v)
}

// IntValue reads the NSControl property intValue.
func (o NSControl) IntValue() int32 {
	return objc.Send[int32](o.ID, selIntValue)
}

// SetIntValue writes the NSControl property intValue.
func (o NSControl) SetIntValue(v int32) {
	o.ID.Send(selSetIntValue, v)
}

// IntegerValue reads the NSControl property integerValue.
func (o NSControl) IntegerValue() int {
	return objc.Send[int](o.ID, selIntegerValue)
}

// SetIntegerValue writes the NSControl property integerValue.
func (o NSControl) SetIntegerValue(v int) {
	o.ID.Send(selSetIntegerValue, v)
}

// ObjectValue reads the NSControl property objectValue.
func (o NSControl) ObjectValue() objc.ID {
	return o.ID.Send(selObjectValue)
}

// SetObjectValue writes the NSControl property objectValue.
func (o NSControl) SetObjectValue(v objc.ID) {
	o.ID.Send(selSetObjectValue, v)
}

// RefusesFirstResponder reads the NSControl property refusesFirstResponder.
func (o NSControl) RefusesFirstResponder() bool {
	return objc.Send[bool](o.ID, selRefusesFirstResponder)
}

// SetRefusesFirstResponder writes the NSControl property refusesFirstResponder.
func (o NSControl) SetRefusesFirstResponder(v bool) {
	o.ID.Send(selSetRefusesFirstResponder, v)
}

// StringValue reads the NSControl property stringValue.
func (o NSControl) StringValue() string {
	return objcrt.GoString(o.ID.Send(selStringValue))
}

// SetStringValue writes the NSControl property stringValue.
func (o NSControl) SetStringValue(v string) {
	o.ID.Send(selSetStringValue, objcrt.NSString(v))
}

// Tag reads the NSControl property tag.
func (o NSControl) Tag() int {
	return objc.Send[int](o.ID, selTag)
}

// SetTag writes the NSControl property tag.
func (o NSControl) SetTag(v int) {
	o.ID.Send(selSetTag, v)
}

// Target reads the NSControl property target.
func (o NSControl) Target() objc.ID {
	return o.ID.Send(selTarget)
}

// SetTarget writes the NSControl property target.
func (o NSControl) SetTarget(v objc.ID) {
	o.ID.Send(selSetTarget, v)
}

// UsesSingleLineMode reads the NSControl property usesSingleLineMode.
func (o NSControl) UsesSingleLineMode() bool {
	return objc.Send[bool](o.ID, selUsesSingleLineMode)
}

// SetUsesSingleLineMode writes the NSControl property usesSingleLineMode.
func (o NSControl) SetUsesSingleLineMode(v bool) {
	o.ID.Send(selSetUsesSingleLineMode, v)
}

// AbortEditing calls -[NSControl abortEditing].
func (o NSControl) AbortEditing() bool {
	return objc.Send[bool](o.ID, selAbortEditing)
}

// DrawWithExpansionFrameInView calls -[NSControl drawWithExpansionFrame:inView:].
func (o NSControl) DrawWithExpansionFrameInView(contentFrame CGRect, view NSView) {
	o.ID.Send(selDrawWithExpansionFrameInView, contentFrame, view.ID)
}

// ExpansionFrameWithFrame calls -[NSControl expansionFrameWithFrame:].
func (o NSControl) ExpansionFrameWithFrame(contentFrame CGRect) CGRect {
	return objc.Send[CGRect](o.ID, selExpansionFrameWithFrame, contentFrame)
}

// InitWithFrame calls -[NSControl initWithFrame:].
func (o NSControl) InitWithFrame(frameRect CGRect) NSControl {
	return NSControl{o.ID.Send(selInitWithFrame, frameRect)}
}

// PerformClick calls -[NSControl performClick:].
func (o NSControl) PerformClick(sender objc.ID) {
	o.ID.Send(selPerformClick, sender)
}

// SelectedTag calls -[NSControl selectedTag].
func (o NSControl) SelectedTag() int {
	return objc.Send[int](o.ID, selSelectedTag)
}

// SendActionTo calls -[NSControl sendAction:to:].
func (o NSControl) SendActionTo(action objc.SEL, target objc.ID) bool {
	return objc.Send[bool](o.ID, selSendActionTo, action, target)
}

// SizeThatFits calls -[NSControl sizeThatFits:].
func (o NSControl) SizeThatFits(size CGSize) CGSize {
	return objc.Send[CGSize](o.ID, selSizeThatFits, size)
}

// SizeToFit calls -[NSControl sizeToFit].
func (o NSControl) SizeToFit() {
	o.ID.Send(selSizeToFit)
}

// TakeDoubleValueFrom calls -[NSControl takeDoubleValueFrom:].
func (o NSControl) TakeDoubleValueFrom(sender objc.ID) {
	o.ID.Send(selTakeDoubleValueFrom, sender)
}

// TakeFloatValueFrom calls -[NSControl takeFloatValueFrom:].
func (o NSControl) TakeFloatValueFrom(sender objc.ID) {
	o.ID.Send(selTakeFloatValueFrom, sender)
}

// TakeIntValueFrom calls -[NSControl takeIntValueFrom:].
func (o NSControl) TakeIntValueFrom(sender objc.ID) {
	o.ID.Send(selTakeIntValueFrom, sender)
}

// TakeIntegerValueFrom calls -[NSControl takeIntegerValueFrom:].
func (o NSControl) TakeIntegerValueFrom(sender objc.ID) {
	o.ID.Send(selTakeIntegerValueFrom, sender)
}

// TakeObjectValueFrom calls -[NSControl takeObjectValueFrom:].
func (o NSControl) TakeObjectValueFrom(sender objc.ID) {
	o.ID.Send(selTakeObjectValueFrom, sender)
}

// TakeStringValueFrom calls -[NSControl takeStringValueFrom:].
func (o NSControl) TakeStringValueFrom(sender objc.ID) {
	o.ID.Send(selTakeStringValueFrom, sender)
}

// ValidateEditing calls -[NSControl validateEditing].
func (o NSControl) ValidateEditing() {
	o.ID.Send(selValidateEditing)
}
