// Code generated by tools/bindgen. DO NOT EDIT.
//
// Source: MacOSX26.2.sdk (Xcode 26.2), target arm64-apple-macos26.0
// Frameworks: Foundation, AppKit
//
// Regenerate with: tools/bindgen/regen.sh

//go:build darwin

package appkit

import (
	"github.com/adriaanm/wata/go-pkgs/appleptt/objcrt"
	"github.com/ebitengine/purego/objc"
)

// NSEvent wraps the ObjC class NSEvent (NSObject subclass).
type NSEvent struct{ objc.ID }

// NSEventClass is the class object of NSEvent.
type NSEventClass struct{ objc.Class }

// GetNSEventClass looks the class up in the ObjC runtime.
func GetNSEventClass() NSEventClass { return NSEventClass{objc.GetClass("NSEvent")} }

// Alloc allocates an uninitialized NSEvent (-[NSObject alloc]).
func (c NSEventClass) Alloc() NSEvent { return NSEvent{objc.ID(c.Class).Send(selAlloc)} }

// ARepeat — the chars that would have been generated, regardless of modifier keys (except shift)
func (o NSEvent) ARepeat() bool {
	return objc.Send[bool](o.ID, selIsARepeat)
}

// AbsoluteX — absolute x coordinate in tablet space at full tablet resolution
func (o NSEvent) AbsoluteX() int {
	return objc.Send[int](o.ID, selAbsoluteX)
}

// AbsoluteY — absolute y coordinate in tablet space at full tablet resolution
func (o NSEvent) AbsoluteY() int {
	return objc.Send[int](o.ID, selAbsoluteY)
}

// AbsoluteZ — absolute z coordinate in tablet space at full tablet resolution
func (o NSEvent) AbsoluteZ() int {
	return objc.Send[int](o.ID, selAbsoluteZ)
}

// ButtonNumber reads the NSEvent property buttonNumber.
func (o NSEvent) ButtonNumber() int {
	return objc.Send[int](o.ID, selButtonNumber)
}

// CapabilityMask — mask representing capabilities of device
func (o NSEvent) CapabilityMask() uint {
	return objc.Send[uint](o.ID, selCapabilityMask)
}

// Characters — these messages are valid for keyup and keydown events
func (o NSEvent) Characters() string {
	return objcrt.GoString(o.ID.Send(selCharacters))
}

// CharactersIgnoringModifiers reads the NSEvent property charactersIgnoringModifiers.
func (o NSEvent) CharactersIgnoringModifiers() string {
	return objcrt.GoString(o.ID.Send(selCharactersIgnoringModifiers))
}

// ClickCount — these messages are valid for all mouse down/up/drag events
func (o NSEvent) ClickCount() int {
	return objc.Send[int](o.ID, selClickCount)
}

// Data1 — these messages are valid for kit, system, and app-defined events
func (o NSEvent) Data1() int {
	return objc.Send[int](o.ID, selData1)
}

// Data2 reads the NSEvent property data2.
func (o NSEvent) Data2() int {
	return objc.Send[int](o.ID, selData2)
}

// DeltaX — these messages are valid for scroll wheel events and mouse move/drag events.  As of 10.5.2, deltaX and deltaY are also valid for swipe events.  A non-0 deltaX will represent a horizontal swipe, -1 for swipe right and 1 for swipe left.  A non-0 deltaY will represent a vertical swipe, -1 for swipe down and 1 for swipe up. As of 10.7, the preferred methods for scroll wheel events are scrollingDeltaX and scrollingDeltaY defined below.
func (o NSEvent) DeltaX() float64 {
	return objc.Send[float64](o.ID, selDeltaX)
}

// DeltaY reads the NSEvent property deltaY.
func (o NSEvent) DeltaY() float64 {
	return objc.Send[float64](o.ID, selDeltaY)
}

// DeltaZ reads the NSEvent property deltaZ.
func (o NSEvent) DeltaZ() float64 {
	return objc.Send[float64](o.ID, selDeltaZ)
}

// DeviceID — this message is valid for mouse events with subtype NSEventSubtypeTabletPoint or NSEventSubtypeTabletProximity, and for NSEventTypeTabletPoint and NSEventTypeTabletProximity events
func (o NSEvent) DeviceID() uint {
	return objc.Send[uint](o.ID, selDeviceID)
}

// DirectionInvertedFromDevice — valid for NSEventScrollWheel events. The user may choose to change the scrolling behavior such that it feels like they are moving the content instead of the scroll bar. To accomplish this, deltaX/Y and scrollingDeltaX/Y are automatically inverted for NSEventScrollWheel events according to the user's preferences. However, for some uses, the behavior should not respect the user preference. This method allows you to determine when the event has been inverted and compensate by multiplying -1 if needed.
func (o NSEvent) DirectionInvertedFromDevice() bool {
	return objc.Send[bool](o.ID, selIsDirectionInvertedFromDevice)
}

// EnteringProximity — YES - entering; NO - leaving
func (o NSEvent) EnteringProximity() bool {
	return objc.Send[bool](o.ID, selIsEnteringProximity)
}

// EventNumber — these messages are valid for all mouse down/up/drag and enter/exit events
func (o NSEvent) EventNumber() int {
	return objc.Send[int](o.ID, selEventNumber)
}

// HasPreciseScrollingDeltas — This message is valid for NSEventTypeScrollWheel events. A generic scroll wheel issues rather coarse scroll deltas. Some Apple mice and trackpads provide much more precise delta. This method determines the resolution of the scrollDeltaX and scrollDeltaY values.
func (o NSEvent) HasPreciseScrollingDeltas() bool {
	return objc.Send[bool](o.ID, selHasPreciseScrollingDeltas)
}

// KeyCode — this message is valid for keyup, keydown and flagschanged events
func (o NSEvent) KeyCode() uint16 {
	return objc.Send[uint16](o.ID, selKeyCode)
}

// LocationInWindow — -locationInWindow is valid for all mouse-related events
func (o NSEvent) LocationInWindow() CGPoint {
	return objc.Send[CGPoint](o.ID, selLocationInWindow)
}

// Magnification — This message is valid for events of type NSEventTypeMagnify, on 10.5.2 or later
func (o NSEvent) Magnification() float64 {
	return objc.Send[float64](o.ID, selMagnification)
}

// ModifierFlags reads the NSEvent property modifierFlags.
func (o NSEvent) ModifierFlags() NSEventModifierFlags {
	return NSEventModifierFlags(objc.Send[uint](o.ID, selModifierFlags))
}

// PointingDeviceID — index of the device on the tablet.  Usually 0, except for tablets that support multiple concurrent devices
func (o NSEvent) PointingDeviceID() uint {
	return objc.Send[uint](o.ID, selPointingDeviceID)
}

// PointingDeviceSerialNumber — vendor defined serial number of pointing device
func (o NSEvent) PointingDeviceSerialNumber() uint {
	return objc.Send[uint](o.ID, selPointingDeviceSerialNumber)
}

// Pressure — -pressure is valid for all mouse down/up/drag events, and is also valid for NSEventTypeTabletPoint events on 10.4 or later and NSEventTypePressure on 10.10.3 or later
func (o NSEvent) Pressure() float32 {
	return objc.Send[float32](o.ID, selPressure)
}

// Rotation — this message is valid for valid for mouse events with subtype NSEventSubtypeTabletPoint, and for NSEventTypeTabletPoint events.  On 10.5.2 or later, it is also valid for NSEventTypeRotate events.
func (o NSEvent) Rotation() float32 {
	return objc.Send[float32](o.ID, selRotation)
}

// ScrollingDeltaX — The following two message are the preferred API for accessing NSEventTypeScrollWheel deltas. When -hasPreciseScrollingDeltas reutrns NO, multiply the returned value by line or row height. When -hasPreciseScrollingDeltas returns YES, scroll by the returned value (in points).
func (o NSEvent) ScrollingDeltaX() float64 {
	return objc.Send[float64](o.ID, selScrollingDeltaX)
}

// ScrollingDeltaY reads the NSEvent property scrollingDeltaY.
func (o NSEvent) ScrollingDeltaY() float64 {
	return objc.Send[float64](o.ID, selScrollingDeltaY)
}

// Stage reads the NSEvent property stage.
func (o NSEvent) Stage() int {
	return objc.Send[int](o.ID, selStage)
}

// StageTransition reads the NSEvent property stageTransition.
func (o NSEvent) StageTransition() float64 {
	return objc.Send[float64](o.ID, selStageTransition)
}

// SystemTabletID — system assigned unique tablet ID
func (o NSEvent) SystemTabletID() uint {
	return objc.Send[uint](o.ID, selSystemTabletID)
}

// TabletID — vendor defined tablet ID
func (o NSEvent) TabletID() uint {
	return objc.Send[uint](o.ID, selTabletID)
}

// TangentialPressure — tangential pressure on the device; range is -1 to 1
func (o NSEvent) TangentialPressure() float32 {
	return objc.Send[float32](o.ID, selTangentialPressure)
}

// Tilt — range is -1 to 1 for both axes
func (o NSEvent) Tilt() CGPoint {
	return objc.Send[CGPoint](o.ID, selTilt)
}

// Timestamp reads the NSEvent property timestamp.
func (o NSEvent) Timestamp() float64 {
	return objc.Send[float64](o.ID, selTimestamp)
}

// TrackingNumber — these messages are valid for enter and exit events
func (o NSEvent) TrackingNumber() int {
	return objc.Send[int](o.ID, selTrackingNumber)
}

// Type — these messages are valid for all events
func (o NSEvent) Type() NSEventType {
	return NSEventType(objc.Send[uint](o.ID, selType))
}

// UniqueID — vendor defined unique ID
func (o NSEvent) UniqueID() uint64 {
	return objc.Send[uint64](o.ID, selUniqueID)
}

// VendorDefined — NSArray of 3 vendor defined shorts
func (o NSEvent) VendorDefined() objc.ID {
	return o.ID.Send(selVendorDefined)
}

// VendorID — vendor defined, typically USB vendor ID
func (o NSEvent) VendorID() uint {
	return objc.Send[uint](o.ID, selVendorID)
}

// VendorPointingDeviceType — vendor defined pointing device type
func (o NSEvent) VendorPointingDeviceType() uint {
	return objc.Send[uint](o.ID, selVendorPointingDeviceType)
}

// Window reads the NSEvent property window.
func (o NSEvent) Window() NSWindow {
	return NSWindow{o.ID.Send(selWindow)}
}

// WindowNumber reads the NSEvent property windowNumber.
func (o NSEvent) WindowNumber() int {
	return objc.Send[int](o.ID, selWindowNumber)
}

// DoubleClickInterval reads the NSEvent class property doubleClickInterval.
func (c NSEventClass) DoubleClickInterval() float64 {
	return objc.Send[float64](objc.ID(c.Class), selDoubleClickInterval)
}

// KeyRepeatDelay reads the NSEvent class property keyRepeatDelay.
func (c NSEventClass) KeyRepeatDelay() float64 {
	return objc.Send[float64](objc.ID(c.Class), selKeyRepeatDelay)
}

// KeyRepeatInterval reads the NSEvent class property keyRepeatInterval.
func (c NSEventClass) KeyRepeatInterval() float64 {
	return objc.Send[float64](objc.ID(c.Class), selKeyRepeatInterval)
}

// MouseCoalescingEnabled — Enable or disable coalescing of mouse movement events, including mouse moved, mouse dragged, and tablet events.  Coalescing is enabled by default.
func (c NSEventClass) MouseCoalescingEnabled() bool {
	return objc.Send[bool](objc.ID(c.Class), selIsMouseCoalescingEnabled)
}

// SetMouseCoalescingEnabled writes the NSEvent class property mouseCoalescingEnabled.
func (c NSEventClass) SetMouseCoalescingEnabled(v bool) {
	objc.ID(c.Class).Send(selSetMouseCoalescingEnabled, v)
}

// MouseLocation reads the NSEvent class property mouseLocation.
func (c NSEventClass) MouseLocation() CGPoint {
	return objc.Send[CGPoint](objc.ID(c.Class), selMouseLocation)
}

// PressedMouseButtons reads the NSEvent class property pressedMouseButtons.
func (c NSEventClass) PressedMouseButtons() uint {
	return objc.Send[uint](objc.ID(c.Class), selPressedMouseButtons)
}

// SwipeTrackingFromScrollEventsEnabled reads the NSEvent class property swipeTrackingFromScrollEventsEnabled.
func (c NSEventClass) SwipeTrackingFromScrollEventsEnabled() bool {
	return objc.Send[bool](objc.ID(c.Class), selIsSwipeTrackingFromScrollEventsEnabled)
}

// CharactersByApplyingModifiers — This message is valid keyup and keydown events.
// It returns the character(s) that would have been generated if a different modifier combination had been used.
// It uses [self keyCode], the new modifiers and the current keyboard input source's layout data for re-translation.  It entirely ignores the modifiers that are already present in the event and calling this method will not affect the dead key state for current text input.
// If there is invalid data in this event, -charactersByApplyingModifiers will return nil.
func (o NSEvent) CharactersByApplyingModifiers(modifiers NSEventModifierFlags) string {
	return objcrt.GoString(o.ID.Send(selCharactersByApplyingModifiers, uint(modifiers)))
}

// RemoveMonitor calls +[NSEvent removeMonitor:].
func (c NSEventClass) RemoveMonitor(eventMonitor objc.ID) {
	objc.ID(c.Class).Send(selRemoveMonitor, eventMonitor)
}

// StartPeriodicEventsAfterDelayWithPeriod calls +[NSEvent startPeriodicEventsAfterDelay:withPeriod:].
func (c NSEventClass) StartPeriodicEventsAfterDelayWithPeriod(delay float64, period float64) {
	objc.ID(c.Class).Send(selStartPeriodicEventsAfterDelayWithPeriod, delay, period)
}

// StopPeriodicEvents calls +[NSEvent stopPeriodicEvents].
func (c NSEventClass) StopPeriodicEvents() {
	objc.ID(c.Class).Send(selStopPeriodicEvents)
}
