// Code generated by tools/bindgen. DO NOT EDIT.
//
// Source: MacOSX26.2.sdk (Xcode 26.2), target arm64-apple-macos26.0
// Frameworks: Foundation, AppKit
//
// Regenerate with: tools/bindgen/regen.sh

//go:build darwin

package appkit

import (
	"github.com/adriaanm/wata/go-pkgs/appleptt/objcrt"
	"github.com/ebitengine/purego/objc"
)

// NSFont wraps the ObjC class NSFont (NSObject subclass).
type NSFont struct{ objc.ID }

// NSFontClass is the class object of NSFont.
type NSFontClass struct{ objc.Class }

// GetNSFontClass looks the class up in the ObjC runtime.
func GetNSFontClass() NSFontClass { return NSFontClass{objc.GetClass("NSFont")} }

// Alloc allocates an uninitialized NSFont (-[NSObject alloc]).
func (c NSFontClass) Alloc() NSFont { return NSFont{objc.ID(c.Class).Send(selAlloc)} }

// Ascender reads the NSFont property ascender.
func (o NSFont) Ascender() float64 {
	return objc.Send[float64](o.ID, selAscender)
}

// BoundingRectForFont — These methods return scaled numbers.  If the font was created with a matrix, the matrix is applied automatically; otherwise the coordinates are multiplied by size.
func (o NSFont) BoundingRectForFont() CGRect {
	return objc.Send[CGRect](o.ID, selBoundingRectForFont)
}

// CapHeight reads the NSFont property capHeight.
func (o NSFont) CapHeight() float64 {
	return objc.Send[float64](o.ID, selCapHeight)
}

// Descender reads the NSFont property descender.
func (o NSFont) Descender() float64 {
	return objc.Send[float64](o.ID, selDescender)
}

// DisplayName reads the NSFont property displayName.
func (o NSFont) DisplayName() string {
	return objcrt.GoString(o.ID.Send(selDisplayName))
}

// FamilyName reads the NSFont property familyName.
func (o NSFont) FamilyName() string {
	return objcrt.GoString(o.ID.Send(selFamilyName))
}

// FixedPitch reads the NSFont property fixedPitch.
func (o NSFont) FixedPitch() bool {
	return objc.Send[bool](o.ID, selIsFixedPitch)
}

// FontName — Core font attribute ********
func (o NSFont) FontName() string {
	return objcrt.GoString(o.ID.Send(selFontName))
}

// ItalicAngle reads the NSFont property italicAngle.
func (o NSFont) ItalicAngle() float64 {
	return objc.Send[float64](o.ID, selItalicAngle)
}

// Leading reads the NSFont property leading.
func (o NSFont) Leading() float64 {
	return objc.Send[float64](o.ID, selLeading)
}

// MaximumAdvancement reads the NSFont property maximumAdvancement.
func (o NSFont) MaximumAdvancement() CGSize {
	return objc.Send[CGSize](o.ID, selMaximumAdvancement)
}

// MostCompatibleStringEncoding reads the NSFont property mostCompatibleStringEncoding.
func (o NSFont) MostCompatibleStringEncoding() uint {
	return objc.Send[uint](o.ID, selMostCompatibleStringEncoding)
}

// NumberOfGlyphs — Glyph coverage ********
func (o NSFont) NumberOfGlyphs() uint {
	return objc.Send[uint](o.ID, selNumberOfGlyphs)
}

// PointSize reads the NSFont property pointSize.
func (o NSFont) PointSize() float64 {
	return objc.Send[float64](o.ID, selPointSize)
}

// PrinterFont — Rendering mode ********
func (o NSFont) PrinterFont() NSFont {
	return NSFont{o.ID.Send(selPrinterFont)}
}

// ScreenFont reads the NSFont property screenFont.
func (o NSFont) ScreenFont() NSFont {
	return NSFont{o.ID.Send(selScreenFont)}
}

// UnderlinePosition reads the NSFont property underlinePosition.
func (o NSFont) UnderlinePosition() float64 {
	return objc.Send[float64](o.ID, selUnderlinePosition)
}

// UnderlineThickness reads the NSFont property underlineThickness.
func (o NSFont) UnderlineThickness() float64 {
	return objc.Send[float64](o.ID, selUnderlineThickness)
}

// Vertical — Returns YES if a vertical variant
func (o NSFont) Vertical() bool {
	return objc.Send[bool](o.ID, selIsVertical)
}

// VerticalFont — Returns a vertical version of the receiver if such a configuration is supported.  Returns the receiver if no vertical variant available.  A vertical font applies appropriate rotation to the text matrix in -setInContext:, returns vertical metrics, and enables the vertical glyph substitution feature by default.
func (o NSFont) VerticalFont() NSFont {
	return NSFont{o.ID.Send(selVerticalFont)}
}

// XHeight reads the NSFont property xHeight.
func (o NSFont) XHeight() float64 {
	return objc.Send[float64](o.ID, selXHeight)
}

// LabelFontSize reads the NSFont class property labelFontSize.
func (c NSFontClass) LabelFontSize() float64 {
	return objc.Send[float64](objc.ID(c.Class), selLabelFontSize)
}

// SmallSystemFontSize reads the NSFont class property smallSystemFontSize.
func (c NSFontClass) SmallSystemFontSize() float64 {
	return objc.Send[float64](objc.ID(c.Class), selSmallSystemFontSize)
}

// SystemFontSize — UI font size settings
func (c NSFontClass) SystemFontSize() float64 {
	return objc.Send[float64](objc.ID(c.Class), selSystemFontSize)
}

// AdvancementForCGGlyph calls -[NSFont advancementForCGGlyph:].
func (o NSFont) AdvancementForCGGlyph(glyph uint16) CGSize {
	return objc.Send[CGSize](o.ID, selAdvancementForCGGlyph, glyph)
}

// AdvancementForGlyph calls -[NSFont advancementForGlyph:].
func (o NSFont) AdvancementForGlyph(glyph uint32) CGSize {
	return objc.Send[CGSize](o.ID, selAdvancementForGlyph, glyph)
}

// BoundingRectForCGGlyph — Glyph metrics ********
func (o NSFont) BoundingRectForCGGlyph(glyph uint16) CGRect {
	return objc.Send[CGRect](o.ID, selBoundingRectForCGGlyph, glyph)
}

// BoundingRectForGlyph calls -[NSFont boundingRectForGlyph:].
func (o NSFont) BoundingRectForGlyph(glyph uint32) CGRect {
	return objc.Send[CGRect](o.ID, selBoundingRectForGlyph, glyph)
}

// FontWithSize calls -[NSFont fontWithSize:].
func (o NSFont) FontWithSize(fontSize float64) NSFont {
	return NSFont{o.ID.Send(selFontWithSize, fontSize)}
}

// GlyphWithName calls -[NSFont glyphWithName:].
func (o NSFont) GlyphWithName(name string) uint32 {
	return objc.Send[uint32](o.ID, selGlyphWithName, objcrt.NSString(name))
}

// Set — NSGraphicsContext-related ********
func (o NSFont) Set() {
	o.ID.Send(selSet)
}

// BoldSystemFontOfSize calls +[NSFont boldSystemFontOfSize:].
func (c NSFontClass) BoldSystemFontOfSize(fontSize float64) NSFont {
	return NSFont{objc.ID(c.Class).Send(selBoldSystemFontOfSize, fontSize)}
}

// ControlContentFontOfSize calls +[NSFont controlContentFontOfSize:].
func (c NSFontClass) ControlContentFontOfSize(fontSize float64) NSFont {
	return NSFont{objc.ID(c.Class).Send(selControlContentFontOfSize, fontSize)}
}

// FontWithNameSize — Factory ********
func (c NSFontClass) FontWithNameSize(fontName string, fontSize float64) NSFont {
	return NSFont{objc.ID(c.Class).Send(selFontWithNameSize, objcrt.NSString(fontName), fontSize)}
}

// LabelFontOfSize calls +[NSFont labelFontOfSize:].
func (c NSFontClass) LabelFontOfSize(fontSize float64) NSFont {
	return NSFont{objc.ID(c.Class).Send(selLabelFontOfSize, fontSize)}
}

// MenuBarFontOfSize calls +[NSFont menuBarFontOfSize:].
func (c NSFontClass) MenuBarFontOfSize(fontSize float64) NSFont {
	return NSFont{objc.ID(c.Class).Send(selMenuBarFontOfSize, fontSize)}
}

// MenuFontOfSize calls +[NSFont menuFontOfSize:].
func (c NSFontClass) MenuFontOfSize(fontSize float64) NSFont {
	return NSFont{objc.ID(c.Class).Send(selMenuFontOfSize, fontSize)}
}

// MessageFontOfSize calls +[NSFont messageFontOfSize:].
func (c NSFontClass) MessageFontOfSize(fontSize float64) NSFont {
	return NSFont{objc.ID(c.Class).Send(selMessageFontOfSize, fontSize)}
}

// MonospacedDigitSystemFontOfSizeWeight calls +[NSFont monospacedDigitSystemFontOfSize:weight:].
func (c NSFontClass) MonospacedDigitSystemFontOfSizeWeight(fontSize float64, weight float64) NSFont {
	return NSFont{objc.ID(c.Class).Send(selMonospacedDigitSystemFontOfSizeWeight, fontSize, weight)}
}

// MonospacedSystemFontOfSizeWeight — Returns current default monospaced font for system UI. Clients of this API should be aware that the monospaced system font has a similar coverage of default system UI font, which includes Latin and common symbols used for displaying text like source code. For the characters it does not cover, the subtituted fonts are usually not the same width as the monospaced system font, they can be wider, narrower, or variable. To ensure fixed advances in text layout, clients can consider using string attributes like NSFontFixedAdvanceAttribute.
func (c NSFontClass) MonospacedSystemFontOfSizeWeight(fontSize float64, weight float64) NSFont {
	return NSFont{objc.ID(c.Class).Send(selMonospacedSystemFontOfSizeWeight, fontSize, weight)}
}

// PaletteFontOfSize calls +[NSFont paletteFontOfSize:].
func (c NSFontClass) PaletteFontOfSize(fontSize float64) NSFont {
	return NSFont{objc.ID(c.Class).Send(selPaletteFontOfSize, fontSize)}
}

// PreferredFontForTextStyleOptions calls +[NSFont preferredFontForTextStyle:options:].
func (c NSFontClass) PreferredFontForTextStyleOptions(style string, options NSDictionary) NSFont {
	return NSFont{objc.ID(c.Class).Send(selPreferredFontForTextStyleOptions, objcrt.NSString(style), options.ID)}
}

// SetUserFixedPitchFont calls +[NSFont setUserFixedPitchFont:].
func (c NSFontClass) SetUserFixedPitchFont(font NSFont) {
	objc.ID(c.Class).Send(selSetUserFixedPitchFont, font.ID)
}

// SetUserFont calls +[NSFont setUserFont:].
func (c NSFontClass) SetUserFont(font NSFont) {
	objc.ID(c.Class).Send(selSetUserFont, font.ID)
}

// SystemFontOfSize — UI font settings
func (c NSFontClass) SystemFontOfSize(fontSize float64) NSFont {
	return NSFont{objc.ID(c.Class).Send(selSystemFontOfSize, fontSize)}
}

// SystemFontOfSizeWeight — Following two factory methods return system font with NSFontWeightTrait. Returns the system font object corresponding to fontSize and weight. +monospacedDigitSystemFontOfSize:weight: always return a system font instance with monospaced digit glyphs. It's recommended to use the symbolic weight values declared in NSFontDescriptor.h. Due to sophisticated system font weight matching logic underneath, it's recommended to use this factory method all the time when getting non-standard weight system fonts instead of transforming existing instances via methods like -[NSFontManager convertFont:toSize]. When asked for a missing weight for the running version of OS X, this method returns the nearest heavier weight available if the application is linked against the current or older SDK; otherwise, it returns the nearest lighter weight available.
func (c NSFontClass) SystemFontOfSizeWeight(fontSize float64, weight float64) NSFont {
	return NSFont{objc.ID(c.Class).Send(selSystemFontOfSizeWeight, fontSize, weight)}
}

// SystemFontOfSizeWeightWidth — Returns an instance with the specified weight and width. Width values are declared in NSFontDescriptor.h.
func (c NSFontClass) SystemFontOfSizeWeightWidth(fontSize float64, weight float64, width float64) NSFont {
	return NSFont{objc.ID(c.Class).Send(selSystemFontOfSizeWeightWidth, fontSize, weight, width)}
}

// TitleBarFontOfSize calls +[NSFont titleBarFontOfSize:].
func (c NSFontClass) TitleBarFontOfSize(fontSize float64) NSFont {
	return NSFont{objc.ID(c.Class).Send(selTitleBarFontOfSize, fontSize)}
}

// ToolTipsFontOfSize calls +[NSFont toolTipsFontOfSize:].
func (c NSFontClass) ToolTipsFontOfSize(fontSize float64) NSFont {
	return NSFont{objc.ID(c.Class).Send(selToolTipsFontOfSize, fontSize)}
}

// UserFixedPitchFontOfSize calls +[NSFont userFixedPitchFontOfSize:].
func (c NSFontClass) UserFixedPitchFontOfSize(fontSize float64) NSFont {
	return NSFont{objc.ID(c.Class).Send(selUserFixedPitchFontOfSize, fontSize)}
}

// UserFontOfSize — User font settings
func (c NSFontClass) UserFontOfSize(fontSize float64) NSFont {
	return NSFont{objc.ID(c.Class).Send(selUserFontOfSize, fontSize)}
}
