// Code generated by tools/bindgen. DO NOT EDIT.
//
// Source: MacOSX26.2.sdk (Xcode 26.2), target arm64-apple-macos26.0
// Frameworks: Foundation, AppKit
//
// Regenerate with: tools/bindgen/regen.sh

//go:build darwin

package appkit

import (
	"github.com/adriaanm/wata/go-pkgs/appleptt/objcrt"
	"github.com/ebitengine/purego/objc"
)

// NSImage — NSIMAGE_UNAVAILABLE_MACCATALYST
type NSImage struct{ objc.ID }

// NSImageClass is the class object of NSImage.
type NSImageClass struct{ objc.Class }

// GetNSImageClass looks the class up in the ObjC runtime.
func GetNSImageClass() NSImageClass { return NSImageClass{objc.GetClass("NSImage")} }

// Alloc allocates an uninitialized NSImage (-[NSObject alloc]).
func (c NSImageClass) Alloc() NSImage { return NSImage{objc.ID(c.Class).Send(selAlloc)} }

// TIFFRepresentation reads the NSImage property TIFFRepresentation.
func (o NSImage) TIFFRepresentation() NSData {
	return NSData{o.ID.Send(selTIFFRepresentation)}
}

// AccessibilityDescription reads the NSImage property accessibilityDescription.
func (o NSImage) AccessibilityDescription() string {
	return objcrt.GoString(o.ID.Send(selAccessibilityDescription))
}

// SetAccessibilityDescription writes the NSImage property accessibilityDescription.
func (o NSImage) SetAccessibilityDescription(v string) {
	o.ID.Send(selSetAccessibilityDescription, objcrt.NSString(v))
}

// AlignmentRect reads the NSImage property alignmentRect.
func (o NSImage) AlignmentRect() CGRect {
	return objc.Send[CGRect](o.ID, selAlignmentRect)
}

// SetAlignmentRect writes the NSImage property alignmentRect.
func (o NSImage) SetAlignmentRect(v CGRect) {
	o.ID.Send(selSetAlignmentRect, v)
}

// BackgroundColor reads the NSImage property backgroundColor.
func (o NSImage) BackgroundColor() NSColor {
	return NSColor{o.ID.Send(selBackgroundColor)}
}

// SetBackgroundColor writes the NSImage property backgroundColor.
func (o NSImage) SetBackgroundColor(v NSColor) {
	o.ID.Send(selSetBackgroundColor, v.ID)
}

// Delegate reads the NSImage property delegate.
func (o NSImage) Delegate() objc.ID {
	return o.ID.Send(selDelegate)
}

// SetDelegate writes the NSImage property delegate.
func (o NSImage) SetDelegate(v objc.ID) {
	o.ID.Send(selSetDelegate, v)
}

// MatchesOnMultipleResolution reads the NSImage property matchesOnMultipleResolution.
func (o NSImage) MatchesOnMultipleResolution() bool {
	return objc.Send[bool](o.ID, selMatchesOnMultipleResolution)
}

// SetMatchesOnMultipleResolution writes the NSImage property matchesOnMultipleResolution.
func (o NSImage) SetMatchesOnMultipleResolution(v bool) {
	o.ID.Send(selSetMatchesOnMultipleResolution, v)
}

// MatchesOnlyOnBestFittingAxis reads the NSImage property matchesOnlyOnBestFittingAxis.
func (o NSImage) MatchesOnlyOnBestFittingAxis() bool {
	return objc.Send[bool](o.ID, selMatchesOnlyOnBestFittingAxis)
}

// SetMatchesOnlyOnBestFittingAxis writes the NSImage property matchesOnlyOnBestFittingAxis.
func (o NSImage) SetMatchesOnlyOnBestFittingAxis(v bool) {
	o.ID.Send(selSetMatchesOnlyOnBestFittingAxis, v)
}

// PrefersColorMatch reads the NSImage property prefersColorMatch.
func (o NSImage) PrefersColorMatch() bool {
	return objc.Send[bool](o.ID, selPrefersColorMatch)
}

// SetPrefersColorMatch writes the NSImage property prefersColorMatch.
func (o NSImage) SetPrefersColorMatch(v bool) {
	o.ID.Send(selSetPrefersColorMatch, v)
}

// Representations reads the NSImage property representations.
func (o NSImage) Representations() NSArray {
	return NSArray{o.ID.Send(selRepresentations)}
}

// Size reads the NSImage property size.
func (o NSImage) Size() CGSize {
	return objc.Send[CGSize](o.ID, selSize)
}

// SetSize writes the NSImage property size.
func (o NSImage) SetSize(v CGSize) {
	o.ID.Send(selSetSize, v)
}

// Template reads the NSImage property template.
func (o NSImage) Template() bool {
	return objc.Send[bool](o.ID, selIsTemplate)
}

// SetTemplate writes the NSImage property template.
func (o NSImage) SetTemplate(v bool) {
	o.ID.Send(selSetTemplate, v)
}

// UsesEPSOnResolutionMismatch reads the NSImage property usesEPSOnResolutionMismatch.
func (o NSImage) UsesEPSOnResolutionMismatch() bool {
	return objc.Send[bool](o.ID, selUsesEPSOnResolutionMismatch)
}

// SetUsesEPSOnResolutionMismatch writes the NSImage property usesEPSOnResolutionMismatch.
func (o NSImage) SetUsesEPSOnResolutionMismatch(v bool) {
	o.ID.Send(selSetUsesEPSOnResolutionMismatch, v)
}

// Valid reads the NSImage property valid.
func (o NSImage) Valid() bool {
	return objc.Send[bool](o.ID, selIsValid)
}

// ImageTypes reads the NSImage class property imageTypes.
func (c NSImageClass) ImageTypes() NSArray {
	return NSArray{objc.ID(c.Class).Send(selImageTypes)}
}

// ImageUnfilteredTypes reads the NSImage class property imageUnfilteredTypes.
func (c NSImageClass) ImageUnfilteredTypes() NSArray {
	return NSArray{objc.ID(c.Class).Send(selImageUnfilteredTypes)}
}

// AddRepresentations calls -[NSImage addRepresentations:].
func (o NSImage) AddRepresentations(imageReps NSArray) {
	o.ID.Send(selAddRepresentations, imageReps.ID)
}

// CacheDepthMatchesImageDepth calls -[NSImage cacheDepthMatchesImageDepth].
func (o NSImage) CacheDepthMatchesImageDepth() bool {
	return objc.Send[bool](o.ID, selCacheDepthMatchesImageDepth)
}

// CancelIncrementalLoad calls -[NSImage cancelIncrementalLoad].
func (o NSImage) CancelIncrementalLoad() {
	o.ID.Send(selCancelIncrementalLoad)
}

// DissolveToPointFraction calls -[NSImage dissolveToPoint:fraction:].
func (o NSImage) DissolveToPointFraction(point CGPoint, fraction float64) {
	o.ID.Send(selDissolveToPointFraction, point, fraction)
}

// DissolveToPointFromRectFraction calls -[NSImage dissolveToPoint:fromRect:fraction:].
func (o NSImage) DissolveToPointFromRectFraction(point CGPoint, rect CGRect, fraction float64) {
	o.ID.Send(selDissolveToPointFromRectFraction, point, rect, fraction)
}

// DrawInRect calls -[NSImage drawInRect:].
func (o NSImage) DrawInRect(rect CGRect) {
	o.ID.Send(selDrawInRect, rect)
}

// InitByReferencingFile calls -[NSImage initByReferencingFile:].
func (o NSImage) InitByReferencingFile(fileName string) NSImage {
	return NSImage{o.ID.Send(selInitByReferencingFile, objcrt.NSString(fileName))}
}

// InitWithContentsOfFile calls -[NSImage initWithContentsOfFile:].
func (o NSImage) InitWithContentsOfFile(fileName string) NSImage {
	return NSImage{o.ID.Send(selInitWithContentsOfFile, objcrt.NSString(fileName))}
}

// InitWithData calls -[NSImage initWithData:].
func (o NSImage) InitWithData(data NSData) NSImage {
	return NSImage{o.ID.Send(selInitWithData, data.ID)}
}

// InitWithDataIgnoringOrientation calls -[NSImage initWithDataIgnoringOrientation:].
func (o NSImage) InitWithDataIgnoringOrientation(data NSData) NSImage {
	return NSImage{o.ID.Send(selInitWithDataIgnoringOrientation, data.ID)}
}

// InitWithSize calls -[NSImage initWithSize:].
func (o NSImage) InitWithSize(size CGSize) NSImage {
	return NSImage{o.ID.Send(selInitWithSize, size)}
}

// IsCachedSeparately calls -[NSImage isCachedSeparately].
func (o NSImage) IsCachedSeparately() bool {
	return objc.Send[bool](o.ID, selIsCachedSeparately)
}

// IsDataRetained calls -[NSImage isDataRetained].
func (o NSImage) IsDataRetained() bool {
	return objc.Send[bool](o.ID, selIsDataRetained)
}

// IsFlipped calls -[NSImage isFlipped].
func (o NSImage) IsFlipped() bool {
	return objc.Send[bool](o.ID, selIsFlipped)
}

// LayerContentsForContentsScale calls -[NSImage layerContentsForContentsScale:].
func (o NSImage) LayerContentsForContentsScale(layerContentsScale float64) objc.ID {
	return o.ID.Send(selLayerContentsForContentsScale, layerContentsScale)
}

// LockFocus calls -[NSImage lockFocus].
func (o NSImage) LockFocus() {
	o.ID.Send(selLockFocus)
}

// LockFocusFlipped calls -[NSImage lockFocusFlipped:].
func (o NSImage) LockFocusFlipped(flipped bool) {
	o.ID.Send(selLockFocusFlipped, flipped)
}

// Name calls -[NSImage name].
func (o NSImage) Name() string {
	return objcrt.GoString(o.ID.Send(selName))
}

// Recache calls -[NSImage recache].
func (o NSImage) Recache() {
	o.ID.Send(selRecache)
}

// RecommendedLayerContentsScale calls -[NSImage recommendedLayerContentsScale:].
func (o NSImage) RecommendedLayerContentsScale(preferredContentsScale float64) float64 {
	return objc.Send[float64](o.ID, selRecommendedLayerContentsScale, preferredContentsScale)
}

// ScalesWhenResized calls -[NSImage scalesWhenResized].
func (o NSImage) ScalesWhenResized() bool {
	return objc.Send[bool](o.ID, selScalesWhenResized)
}

// SetCacheDepthMatchesImageDepth calls -[NSImage setCacheDepthMatchesImageDepth:].
func (o NSImage) SetCacheDepthMatchesImageDepth(flag bool) {
	o.ID.Send(selSetCacheDepthMatchesImageDepth, flag)
}

// SetCachedSeparately calls -[NSImage setCachedSeparately:].
func (o NSImage) SetCachedSeparately(flag bool) {
	o.ID.Send(selSetCachedSeparately, flag)
}

// SetDataRetained calls -[NSImage setDataRetained:].
func (o NSImage) SetDataRetained(flag bool) {
	o.ID.Send(selSetDataRetained, flag)
}

// SetFlipped calls -[NSImage setFlipped:].
func (o NSImage) SetFlipped(flag bool) {
	o.ID.Send(selSetFlipped, flag)
}

// SetName calls -[NSImage setName:].
func (o NSImage) SetName(string_ string) bool {
	return objc.Send[bool](o.ID, selSetName, objcrt.NSString(string_))
}

// SetScalesWhenResized calls -[NSImage setScalesWhenResized:].
func (o NSImage) SetScalesWhenResized(flag bool) {
	o.ID.Send(selSetScalesWhenResized, flag)
}

// UnlockFocus calls -[NSImage unlockFocus].
func (o NSImage) UnlockFocus() {
	o.ID.Send(selUnlockFocus)
}

// ImageFileTypes calls +[NSImage imageFileTypes].
func (c NSImageClass) ImageFileTypes() NSArray {
	return NSArray{objc.ID(c.Class).Send(selImageFileTypes)}
}

// ImageNamed — NSIMAGE_UNAVAILABLE_MACCATALYST
func (c NSImageClass) ImageNamed(name string) NSImage {
	return NSImage{objc.ID(c.Class).Send(selImageNamed, objcrt.NSString(name))}
}

// ImagePasteboardTypes calls +[NSImage imagePasteboardTypes].
func (c NSImageClass) ImagePasteboardTypes() NSArray {
	return NSArray{objc.ID(c.Class).Send(selImagePasteboardTypes)}
}

// ImageUnfilteredFileTypes calls +[NSImage imageUnfilteredFileTypes].
func (c NSImageClass) ImageUnfilteredFileTypes() NSArray {
	return NSArray{objc.ID(c.Class).Send(selImageUnfilteredFileTypes)}
}

// ImageUnfilteredPasteboardTypes calls +[NSImage imageUnfilteredPasteboardTypes].
func (c NSImageClass) ImageUnfilteredPasteboardTypes() NSArray {
	return NSArray{objc.ID(c.Class).Send(selImageUnfilteredPasteboardTypes)}
}

// ImageWithSymbolNameVariableValue calls +[NSImage imageWithSymbolName:variableValue:].
func (c NSImageClass) ImageWithSymbolNameVariableValue(name string, value float64) NSImage {
	return NSImage{objc.ID(c.Class).Send(selImageWithSymbolNameVariableValue, objcrt.NSString(name), value)}
}

// ImageWithSystemSymbolNameAccessibilityDescription calls +[NSImage imageWithSystemSymbolName:accessibilityDescription:].
func (c NSImageClass) ImageWithSystemSymbolNameAccessibilityDescription(name string, description string) NSImage {
	return NSImage{objc.ID(c.Class).Send(selImageWithSystemSymbolNameAccessibilityDescription, objcrt.NSString(name), objcrt.NSString(description))}
}

// ImageWithSystemSymbolNameVariableValueAccessibilityDescription calls +[NSImage imageWithSystemSymbolName:variableValue:accessibilityDescription:].
func (c NSImageClass) ImageWithSystemSymbolNameVariableValueAccessibilityDescription(name string, value float64, description string) NSImage {
	return NSImage{objc.ID(c.Class).Send(selImageWithSystemSymbolNameVariableValueAccessibilityDescription, objcrt.NSString(name), value, objcrt.NSString(description))}
}
