// Code generated by tools/bindgen. DO NOT EDIT.
//
// Source: MacOSX26.2.sdk (Xcode 26.2), target arm64-apple-macos26.0
// Frameworks: Foundation, AppKit
//
// Regenerate with: tools/bindgen/regen.sh

//go:build darwin

package appkit

import (
	"github.com/adriaanm/wata/go-pkgs/appleptt/objcrt"
	"github.com/ebitengine/purego/objc"
)

// NSImageRep wraps the ObjC class NSImageRep (NSObject subclass).
type NSImageRep struct{ objc.ID }

// NSImageRepClass is the class object of NSImageRep.
type NSImageRepClass struct{ objc.Class }

// GetNSImageRepClass looks the class up in the ObjC runtime.
func GetNSImageRepClass() NSImageRepClass { return NSImageRepClass{objc.GetClass("NSImageRep")} }

// Alloc allocates an uninitialized NSImageRep (-[NSObject alloc]).
func (c NSImageRepClass) Alloc() NSImageRep { return NSImageRep{objc.ID(c.Class).Send(selAlloc)} }

// Alpha reads the NSImageRep property alpha.
func (o NSImageRep) Alpha() bool {
	return objc.Send[bool](o.ID, selHasAlpha)
}

// SetAlpha writes the NSImageRep property alpha.
func (o NSImageRep) SetAlpha(v bool) {
	o.ID.Send(selSetAlpha, v)
}

// BitsPerSample reads the NSImageRep property bitsPerSample.
func (o NSImageRep) BitsPerSample() int {
	return objc.Send[int](o.ID, selBitsPerSample)
}

// SetBitsPerSample writes the NSImageRep property bitsPerSample.
func (o NSImageRep) SetBitsPerSample(v int) {
	o.ID.Send(selSetBitsPerSample, v)
}

// ColorSpaceName reads the NSImageRep property colorSpaceName.
func (o NSImageRep) ColorSpaceName() string {
	return objcrt.GoString(o.ID.Send(selColorSpaceName))
}

// SetColorSpaceName writes the NSImageRep property colorSpaceName.
func (o NSImageRep) SetColorSpaceName(v string) {
	o.ID.Send(selSetColorSpaceName, objcrt.NSString(v))
}

// Opaque reads the NSImageRep property opaque.
func (o NSImageRep) Opaque() bool {
	return objc.Send[bool](o.ID, selIsOpaque)
}

// SetOpaque writes the NSImageRep property opaque.
func (o NSImageRep) SetOpaque(v bool) {
	o.ID.Send(selSetOpaque, v)
}

// PixelsHigh reads the NSImageRep property pixelsHigh.
func (o NSImageRep) PixelsHigh() int {
	return objc.Send[int](o.ID, selPixelsHigh)
}

// SetPixelsHigh writes the NSImageRep property pixelsHigh.
func (o NSImageRep) SetPixelsHigh(v int) {
	o.ID.Send(selSetPixelsHigh, v)
}

// PixelsWide reads the NSImageRep property pixelsWide.
func (o NSImageRep) PixelsWide() int {
	return objc.Send[int](o.ID, selPixelsWide)
}

// SetPixelsWide writes the NSImageRep property pixelsWide.
func (o NSImageRep) SetPixelsWide(v int) {
	o.ID.Send(selSetPixelsWide, v)
}

// Size — Methods to return info about the image. NSImageRep provides storage for all of these; however, it's illegal to set them in some subclasses.
func (o NSImageRep) Size() CGSize {
	return objc.Send[CGSize](o.ID, selSize)
}

// SetSize writes the NSImageRep property size.
func (o NSImageRep) SetSize(v CGSize) {
	o.ID.Send(selSetSize, v)
}

// ImageTypes — This expands the unfiltered list returned by imageUnfilteredTypes.
func (c NSImageRepClass) ImageTypes() NSArray {
	return NSArray{objc.ID(c.Class).Send(selImageTypes)}
}

// ImageUnfilteredTypes — Implemented by subclassers to indicate what UTI-identified data types they can deal with.
func (c NSImageRepClass) ImageUnfilteredTypes() NSArray {
	return NSArray{objc.ID(c.Class).Send(selImageUnfilteredTypes)}
}

// RegisteredImageRepClasses reads the NSImageRep class property registeredImageRepClasses.
func (c NSImageRepClass) RegisteredImageRepClasses() NSArray {
	return NSArray{objc.ID(c.Class).Send(selRegisteredImageRepClasses)}
}

// Draw — Drawing methods. draw is the only primitive.
func (o NSImageRep) Draw() bool {
	return objc.Send[bool](o.ID, selDraw)
}

// DrawAtPoint calls -[NSImageRep drawAtPoint:].
func (o NSImageRep) DrawAtPoint(point CGPoint) bool {
	return objc.Send[bool](o.ID, selDrawAtPoint, point)
}

// DrawInRect calls -[NSImageRep drawInRect:].
func (o NSImageRep) DrawInRect(rect CGRect) bool {
	return objc.Send[bool](o.ID, selDrawInRect, rect)
}

// Init calls -[NSImageRep init].
func (o NSImageRep) Init() NSImageRep {
	return NSImageRep{o.ID.Send(selInit)}
}

// CanInitWithData — Should be overridden by subclassers to load an unfiltered image.
func (c NSImageRepClass) CanInitWithData(data NSData) bool {
	return objc.Send[bool](objc.ID(c.Class), selCanInitWithData, data.ID)
}

// ImageFileTypes — These expand the unfiltered lists returned by imageUnfilteredFileTypes and imageUnfilteredPasteboardTypes.
func (c NSImageRepClass) ImageFileTypes() NSArray {
	return NSArray{objc.ID(c.Class).Send(selImageFileTypes)}
}

// ImagePasteboardTypes calls +[NSImageRep imagePasteboardTypes].
func (c NSImageRepClass) ImagePasteboardTypes() NSArray {
	return NSArray{objc.ID(c.Class).Send(selImagePasteboardTypes)}
}

// ImageRepClassForData calls +[NSImageRep imageRepClassForData:].
func (c NSImageRepClass) ImageRepClassForData(data NSData) objc.Class {
	return objc.Send[objc.Class](objc.ID(c.Class), selImageRepClassForData, data.ID)
}

// ImageRepClassForFileType calls +[NSImageRep imageRepClassForFileType:].
func (c NSImageRepClass) ImageRepClassForFileType(type_ string) objc.Class {
	return objc.Send[objc.Class](objc.ID(c.Class), selImageRepClassForFileType, objcrt.NSString(type_))
}

// ImageRepClassForPasteboardType calls +[NSImageRep imageRepClassForPasteboardType:].
func (c NSImageRepClass) ImageRepClassForPasteboardType(type_ string) objc.Class {
	return objc.Send[objc.Class](objc.ID(c.Class), selImageRepClassForPasteboardType, objcrt.NSString(type_))
}

// ImageRepClassForType calls +[NSImageRep imageRepClassForType:].
func (c NSImageRepClass) ImageRepClassForType(type_ string) objc.Class {
	return objc.Send[objc.Class](objc.ID(c.Class), selImageRepClassForType, objcrt.NSString(type_))
}

// ImageRepWithContentsOfFile calls +[NSImageRep imageRepWithContentsOfFile:].
func (c NSImageRepClass) ImageRepWithContentsOfFile(filename string) NSImageRep {
	return NSImageRep{objc.ID(c.Class).Send(selImageRepWithContentsOfFile, objcrt.NSString(filename))}
}

// ImageRepsWithContentsOfFile — Convenience methods: Checks to see if the provided file or pasteboard types can be understood by a registered imagerep class after filtering; if so, calls imageRepsWithData: or imageRepWithData:. If sent to a subclass, does this just for the types understood by that subclass.
func (c NSImageRepClass) ImageRepsWithContentsOfFile(filename string) NSArray {
	return NSArray{objc.ID(c.Class).Send(selImageRepsWithContentsOfFile, objcrt.NSString(filename))}
}

// ImageUnfilteredFileTypes — Implemented by subclassers to indicate what data types they can deal with.
func (c NSImageRepClass) ImageUnfilteredFileTypes() NSArray {
	return NSArray{objc.ID(c.Class).Send(selImageUnfilteredFileTypes)}
}

// ImageUnfilteredPasteboardTypes calls +[NSImageRep imageUnfilteredPasteboardTypes].
func (c NSImageRepClass) ImageUnfilteredPasteboardTypes() NSArray {
	return NSArray{objc.ID(c.Class).Send(selImageUnfilteredPasteboardTypes)}
}

// RegisterImageRepClass — Registry management: Subclasses which deal with file & pasteboard types should register themselves. These classes should also implement imageUnfilteredFileTypes, imageUnfilteredPasteboardTypes, initWithData:, canInitWithData:, imageRepWithData:, and, if they have the ability to read multiple images from a file, imageRepsWithData:. These last three should not do any filtering; all filtering is automatic.
func (c NSImageRepClass) RegisterImageRepClass(imageRepClass objc.Class) {
	objc.ID(c.Class).Send(selRegisterImageRepClass, imageRepClass)
}

// UnregisterImageRepClass calls +[NSImageRep unregisterImageRepClass:].
func (c NSImageRepClass) UnregisterImageRepClass(imageRepClass objc.Class) {
	objc.ID(c.Class).Send(selUnregisterImageRepClass, imageRepClass)
}
