// Code generated by tools/bindgen. DO NOT EDIT.
//
// Source: MacOSX26.2.sdk (Xcode 26.2), target arm64-apple-macos26.0
// Frameworks: Foundation, AppKit
//
// Regenerate with: tools/bindgen/regen.sh

//go:build darwin

package appkit

import "github.com/ebitengine/purego/objc"

// NSImageView wraps the ObjC class NSImageView (NSControl subclass).
type NSImageView struct{ objc.ID }

// NSImageViewClass is the class object of NSImageView.
type NSImageViewClass struct{ objc.Class }

// GetNSImageViewClass looks the class up in the ObjC runtime.
func GetNSImageViewClass() NSImageViewClass { return NSImageViewClass{objc.GetClass("NSImageView")} }

// Alloc allocates an uninitialized NSImageView (-[NSObject alloc]).
func (c NSImageViewClass) Alloc() NSImageView { return NSImageView{objc.ID(c.Class).Send(selAlloc)} }

// AllowsCutCopyPaste reads the NSImageView property allowsCutCopyPaste.
func (o NSImageView) AllowsCutCopyPaste() bool {
	return objc.Send[bool](o.ID, selAllowsCutCopyPaste)
}

// SetAllowsCutCopyPaste writes the NSImageView property allowsCutCopyPaste.
func (o NSImageView) SetAllowsCutCopyPaste(v bool) {
	o.ID.Send(selSetAllowsCutCopyPaste, v)
}

// Animates reads the NSImageView property animates.
func (o NSImageView) Animates() bool {
	return objc.Send[bool](o.ID, selAnimates)
}

// SetAnimates writes the NSImageView property animates.
func (o NSImageView) SetAnimates(v bool) {
	o.ID.Send(selSetAnimates, v)
}

// ContentTintColor — !
// A tint color to be used when rendering template image content. This color may be combined with other effects to produce a theme-appropriate rendition of the template image. A nil value indicates the standard set of effects without color modification. The default value is nil.
func (o NSImageView) ContentTintColor() NSColor {
	return NSColor{o.ID.Send(selContentTintColor)}
}

// SetContentTintColor writes the NSImageView property contentTintColor.
func (o NSImageView) SetContentTintColor(v NSColor) {
	o.ID.Send(selSetContentTintColor, v.ID)
}

// Editable reads the NSImageView property editable.
func (o NSImageView) Editable() bool {
	return objc.Send[bool](o.ID, selIsEditable)
}

// SetEditable writes the NSImageView property editable.
func (o NSImageView) SetEditable(v bool) {
	o.ID.Send(selSetEditable, v)
}

// Image reads the NSImageView property image.
func (o NSImageView) Image() NSImage {
	return NSImage{o.ID.Send(selImage)}
}

// SetImage writes the NSImageView property image.
func (o NSImageView) SetImage(v NSImage) {
	o.ID.Send(selSetImage, v.ID)
}

// ImageScaling reads the NSImageView property imageScaling.
func (o NSImageView) ImageScaling() NSImageScaling {
	return NSImageScaling(objc.Send[uint](o.ID, selImageScaling))
}

// SetImageScaling writes the NSImageView property imageScaling.
func (o NSImageView) SetImageScaling(v NSImageScaling) {
	o.ID.Send(selSetImageScaling, uint(v))
}

// RemoveAllSymbolEffects — Removes all symbol effects from the image view with default options and animation.
func (o NSImageView) RemoveAllSymbolEffects() {
	o.ID.Send(selRemoveAllSymbolEffects)
}

// ImageViewWithImage — !
// Creates a non-editable image view containing the provided image. The image is scaled proportionally down to fit the view, and is centered within the view.
// @param image The image to display within the view.
// @return An initialized image view.
func (c NSImageViewClass) ImageViewWithImage(image NSImage) NSImageView {
	return NSImageView{objc.ID(c.Class).Send(selImageViewWithImage, image.ID)}
}
