// Code generated by tools/bindgen. DO NOT EDIT.
//
// Source: MacOSX26.2.sdk (Xcode 26.2), target arm64-apple-macos26.0
// Frameworks: Foundation, AppKit
//
// Regenerate with: tools/bindgen/regen.sh

//go:build darwin

package appkit

import "github.com/ebitengine/purego/objc"

// NSNotification — Notifications	***************
// Only the identity crosses: no method of NSNotification is on the allowlist.
type NSNotification struct{ objc.ID }

// NSNotificationClass is the class object of NSNotification.
type NSNotificationClass struct{ objc.Class }

// GetNSNotificationClass looks the class up in the ObjC runtime.
func GetNSNotificationClass() NSNotificationClass {
	return NSNotificationClass{objc.GetClass("NSNotification")}
}
