// Code generated by tools/bindgen. DO NOT EDIT.
//
// Source: MacOSX26.2.sdk (Xcode 26.2), target arm64-apple-macos26.0
// Frameworks: Foundation, AppKit
//
// Regenerate with: tools/bindgen/regen.sh

//go:build darwin

package appkit

import (
	"github.com/adriaanm/wata/go-pkgs/appleptt/objcrt"
	"github.com/ebitengine/purego/objc"
)

// NSPopUpButton wraps the ObjC class NSPopUpButton (NSButton subclass).
type NSPopUpButton struct{ objc.ID }

// NSPopUpButtonClass is the class object of NSPopUpButton.
type NSPopUpButtonClass struct{ objc.Class }

// GetNSPopUpButtonClass looks the class up in the ObjC runtime.
func GetNSPopUpButtonClass() NSPopUpButtonClass {
	return NSPopUpButtonClass{objc.GetClass("NSPopUpButton")}
}

// Alloc allocates an uninitialized NSPopUpButton (-[NSObject alloc]).
func (c NSPopUpButtonClass) Alloc() NSPopUpButton {
	return NSPopUpButton{objc.ID(c.Class).Send(selAlloc)}
}

// AltersStateOfSelectedItem — ! When the value of this property is `YES`, the selected menu item's `state` is set to `NSControlStateValueOn`. When the value of this property is `NO`, the menu item's `state` is not changed. When this property changes, the `state` of the currently selected item is updated appropriately. This property is ignored for pull-down buttons.
func (o NSPopUpButton) AltersStateOfSelectedItem() bool {
	return objc.Send[bool](o.ID, selAltersStateOfSelectedItem)
}

// SetAltersStateOfSelectedItem writes the NSPopUpButton property altersStateOfSelectedItem.
func (o NSPopUpButton) SetAltersStateOfSelectedItem(v bool) {
	o.ID.Send(selSetAltersStateOfSelectedItem, v)
}

// AutoenablesItems — ! When the value of this property is `YES`, the popup button automatically enables and disables its menu items according to the `NSMenuValidation` protocol prior to user interaction.
func (o NSPopUpButton) AutoenablesItems() bool {
	return objc.Send[bool](o.ID, selAutoenablesItems)
}

// SetAutoenablesItems writes the NSPopUpButton property autoenablesItems.
func (o NSPopUpButton) SetAutoenablesItems(v bool) {
	o.ID.Send(selSetAutoenablesItems, v)
}

// IndexOfSelectedItem reads the NSPopUpButton property indexOfSelectedItem.
func (o NSPopUpButton) IndexOfSelectedItem() int {
	return objc.Send[int](o.ID, selIndexOfSelectedItem)
}

// ItemArray reads the NSPopUpButton property itemArray.
func (o NSPopUpButton) ItemArray() NSArray {
	return NSArray{o.ID.Send(selItemArray)}
}

// ItemTitles reads the NSPopUpButton property itemTitles.
func (o NSPopUpButton) ItemTitles() NSArray {
	return NSArray{o.ID.Send(selItemTitles)}
}

// NumberOfItems reads the NSPopUpButton property numberOfItems.
func (o NSPopUpButton) NumberOfItems() int {
	return objc.Send[int](o.ID, selNumberOfItems)
}

// PullsDown — ! When the value of this property is `YES` the button adopts 'pull-down' behavior, displaying static button contents and presenting its menu at the edge of the button. When the value of this property is `NO` the button behaves as a popup, displaying the currently-selected menu item and presenting its menu above the button, positioning the selected menu item to match the button's contents.
func (o NSPopUpButton) PullsDown() bool {
	return objc.Send[bool](o.ID, selPullsDown)
}

// SetPullsDown writes the NSPopUpButton property pullsDown.
func (o NSPopUpButton) SetPullsDown(v bool) {
	o.ID.Send(selSetPullsDown, v)
}

// SelectedTag reads the NSPopUpButton property selectedTag.
func (o NSPopUpButton) SelectedTag() int {
	return objc.Send[int](o.ID, selSelectedTag)
}

// TitleOfSelectedItem reads the NSPopUpButton property titleOfSelectedItem.
func (o NSPopUpButton) TitleOfSelectedItem() string {
	return objcrt.GoString(o.ID.Send(selTitleOfSelectedItem))
}

// UsesItemFromMenu — ! When `usesItemFromMenu` is `YES`, a pull-down button uses the title of the first menu item and hides the first menu item. A pop-up button uses the title of the currently selected menu. The default value is `YES`.
func (o NSPopUpButton) UsesItemFromMenu() bool {
	return objc.Send[bool](o.ID, selUsesItemFromMenu)
}

// SetUsesItemFromMenu writes the NSPopUpButton property usesItemFromMenu.
func (o NSPopUpButton) SetUsesItemFromMenu(v bool) {
	o.ID.Send(selSetUsesItemFromMenu, v)
}

// AddItemWithTitle calls -[NSPopUpButton addItemWithTitle:].
func (o NSPopUpButton) AddItemWithTitle(title string) {
	o.ID.Send(selAddItemWithTitle, objcrt.NSString(title))
}

// AddItemsWithTitles calls -[NSPopUpButton addItemsWithTitles:].
func (o NSPopUpButton) AddItemsWithTitles(itemTitles NSArray) {
	o.ID.Send(selAddItemsWithTitles, itemTitles.ID)
}

// IndexOfItemWithRepresentedObject calls -[NSPopUpButton indexOfItemWithRepresentedObject:].
func (o NSPopUpButton) IndexOfItemWithRepresentedObject(obj objc.ID) int {
	return objc.Send[int](o.ID, selIndexOfItemWithRepresentedObject, obj)
}

// IndexOfItemWithTag calls -[NSPopUpButton indexOfItemWithTag:].
func (o NSPopUpButton) IndexOfItemWithTag(tag int) int {
	return objc.Send[int](o.ID, selIndexOfItemWithTag, tag)
}

// IndexOfItemWithTargetAndAction calls -[NSPopUpButton indexOfItemWithTarget:andAction:].
func (o NSPopUpButton) IndexOfItemWithTargetAndAction(target objc.ID, actionSelector objc.SEL) int {
	return objc.Send[int](o.ID, selIndexOfItemWithTargetAndAction, target, actionSelector)
}

// IndexOfItemWithTitle calls -[NSPopUpButton indexOfItemWithTitle:].
func (o NSPopUpButton) IndexOfItemWithTitle(title string) int {
	return objc.Send[int](o.ID, selIndexOfItemWithTitle, objcrt.NSString(title))
}

// InitWithFramePullsDown calls -[NSPopUpButton initWithFrame:pullsDown:].
func (o NSPopUpButton) InitWithFramePullsDown(buttonFrame CGRect, flag bool) NSPopUpButton {
	return NSPopUpButton{o.ID.Send(selInitWithFramePullsDown, buttonFrame, flag)}
}

// InsertItemWithTitleAtIndex calls -[NSPopUpButton insertItemWithTitle:atIndex:].
func (o NSPopUpButton) InsertItemWithTitleAtIndex(title string, index int) {
	o.ID.Send(selInsertItemWithTitleAtIndex, objcrt.NSString(title), index)
}

// ItemTitleAtIndex calls -[NSPopUpButton itemTitleAtIndex:].
func (o NSPopUpButton) ItemTitleAtIndex(index int) string {
	return objcrt.GoString(o.ID.Send(selItemTitleAtIndex, index))
}

// RemoveAllItems calls -[NSPopUpButton removeAllItems].
func (o NSPopUpButton) RemoveAllItems() {
	o.ID.Send(selRemoveAllItems)
}

// RemoveItemAtIndex calls -[NSPopUpButton removeItemAtIndex:].
func (o NSPopUpButton) RemoveItemAtIndex(index int) {
	o.ID.Send(selRemoveItemAtIndex, index)
}

// RemoveItemWithTitle calls -[NSPopUpButton removeItemWithTitle:].
func (o NSPopUpButton) RemoveItemWithTitle(title string) {
	o.ID.Send(selRemoveItemWithTitle, objcrt.NSString(title))
}

// SelectItemAtIndex calls -[NSPopUpButton selectItemAtIndex:].
func (o NSPopUpButton) SelectItemAtIndex(index int) {
	o.ID.Send(selSelectItemAtIndex, index)
}

// SelectItemWithTag calls -[NSPopUpButton selectItemWithTag:].
func (o NSPopUpButton) SelectItemWithTag(tag int) bool {
	return objc.Send[bool](o.ID, selSelectItemWithTag, tag)
}

// SelectItemWithTitle calls -[NSPopUpButton selectItemWithTitle:].
func (o NSPopUpButton) SelectItemWithTitle(title string) {
	o.ID.Send(selSelectItemWithTitle, objcrt.NSString(title))
}

// SetTitle calls -[NSPopUpButton setTitle:].
func (o NSPopUpButton) SetTitle(string_ string) {
	o.ID.Send(selSetTitle, objcrt.NSString(string_))
}

// SynchronizeTitleAndSelectedItem calls -[NSPopUpButton synchronizeTitleAndSelectedItem].
func (o NSPopUpButton) SynchronizeTitleAndSelectedItem() {
	o.ID.Send(selSynchronizeTitleAndSelectedItem)
}
