// Code generated by tools/bindgen. DO NOT EDIT.
//
// Source: MacOSX26.2.sdk (Xcode 26.2), target arm64-apple-macos26.0
// Frameworks: Foundation, AppKit
//
// Regenerate with: tools/bindgen/regen.sh

//go:build darwin

package appkit

import "github.com/ebitengine/purego/objc"

// NSScreen an opaque handle for the ObjC class NSScreen (NSObject subclass).
// Only the identity crosses: no method of NSScreen is on the allowlist.
type NSScreen struct{ objc.ID }

// NSScreenClass is the class object of NSScreen.
type NSScreenClass struct{ objc.Class }

// GetNSScreenClass looks the class up in the ObjC runtime.
func GetNSScreenClass() NSScreenClass { return NSScreenClass{objc.GetClass("NSScreen")} }
