// Code generated by tools/bindgen. DO NOT EDIT.
//
// Source: MacOSX26.2.sdk (Xcode 26.2), target arm64-apple-macos26.0
// Frameworks: Foundation, AppKit
//
// Regenerate with: tools/bindgen/regen.sh

//go:build darwin

package appkit

import (
	"github.com/adriaanm/wata/go-pkgs/appleptt/objcrt"
	"github.com/ebitengine/purego/objc"
)

// NSTextField wraps the ObjC class NSTextField (NSControl subclass).
type NSTextField struct{ objc.ID }

// NSTextFieldClass is the class object of NSTextField.
type NSTextFieldClass struct{ objc.Class }

// GetNSTextFieldClass looks the class up in the ObjC runtime.
func GetNSTextFieldClass() NSTextFieldClass { return NSTextFieldClass{objc.GetClass("NSTextField")} }

// Alloc allocates an uninitialized NSTextField (-[NSObject alloc]).
func (c NSTextFieldClass) Alloc() NSTextField { return NSTextField{objc.ID(c.Class).Send(selAlloc)} }

// AcceptsFirstResponder reads the NSTextField property acceptsFirstResponder.
func (o NSTextField) AcceptsFirstResponder() bool {
	return objc.Send[bool](o.ID, selAcceptsFirstResponder)
}

// AllowsDefaultTighteningForTruncation reads the NSTextField property allowsDefaultTighteningForTruncation.
func (o NSTextField) AllowsDefaultTighteningForTruncation() bool {
	return objc.Send[bool](o.ID, selAllowsDefaultTighteningForTruncation)
}

// SetAllowsDefaultTighteningForTruncation writes the NSTextField property allowsDefaultTighteningForTruncation.
func (o NSTextField) SetAllowsDefaultTighteningForTruncation(v bool) {
	o.ID.Send(selSetAllowsDefaultTighteningForTruncation, v)
}

// AllowsEditingTextAttributes reads the NSTextField property allowsEditingTextAttributes.
func (o NSTextField) AllowsEditingTextAttributes() bool {
	return objc.Send[bool](o.ID, selAllowsEditingTextAttributes)
}

// SetAllowsEditingTextAttributes writes the NSTextField property allowsEditingTextAttributes.
func (o NSTextField) SetAllowsEditingTextAttributes(v bool) {
	o.ID.Send(selSetAllowsEditingTextAttributes, v)
}

// AllowsWritingTools reads the NSTextField property allowsWritingTools.
func (o NSTextField) AllowsWritingTools() bool {
	return objc.Send[bool](o.ID, selAllowsWritingTools)
}

// SetAllowsWritingTools writes the NSTextField property allowsWritingTools.
func (o NSTextField) SetAllowsWritingTools(v bool) {
	o.ID.Send(selSetAllowsWritingTools, v)
}

// AllowsWritingToolsAffordance reads the NSTextField property allowsWritingToolsAffordance.
func (o NSTextField) AllowsWritingToolsAffordance() bool {
	return objc.Send[bool](o.ID, selAllowsWritingToolsAffordance)
}

// SetAllowsWritingToolsAffordance writes the NSTextField property allowsWritingToolsAffordance.
func (o NSTextField) SetAllowsWritingToolsAffordance(v bool) {
	o.ID.Send(selSetAllowsWritingToolsAffordance, v)
}

// BackgroundColor reads the NSTextField property backgroundColor.
func (o NSTextField) BackgroundColor() NSColor {
	return NSColor{o.ID.Send(selBackgroundColor)}
}

// SetBackgroundColor writes the NSTextField property backgroundColor.
func (o NSTextField) SetBackgroundColor(v NSColor) {
	o.ID.Send(selSetBackgroundColor, v.ID)
}

// Bezeled reads the NSTextField property bezeled.
func (o NSTextField) Bezeled() bool {
	return objc.Send[bool](o.ID, selIsBezeled)
}

// SetBezeled writes the NSTextField property bezeled.
func (o NSTextField) SetBezeled(v bool) {
	o.ID.Send(selSetBezeled, v)
}

// Bordered reads the NSTextField property bordered.
func (o NSTextField) Bordered() bool {
	return objc.Send[bool](o.ID, selIsBordered)
}

// SetBordered writes the NSTextField property bordered.
func (o NSTextField) SetBordered(v bool) {
	o.ID.Send(selSetBordered, v)
}

// Delegate reads the NSTextField property delegate.
func (o NSTextField) Delegate() objc.ID {
	return o.ID.Send(selDelegate)
}

// SetDelegate writes the NSTextField property delegate.
func (o NSTextField) SetDelegate(v objc.ID) {
	o.ID.Send(selSetDelegate, v)
}

// DrawsBackground reads the NSTextField property drawsBackground.
func (o NSTextField) DrawsBackground() bool {
	return objc.Send[bool](o.ID, selDrawsBackground)
}

// SetDrawsBackground writes the NSTextField property drawsBackground.
func (o NSTextField) SetDrawsBackground(v bool) {
	o.ID.Send(selSetDrawsBackground, v)
}

// Editable reads the NSTextField property editable.
func (o NSTextField) Editable() bool {
	return objc.Send[bool](o.ID, selIsEditable)
}

// SetEditable writes the NSTextField property editable.
func (o NSTextField) SetEditable(v bool) {
	o.ID.Send(selSetEditable, v)
}

// ImportsGraphics reads the NSTextField property importsGraphics.
func (o NSTextField) ImportsGraphics() bool {
	return objc.Send[bool](o.ID, selImportsGraphics)
}

// SetImportsGraphics writes the NSTextField property importsGraphics.
func (o NSTextField) SetImportsGraphics(v bool) {
	o.ID.Send(selSetImportsGraphics, v)
}

// MaximumNumberOfLines reads the NSTextField property maximumNumberOfLines.
func (o NSTextField) MaximumNumberOfLines() int {
	return objc.Send[int](o.ID, selMaximumNumberOfLines)
}

// SetMaximumNumberOfLines writes the NSTextField property maximumNumberOfLines.
func (o NSTextField) SetMaximumNumberOfLines(v int) {
	o.ID.Send(selSetMaximumNumberOfLines, v)
}

// PlaceholderAttributedStrings reads the NSTextField property placeholderAttributedStrings.
func (o NSTextField) PlaceholderAttributedStrings() NSArray {
	return NSArray{o.ID.Send(selPlaceholderAttributedStrings)}
}

// SetPlaceholderAttributedStrings writes the NSTextField property placeholderAttributedStrings.
func (o NSTextField) SetPlaceholderAttributedStrings(v NSArray) {
	o.ID.Send(selSetPlaceholderAttributedStrings, v.ID)
}

// PlaceholderString reads the NSTextField property placeholderString.
func (o NSTextField) PlaceholderString() string {
	return objcrt.GoString(o.ID.Send(selPlaceholderString))
}

// SetPlaceholderString writes the NSTextField property placeholderString.
func (o NSTextField) SetPlaceholderString(v string) {
	o.ID.Send(selSetPlaceholderString, objcrt.NSString(v))
}

// PlaceholderStrings reads the NSTextField property placeholderStrings.
func (o NSTextField) PlaceholderStrings() NSArray {
	return NSArray{o.ID.Send(selPlaceholderStrings)}
}

// SetPlaceholderStrings writes the NSTextField property placeholderStrings.
func (o NSTextField) SetPlaceholderStrings(v NSArray) {
	o.ID.Send(selSetPlaceholderStrings, v.ID)
}

// PreferredMaxLayoutWidth — The preferredMaxLayoutWidth determines the maximum width of the intrinsicContentSize. If the text field wraps, the intrinsic height will be large enough to show the entire text contents at that width. The default is 0, which implies no maximum preferred width.
func (o NSTextField) PreferredMaxLayoutWidth() float64 {
	return objc.Send[float64](o.ID, selPreferredMaxLayoutWidth)
}

// SetPreferredMaxLayoutWidth writes the NSTextField property preferredMaxLayoutWidth.
func (o NSTextField) SetPreferredMaxLayoutWidth(v float64) {
	o.ID.Send(selSetPreferredMaxLayoutWidth, v)
}

// ResolvesNaturalAlignmentWithBaseWritingDirection reads the NSTextField property resolvesNaturalAlignmentWithBaseWritingDirection.
func (o NSTextField) ResolvesNaturalAlignmentWithBaseWritingDirection() bool {
	return objc.Send[bool](o.ID, selResolvesNaturalAlignmentWithBaseWritingDirection)
}

// SetResolvesNaturalAlignmentWithBaseWritingDirection writes the NSTextField property resolvesNaturalAlignmentWithBaseWritingDirection.
func (o NSTextField) SetResolvesNaturalAlignmentWithBaseWritingDirection(v bool) {
	o.ID.Send(selSetResolvesNaturalAlignmentWithBaseWritingDirection, v)
}

// Selectable reads the NSTextField property selectable.
func (o NSTextField) Selectable() bool {
	return objc.Send[bool](o.ID, selIsSelectable)
}

// SetSelectable writes the NSTextField property selectable.
func (o NSTextField) SetSelectable(v bool) {
	o.ID.Send(selSetSelectable, v)
}

// TextColor reads the NSTextField property textColor.
func (o NSTextField) TextColor() NSColor {
	return NSColor{o.ID.Send(selTextColor)}
}

// SetTextColor writes the NSTextField property textColor.
func (o NSTextField) SetTextColor(v NSColor) {
	o.ID.Send(selSetTextColor, v.ID)
}

// SelectText calls -[NSTextField selectText:].
func (o NSTextField) SelectText(sender objc.ID) {
	o.ID.Send(selSelectText, sender)
}

// SetTitleWithMnemonic calls -[NSTextField setTitleWithMnemonic:].
func (o NSTextField) SetTitleWithMnemonic(stringWithAmpersand string) {
	o.ID.Send(selSetTitleWithMnemonic, objcrt.NSString(stringWithAmpersand))
}

// TextDidBeginEditing calls -[NSTextField textDidBeginEditing:].
func (o NSTextField) TextDidBeginEditing(notification NSNotification) {
	o.ID.Send(selTextDidBeginEditing, notification.ID)
}

// TextDidChange calls -[NSTextField textDidChange:].
func (o NSTextField) TextDidChange(notification NSNotification) {
	o.ID.Send(selTextDidChange, notification.ID)
}

// TextDidEndEditing calls -[NSTextField textDidEndEditing:].
func (o NSTextField) TextDidEndEditing(notification NSNotification) {
	o.ID.Send(selTextDidEndEditing, notification.ID)
}

// LabelWithString calls +[NSTextField labelWithString:].
func (c NSTextFieldClass) LabelWithString(stringValue string) NSTextField {
	return NSTextField{objc.ID(c.Class).Send(selLabelWithString, objcrt.NSString(stringValue))}
}

// TextFieldWithString calls +[NSTextField textFieldWithString:].
func (c NSTextFieldClass) TextFieldWithString(stringValue string) NSTextField {
	return NSTextField{objc.ID(c.Class).Send(selTextFieldWithString, objcrt.NSString(stringValue))}
}

// WrappingLabelWithString calls +[NSTextField wrappingLabelWithString:].
func (c NSTextFieldClass) WrappingLabelWithString(stringValue string) NSTextField {
	return NSTextField{objc.ID(c.Class).Send(selWrappingLabelWithString, objcrt.NSString(stringValue))}
}
