// Code generated by tools/bindgen. DO NOT EDIT.
//
// Source: MacOSX26.2.sdk (Xcode 26.2), target arm64-apple-macos26.0
// Frameworks: Foundation, AppKit
//
// Regenerate with: tools/bindgen/regen.sh

//go:build darwin

package appkit

import (
	"github.com/adriaanm/wata/go-pkgs/appleptt/objcrt"
	"github.com/ebitengine/purego/objc"
)

// NSView wraps the ObjC class NSView (NSResponder subclass).
type NSView struct{ objc.ID }

// NSViewClass is the class object of NSView.
type NSViewClass struct{ objc.Class }

// GetNSViewClass looks the class up in the ObjC runtime.
func GetNSViewClass() NSViewClass { return NSViewClass{objc.GetClass("NSView")} }

// Alloc allocates an uninitialized NSView (-[NSObject alloc]).
func (c NSViewClass) Alloc() NSView { return NSView{objc.ID(c.Class).Send(selAlloc)} }

// AcceptsTouchEvents reads the NSView property acceptsTouchEvents.
func (o NSView) AcceptsTouchEvents() bool {
	return objc.Send[bool](o.ID, selAcceptsTouchEvents)
}

// SetAcceptsTouchEvents writes the NSView property acceptsTouchEvents.
func (o NSView) SetAcceptsTouchEvents(v bool) {
	o.ID.Send(selSetAcceptsTouchEvents, v)
}

// AllowsVibrancy reads the NSView property allowsVibrancy.
func (o NSView) AllowsVibrancy() bool {
	return objc.Send[bool](o.ID, selAllowsVibrancy)
}

// AlphaValue reads the NSView property alphaValue.
func (o NSView) AlphaValue() float64 {
	return objc.Send[float64](o.ID, selAlphaValue)
}

// SetAlphaValue writes the NSView property alphaValue.
func (o NSView) SetAlphaValue(v float64) {
	o.ID.Send(selSetAlphaValue, v)
}

// AutoresizesSubviews reads the NSView property autoresizesSubviews.
func (o NSView) AutoresizesSubviews() bool {
	return objc.Send[bool](o.ID, selAutoresizesSubviews)
}

// SetAutoresizesSubviews writes the NSView property autoresizesSubviews.
func (o NSView) SetAutoresizesSubviews(v bool) {
	o.ID.Send(selSetAutoresizesSubviews, v)
}

// BackgroundFilters reads the NSView property backgroundFilters.
func (o NSView) BackgroundFilters() NSArray {
	return NSArray{o.ID.Send(selBackgroundFilters)}
}

// SetBackgroundFilters writes the NSView property backgroundFilters.
func (o NSView) SetBackgroundFilters(v NSArray) {
	o.ID.Send(selSetBackgroundFilters, v.ID)
}

// Bounds reads the NSView property bounds.
func (o NSView) Bounds() CGRect {
	return objc.Send[CGRect](o.ID, selBounds)
}

// SetBounds writes the NSView property bounds.
func (o NSView) SetBounds(v CGRect) {
	o.ID.Send(selSetBounds, v)
}

// BoundsRotation reads the NSView property boundsRotation.
func (o NSView) BoundsRotation() float64 {
	return objc.Send[float64](o.ID, selBoundsRotation)
}

// SetBoundsRotation writes the NSView property boundsRotation.
func (o NSView) SetBoundsRotation(v float64) {
	o.ID.Send(selSetBoundsRotation, v)
}

// CanDraw — Sets whether AppKit may invoke the view's -drawRect: method on a background thread, where it would otherwise be invoked on the main thread.  Defaults to NO for most kinds of views.  May be set to YES to enable threaded drawing for a particular view instance.  The view's window must also have its "allowsConcurrentViewDrawing" property set to YES (the default) for threading of view drawing to actually take place.
func (o NSView) CanDraw() bool {
	return objc.Send[bool](o.ID, selCanDraw)
}

// CanDrawConcurrently — Reports whether AppKit may invoke the view's -drawRect: method on a background thread, where it would otherwise be invoked on the main thread.  Defaults to NO.
func (o NSView) CanDrawConcurrently() bool {
	return objc.Send[bool](o.ID, selCanDrawConcurrently)
}

// SetCanDrawConcurrently writes the NSView property canDrawConcurrently.
func (o NSView) SetCanDrawConcurrently(v bool) {
	o.ID.Send(selSetCanDrawConcurrently, v)
}

// CanDrawSubviewsIntoLayer reads the NSView property canDrawSubviewsIntoLayer.
func (o NSView) CanDrawSubviewsIntoLayer() bool {
	return objc.Send[bool](o.ID, selCanDrawSubviewsIntoLayer)
}

// SetCanDrawSubviewsIntoLayer writes the NSView property canDrawSubviewsIntoLayer.
func (o NSView) SetCanDrawSubviewsIntoLayer(v bool) {
	o.ID.Send(selSetCanDrawSubviewsIntoLayer, v)
}

// ClipsToBounds reads the NSView property clipsToBounds.
func (o NSView) ClipsToBounds() bool {
	return objc.Send[bool](o.ID, selClipsToBounds)
}

// SetClipsToBounds writes the NSView property clipsToBounds.
func (o NSView) SetClipsToBounds(v bool) {
	o.ID.Send(selSetClipsToBounds, v)
}

// ContentFilters reads the NSView property contentFilters.
func (o NSView) ContentFilters() NSArray {
	return NSArray{o.ID.Send(selContentFilters)}
}

// SetContentFilters writes the NSView property contentFilters.
func (o NSView) SetContentFilters(v NSArray) {
	o.ID.Send(selSetContentFilters, v.ID)
}

// Flipped reads the NSView property flipped.
func (o NSView) Flipped() bool {
	return objc.Send[bool](o.ID, selIsFlipped)
}

// Frame reads the NSView property frame.
func (o NSView) Frame() CGRect {
	return objc.Send[CGRect](o.ID, selFrame)
}

// SetFrame writes the NSView property frame.
func (o NSView) SetFrame(v CGRect) {
	o.ID.Send(selSetFrame, v)
}

// FrameCenterRotation reads the NSView property frameCenterRotation.
func (o NSView) FrameCenterRotation() float64 {
	return objc.Send[float64](o.ID, selFrameCenterRotation)
}

// SetFrameCenterRotation writes the NSView property frameCenterRotation.
func (o NSView) SetFrameCenterRotation(v float64) {
	o.ID.Send(selSetFrameCenterRotation, v)
}

// FrameRotation reads the NSView property frameRotation.
func (o NSView) FrameRotation() float64 {
	return objc.Send[float64](o.ID, selFrameRotation)
}

// SetFrameRotation writes the NSView property frameRotation.
func (o NSView) SetFrameRotation(v float64) {
	o.ID.Send(selSetFrameRotation, v)
}

// Hidden reads the NSView property hidden.
func (o NSView) Hidden() bool {
	return objc.Send[bool](o.ID, selIsHidden)
}

// SetHidden writes the NSView property hidden.
func (o NSView) SetHidden(v bool) {
	o.ID.Send(selSetHidden, v)
}

// HiddenOrHasHiddenAncestor reads the NSView property hiddenOrHasHiddenAncestor.
func (o NSView) HiddenOrHasHiddenAncestor() bool {
	return objc.Send[bool](o.ID, selIsHiddenOrHasHiddenAncestor)
}

// InLiveResize reads the NSView property inLiveResize.
func (o NSView) InLiveResize() bool {
	return objc.Send[bool](o.ID, selInLiveResize)
}

// LayerUsesCoreImageFilters reads the NSView property layerUsesCoreImageFilters.
func (o NSView) LayerUsesCoreImageFilters() bool {
	return objc.Send[bool](o.ID, selLayerUsesCoreImageFilters)
}

// SetLayerUsesCoreImageFilters writes the NSView property layerUsesCoreImageFilters.
func (o NSView) SetLayerUsesCoreImageFilters(v bool) {
	o.ID.Send(selSetLayerUsesCoreImageFilters, v)
}

// MouseDownCanMoveWindow reads the NSView property mouseDownCanMoveWindow.
func (o NSView) MouseDownCanMoveWindow() bool {
	return objc.Send[bool](o.ID, selMouseDownCanMoveWindow)
}

// NeedsDisplay reads the NSView property needsDisplay.
func (o NSView) NeedsDisplay() bool {
	return objc.Send[bool](o.ID, selNeedsDisplay)
}

// SetNeedsDisplay writes the NSView property needsDisplay.
func (o NSView) SetNeedsDisplay(v bool) {
	o.ID.Send(selSetNeedsDisplay, v)
}

// NeedsLayout reads the NSView property needsLayout.
func (o NSView) NeedsLayout() bool {
	return objc.Send[bool](o.ID, selNeedsLayout)
}

// SetNeedsLayout writes the NSView property needsLayout.
func (o NSView) SetNeedsLayout(v bool) {
	o.ID.Send(selSetNeedsLayout, v)
}

// NeedsPanelToBecomeKey reads the NSView property needsPanelToBecomeKey.
func (o NSView) NeedsPanelToBecomeKey() bool {
	return objc.Send[bool](o.ID, selNeedsPanelToBecomeKey)
}

// Opaque — A hint as to whether or not this view draws its contents completely opaque or not. Opaque content drawing can allow some optimizations to happen. The default value is NO.
func (o NSView) Opaque() bool {
	return objc.Send[bool](o.ID, selIsOpaque)
}

// OpaqueAncestor reads the NSView property opaqueAncestor.
func (o NSView) OpaqueAncestor() NSView {
	return NSView{o.ID.Send(selOpaqueAncestor)}
}

// PostsBoundsChangedNotifications reads the NSView property postsBoundsChangedNotifications.
func (o NSView) PostsBoundsChangedNotifications() bool {
	return objc.Send[bool](o.ID, selPostsBoundsChangedNotifications)
}

// SetPostsBoundsChangedNotifications writes the NSView property postsBoundsChangedNotifications.
func (o NSView) SetPostsBoundsChangedNotifications(v bool) {
	o.ID.Send(selSetPostsBoundsChangedNotifications, v)
}

// PostsFrameChangedNotifications reads the NSView property postsFrameChangedNotifications.
func (o NSView) PostsFrameChangedNotifications() bool {
	return objc.Send[bool](o.ID, selPostsFrameChangedNotifications)
}

// SetPostsFrameChangedNotifications writes the NSView property postsFrameChangedNotifications.
func (o NSView) SetPostsFrameChangedNotifications(v bool) {
	o.ID.Send(selSetPostsFrameChangedNotifications, v)
}

// PreparedContentRect reads the NSView property preparedContentRect.
func (o NSView) PreparedContentRect() CGRect {
	return objc.Send[CGRect](o.ID, selPreparedContentRect)
}

// SetPreparedContentRect writes the NSView property preparedContentRect.
func (o NSView) SetPreparedContentRect(v CGRect) {
	o.ID.Send(selSetPreparedContentRect, v)
}

// PreservesContentDuringLiveResize reads the NSView property preservesContentDuringLiveResize.
func (o NSView) PreservesContentDuringLiveResize() bool {
	return objc.Send[bool](o.ID, selPreservesContentDuringLiveResize)
}

// RectPreservedDuringLiveResize reads the NSView property rectPreservedDuringLiveResize.
func (o NSView) RectPreservedDuringLiveResize() CGRect {
	return objc.Send[CGRect](o.ID, selRectPreservedDuringLiveResize)
}

// RotatedFromBase reads the NSView property rotatedFromBase.
func (o NSView) RotatedFromBase() bool {
	return objc.Send[bool](o.ID, selIsRotatedFromBase)
}

// RotatedOrScaledFromBase reads the NSView property rotatedOrScaledFromBase.
func (o NSView) RotatedOrScaledFromBase() bool {
	return objc.Send[bool](o.ID, selIsRotatedOrScaledFromBase)
}

// Subviews reads the NSView property subviews.
func (o NSView) Subviews() NSArray {
	return NSArray{o.ID.Send(selSubviews)}
}

// SetSubviews writes the NSView property subviews.
func (o NSView) SetSubviews(v NSArray) {
	o.ID.Send(selSetSubviews, v.ID)
}

// Superview reads the NSView property superview.
func (o NSView) Superview() NSView {
	return NSView{o.ID.Send(selSuperview)}
}

// Tag reads the NSView property tag.
func (o NSView) Tag() int {
	return objc.Send[int](o.ID, selTag)
}

// ToolTip reads the NSView property toolTip.
func (o NSView) ToolTip() string {
	return objcrt.GoString(o.ID.Send(selToolTip))
}

// SetToolTip writes the NSView property toolTip.
func (o NSView) SetToolTip(v string) {
	o.ID.Send(selSetToolTip, objcrt.NSString(v))
}

// VisibleRect reads the NSView property visibleRect.
func (o NSView) VisibleRect() CGRect {
	return objc.Send[CGRect](o.ID, selVisibleRect)
}

// WantsDefaultClipping reads the NSView property wantsDefaultClipping.
func (o NSView) WantsDefaultClipping() bool {
	return objc.Send[bool](o.ID, selWantsDefaultClipping)
}

// WantsLayer reads the NSView property wantsLayer.
func (o NSView) WantsLayer() bool {
	return objc.Send[bool](o.ID, selWantsLayer)
}

// SetWantsLayer writes the NSView property wantsLayer.
func (o NSView) SetWantsLayer(v bool) {
	o.ID.Send(selSetWantsLayer, v)
}

// WantsRestingTouches reads the NSView property wantsRestingTouches.
func (o NSView) WantsRestingTouches() bool {
	return objc.Send[bool](o.ID, selWantsRestingTouches)
}

// SetWantsRestingTouches writes the NSView property wantsRestingTouches.
func (o NSView) SetWantsRestingTouches(v bool) {
	o.ID.Send(selSetWantsRestingTouches, v)
}

// WantsUpdateLayer reads the NSView property wantsUpdateLayer.
func (o NSView) WantsUpdateLayer() bool {
	return objc.Send[bool](o.ID, selWantsUpdateLayer)
}

// Window reads the NSView property window.
func (o NSView) Window() NSWindow {
	return NSWindow{o.ID.Send(selWindow)}
}

// CompatibleWithResponsiveScrolling reads the NSView class property compatibleWithResponsiveScrolling.
func (c NSViewClass) CompatibleWithResponsiveScrolling() bool {
	return objc.Send[bool](objc.ID(c.Class), selIsCompatibleWithResponsiveScrolling)
}

// FocusView reads the NSView class property focusView.
func (c NSViewClass) FocusView() NSView {
	return NSView{objc.ID(c.Class).Send(selFocusView)}
}

// AcceptsFirstMouse calls -[NSView acceptsFirstMouse:].
func (o NSView) AcceptsFirstMouse(event NSEvent) bool {
	return objc.Send[bool](o.ID, selAcceptsFirstMouse, event.ID)
}

// AddConstraints calls -[NSView addConstraints:].
func (o NSView) AddConstraints(constraints NSArray) {
	o.ID.Send(selAddConstraints, constraints.ID)
}

// AddSubview calls -[NSView addSubview:].
func (o NSView) AddSubview(view NSView) {
	o.ID.Send(selAddSubview, view.ID)
}

// AddSubviewPositionedRelativeTo calls -[NSView addSubview:positioned:relativeTo:].
func (o NSView) AddSubviewPositionedRelativeTo(view NSView, place NSWindowOrderingMode, otherView NSView) {
	o.ID.Send(selAddSubviewPositionedRelativeTo, view.ID, int(place), otherView.ID)
}

// AdjustScroll calls -[NSView adjustScroll:].
func (o NSView) AdjustScroll(newVisible CGRect) CGRect {
	return objc.Send[CGRect](o.ID, selAdjustScroll, newVisible)
}

// AlignmentRectForFrame calls -[NSView alignmentRectForFrame:].
func (o NSView) AlignmentRectForFrame(frame CGRect) CGRect {
	return objc.Send[CGRect](o.ID, selAlignmentRectForFrame, frame)
}

// AllocateGState calls -[NSView allocateGState].
func (o NSView) AllocateGState() {
	o.ID.Send(selAllocateGState)
}

// AncestorSharedWithView calls -[NSView ancestorSharedWithView:].
func (o NSView) AncestorSharedWithView(view NSView) NSView {
	return NSView{o.ID.Send(selAncestorSharedWithView, view.ID)}
}

// Autoscroll calls -[NSView autoscroll:].
func (o NSView) Autoscroll(event NSEvent) bool {
	return objc.Send[bool](o.ID, selAutoscroll, event.ID)
}

// BeginDocument calls -[NSView beginDocument].
func (o NSView) BeginDocument() {
	o.ID.Send(selBeginDocument)
}

// BeginPageInRectAtPlacement calls -[NSView beginPageInRect:atPlacement:].
func (o NSView) BeginPageInRectAtPlacement(rect CGRect, location CGPoint) {
	o.ID.Send(selBeginPageInRectAtPlacement, rect, location)
}

// BitmapImageRepForCachingDisplayInRect calls -[NSView bitmapImageRepForCachingDisplayInRect:].
func (o NSView) BitmapImageRepForCachingDisplayInRect(rect CGRect) NSBitmapImageRep {
	return NSBitmapImageRep{o.ID.Send(selBitmapImageRepForCachingDisplayInRect, rect)}
}

// CacheDisplayInRectToBitmapImageRep calls -[NSView cacheDisplayInRect:toBitmapImageRep:].
func (o NSView) CacheDisplayInRectToBitmapImageRep(rect CGRect, bitmapImageRep NSBitmapImageRep) {
	o.ID.Send(selCacheDisplayInRectToBitmapImageRep, rect, bitmapImageRep.ID)
}

// CenterScanRect calls -[NSView centerScanRect:].
func (o NSView) CenterScanRect(rect CGRect) CGRect {
	return objc.Send[CGRect](o.ID, selCenterScanRect, rect)
}

// ConvertPointFromView calls -[NSView convertPoint:fromView:].
func (o NSView) ConvertPointFromView(point CGPoint, view NSView) CGPoint {
	return objc.Send[CGPoint](o.ID, selConvertPointFromView, point, view.ID)
}

// ConvertPointToView calls -[NSView convertPoint:toView:].
func (o NSView) ConvertPointToView(point CGPoint, view NSView) CGPoint {
	return objc.Send[CGPoint](o.ID, selConvertPointToView, point, view.ID)
}

// ConvertPointFromBacking calls -[NSView convertPointFromBacking:].
func (o NSView) ConvertPointFromBacking(point CGPoint) CGPoint {
	return objc.Send[CGPoint](o.ID, selConvertPointFromBacking, point)
}

// ConvertPointFromBase calls -[NSView convertPointFromBase:].
func (o NSView) ConvertPointFromBase(point CGPoint) CGPoint {
	return objc.Send[CGPoint](o.ID, selConvertPointFromBase, point)
}

// ConvertPointFromLayer calls -[NSView convertPointFromLayer:].
func (o NSView) ConvertPointFromLayer(point CGPoint) CGPoint {
	return objc.Send[CGPoint](o.ID, selConvertPointFromLayer, point)
}

// ConvertPointToBacking — New methods for converting to and from backing store pixels
func (o NSView) ConvertPointToBacking(point CGPoint) CGPoint {
	return objc.Send[CGPoint](o.ID, selConvertPointToBacking, point)
}

// ConvertPointToBase calls -[NSView convertPointToBase:].
func (o NSView) ConvertPointToBase(point CGPoint) CGPoint {
	return objc.Send[CGPoint](o.ID, selConvertPointToBase, point)
}

// ConvertPointToLayer — Use these methods to transform geometry between a view's interior (bounds) coordinate space and its layer's interior coordinate space.  The layer's space is virtual, and doesn't take into account the layer's contentsScale setting.  For conversion between view space and layer pixels, use -convert(Point/Size/Rect)(To/From)Backing: instead.
func (o NSView) ConvertPointToLayer(point CGPoint) CGPoint {
	return objc.Send[CGPoint](o.ID, selConvertPointToLayer, point)
}

// ConvertRectFromView calls -[NSView convertRect:fromView:].
func (o NSView) ConvertRectFromView(rect CGRect, view NSView) CGRect {
	return objc.Send[CGRect](o.ID, selConvertRectFromView, rect, view.ID)
}

// ConvertRectToView calls -[NSView convertRect:toView:].
func (o NSView) ConvertRectToView(rect CGRect, view NSView) CGRect {
	return objc.Send[CGRect](o.ID, selConvertRectToView, rect, view.ID)
}

// ConvertRectFromBacking calls -[NSView convertRectFromBacking:].
func (o NSView) ConvertRectFromBacking(rect CGRect) CGRect {
	return objc.Send[CGRect](o.ID, selConvertRectFromBacking, rect)
}

// ConvertRectFromBase calls -[NSView convertRectFromBase:].
func (o NSView) ConvertRectFromBase(rect CGRect) CGRect {
	return objc.Send[CGRect](o.ID, selConvertRectFromBase, rect)
}

// ConvertRectFromLayer calls -[NSView convertRectFromLayer:].
func (o NSView) ConvertRectFromLayer(rect CGRect) CGRect {
	return objc.Send[CGRect](o.ID, selConvertRectFromLayer, rect)
}

// ConvertRectToBacking calls -[NSView convertRectToBacking:].
func (o NSView) ConvertRectToBacking(rect CGRect) CGRect {
	return objc.Send[CGRect](o.ID, selConvertRectToBacking, rect)
}

// ConvertRectToBase calls -[NSView convertRectToBase:].
func (o NSView) ConvertRectToBase(rect CGRect) CGRect {
	return objc.Send[CGRect](o.ID, selConvertRectToBase, rect)
}

// ConvertRectToLayer calls -[NSView convertRectToLayer:].
func (o NSView) ConvertRectToLayer(rect CGRect) CGRect {
	return objc.Send[CGRect](o.ID, selConvertRectToLayer, rect)
}

// ConvertSizeFromView calls -[NSView convertSize:fromView:].
func (o NSView) ConvertSizeFromView(size CGSize, view NSView) CGSize {
	return objc.Send[CGSize](o.ID, selConvertSizeFromView, size, view.ID)
}

// ConvertSizeToView calls -[NSView convertSize:toView:].
func (o NSView) ConvertSizeToView(size CGSize, view NSView) CGSize {
	return objc.Send[CGSize](o.ID, selConvertSizeToView, size, view.ID)
}

// ConvertSizeFromBacking calls -[NSView convertSizeFromBacking:].
func (o NSView) ConvertSizeFromBacking(size CGSize) CGSize {
	return objc.Send[CGSize](o.ID, selConvertSizeFromBacking, size)
}

// ConvertSizeFromBase calls -[NSView convertSizeFromBase:].
func (o NSView) ConvertSizeFromBase(size CGSize) CGSize {
	return objc.Send[CGSize](o.ID, selConvertSizeFromBase, size)
}

// ConvertSizeFromLayer calls -[NSView convertSizeFromLayer:].
func (o NSView) ConvertSizeFromLayer(size CGSize) CGSize {
	return objc.Send[CGSize](o.ID, selConvertSizeFromLayer, size)
}

// ConvertSizeToBacking calls -[NSView convertSizeToBacking:].
func (o NSView) ConvertSizeToBacking(size CGSize) CGSize {
	return objc.Send[CGSize](o.ID, selConvertSizeToBacking, size)
}

// ConvertSizeToBase calls -[NSView convertSizeToBase:].
func (o NSView) ConvertSizeToBase(size CGSize) CGSize {
	return objc.Send[CGSize](o.ID, selConvertSizeToBase, size)
}

// ConvertSizeToLayer calls -[NSView convertSizeToLayer:].
func (o NSView) ConvertSizeToLayer(size CGSize) CGSize {
	return objc.Send[CGSize](o.ID, selConvertSizeToLayer, size)
}

// DataWithEPSInsideRect calls -[NSView dataWithEPSInsideRect:].
func (o NSView) DataWithEPSInsideRect(rect CGRect) NSData {
	return NSData{o.ID.Send(selDataWithEPSInsideRect, rect)}
}

// DataWithPDFInsideRect calls -[NSView dataWithPDFInsideRect:].
func (o NSView) DataWithPDFInsideRect(rect CGRect) NSData {
	return NSData{o.ID.Send(selDataWithPDFInsideRect, rect)}
}

// DidAddSubview calls -[NSView didAddSubview:].
func (o NSView) DidAddSubview(subview NSView) {
	o.ID.Send(selDidAddSubview, subview.ID)
}

// DiscardCursorRects calls -[NSView discardCursorRects].
func (o NSView) DiscardCursorRects() {
	o.ID.Send(selDiscardCursorRects)
}

// Display calls -[NSView display].
func (o NSView) Display() {
	o.ID.Send(selDisplay)
}

// DisplayIfNeeded calls -[NSView displayIfNeeded].
func (o NSView) DisplayIfNeeded() {
	o.ID.Send(selDisplayIfNeeded)
}

// DisplayIfNeededIgnoringOpacity calls -[NSView displayIfNeededIgnoringOpacity].
func (o NSView) DisplayIfNeededIgnoringOpacity() {
	o.ID.Send(selDisplayIfNeededIgnoringOpacity)
}

// DisplayIfNeededInRect calls -[NSView displayIfNeededInRect:].
func (o NSView) DisplayIfNeededInRect(rect CGRect) {
	o.ID.Send(selDisplayIfNeededInRect, rect)
}

// DisplayIfNeededInRectIgnoringOpacity calls -[NSView displayIfNeededInRectIgnoringOpacity:].
func (o NSView) DisplayIfNeededInRectIgnoringOpacity(rect CGRect) {
	o.ID.Send(selDisplayIfNeededInRectIgnoringOpacity, rect)
}

// DisplayRect calls -[NSView displayRect:].
func (o NSView) DisplayRect(rect CGRect) {
	o.ID.Send(selDisplayRect, rect)
}

// DisplayRectIgnoringOpacity calls -[NSView displayRectIgnoringOpacity:].
func (o NSView) DisplayRectIgnoringOpacity(rect CGRect) {
	o.ID.Send(selDisplayRectIgnoringOpacity, rect)
}

// DragFileFromRectSlideBackEvent calls -[NSView dragFile:fromRect:slideBack:event:].
func (o NSView) DragFileFromRectSlideBackEvent(filename string, rect CGRect, flag bool, event NSEvent) bool {
	return objc.Send[bool](o.ID, selDragFileFromRectSlideBackEvent, objcrt.NSString(filename), rect, flag, event.ID)
}

// DragPromisedFilesOfTypesFromRectSourceSlideBackEvent calls -[NSView dragPromisedFilesOfTypes:fromRect:source:slideBack:event:].
func (o NSView) DragPromisedFilesOfTypesFromRectSourceSlideBackEvent(typeArray NSArray, rect CGRect, sourceObject objc.ID, flag bool, event NSEvent) bool {
	return objc.Send[bool](o.ID, selDragPromisedFilesOfTypesFromRectSourceSlideBackEvent, typeArray.ID, rect, sourceObject, flag, event.ID)
}

// DrawFocusRingMask calls -[NSView drawFocusRingMask].
func (o NSView) DrawFocusRingMask() {
	o.ID.Send(selDrawFocusRingMask)
}

// DrawPageBorderWithSize calls -[NSView drawPageBorderWithSize:].
func (o NSView) DrawPageBorderWithSize(borderSize CGSize) {
	o.ID.Send(selDrawPageBorderWithSize, borderSize)
}

// DrawRect calls -[NSView drawRect:].
func (o NSView) DrawRect(dirtyRect CGRect) {
	o.ID.Send(selDrawRect, dirtyRect)
}

// DrawSheetBorderWithSize calls -[NSView drawSheetBorderWithSize:].
func (o NSView) DrawSheetBorderWithSize(borderSize CGSize) {
	o.ID.Send(selDrawSheetBorderWithSize, borderSize)
}

// EndDocument calls -[NSView endDocument].
func (o NSView) EndDocument() {
	o.ID.Send(selEndDocument)
}

// EndPage calls -[NSView endPage].
func (o NSView) EndPage() {
	o.ID.Send(selEndPage)
}

// EnterFullScreenModeWithOptions calls -[NSView enterFullScreenMode:withOptions:].
func (o NSView) EnterFullScreenModeWithOptions(screen NSScreen, options NSDictionary) bool {
	return objc.Send[bool](o.ID, selEnterFullScreenModeWithOptions, screen.ID, options.ID)
}

// ExerciseAmbiguityInLayout calls -[NSView exerciseAmbiguityInLayout].
func (o NSView) ExerciseAmbiguityInLayout() {
	o.ID.Send(selExerciseAmbiguityInLayout)
}

// ExitFullScreenModeWithOptions calls -[NSView exitFullScreenModeWithOptions:].
func (o NSView) ExitFullScreenModeWithOptions(options NSDictionary) {
	o.ID.Send(selExitFullScreenModeWithOptions, options.ID)
}

// FrameForAlignmentRect calls -[NSView frameForAlignmentRect:].
func (o NSView) FrameForAlignmentRect(alignmentRect CGRect) CGRect {
	return objc.Send[CGRect](o.ID, selFrameForAlignmentRect, alignmentRect)
}

// GState calls -[NSView gState].
func (o NSView) GState() int {
	return objc.Send[int](o.ID, selGState)
}

// HitTest calls -[NSView hitTest:].
func (o NSView) HitTest(point CGPoint) NSView {
	return NSView{o.ID.Send(selHitTest, point)}
}

// InitWithFrame calls -[NSView initWithFrame:].
func (o NSView) InitWithFrame(frameRect CGRect) NSView {
	return NSView{o.ID.Send(selInitWithFrame, frameRect)}
}

// InvalidateIntrinsicContentSize calls -[NSView invalidateIntrinsicContentSize].
func (o NSView) InvalidateIntrinsicContentSize() {
	o.ID.Send(selInvalidateIntrinsicContentSize)
}

// IsDescendantOf calls -[NSView isDescendantOf:].
func (o NSView) IsDescendantOf(view NSView) bool {
	return objc.Send[bool](o.ID, selIsDescendantOf, view.ID)
}

// Layout calls -[NSView layout].
func (o NSView) Layout() {
	o.ID.Send(selLayout)
}

// LayoutSubtreeIfNeeded calls -[NSView layoutSubtreeIfNeeded].
func (o NSView) LayoutSubtreeIfNeeded() {
	o.ID.Send(selLayoutSubtreeIfNeeded)
}

// LocationOfPrintRect calls -[NSView locationOfPrintRect:].
func (o NSView) LocationOfPrintRect(rect CGRect) CGPoint {
	return objc.Send[CGPoint](o.ID, selLocationOfPrintRect, rect)
}

// LockFocus calls -[NSView lockFocus].
func (o NSView) LockFocus() {
	o.ID.Send(selLockFocus)
}

// LockFocusIfCanDraw calls -[NSView lockFocusIfCanDraw].
func (o NSView) LockFocusIfCanDraw() bool {
	return objc.Send[bool](o.ID, selLockFocusIfCanDraw)
}

// MouseInRect calls -[NSView mouse:inRect:].
func (o NSView) MouseInRect(point CGPoint, rect CGRect) bool {
	return objc.Send[bool](o.ID, selMouseInRect, point, rect)
}

// NeedsToDrawRect calls -[NSView needsToDrawRect:].
func (o NSView) NeedsToDrawRect(rect CGRect) bool {
	return objc.Send[bool](o.ID, selNeedsToDrawRect, rect)
}

// NoteFocusRingMaskChanged calls -[NSView noteFocusRingMaskChanged].
func (o NSView) NoteFocusRingMaskChanged() {
	o.ID.Send(selNoteFocusRingMaskChanged)
}

// PerformKeyEquivalent calls -[NSView performKeyEquivalent:].
func (o NSView) PerformKeyEquivalent(event NSEvent) bool {
	return objc.Send[bool](o.ID, selPerformKeyEquivalent, event.ID)
}

// PerformMnemonic calls -[NSView performMnemonic:].
func (o NSView) PerformMnemonic(string_ string) bool {
	return objc.Send[bool](o.ID, selPerformMnemonic, objcrt.NSString(string_))
}

// PrepareContentInRect calls -[NSView prepareContentInRect:].
func (o NSView) PrepareContentInRect(rect CGRect) {
	o.ID.Send(selPrepareContentInRect, rect)
}

// PrepareForReuse calls -[NSView prepareForReuse].
func (o NSView) PrepareForReuse() {
	o.ID.Send(selPrepareForReuse)
}

// Print calls -[NSView print:].
func (o NSView) Print(sender objc.ID) {
	o.ID.Send(selPrint, sender)
}

// RectForPage calls -[NSView rectForPage:].
func (o NSView) RectForPage(page int) CGRect {
	return objc.Send[CGRect](o.ID, selRectForPage, page)
}

// RectForSmartMagnificationAtPointInRect calls -[NSView rectForSmartMagnificationAtPoint:inRect:].
func (o NSView) RectForSmartMagnificationAtPointInRect(location CGPoint, visibleRect CGRect) CGRect {
	return objc.Send[CGRect](o.ID, selRectForSmartMagnificationAtPointInRect, location, visibleRect)
}

// RegisterForDraggedTypes calls -[NSView registerForDraggedTypes:].
func (o NSView) RegisterForDraggedTypes(newTypes NSArray) {
	o.ID.Send(selRegisterForDraggedTypes, newTypes.ID)
}

// ReleaseGState calls -[NSView releaseGState].
func (o NSView) ReleaseGState() {
	o.ID.Send(selReleaseGState)
}

// RemoveAllToolTips calls -[NSView removeAllToolTips].
func (o NSView) RemoveAllToolTips() {
	o.ID.Send(selRemoveAllToolTips)
}

// RemoveConstraints calls -[NSView removeConstraints:].
func (o NSView) RemoveConstraints(constraints NSArray) {
	o.ID.Send(selRemoveConstraints, constraints.ID)
}

// RemoveFromSuperview calls -[NSView removeFromSuperview].
func (o NSView) RemoveFromSuperview() {
	o.ID.Send(selRemoveFromSuperview)
}

// RemoveFromSuperviewWithoutNeedingDisplay calls -[NSView removeFromSuperviewWithoutNeedingDisplay].
func (o NSView) RemoveFromSuperviewWithoutNeedingDisplay() {
	o.ID.Send(selRemoveFromSuperviewWithoutNeedingDisplay)
}

// RemoveToolTip calls -[NSView removeToolTip:].
func (o NSView) RemoveToolTip(tag int) {
	o.ID.Send(selRemoveToolTip, tag)
}

// RemoveTrackingRect calls -[NSView removeTrackingRect:].
func (o NSView) RemoveTrackingRect(tag int) {
	o.ID.Send(selRemoveTrackingRect, tag)
}

// RenewGState calls -[NSView renewGState].
func (o NSView) RenewGState() {
	o.ID.Send(selRenewGState)
}

// ReplaceSubviewWith calls -[NSView replaceSubview:with:].
func (o NSView) ReplaceSubviewWith(oldView NSView, newView NSView) {
	o.ID.Send(selReplaceSubviewWith, oldView.ID, newView.ID)
}

// ResetCursorRects calls -[NSView resetCursorRects].
func (o NSView) ResetCursorRects() {
	o.ID.Send(selResetCursorRects)
}

// ResizeSubviewsWithOldSize calls -[NSView resizeSubviewsWithOldSize:].
func (o NSView) ResizeSubviewsWithOldSize(oldSize CGSize) {
	o.ID.Send(selResizeSubviewsWithOldSize, oldSize)
}

// ResizeWithOldSuperviewSize calls -[NSView resizeWithOldSuperviewSize:].
func (o NSView) ResizeWithOldSuperviewSize(oldSize CGSize) {
	o.ID.Send(selResizeWithOldSuperviewSize, oldSize)
}

// RotateByAngle calls -[NSView rotateByAngle:].
func (o NSView) RotateByAngle(angle float64) {
	o.ID.Send(selRotateByAngle, angle)
}

// ScaleUnitSquareToSize calls -[NSView scaleUnitSquareToSize:].
func (o NSView) ScaleUnitSquareToSize(newUnitSize CGSize) {
	o.ID.Send(selScaleUnitSquareToSize, newUnitSize)
}

// ScrollPoint calls -[NSView scrollPoint:].
func (o NSView) ScrollPoint(point CGPoint) {
	o.ID.Send(selScrollPoint, point)
}

// ScrollRectToVisible calls -[NSView scrollRectToVisible:].
func (o NSView) ScrollRectToVisible(rect CGRect) bool {
	return objc.Send[bool](o.ID, selScrollRectToVisible, rect)
}

// SetBoundsOrigin calls -[NSView setBoundsOrigin:].
func (o NSView) SetBoundsOrigin(newOrigin CGPoint) {
	o.ID.Send(selSetBoundsOrigin, newOrigin)
}

// SetBoundsSize calls -[NSView setBoundsSize:].
func (o NSView) SetBoundsSize(newSize CGSize) {
	o.ID.Send(selSetBoundsSize, newSize)
}

// SetFrameOrigin calls -[NSView setFrameOrigin:].
func (o NSView) SetFrameOrigin(newOrigin CGPoint) {
	o.ID.Send(selSetFrameOrigin, newOrigin)
}

// SetFrameSize calls -[NSView setFrameSize:].
func (o NSView) SetFrameSize(newSize CGSize) {
	o.ID.Send(selSetFrameSize, newSize)
}

// SetKeyboardFocusRingNeedsDisplayInRect calls -[NSView setKeyboardFocusRingNeedsDisplayInRect:].
func (o NSView) SetKeyboardFocusRingNeedsDisplayInRect(rect CGRect) {
	o.ID.Send(selSetKeyboardFocusRingNeedsDisplayInRect, rect)
}

// SetNeedsDisplayInRect calls -[NSView setNeedsDisplayInRect:].
func (o NSView) SetNeedsDisplayInRect(invalidRect CGRect) {
	o.ID.Send(selSetNeedsDisplayInRect, invalidRect)
}

// SetUpGState calls -[NSView setUpGState].
func (o NSView) SetUpGState() {
	o.ID.Send(selSetUpGState)
}

// ShouldDelayWindowOrderingForEvent calls -[NSView shouldDelayWindowOrderingForEvent:].
func (o NSView) ShouldDelayWindowOrderingForEvent(event NSEvent) bool {
	return objc.Send[bool](o.ID, selShouldDelayWindowOrderingForEvent, event.ID)
}

// ShouldDrawColor calls -[NSView shouldDrawColor].
func (o NSView) ShouldDrawColor() bool {
	return objc.Send[bool](o.ID, selShouldDrawColor)
}

// TranslateOriginToPoint calls -[NSView translateOriginToPoint:].
func (o NSView) TranslateOriginToPoint(translation CGPoint) {
	o.ID.Send(selTranslateOriginToPoint, translation)
}

// TranslateRectsNeedingDisplayInRectBy calls -[NSView translateRectsNeedingDisplayInRect:by:].
func (o NSView) TranslateRectsNeedingDisplayInRectBy(clipRect CGRect, delta CGSize) {
	o.ID.Send(selTranslateRectsNeedingDisplayInRectBy, clipRect, delta)
}

// UnlockFocus calls -[NSView unlockFocus].
func (o NSView) UnlockFocus() {
	o.ID.Send(selUnlockFocus)
}

// UnregisterDraggedTypes calls -[NSView unregisterDraggedTypes].
func (o NSView) UnregisterDraggedTypes() {
	o.ID.Send(selUnregisterDraggedTypes)
}

// UpdateConstraints calls -[NSView updateConstraints].
func (o NSView) UpdateConstraints() {
	o.ID.Send(selUpdateConstraints)
}

// UpdateConstraintsForSubtreeIfNeeded calls -[NSView updateConstraintsForSubtreeIfNeeded].
func (o NSView) UpdateConstraintsForSubtreeIfNeeded() {
	o.ID.Send(selUpdateConstraintsForSubtreeIfNeeded)
}

// UpdateLayer calls -[NSView updateLayer].
func (o NSView) UpdateLayer() {
	o.ID.Send(selUpdateLayer)
}

// UpdateTrackingAreas calls -[NSView updateTrackingAreas].
func (o NSView) UpdateTrackingAreas() {
	o.ID.Send(selUpdateTrackingAreas)
}

// ViewDidChangeBackingProperties calls -[NSView viewDidChangeBackingProperties].
func (o NSView) ViewDidChangeBackingProperties() {
	o.ID.Send(selViewDidChangeBackingProperties)
}

// ViewDidChangeEffectiveAppearance calls -[NSView viewDidChangeEffectiveAppearance].
func (o NSView) ViewDidChangeEffectiveAppearance() {
	o.ID.Send(selViewDidChangeEffectiveAppearance)
}

// ViewDidEndLiveResize calls -[NSView viewDidEndLiveResize].
func (o NSView) ViewDidEndLiveResize() {
	o.ID.Send(selViewDidEndLiveResize)
}

// ViewDidHide calls -[NSView viewDidHide].
func (o NSView) ViewDidHide() {
	o.ID.Send(selViewDidHide)
}

// ViewDidMoveToSuperview calls -[NSView viewDidMoveToSuperview].
func (o NSView) ViewDidMoveToSuperview() {
	o.ID.Send(selViewDidMoveToSuperview)
}

// ViewDidMoveToWindow calls -[NSView viewDidMoveToWindow].
func (o NSView) ViewDidMoveToWindow() {
	o.ID.Send(selViewDidMoveToWindow)
}

// ViewDidUnhide calls -[NSView viewDidUnhide].
func (o NSView) ViewDidUnhide() {
	o.ID.Send(selViewDidUnhide)
}

// ViewWillDraw calls -[NSView viewWillDraw].
func (o NSView) ViewWillDraw() {
	o.ID.Send(selViewWillDraw)
}

// ViewWillMoveToSuperview calls -[NSView viewWillMoveToSuperview:].
func (o NSView) ViewWillMoveToSuperview(newSuperview NSView) {
	o.ID.Send(selViewWillMoveToSuperview, newSuperview.ID)
}

// ViewWillMoveToWindow — NOTE: In general, it is good practice to call 'super' for the viewWill* and viewDid* methods. Some AppKit subclasses, such as NSTableView, depend on this behavior, and calling super is required for things to work properly.
func (o NSView) ViewWillMoveToWindow(newWindow NSWindow) {
	o.ID.Send(selViewWillMoveToWindow, newWindow.ID)
}

// ViewWillStartLiveResize calls -[NSView viewWillStartLiveResize].
func (o NSView) ViewWillStartLiveResize() {
	o.ID.Send(selViewWillStartLiveResize)
}

// ViewWithTag calls -[NSView viewWithTag:].
func (o NSView) ViewWithTag(tag int) NSView {
	return NSView{o.ID.Send(selViewWithTag, tag)}
}

// WillRemoveSubview calls -[NSView willRemoveSubview:].
func (o NSView) WillRemoveSubview(subview NSView) {
	o.ID.Send(selWillRemoveSubview, subview.ID)
}
