// Code generated by tools/bindgen. DO NOT EDIT.
//
// Source: MacOSX26.2.sdk (Xcode 26.2), target arm64-apple-macos26.0
// Frameworks: Foundation, AppKit
//
// Regenerate with: tools/bindgen/regen.sh

//go:build darwin

package appkit

import (
	"github.com/adriaanm/wata/go-pkgs/appleptt/objcrt"
	"github.com/ebitengine/purego/objc"
)

// NSWindowDelegate is the Go side of the ObjC protocol NSWindowDelegate.
//
// A nil field is not installed on the synthesized class, which is exactly
// ObjC's optional-method semantics: -respondsToSelector: answers NO for it.
type NSWindowDelegate struct {
	// -[NSWindowDelegate customWindowsToEnterFullScreenForWindow:]
	CustomWindowsToEnterFullScreenForWindow func(window NSWindow) NSArray
	// -[NSWindowDelegate customWindowsToEnterFullScreenForWindow:onScreen:]
	CustomWindowsToEnterFullScreenForWindowOnScreen func(window NSWindow, screen NSScreen) NSArray
	// -[NSWindowDelegate customWindowsToExitFullScreenForWindow:]
	CustomWindowsToExitFullScreenForWindow func(window NSWindow) NSArray
	// -[NSWindowDelegate window:startCustomAnimationToEnterFullScreenOnScreen:withDuration:]
	WindowStartCustomAnimationToEnterFullScreenOnScreenWithDuration func(window NSWindow, screen NSScreen, duration float64)
	// -[NSWindowDelegate window:startCustomAnimationToEnterFullScreenWithDuration:]
	WindowStartCustomAnimationToEnterFullScreenWithDuration func(window NSWindow, duration float64)
	// -[NSWindowDelegate window:startCustomAnimationToExitFullScreenWithDuration:]
	WindowStartCustomAnimationToExitFullScreenWithDuration func(window NSWindow, duration float64)
	// -[NSWindowDelegate window:willPositionSheet:usingRect:]
	WindowWillPositionSheetUsingRect func(window NSWindow, sheet NSWindow, rect CGRect) CGRect
	// -[NSWindowDelegate window:willResizeForVersionBrowserWithMaxPreferredSize:maxAllowedSize:]
	WindowWillResizeForVersionBrowserWithMaxPreferredSizeMaxAllowedSize func(window NSWindow, maxPreferredFrameSize CGSize, maxAllowedFrameSize CGSize) CGSize
	// -[NSWindowDelegate window:willUseFullScreenContentSize:]
	WindowWillUseFullScreenContentSize func(window NSWindow, proposedSize CGSize) CGSize
	// -[NSWindowDelegate windowDidBecomeKey:]
	WindowDidBecomeKey func(notification NSNotification)
	// -[NSWindowDelegate windowDidBecomeMain:]
	WindowDidBecomeMain func(notification NSNotification)
	// -[NSWindowDelegate windowDidChangeBackingProperties:]
	WindowDidChangeBackingProperties func(notification NSNotification)
	// -[NSWindowDelegate windowDidChangeOcclusionState:]
	WindowDidChangeOcclusionState func(notification NSNotification)
	// -[NSWindowDelegate windowDidChangeScreen:]
	WindowDidChangeScreen func(notification NSNotification)
	// -[NSWindowDelegate windowDidChangeScreenProfile:]
	WindowDidChangeScreenProfile func(notification NSNotification)
	// -[NSWindowDelegate windowDidDeminiaturize:]
	WindowDidDeminiaturize func(notification NSNotification)
	// -[NSWindowDelegate windowDidEndLiveResize:]
	WindowDidEndLiveResize func(notification NSNotification)
	// -[NSWindowDelegate windowDidEndSheet:]
	WindowDidEndSheet func(notification NSNotification)
	// -[NSWindowDelegate windowDidEnterFullScreen:]
	WindowDidEnterFullScreen func(notification NSNotification)
	// -[NSWindowDelegate windowDidEnterVersionBrowser:]
	WindowDidEnterVersionBrowser func(notification NSNotification)
	// -[NSWindowDelegate windowDidExitFullScreen:]
	WindowDidExitFullScreen func(notification NSNotification)
	// -[NSWindowDelegate windowDidExitVersionBrowser:]
	WindowDidExitVersionBrowser func(notification NSNotification)
	// -[NSWindowDelegate windowDidExpose:]
	WindowDidExpose func(notification NSNotification)
	// -[NSWindowDelegate windowDidFailToEnterFullScreen:]
	WindowDidFailToEnterFullScreen func(window NSWindow)
	// -[NSWindowDelegate windowDidFailToExitFullScreen:]
	WindowDidFailToExitFullScreen func(window NSWindow)
	// -[NSWindowDelegate windowDidMiniaturize:]
	WindowDidMiniaturize func(notification NSNotification)
	// -[NSWindowDelegate windowDidMove:]
	WindowDidMove func(notification NSNotification)
	// -[NSWindowDelegate windowDidResignKey:]
	WindowDidResignKey func(notification NSNotification)
	// -[NSWindowDelegate windowDidResignMain:]
	WindowDidResignMain func(notification NSNotification)
	// -[NSWindowDelegate windowDidResize:]
	WindowDidResize func(notification NSNotification)
	// -[NSWindowDelegate windowDidUpdate:]
	WindowDidUpdate func(notification NSNotification)
	// -[NSWindowDelegate windowForSharingRequestFromWindow:]
	WindowForSharingRequestFromWindow func(window NSWindow) NSWindow
	// -[NSWindowDelegate windowShouldClose:]
	WindowShouldClose func(sender NSWindow) bool
	// -[NSWindowDelegate windowShouldZoom:toFrame:]
	WindowShouldZoomToFrame func(window NSWindow, newFrame CGRect) bool
	// -[NSWindowDelegate windowWillBeginSheet:]
	WindowWillBeginSheet func(notification NSNotification)
	// -[NSWindowDelegate windowWillClose:]
	WindowWillClose func(notification NSNotification)
	// -[NSWindowDelegate windowWillEnterFullScreen:]
	WindowWillEnterFullScreen func(notification NSNotification)
	// -[NSWindowDelegate windowWillEnterVersionBrowser:]
	WindowWillEnterVersionBrowser func(notification NSNotification)
	// -[NSWindowDelegate windowWillExitFullScreen:]
	WindowWillExitFullScreen func(notification NSNotification)
	// -[NSWindowDelegate windowWillExitVersionBrowser:]
	WindowWillExitVersionBrowser func(notification NSNotification)
	// -[NSWindowDelegate windowWillMiniaturize:]
	WindowWillMiniaturize func(notification NSNotification)
	// -[NSWindowDelegate windowWillMove:]
	WindowWillMove func(notification NSNotification)
	// -[NSWindowDelegate windowWillResize:toSize:]
	WindowWillResizeToSize func(sender NSWindow, frameSize CGSize) CGSize
	// -[NSWindowDelegate windowWillReturnFieldEditor:toObject:]
	WindowWillReturnFieldEditorToObject func(sender NSWindow, client objc.ID) objc.ID
	// -[NSWindowDelegate windowWillStartLiveResize:]
	WindowWillStartLiveResize func(notification NSNotification)
	// -[NSWindowDelegate windowWillUseStandardFrame:defaultFrame:]
	WindowWillUseStandardFrameDefaultFrame func(window NSWindow, newFrame CGRect) CGRect
}

// NewNSWindowDelegate synthesizes an ObjC object conforming to NSWindowDelegate
// that forwards to d's non-nil funcs. The object is retained forever: the
// ObjC runtime cannot unregister a class.
func NewNSWindowDelegate(d NSWindowDelegate) objc.ID {
	var ms []objcrt.Method
	if d.CustomWindowsToEnterFullScreenForWindow != nil {
		ms = append(ms, objcrt.Method{
			Sel: "customWindowsToEnterFullScreenForWindow:",
			Fn: func(_ objc.ID, _ objc.SEL, a0 objc.ID) objc.ID {
				return d.CustomWindowsToEnterFullScreenForWindow(NSWindow{a0}).ID
			},
		})
	}
	if d.CustomWindowsToEnterFullScreenForWindowOnScreen != nil {
		ms = append(ms, objcrt.Method{
			Sel: "customWindowsToEnterFullScreenForWindow:onScreen:",
			Fn: func(_ objc.ID, _ objc.SEL, a0 objc.ID, a1 objc.ID) objc.ID {
				return d.CustomWindowsToEnterFullScreenForWindowOnScreen(NSWindow{a0}, NSScreen{a1}).ID
			},
		})
	}
	if d.CustomWindowsToExitFullScreenForWindow != nil {
		ms = append(ms, objcrt.Method{
			Sel: "customWindowsToExitFullScreenForWindow:",
			Fn: func(_ objc.ID, _ objc.SEL, a0 objc.ID) objc.ID {
				return d.CustomWindowsToExitFullScreenForWindow(NSWindow{a0}).ID
			},
		})
	}
	if d.WindowStartCustomAnimationToEnterFullScreenOnScreenWithDuration != nil {
		ms = append(ms, objcrt.Method{
			Sel: "window:startCustomAnimationToEnterFullScreenOnScreen:withDuration:",
			Fn: func(_ objc.ID, _ objc.SEL, a0 objc.ID, a1 objc.ID, a2 float64) {
				d.WindowStartCustomAnimationToEnterFullScreenOnScreenWithDuration(NSWindow{a0}, NSScreen{a1}, a2)
			},
		})
	}
	if d.WindowStartCustomAnimationToEnterFullScreenWithDuration != nil {
		ms = append(ms, objcrt.Method{
			Sel: "window:startCustomAnimationToEnterFullScreenWithDuration:",
			Fn: func(_ objc.ID, _ objc.SEL, a0 objc.ID, a1 float64) {
				d.WindowStartCustomAnimationToEnterFullScreenWithDuration(NSWindow{a0}, a1)
			},
		})
	}
	if d.WindowStartCustomAnimationToExitFullScreenWithDuration != nil {
		ms = append(ms, objcrt.Method{
			Sel: "window:startCustomAnimationToExitFullScreenWithDuration:",
			Fn: func(_ objc.ID, _ objc.SEL, a0 objc.ID, a1 float64) {
				d.WindowStartCustomAnimationToExitFullScreenWithDuration(NSWindow{a0}, a1)
			},
		})
	}
	if d.WindowWillPositionSheetUsingRect != nil {
		ms = append(ms, objcrt.Method{
			Sel: "window:willPositionSheet:usingRect:",
			Enc: "{CGRect={CGPoint=dd}{CGSize=dd}}@:@@{CGRect={CGPoint=dd}{CGSize=dd}}",
			Fn: func(_ objc.ID, _ objc.SEL, a0 objc.ID, a1 objc.ID, a2 CGRect) CGRect {
				return d.WindowWillPositionSheetUsingRect(NSWindow{a0}, NSWindow{a1}, a2)
			},
		})
	}
	if d.WindowWillResizeForVersionBrowserWithMaxPreferredSizeMaxAllowedSize != nil {
		ms = append(ms, objcrt.Method{
			Sel: "window:willResizeForVersionBrowserWithMaxPreferredSize:maxAllowedSize:",
			Enc: "{CGSize=dd}@:@{CGSize=dd}{CGSize=dd}",
			Fn: func(_ objc.ID, _ objc.SEL, a0 objc.ID, a1 CGSize, a2 CGSize) CGSize {
				return d.WindowWillResizeForVersionBrowserWithMaxPreferredSizeMaxAllowedSize(NSWindow{a0}, a1, a2)
			},
		})
	}
	if d.WindowWillUseFullScreenContentSize != nil {
		ms = append(ms, objcrt.Method{
			Sel: "window:willUseFullScreenContentSize:",
			Enc: "{CGSize=dd}@:@{CGSize=dd}",
			Fn: func(_ objc.ID, _ objc.SEL, a0 objc.ID, a1 CGSize) CGSize {
				return d.WindowWillUseFullScreenContentSize(NSWindow{a0}, a1)
			},
		})
	}
	if d.WindowDidBecomeKey != nil {
		ms = append(ms, objcrt.Method{
			Sel: "windowDidBecomeKey:",
			Fn: func(_ objc.ID, _ objc.SEL, a0 objc.ID) {
				d.WindowDidBecomeKey(NSNotification{a0})
			},
		})
	}
	if d.WindowDidBecomeMain != nil {
		ms = append(ms, objcrt.Method{
			Sel: "windowDidBecomeMain:",
			Fn: func(_ objc.ID, _ objc.SEL, a0 objc.ID) {
				d.WindowDidBecomeMain(NSNotification{a0})
			},
		})
	}
	if d.WindowDidChangeBackingProperties != nil {
		ms = append(ms, objcrt.Method{
			Sel: "windowDidChangeBackingProperties:",
			Fn: func(_ objc.ID, _ objc.SEL, a0 objc.ID) {
				d.WindowDidChangeBackingProperties(NSNotification{a0})
			},
		})
	}
	if d.WindowDidChangeOcclusionState != nil {
		ms = append(ms, objcrt.Method{
			Sel: "windowDidChangeOcclusionState:",
			Fn: func(_ objc.ID, _ objc.SEL, a0 objc.ID) {
				d.WindowDidChangeOcclusionState(NSNotification{a0})
			},
		})
	}
	if d.WindowDidChangeScreen != nil {
		ms = append(ms, objcrt.Method{
			Sel: "windowDidChangeScreen:",
			Fn: func(_ objc.ID, _ objc.SEL, a0 objc.ID) {
				d.WindowDidChangeScreen(NSNotification{a0})
			},
		})
	}
	if d.WindowDidChangeScreenProfile != nil {
		ms = append(ms, objcrt.Method{
			Sel: "windowDidChangeScreenProfile:",
			Fn: func(_ objc.ID, _ objc.SEL, a0 objc.ID) {
				d.WindowDidChangeScreenProfile(NSNotification{a0})
			},
		})
	}
	if d.WindowDidDeminiaturize != nil {
		ms = append(ms, objcrt.Method{
			Sel: "windowDidDeminiaturize:",
			Fn: func(_ objc.ID, _ objc.SEL, a0 objc.ID) {
				d.WindowDidDeminiaturize(NSNotification{a0})
			},
		})
	}
	if d.WindowDidEndLiveResize != nil {
		ms = append(ms, objcrt.Method{
			Sel: "windowDidEndLiveResize:",
			Fn: func(_ objc.ID, _ objc.SEL, a0 objc.ID) {
				d.WindowDidEndLiveResize(NSNotification{a0})
			},
		})
	}
	if d.WindowDidEndSheet != nil {
		ms = append(ms, objcrt.Method{
			Sel: "windowDidEndSheet:",
			Fn: func(_ objc.ID, _ objc.SEL, a0 objc.ID) {
				d.WindowDidEndSheet(NSNotification{a0})
			},
		})
	}
	if d.WindowDidEnterFullScreen != nil {
		ms = append(ms, objcrt.Method{
			Sel: "windowDidEnterFullScreen:",
			Fn: func(_ objc.ID, _ objc.SEL, a0 objc.ID) {
				d.WindowDidEnterFullScreen(NSNotification{a0})
			},
		})
	}
	if d.WindowDidEnterVersionBrowser != nil {
		ms = append(ms, objcrt.Method{
			Sel: "windowDidEnterVersionBrowser:",
			Fn: func(_ objc.ID, _ objc.SEL, a0 objc.ID) {
				d.WindowDidEnterVersionBrowser(NSNotification{a0})
			},
		})
	}
	if d.WindowDidExitFullScreen != nil {
		ms = append(ms, objcrt.Method{
			Sel: "windowDidExitFullScreen:",
			Fn: func(_ objc.ID, _ objc.SEL, a0 objc.ID) {
				d.WindowDidExitFullScreen(NSNotification{a0})
			},
		})
	}
	if d.WindowDidExitVersionBrowser != nil {
		ms = append(ms, objcrt.Method{
			Sel: "windowDidExitVersionBrowser:",
			Fn: func(_ objc.ID, _ objc.SEL, a0 objc.ID) {
				d.WindowDidExitVersionBrowser(NSNotification{a0})
			},
		})
	}
	if d.WindowDidExpose != nil {
		ms = append(ms, objcrt.Method{
			Sel: "windowDidExpose:",
			Fn: func(_ objc.ID, _ objc.SEL, a0 objc.ID) {
				d.WindowDidExpose(NSNotification{a0})
			},
		})
	}
	if d.WindowDidFailToEnterFullScreen != nil {
		ms = append(ms, objcrt.Method{
			Sel: "windowDidFailToEnterFullScreen:",
			Fn: func(_ objc.ID, _ objc.SEL, a0 objc.ID) {
				d.WindowDidFailToEnterFullScreen(NSWindow{a0})
			},
		})
	}
	if d.WindowDidFailToExitFullScreen != nil {
		ms = append(ms, objcrt.Method{
			Sel: "windowDidFailToExitFullScreen:",
			Fn: func(_ objc.ID, _ objc.SEL, a0 objc.ID) {
				d.WindowDidFailToExitFullScreen(NSWindow{a0})
			},
		})
	}
	if d.WindowDidMiniaturize != nil {
		ms = append(ms, objcrt.Method{
			Sel: "windowDidMiniaturize:",
			Fn: func(_ objc.ID, _ objc.SEL, a0 objc.ID) {
				d.WindowDidMiniaturize(NSNotification{a0})
			},
		})
	}
	if d.WindowDidMove != nil {
		ms = append(ms, objcrt.Method{
			Sel: "windowDidMove:",
			Fn: func(_ objc.ID, _ objc.SEL, a0 objc.ID) {
				d.WindowDidMove(NSNotification{a0})
			},
		})
	}
	if d.WindowDidResignKey != nil {
		ms = append(ms, objcrt.Method{
			Sel: "windowDidResignKey:",
			Fn: func(_ objc.ID, _ objc.SEL, a0 objc.ID) {
				d.WindowDidResignKey(NSNotification{a0})
			},
		})
	}
	if d.WindowDidResignMain != nil {
		ms = append(ms, objcrt.Method{
			Sel: "windowDidResignMain:",
			Fn: func(_ objc.ID, _ objc.SEL, a0 objc.ID) {
				d.WindowDidResignMain(NSNotification{a0})
			},
		})
	}
	if d.WindowDidResize != nil {
		ms = append(ms, objcrt.Method{
			Sel: "windowDidResize:",
			Fn: func(_ objc.ID, _ objc.SEL, a0 objc.ID) {
				d.WindowDidResize(NSNotification{a0})
			},
		})
	}
	if d.WindowDidUpdate != nil {
		ms = append(ms, objcrt.Method{
			Sel: "windowDidUpdate:",
			Fn: func(_ objc.ID, _ objc.SEL, a0 objc.ID) {
				d.WindowDidUpdate(NSNotification{a0})
			},
		})
	}
	if d.WindowForSharingRequestFromWindow != nil {
		ms = append(ms, objcrt.Method{
			Sel: "windowForSharingRequestFromWindow:",
			Fn: func(_ objc.ID, _ objc.SEL, a0 objc.ID) objc.ID {
				return d.WindowForSharingRequestFromWindow(NSWindow{a0}).ID
			},
		})
	}
	if d.WindowShouldClose != nil {
		ms = append(ms, objcrt.Method{
			Sel: "windowShouldClose:",
			Fn: func(_ objc.ID, _ objc.SEL, a0 objc.ID) bool {
				return d.WindowShouldClose(NSWindow{a0})
			},
		})
	}
	if d.WindowShouldZoomToFrame != nil {
		ms = append(ms, objcrt.Method{
			Sel: "windowShouldZoom:toFrame:",
			Enc: "B@:@{CGRect={CGPoint=dd}{CGSize=dd}}",
			Fn: func(_ objc.ID, _ objc.SEL, a0 objc.ID, a1 CGRect) bool {
				return d.WindowShouldZoomToFrame(NSWindow{a0}, a1)
			},
		})
	}
	if d.WindowWillBeginSheet != nil {
		ms = append(ms, objcrt.Method{
			Sel: "windowWillBeginSheet:",
			Fn: func(_ objc.ID, _ objc.SEL, a0 objc.ID) {
				d.WindowWillBeginSheet(NSNotification{a0})
			},
		})
	}
	if d.WindowWillClose != nil {
		ms = append(ms, objcrt.Method{
			Sel: "windowWillClose:",
			Fn: func(_ objc.ID, _ objc.SEL, a0 objc.ID) {
				d.WindowWillClose(NSNotification{a0})
			},
		})
	}
	if d.WindowWillEnterFullScreen != nil {
		ms = append(ms, objcrt.Method{
			Sel: "windowWillEnterFullScreen:",
			Fn: func(_ objc.ID, _ objc.SEL, a0 objc.ID) {
				d.WindowWillEnterFullScreen(NSNotification{a0})
			},
		})
	}
	if d.WindowWillEnterVersionBrowser != nil {
		ms = append(ms, objcrt.Method{
			Sel: "windowWillEnterVersionBrowser:",
			Fn: func(_ objc.ID, _ objc.SEL, a0 objc.ID) {
				d.WindowWillEnterVersionBrowser(NSNotification{a0})
			},
		})
	}
	if d.WindowWillExitFullScreen != nil {
		ms = append(ms, objcrt.Method{
			Sel: "windowWillExitFullScreen:",
			Fn: func(_ objc.ID, _ objc.SEL, a0 objc.ID) {
				d.WindowWillExitFullScreen(NSNotification{a0})
			},
		})
	}
	if d.WindowWillExitVersionBrowser != nil {
		ms = append(ms, objcrt.Method{
			Sel: "windowWillExitVersionBrowser:",
			Fn: func(_ objc.ID, _ objc.SEL, a0 objc.ID) {
				d.WindowWillExitVersionBrowser(NSNotification{a0})
			},
		})
	}
	if d.WindowWillMiniaturize != nil {
		ms = append(ms, objcrt.Method{
			Sel: "windowWillMiniaturize:",
			Fn: func(_ objc.ID, _ objc.SEL, a0 objc.ID) {
				d.WindowWillMiniaturize(NSNotification{a0})
			},
		})
	}
	if d.WindowWillMove != nil {
		ms = append(ms, objcrt.Method{
			Sel: "windowWillMove:",
			Fn: func(_ objc.ID, _ objc.SEL, a0 objc.ID) {
				d.WindowWillMove(NSNotification{a0})
			},
		})
	}
	if d.WindowWillResizeToSize != nil {
		ms = append(ms, objcrt.Method{
			Sel: "windowWillResize:toSize:",
			Enc: "{CGSize=dd}@:@{CGSize=dd}",
			Fn: func(_ objc.ID, _ objc.SEL, a0 objc.ID, a1 CGSize) CGSize {
				return d.WindowWillResizeToSize(NSWindow{a0}, a1)
			},
		})
	}
	if d.WindowWillReturnFieldEditorToObject != nil {
		ms = append(ms, objcrt.Method{
			Sel: "windowWillReturnFieldEditor:toObject:",
			Fn: func(_ objc.ID, _ objc.SEL, a0 objc.ID, a1 objc.ID) objc.ID {
				return d.WindowWillReturnFieldEditorToObject(NSWindow{a0}, a1)
			},
		})
	}
	if d.WindowWillStartLiveResize != nil {
		ms = append(ms, objcrt.Method{
			Sel: "windowWillStartLiveResize:",
			Fn: func(_ objc.ID, _ objc.SEL, a0 objc.ID) {
				d.WindowWillStartLiveResize(NSNotification{a0})
			},
		})
	}
	if d.WindowWillUseStandardFrameDefaultFrame != nil {
		ms = append(ms, objcrt.Method{
			Sel: "windowWillUseStandardFrame:defaultFrame:",
			Enc: "{CGRect={CGPoint=dd}{CGSize=dd}}@:@{CGRect={CGPoint=dd}{CGSize=dd}}",
			Fn: func(_ objc.ID, _ objc.SEL, a0 objc.ID, a1 CGRect) CGRect {
				return d.WindowWillUseStandardFrameDefaultFrame(NSWindow{a0}, a1)
			},
		})
	}
	return objcrt.NewDelegate("WataNSWindowDelegate", []string{"NSWindowDelegate"}, ms)
}
