// Code generated by tools/bindgen. DO NOT EDIT.
//
// Source: MacOSX26.2.sdk (Xcode 26.2), target arm64-apple-macos26.0
// Frameworks: Foundation, AppKit
//
// Regenerate with: tools/bindgen/regen.sh

//go:build darwin

package appkit

import (
	"github.com/adriaanm/wata/go-pkgs/appleptt/objcrt"
	"github.com/ebitengine/purego/objc"
)

// NSWindow wraps the ObjC class NSWindow (NSResponder subclass).
type NSWindow struct{ objc.ID }

// NSWindowClass is the class object of NSWindow.
type NSWindowClass struct{ objc.Class }

// GetNSWindowClass looks the class up in the ObjC runtime.
func GetNSWindowClass() NSWindowClass { return NSWindowClass{objc.GetClass("NSWindow")} }

// Alloc allocates an uninitialized NSWindow (-[NSObject alloc]).
func (c NSWindowClass) Alloc() NSWindow { return NSWindow{objc.ID(c.Class).Send(selAlloc)} }

// AllowsConcurrentViewDrawing reads the NSWindow property allowsConcurrentViewDrawing.
func (o NSWindow) AllowsConcurrentViewDrawing() bool {
	return objc.Send[bool](o.ID, selAllowsConcurrentViewDrawing)
}

// SetAllowsConcurrentViewDrawing writes the NSWindow property allowsConcurrentViewDrawing.
func (o NSWindow) SetAllowsConcurrentViewDrawing(v bool) {
	o.ID.Send(selSetAllowsConcurrentViewDrawing, v)
}

// AllowsToolTipsWhenApplicationIsInactive reads the NSWindow property allowsToolTipsWhenApplicationIsInactive.
func (o NSWindow) AllowsToolTipsWhenApplicationIsInactive() bool {
	return objc.Send[bool](o.ID, selAllowsToolTipsWhenApplicationIsInactive)
}

// SetAllowsToolTipsWhenApplicationIsInactive writes the NSWindow property allowsToolTipsWhenApplicationIsInactive.
func (o NSWindow) SetAllowsToolTipsWhenApplicationIsInactive(v bool) {
	o.ID.Send(selSetAllowsToolTipsWhenApplicationIsInactive, v)
}

// AlphaValue reads the NSWindow property alphaValue.
func (o NSWindow) AlphaValue() float64 {
	return objc.Send[float64](o.ID, selAlphaValue)
}

// SetAlphaValue writes the NSWindow property alphaValue.
func (o NSWindow) SetAlphaValue(v float64) {
	o.ID.Send(selSetAlphaValue, v)
}

// AspectRatio reads the NSWindow property aspectRatio.
func (o NSWindow) AspectRatio() CGSize {
	return objc.Send[CGSize](o.ID, selAspectRatio)
}

// SetAspectRatio writes the NSWindow property aspectRatio.
func (o NSWindow) SetAspectRatio(v CGSize) {
	o.ID.Send(selSetAspectRatio, v)
}

// AttachedSheet reads the NSWindow property attachedSheet.
func (o NSWindow) AttachedSheet() NSWindow {
	return NSWindow{o.ID.Send(selAttachedSheet)}
}

// AutorecalculatesKeyViewLoop reads the NSWindow property autorecalculatesKeyViewLoop.
func (o NSWindow) AutorecalculatesKeyViewLoop() bool {
	return objc.Send[bool](o.ID, selAutorecalculatesKeyViewLoop)
}

// SetAutorecalculatesKeyViewLoop writes the NSWindow property autorecalculatesKeyViewLoop.
func (o NSWindow) SetAutorecalculatesKeyViewLoop(v bool) {
	o.ID.Send(selSetAutorecalculatesKeyViewLoop, v)
}

// BackgroundColor reads the NSWindow property backgroundColor.
func (o NSWindow) BackgroundColor() NSColor {
	return NSColor{o.ID.Send(selBackgroundColor)}
}

// SetBackgroundColor writes the NSWindow property backgroundColor.
func (o NSWindow) SetBackgroundColor(v NSColor) {
	o.ID.Send(selSetBackgroundColor, v.ID)
}

// BackingScaleFactor reads the NSWindow property backingScaleFactor.
func (o NSWindow) BackingScaleFactor() float64 {
	return objc.Send[float64](o.ID, selBackingScaleFactor)
}

// BackingType reads the NSWindow property backingType.
func (o NSWindow) BackingType() NSBackingStoreType {
	return NSBackingStoreType(objc.Send[uint](o.ID, selBackingType))
}

// SetBackingType writes the NSWindow property backingType.
func (o NSWindow) SetBackingType(v NSBackingStoreType) {
	o.ID.Send(selSetBackingType, uint(v))
}

// CanBecomeKeyWindow reads the NSWindow property canBecomeKeyWindow.
func (o NSWindow) CanBecomeKeyWindow() bool {
	return objc.Send[bool](o.ID, selCanBecomeKeyWindow)
}

// CanBecomeMainWindow reads the NSWindow property canBecomeMainWindow.
func (o NSWindow) CanBecomeMainWindow() bool {
	return objc.Send[bool](o.ID, selCanBecomeMainWindow)
}

// CanBecomeVisibleWithoutLogin reads the NSWindow property canBecomeVisibleWithoutLogin.
func (o NSWindow) CanBecomeVisibleWithoutLogin() bool {
	return objc.Send[bool](o.ID, selCanBecomeVisibleWithoutLogin)
}

// SetCanBecomeVisibleWithoutLogin writes the NSWindow property canBecomeVisibleWithoutLogin.
func (o NSWindow) SetCanBecomeVisibleWithoutLogin(v bool) {
	o.ID.Send(selSetCanBecomeVisibleWithoutLogin, v)
}

// CanHide reads the NSWindow property canHide.
func (o NSWindow) CanHide() bool {
	return objc.Send[bool](o.ID, selCanHide)
}

// SetCanHide writes the NSWindow property canHide.
func (o NSWindow) SetCanHide(v bool) {
	o.ID.Send(selSetCanHide, v)
}

// CascadingReferenceFrame reads the NSWindow property cascadingReferenceFrame.
func (o NSWindow) CascadingReferenceFrame() CGRect {
	return objc.Send[CGRect](o.ID, selCascadingReferenceFrame)
}

// ChildWindows reads the NSWindow property childWindows.
func (o NSWindow) ChildWindows() NSArray {
	return NSArray{o.ID.Send(selChildWindows)}
}

// ContentAspectRatio reads the NSWindow property contentAspectRatio.
func (o NSWindow) ContentAspectRatio() CGSize {
	return objc.Send[CGSize](o.ID, selContentAspectRatio)
}

// SetContentAspectRatio writes the NSWindow property contentAspectRatio.
func (o NSWindow) SetContentAspectRatio(v CGSize) {
	o.ID.Send(selSetContentAspectRatio, v)
}

// ContentLayoutGuide reads the NSWindow property contentLayoutGuide.
func (o NSWindow) ContentLayoutGuide() objc.ID {
	return o.ID.Send(selContentLayoutGuide)
}

// ContentLayoutRect reads the NSWindow property contentLayoutRect.
func (o NSWindow) ContentLayoutRect() CGRect {
	return objc.Send[CGRect](o.ID, selContentLayoutRect)
}

// ContentMaxSize reads the NSWindow property contentMaxSize.
func (o NSWindow) ContentMaxSize() CGSize {
	return objc.Send[CGSize](o.ID, selContentMaxSize)
}

// SetContentMaxSize writes the NSWindow property contentMaxSize.
func (o NSWindow) SetContentMaxSize(v CGSize) {
	o.ID.Send(selSetContentMaxSize, v)
}

// ContentMinSize reads the NSWindow property contentMinSize.
func (o NSWindow) ContentMinSize() CGSize {
	return objc.Send[CGSize](o.ID, selContentMinSize)
}

// SetContentMinSize writes the NSWindow property contentMinSize.
func (o NSWindow) SetContentMinSize(v CGSize) {
	o.ID.Send(selSetContentMinSize, v)
}

// ContentResizeIncrements reads the NSWindow property contentResizeIncrements.
func (o NSWindow) ContentResizeIncrements() CGSize {
	return objc.Send[CGSize](o.ID, selContentResizeIncrements)
}

// SetContentResizeIncrements writes the NSWindow property contentResizeIncrements.
func (o NSWindow) SetContentResizeIncrements(v CGSize) {
	o.ID.Send(selSetContentResizeIncrements, v)
}

// ContentView reads the NSWindow property contentView.
func (o NSWindow) ContentView() NSView {
	return NSView{o.ID.Send(selContentView)}
}

// SetContentView writes the NSWindow property contentView.
func (o NSWindow) SetContentView(v NSView) {
	o.ID.Send(selSetContentView, v.ID)
}

// DeepestScreen reads the NSWindow property deepestScreen.
func (o NSWindow) DeepestScreen() NSScreen {
	return NSScreen{o.ID.Send(selDeepestScreen)}
}

// Delegate reads the NSWindow property delegate.
func (o NSWindow) Delegate() objc.ID {
	return o.ID.Send(selDelegate)
}

// SetDelegate writes the NSWindow property delegate.
func (o NSWindow) SetDelegate(v objc.ID) {
	o.ID.Send(selSetDelegate, v)
}

// DeviceDescription reads the NSWindow property deviceDescription.
func (o NSWindow) DeviceDescription() NSDictionary {
	return NSDictionary{o.ID.Send(selDeviceDescription)}
}

// DisplaysWhenScreenProfileChanges reads the NSWindow property displaysWhenScreenProfileChanges.
func (o NSWindow) DisplaysWhenScreenProfileChanges() bool {
	return objc.Send[bool](o.ID, selDisplaysWhenScreenProfileChanges)
}

// SetDisplaysWhenScreenProfileChanges writes the NSWindow property displaysWhenScreenProfileChanges.
func (o NSWindow) SetDisplaysWhenScreenProfileChanges(v bool) {
	o.ID.Send(selSetDisplaysWhenScreenProfileChanges, v)
}

// DocumentEdited reads the NSWindow property documentEdited.
func (o NSWindow) DocumentEdited() bool {
	return objc.Send[bool](o.ID, selIsDocumentEdited)
}

// SetDocumentEdited writes the NSWindow property documentEdited.
func (o NSWindow) SetDocumentEdited(v bool) {
	o.ID.Send(selSetDocumentEdited, v)
}

// ExcludedFromWindowsMenu reads the NSWindow property excludedFromWindowsMenu.
func (o NSWindow) ExcludedFromWindowsMenu() bool {
	return objc.Send[bool](o.ID, selIsExcludedFromWindowsMenu)
}

// SetExcludedFromWindowsMenu writes the NSWindow property excludedFromWindowsMenu.
func (o NSWindow) SetExcludedFromWindowsMenu(v bool) {
	o.ID.Send(selSetExcludedFromWindowsMenu, v)
}

// Frame reads the NSWindow property frame.
func (o NSWindow) Frame() CGRect {
	return objc.Send[CGRect](o.ID, selFrame)
}

// FrameAutosaveName reads the NSWindow property frameAutosaveName.
func (o NSWindow) FrameAutosaveName() string {
	return objcrt.GoString(o.ID.Send(selFrameAutosaveName))
}

// HasActiveWindowSharingSession reads the NSWindow property hasActiveWindowSharingSession.
func (o NSWindow) HasActiveWindowSharingSession() bool {
	return objc.Send[bool](o.ID, selHasActiveWindowSharingSession)
}

// HasDynamicDepthLimit reads the NSWindow property hasDynamicDepthLimit.
func (o NSWindow) HasDynamicDepthLimit() bool {
	return objc.Send[bool](o.ID, selHasDynamicDepthLimit)
}

// HasShadow reads the NSWindow property hasShadow.
func (o NSWindow) HasShadow() bool {
	return objc.Send[bool](o.ID, selHasShadow)
}

// SetHasShadow writes the NSWindow property hasShadow.
func (o NSWindow) SetHasShadow(v bool) {
	o.ID.Send(selSetHasShadow, v)
}

// HidesOnDeactivate reads the NSWindow property hidesOnDeactivate.
func (o NSWindow) HidesOnDeactivate() bool {
	return objc.Send[bool](o.ID, selHidesOnDeactivate)
}

// SetHidesOnDeactivate writes the NSWindow property hidesOnDeactivate.
func (o NSWindow) SetHidesOnDeactivate(v bool) {
	o.ID.Send(selSetHidesOnDeactivate, v)
}

// InLiveResize reads the NSWindow property inLiveResize.
func (o NSWindow) InLiveResize() bool {
	return objc.Send[bool](o.ID, selInLiveResize)
}

// InitialFirstResponder reads the NSWindow property initialFirstResponder.
func (o NSWindow) InitialFirstResponder() NSView {
	return NSView{o.ID.Send(selInitialFirstResponder)}
}

// SetInitialFirstResponder writes the NSWindow property initialFirstResponder.
func (o NSWindow) SetInitialFirstResponder(v NSView) {
	o.ID.Send(selSetInitialFirstResponder, v.ID)
}

// KeyWindow reads the NSWindow property keyWindow.
func (o NSWindow) KeyWindow() bool {
	return objc.Send[bool](o.ID, selIsKeyWindow)
}

// Level reads the NSWindow property level.
func (o NSWindow) Level() int {
	return objc.Send[int](o.ID, selLevel)
}

// SetLevel writes the NSWindow property level.
func (o NSWindow) SetLevel(v int) {
	o.ID.Send(selSetLevel, v)
}

// MainWindow reads the NSWindow property mainWindow.
func (o NSWindow) MainWindow() bool {
	return objc.Send[bool](o.ID, selIsMainWindow)
}

// MaxFullScreenContentSize reads the NSWindow property maxFullScreenContentSize.
func (o NSWindow) MaxFullScreenContentSize() CGSize {
	return objc.Send[CGSize](o.ID, selMaxFullScreenContentSize)
}

// SetMaxFullScreenContentSize writes the NSWindow property maxFullScreenContentSize.
func (o NSWindow) SetMaxFullScreenContentSize(v CGSize) {
	o.ID.Send(selSetMaxFullScreenContentSize, v)
}

// MaxSize reads the NSWindow property maxSize.
func (o NSWindow) MaxSize() CGSize {
	return objc.Send[CGSize](o.ID, selMaxSize)
}

// SetMaxSize writes the NSWindow property maxSize.
func (o NSWindow) SetMaxSize(v CGSize) {
	o.ID.Send(selSetMaxSize, v)
}

// MinFullScreenContentSize reads the NSWindow property minFullScreenContentSize.
func (o NSWindow) MinFullScreenContentSize() CGSize {
	return objc.Send[CGSize](o.ID, selMinFullScreenContentSize)
}

// SetMinFullScreenContentSize writes the NSWindow property minFullScreenContentSize.
func (o NSWindow) SetMinFullScreenContentSize(v CGSize) {
	o.ID.Send(selSetMinFullScreenContentSize, v)
}

// MinSize reads the NSWindow property minSize.
func (o NSWindow) MinSize() CGSize {
	return objc.Send[CGSize](o.ID, selMinSize)
}

// SetMinSize writes the NSWindow property minSize.
func (o NSWindow) SetMinSize(v CGSize) {
	o.ID.Send(selSetMinSize, v)
}

// Miniaturized reads the NSWindow property miniaturized.
func (o NSWindow) Miniaturized() bool {
	return objc.Send[bool](o.ID, selIsMiniaturized)
}

// MiniwindowImage reads the NSWindow property miniwindowImage.
func (o NSWindow) MiniwindowImage() NSImage {
	return NSImage{o.ID.Send(selMiniwindowImage)}
}

// SetMiniwindowImage writes the NSWindow property miniwindowImage.
func (o NSWindow) SetMiniwindowImage(v NSImage) {
	o.ID.Send(selSetMiniwindowImage, v.ID)
}

// MiniwindowTitle reads the NSWindow property miniwindowTitle.
func (o NSWindow) MiniwindowTitle() string {
	return objcrt.GoString(o.ID.Send(selMiniwindowTitle))
}

// SetMiniwindowTitle writes the NSWindow property miniwindowTitle.
func (o NSWindow) SetMiniwindowTitle(v string) {
	o.ID.Send(selSetMiniwindowTitle, objcrt.NSString(v))
}

// Movable reads the NSWindow property movable.
func (o NSWindow) Movable() bool {
	return objc.Send[bool](o.ID, selIsMovable)
}

// SetMovable writes the NSWindow property movable.
func (o NSWindow) SetMovable(v bool) {
	o.ID.Send(selSetMovable, v)
}

// MovableByWindowBackground reads the NSWindow property movableByWindowBackground.
func (o NSWindow) MovableByWindowBackground() bool {
	return objc.Send[bool](o.ID, selIsMovableByWindowBackground)
}

// SetMovableByWindowBackground writes the NSWindow property movableByWindowBackground.
func (o NSWindow) SetMovableByWindowBackground(v bool) {
	o.ID.Send(selSetMovableByWindowBackground, v)
}

// OnActiveSpace reads the NSWindow property onActiveSpace.
func (o NSWindow) OnActiveSpace() bool {
	return objc.Send[bool](o.ID, selIsOnActiveSpace)
}

// Opaque reads the NSWindow property opaque.
func (o NSWindow) Opaque() bool {
	return objc.Send[bool](o.ID, selIsOpaque)
}

// SetOpaque writes the NSWindow property opaque.
func (o NSWindow) SetOpaque(v bool) {
	o.ID.Send(selSetOpaque, v)
}

// ParentWindow reads the NSWindow property parentWindow.
func (o NSWindow) ParentWindow() NSWindow {
	return NSWindow{o.ID.Send(selParentWindow)}
}

// SetParentWindow writes the NSWindow property parentWindow.
func (o NSWindow) SetParentWindow(v NSWindow) {
	o.ID.Send(selSetParentWindow, v.ID)
}

// PreservesContentDuringLiveResize reads the NSWindow property preservesContentDuringLiveResize.
func (o NSWindow) PreservesContentDuringLiveResize() bool {
	return objc.Send[bool](o.ID, selPreservesContentDuringLiveResize)
}

// SetPreservesContentDuringLiveResize writes the NSWindow property preservesContentDuringLiveResize.
func (o NSWindow) SetPreservesContentDuringLiveResize(v bool) {
	o.ID.Send(selSetPreservesContentDuringLiveResize, v)
}

// PreventsApplicationTerminationWhenModal reads the NSWindow property preventsApplicationTerminationWhenModal.
func (o NSWindow) PreventsApplicationTerminationWhenModal() bool {
	return objc.Send[bool](o.ID, selPreventsApplicationTerminationWhenModal)
}

// SetPreventsApplicationTerminationWhenModal writes the NSWindow property preventsApplicationTerminationWhenModal.
func (o NSWindow) SetPreventsApplicationTerminationWhenModal(v bool) {
	o.ID.Send(selSetPreventsApplicationTerminationWhenModal, v)
}

// ReleasedWhenClosed reads the NSWindow property releasedWhenClosed.
func (o NSWindow) ReleasedWhenClosed() bool {
	return objc.Send[bool](o.ID, selIsReleasedWhenClosed)
}

// SetReleasedWhenClosed writes the NSWindow property releasedWhenClosed.
func (o NSWindow) SetReleasedWhenClosed(v bool) {
	o.ID.Send(selSetReleasedWhenClosed, v)
}

// RepresentedFilename reads the NSWindow property representedFilename.
func (o NSWindow) RepresentedFilename() string {
	return objcrt.GoString(o.ID.Send(selRepresentedFilename))
}

// SetRepresentedFilename writes the NSWindow property representedFilename.
func (o NSWindow) SetRepresentedFilename(v string) {
	o.ID.Send(selSetRepresentedFilename, objcrt.NSString(v))
}

// ResizeFlags reads the NSWindow property resizeFlags.
func (o NSWindow) ResizeFlags() NSEventModifierFlags {
	return NSEventModifierFlags(objc.Send[uint](o.ID, selResizeFlags))
}

// ResizeIncrements reads the NSWindow property resizeIncrements.
func (o NSWindow) ResizeIncrements() CGSize {
	return objc.Send[CGSize](o.ID, selResizeIncrements)
}

// SetResizeIncrements writes the NSWindow property resizeIncrements.
func (o NSWindow) SetResizeIncrements(v CGSize) {
	o.ID.Send(selSetResizeIncrements, v)
}

// Screen reads the NSWindow property screen.
func (o NSWindow) Screen() NSScreen {
	return NSScreen{o.ID.Send(selScreen)}
}

// Sheet reads the NSWindow property sheet.
func (o NSWindow) Sheet() bool {
	return objc.Send[bool](o.ID, selIsSheet)
}

// SheetParent reads the NSWindow property sheetParent.
func (o NSWindow) SheetParent() NSWindow {
	return NSWindow{o.ID.Send(selSheetParent)}
}

// Sheets reads the NSWindow property sheets.
func (o NSWindow) Sheets() NSArray {
	return NSArray{o.ID.Send(selSheets)}
}

// ShowsToolbarButton reads the NSWindow property showsToolbarButton.
func (o NSWindow) ShowsToolbarButton() bool {
	return objc.Send[bool](o.ID, selShowsToolbarButton)
}

// SetShowsToolbarButton writes the NSWindow property showsToolbarButton.
func (o NSWindow) SetShowsToolbarButton(v bool) {
	o.ID.Send(selSetShowsToolbarButton, v)
}

// StringWithSavedFrame reads the NSWindow property stringWithSavedFrame.
func (o NSWindow) StringWithSavedFrame() string {
	return objcrt.GoString(o.ID.Send(selStringWithSavedFrame))
}

// StyleMask reads the NSWindow property styleMask.
func (o NSWindow) StyleMask() NSWindowStyleMask {
	return NSWindowStyleMask(objc.Send[uint](o.ID, selStyleMask))
}

// SetStyleMask writes the NSWindow property styleMask.
func (o NSWindow) SetStyleMask(v NSWindowStyleMask) {
	o.ID.Send(selSetStyleMask, uint(v))
}

// Subtitle reads the NSWindow property subtitle.
func (o NSWindow) Subtitle() string {
	return objcrt.GoString(o.ID.Send(selSubtitle))
}

// SetSubtitle writes the NSWindow property subtitle.
func (o NSWindow) SetSubtitle(v string) {
	o.ID.Send(selSetSubtitle, objcrt.NSString(v))
}

// TabbedWindows reads the NSWindow property tabbedWindows.
func (o NSWindow) TabbedWindows() NSArray {
	return NSArray{o.ID.Send(selTabbedWindows)}
}

// TabbingIdentifier reads the NSWindow property tabbingIdentifier.
func (o NSWindow) TabbingIdentifier() string {
	return objcrt.GoString(o.ID.Send(selTabbingIdentifier))
}

// SetTabbingIdentifier writes the NSWindow property tabbingIdentifier.
func (o NSWindow) SetTabbingIdentifier(v string) {
	o.ID.Send(selSetTabbingIdentifier, objcrt.NSString(v))
}

// Title reads the NSWindow property title.
func (o NSWindow) Title() string {
	return objcrt.GoString(o.ID.Send(selTitle))
}

// SetTitle writes the NSWindow property title.
func (o NSWindow) SetTitle(v string) {
	o.ID.Send(selSetTitle, objcrt.NSString(v))
}

// TitlebarAccessoryViewControllers reads the NSWindow property titlebarAccessoryViewControllers.
func (o NSWindow) TitlebarAccessoryViewControllers() NSArray {
	return NSArray{o.ID.Send(selTitlebarAccessoryViewControllers)}
}

// SetTitlebarAccessoryViewControllers writes the NSWindow property titlebarAccessoryViewControllers.
func (o NSWindow) SetTitlebarAccessoryViewControllers(v NSArray) {
	o.ID.Send(selSetTitlebarAccessoryViewControllers, v.ID)
}

// TitlebarAppearsTransparent reads the NSWindow property titlebarAppearsTransparent.
func (o NSWindow) TitlebarAppearsTransparent() bool {
	return objc.Send[bool](o.ID, selTitlebarAppearsTransparent)
}

// SetTitlebarAppearsTransparent writes the NSWindow property titlebarAppearsTransparent.
func (o NSWindow) SetTitlebarAppearsTransparent(v bool) {
	o.ID.Send(selSetTitlebarAppearsTransparent, v)
}

// ViewsNeedDisplay reads the NSWindow property viewsNeedDisplay.
func (o NSWindow) ViewsNeedDisplay() bool {
	return objc.Send[bool](o.ID, selViewsNeedDisplay)
}

// SetViewsNeedDisplay writes the NSWindow property viewsNeedDisplay.
func (o NSWindow) SetViewsNeedDisplay(v bool) {
	o.ID.Send(selSetViewsNeedDisplay, v)
}

// Visible reads the NSWindow property visible.
func (o NSWindow) Visible() bool {
	return objc.Send[bool](o.ID, selIsVisible)
}

// WindowNumber reads the NSWindow property windowNumber.
func (o NSWindow) WindowNumber() int {
	return objc.Send[int](o.ID, selWindowNumber)
}

// WorksWhenModal reads the NSWindow property worksWhenModal.
func (o NSWindow) WorksWhenModal() bool {
	return objc.Send[bool](o.ID, selWorksWhenModal)
}

// Zoomed reads the NSWindow property zoomed.
func (o NSWindow) Zoomed() bool {
	return objc.Send[bool](o.ID, selIsZoomed)
}

// AllowsAutomaticWindowTabbing reads the NSWindow class property allowsAutomaticWindowTabbing.
func (c NSWindowClass) AllowsAutomaticWindowTabbing() bool {
	return objc.Send[bool](objc.ID(c.Class), selAllowsAutomaticWindowTabbing)
}

// SetAllowsAutomaticWindowTabbing writes the NSWindow class property allowsAutomaticWindowTabbing.
func (c NSWindowClass) SetAllowsAutomaticWindowTabbing(v bool) {
	objc.ID(c.Class).Send(selSetAllowsAutomaticWindowTabbing, v)
}

// AddChildWindowOrdered calls -[NSWindow addChildWindow:ordered:].
func (o NSWindow) AddChildWindowOrdered(childWin NSWindow, place NSWindowOrderingMode) {
	o.ID.Send(selAddChildWindowOrdered, childWin.ID, int(place))
}

// AddTabbedWindowOrdered calls -[NSWindow addTabbedWindow:ordered:].
func (o NSWindow) AddTabbedWindowOrdered(window NSWindow, ordered NSWindowOrderingMode) {
	o.ID.Send(selAddTabbedWindowOrdered, window.ID, int(ordered))
}

// AnimationResizeTime calls -[NSWindow animationResizeTime:].
func (o NSWindow) AnimationResizeTime(newFrame CGRect) float64 {
	return objc.Send[float64](o.ID, selAnimationResizeTime, newFrame)
}

// BecomeKeyWindow calls -[NSWindow becomeKeyWindow].
func (o NSWindow) BecomeKeyWindow() {
	o.ID.Send(selBecomeKeyWindow)
}

// BecomeMainWindow calls -[NSWindow becomeMainWindow].
func (o NSWindow) BecomeMainWindow() {
	o.ID.Send(selBecomeMainWindow)
}

// CacheImageInRect calls -[NSWindow cacheImageInRect:].
func (o NSWindow) CacheImageInRect(rect CGRect) {
	o.ID.Send(selCacheImageInRect, rect)
}

// CanStoreColor calls -[NSWindow canStoreColor].
func (o NSWindow) CanStoreColor() bool {
	return objc.Send[bool](o.ID, selCanStoreColor)
}

// CascadeTopLeftFromPoint calls -[NSWindow cascadeTopLeftFromPoint:].
func (o NSWindow) CascadeTopLeftFromPoint(topLeftPoint CGPoint) CGPoint {
	return objc.Send[CGPoint](o.ID, selCascadeTopLeftFromPoint, topLeftPoint)
}

// Center calls -[NSWindow center].
func (o NSWindow) Center() {
	o.ID.Send(selCenter)
}

// Close calls -[NSWindow close].
func (o NSWindow) Close() {
	o.ID.Send(selClose)
}

// ConstrainFrameRectToScreen calls -[NSWindow constrainFrameRect:toScreen:].
func (o NSWindow) ConstrainFrameRectToScreen(frameRect CGRect, screen NSScreen) CGRect {
	return objc.Send[CGRect](o.ID, selConstrainFrameRectToScreen, frameRect, screen.ID)
}

// ContentRectForFrameRect calls -[NSWindow contentRectForFrameRect:].
func (o NSWindow) ContentRectForFrameRect(frameRect CGRect) CGRect {
	return objc.Send[CGRect](o.ID, selContentRectForFrameRect, frameRect)
}

// ConvertBaseToScreen calls -[NSWindow convertBaseToScreen:].
func (o NSWindow) ConvertBaseToScreen(point CGPoint) CGPoint {
	return objc.Send[CGPoint](o.ID, selConvertBaseToScreen, point)
}

// ConvertPointFromBacking calls -[NSWindow convertPointFromBacking:].
func (o NSWindow) ConvertPointFromBacking(point CGPoint) CGPoint {
	return objc.Send[CGPoint](o.ID, selConvertPointFromBacking, point)
}

// ConvertPointFromScreen calls -[NSWindow convertPointFromScreen:].
func (o NSWindow) ConvertPointFromScreen(point CGPoint) CGPoint {
	return objc.Send[CGPoint](o.ID, selConvertPointFromScreen, point)
}

// ConvertPointToBacking calls -[NSWindow convertPointToBacking:].
func (o NSWindow) ConvertPointToBacking(point CGPoint) CGPoint {
	return objc.Send[CGPoint](o.ID, selConvertPointToBacking, point)
}

// ConvertPointToScreen calls -[NSWindow convertPointToScreen:].
func (o NSWindow) ConvertPointToScreen(point CGPoint) CGPoint {
	return objc.Send[CGPoint](o.ID, selConvertPointToScreen, point)
}

// ConvertRectFromBacking calls -[NSWindow convertRectFromBacking:].
func (o NSWindow) ConvertRectFromBacking(rect CGRect) CGRect {
	return objc.Send[CGRect](o.ID, selConvertRectFromBacking, rect)
}

// ConvertRectFromScreen calls -[NSWindow convertRectFromScreen:].
func (o NSWindow) ConvertRectFromScreen(rect CGRect) CGRect {
	return objc.Send[CGRect](o.ID, selConvertRectFromScreen, rect)
}

// ConvertRectToBacking calls -[NSWindow convertRectToBacking:].
func (o NSWindow) ConvertRectToBacking(rect CGRect) CGRect {
	return objc.Send[CGRect](o.ID, selConvertRectToBacking, rect)
}

// ConvertRectToScreen calls -[NSWindow convertRectToScreen:].
func (o NSWindow) ConvertRectToScreen(rect CGRect) CGRect {
	return objc.Send[CGRect](o.ID, selConvertRectToScreen, rect)
}

// ConvertScreenToBase calls -[NSWindow convertScreenToBase:].
func (o NSWindow) ConvertScreenToBase(point CGPoint) CGPoint {
	return objc.Send[CGPoint](o.ID, selConvertScreenToBase, point)
}

// DataWithEPSInsideRect calls -[NSWindow dataWithEPSInsideRect:].
func (o NSWindow) DataWithEPSInsideRect(rect CGRect) NSData {
	return NSData{o.ID.Send(selDataWithEPSInsideRect, rect)}
}

// DataWithPDFInsideRect calls -[NSWindow dataWithPDFInsideRect:].
func (o NSWindow) DataWithPDFInsideRect(rect CGRect) NSData {
	return NSData{o.ID.Send(selDataWithPDFInsideRect, rect)}
}

// Deminiaturize calls -[NSWindow deminiaturize:].
func (o NSWindow) Deminiaturize(sender objc.ID) {
	o.ID.Send(selDeminiaturize, sender)
}

// DisableCursorRects calls -[NSWindow disableCursorRects].
func (o NSWindow) DisableCursorRects() {
	o.ID.Send(selDisableCursorRects)
}

// DisableFlushWindow calls -[NSWindow disableFlushWindow].
func (o NSWindow) DisableFlushWindow() {
	o.ID.Send(selDisableFlushWindow)
}

// DisableKeyEquivalentForDefaultButtonCell calls -[NSWindow disableKeyEquivalentForDefaultButtonCell].
func (o NSWindow) DisableKeyEquivalentForDefaultButtonCell() {
	o.ID.Send(selDisableKeyEquivalentForDefaultButtonCell)
}

// DisableScreenUpdatesUntilFlush calls -[NSWindow disableScreenUpdatesUntilFlush].
func (o NSWindow) DisableScreenUpdatesUntilFlush() {
	o.ID.Send(selDisableScreenUpdatesUntilFlush)
}

// DisableSnapshotRestoration — Disable or enable snapshot restoration. While snapshot restoration is disabled, the window will not be snapshotted for restorable state.
func (o NSWindow) DisableSnapshotRestoration() {
	o.ID.Send(selDisableSnapshotRestoration)
}

// DiscardCachedImage calls -[NSWindow discardCachedImage].
func (o NSWindow) DiscardCachedImage() {
	o.ID.Send(selDiscardCachedImage)
}

// DiscardCursorRects calls -[NSWindow discardCursorRects].
func (o NSWindow) DiscardCursorRects() {
	o.ID.Send(selDiscardCursorRects)
}

// Display calls -[NSWindow display].
func (o NSWindow) Display() {
	o.ID.Send(selDisplay)
}

// DisplayIfNeeded calls -[NSWindow displayIfNeeded].
func (o NSWindow) DisplayIfNeeded() {
	o.ID.Send(selDisplayIfNeeded)
}

// EnableCursorRects calls -[NSWindow enableCursorRects].
func (o NSWindow) EnableCursorRects() {
	o.ID.Send(selEnableCursorRects)
}

// EnableFlushWindow calls -[NSWindow enableFlushWindow].
func (o NSWindow) EnableFlushWindow() {
	o.ID.Send(selEnableFlushWindow)
}

// EnableKeyEquivalentForDefaultButtonCell calls -[NSWindow enableKeyEquivalentForDefaultButtonCell].
func (o NSWindow) EnableKeyEquivalentForDefaultButtonCell() {
	o.ID.Send(selEnableKeyEquivalentForDefaultButtonCell)
}

// EnableSnapshotRestoration calls -[NSWindow enableSnapshotRestoration].
func (o NSWindow) EnableSnapshotRestoration() {
	o.ID.Send(selEnableSnapshotRestoration)
}

// EndEditingFor calls -[NSWindow endEditingFor:].
func (o NSWindow) EndEditingFor(object objc.ID) {
	o.ID.Send(selEndEditingFor, object)
}

// EndSheet calls -[NSWindow endSheet:].
func (o NSWindow) EndSheet(sheetWindow NSWindow) {
	o.ID.Send(selEndSheet, sheetWindow.ID)
}

// EndSheetReturnCode calls -[NSWindow endSheet:returnCode:].
func (o NSWindow) EndSheetReturnCode(sheetWindow NSWindow, returnCode int) {
	o.ID.Send(selEndSheetReturnCode, sheetWindow.ID, returnCode)
}

// FlushWindow calls -[NSWindow flushWindow].
func (o NSWindow) FlushWindow() {
	o.ID.Send(selFlushWindow)
}

// FlushWindowIfNeeded calls -[NSWindow flushWindowIfNeeded].
func (o NSWindow) FlushWindowIfNeeded() {
	o.ID.Send(selFlushWindowIfNeeded)
}

// FrameRectForContentRect calls -[NSWindow frameRectForContentRect:].
func (o NSWindow) FrameRectForContentRect(contentRect CGRect) CGRect {
	return objc.Send[CGRect](o.ID, selFrameRectForContentRect, contentRect)
}

// GState calls -[NSWindow gState].
func (o NSWindow) GState() int {
	return objc.Send[int](o.ID, selGState)
}

// InitWithContentRectStyleMaskBackingDefer calls -[NSWindow initWithContentRect:styleMask:backing:defer:].
func (o NSWindow) InitWithContentRectStyleMaskBackingDefer(contentRect CGRect, style NSWindowStyleMask, backingStoreType NSBackingStoreType, flag bool) NSWindow {
	return NSWindow{o.ID.Send(selInitWithContentRectStyleMaskBackingDefer, contentRect, uint(style), uint(backingStoreType), flag)}
}

// InitWithContentRectStyleMaskBackingDeferScreen calls -[NSWindow initWithContentRect:styleMask:backing:defer:screen:].
func (o NSWindow) InitWithContentRectStyleMaskBackingDeferScreen(contentRect CGRect, style NSWindowStyleMask, backingStoreType NSBackingStoreType, flag bool, screen NSScreen) NSWindow {
	return NSWindow{o.ID.Send(selInitWithContentRectStyleMaskBackingDeferScreen, contentRect, uint(style), uint(backingStoreType), flag, screen.ID)}
}

// InvalidateCursorRectsForView calls -[NSWindow invalidateCursorRectsForView:].
func (o NSWindow) InvalidateCursorRectsForView(view NSView) {
	o.ID.Send(selInvalidateCursorRectsForView, view.ID)
}

// InvalidateShadow calls -[NSWindow invalidateShadow].
func (o NSWindow) InvalidateShadow() {
	o.ID.Send(selInvalidateShadow)
}

// LayoutIfNeeded calls -[NSWindow layoutIfNeeded].
func (o NSWindow) LayoutIfNeeded() {
	o.ID.Send(selLayoutIfNeeded)
}

// MakeKeyAndOrderFront calls -[NSWindow makeKeyAndOrderFront:].
func (o NSWindow) MakeKeyAndOrderFront(sender objc.ID) {
	o.ID.Send(selMakeKeyAndOrderFront, sender)
}

// MakeKeyWindow calls -[NSWindow makeKeyWindow].
func (o NSWindow) MakeKeyWindow() {
	o.ID.Send(selMakeKeyWindow)
}

// MakeMainWindow calls -[NSWindow makeMainWindow].
func (o NSWindow) MakeMainWindow() {
	o.ID.Send(selMakeMainWindow)
}

// MergeAllWindows calls -[NSWindow mergeAllWindows:].
func (o NSWindow) MergeAllWindows(sender objc.ID) {
	o.ID.Send(selMergeAllWindows, sender)
}

// Miniaturize calls -[NSWindow miniaturize:].
func (o NSWindow) Miniaturize(sender objc.ID) {
	o.ID.Send(selMiniaturize, sender)
}

// MoveTabToNewWindow calls -[NSWindow moveTabToNewWindow:].
func (o NSWindow) MoveTabToNewWindow(sender objc.ID) {
	o.ID.Send(selMoveTabToNewWindow, sender)
}

// OrderBack calls -[NSWindow orderBack:].
func (o NSWindow) OrderBack(sender objc.ID) {
	o.ID.Send(selOrderBack, sender)
}

// OrderFront calls -[NSWindow orderFront:].
func (o NSWindow) OrderFront(sender objc.ID) {
	o.ID.Send(selOrderFront, sender)
}

// OrderFrontRegardless calls -[NSWindow orderFrontRegardless].
func (o NSWindow) OrderFrontRegardless() {
	o.ID.Send(selOrderFrontRegardless)
}

// OrderOut calls -[NSWindow orderOut:].
func (o NSWindow) OrderOut(sender objc.ID) {
	o.ID.Send(selOrderOut, sender)
}

// OrderWindowRelativeTo calls -[NSWindow orderWindow:relativeTo:].
func (o NSWindow) OrderWindowRelativeTo(place NSWindowOrderingMode, otherWin int) {
	o.ID.Send(selOrderWindowRelativeTo, int(place), otherWin)
}

// PerformClose calls -[NSWindow performClose:].
func (o NSWindow) PerformClose(sender objc.ID) {
	o.ID.Send(selPerformClose, sender)
}

// PerformMiniaturize calls -[NSWindow performMiniaturize:].
func (o NSWindow) PerformMiniaturize(sender objc.ID) {
	o.ID.Send(selPerformMiniaturize, sender)
}

// PerformWindowDragWithEvent calls -[NSWindow performWindowDragWithEvent:].
func (o NSWindow) PerformWindowDragWithEvent(event NSEvent) {
	o.ID.Send(selPerformWindowDragWithEvent, event.ID)
}

// PerformZoom calls -[NSWindow performZoom:].
func (o NSWindow) PerformZoom(sender objc.ID) {
	o.ID.Send(selPerformZoom, sender)
}

// PostEventAtStart calls -[NSWindow postEvent:atStart:].
func (o NSWindow) PostEventAtStart(event NSEvent, flag bool) {
	o.ID.Send(selPostEventAtStart, event.ID, flag)
}

// Print calls -[NSWindow print:].
func (o NSWindow) Print(sender objc.ID) {
	o.ID.Send(selPrint, sender)
}

// RecalculateKeyViewLoop calls -[NSWindow recalculateKeyViewLoop].
func (o NSWindow) RecalculateKeyViewLoop() {
	o.ID.Send(selRecalculateKeyViewLoop)
}

// RegisterForDraggedTypes calls -[NSWindow registerForDraggedTypes:].
func (o NSWindow) RegisterForDraggedTypes(newTypes NSArray) {
	o.ID.Send(selRegisterForDraggedTypes, newTypes.ID)
}

// RemoveChildWindow calls -[NSWindow removeChildWindow:].
func (o NSWindow) RemoveChildWindow(childWin NSWindow) {
	o.ID.Send(selRemoveChildWindow, childWin.ID)
}

// RemoveTitlebarAccessoryViewControllerAtIndex calls -[NSWindow removeTitlebarAccessoryViewControllerAtIndex:].
func (o NSWindow) RemoveTitlebarAccessoryViewControllerAtIndex(index int) {
	o.ID.Send(selRemoveTitlebarAccessoryViewControllerAtIndex, index)
}

// RequestSharingOfWindowCompletionHandler calls -[NSWindow requestSharingOfWindow:completionHandler:].
func (o NSWindow) RequestSharingOfWindowCompletionHandler(window NSWindow, completionHandler func(error)) {
	blockCompletionHandler := objc.NewBlock(func(_ objc.Block, a0 objc.ID) {
		completionHandler(objcrt.GoError(a0))
	})
	defer blockCompletionHandler.Release()
	o.ID.Send(selRequestSharingOfWindowCompletionHandler, window.ID, blockCompletionHandler)
}

// RequestSharingOfWindowUsingPreviewTitleCompletionHandler calls -[NSWindow requestSharingOfWindowUsingPreview:title:completionHandler:].
func (o NSWindow) RequestSharingOfWindowUsingPreviewTitleCompletionHandler(image NSImage, title string, completionHandler func(error)) {
	blockCompletionHandler := objc.NewBlock(func(_ objc.Block, a0 objc.ID) {
		completionHandler(objcrt.GoError(a0))
	})
	defer blockCompletionHandler.Release()
	o.ID.Send(selRequestSharingOfWindowUsingPreviewTitleCompletionHandler, image.ID, objcrt.NSString(title), blockCompletionHandler)
}

// ResetCursorRects calls -[NSWindow resetCursorRects].
func (o NSWindow) ResetCursorRects() {
	o.ID.Send(selResetCursorRects)
}

// ResignKeyWindow calls -[NSWindow resignKeyWindow].
func (o NSWindow) ResignKeyWindow() {
	o.ID.Send(selResignKeyWindow)
}

// ResignMainWindow calls -[NSWindow resignMainWindow].
func (o NSWindow) ResignMainWindow() {
	o.ID.Send(selResignMainWindow)
}

// RestoreCachedImage calls -[NSWindow restoreCachedImage].
func (o NSWindow) RestoreCachedImage() {
	o.ID.Send(selRestoreCachedImage)
}

// RunToolbarCustomizationPalette calls -[NSWindow runToolbarCustomizationPalette:].
func (o NSWindow) RunToolbarCustomizationPalette(sender objc.ID) {
	o.ID.Send(selRunToolbarCustomizationPalette, sender)
}

// SaveFrameUsingName calls -[NSWindow saveFrameUsingName:].
func (o NSWindow) SaveFrameUsingName(name string) {
	o.ID.Send(selSaveFrameUsingName, objcrt.NSString(name))
}

// SelectKeyViewFollowingView calls -[NSWindow selectKeyViewFollowingView:].
func (o NSWindow) SelectKeyViewFollowingView(view NSView) {
	o.ID.Send(selSelectKeyViewFollowingView, view.ID)
}

// SelectKeyViewPrecedingView calls -[NSWindow selectKeyViewPrecedingView:].
func (o NSWindow) SelectKeyViewPrecedingView(view NSView) {
	o.ID.Send(selSelectKeyViewPrecedingView, view.ID)
}

// SelectNextKeyView calls -[NSWindow selectNextKeyView:].
func (o NSWindow) SelectNextKeyView(sender objc.ID) {
	o.ID.Send(selSelectNextKeyView, sender)
}

// SelectNextTab calls -[NSWindow selectNextTab:].
func (o NSWindow) SelectNextTab(sender objc.ID) {
	o.ID.Send(selSelectNextTab, sender)
}

// SelectPreviousKeyView calls -[NSWindow selectPreviousKeyView:].
func (o NSWindow) SelectPreviousKeyView(sender objc.ID) {
	o.ID.Send(selSelectPreviousKeyView, sender)
}

// SelectPreviousTab calls -[NSWindow selectPreviousTab:].
func (o NSWindow) SelectPreviousTab(sender objc.ID) {
	o.ID.Send(selSelectPreviousTab, sender)
}

// SendEvent calls -[NSWindow sendEvent:].
func (o NSWindow) SendEvent(event NSEvent) {
	o.ID.Send(selSendEvent, event.ID)
}

// SetContentSize calls -[NSWindow setContentSize:].
func (o NSWindow) SetContentSize(size CGSize) {
	o.ID.Send(selSetContentSize, size)
}

// SetDynamicDepthLimit calls -[NSWindow setDynamicDepthLimit:].
func (o NSWindow) SetDynamicDepthLimit(flag bool) {
	o.ID.Send(selSetDynamicDepthLimit, flag)
}

// SetFrameDisplay calls -[NSWindow setFrame:display:].
func (o NSWindow) SetFrameDisplay(frameRect CGRect, flag bool) {
	o.ID.Send(selSetFrameDisplay, frameRect, flag)
}

// SetFrameDisplayAnimate calls -[NSWindow setFrame:display:animate:].
func (o NSWindow) SetFrameDisplayAnimate(frameRect CGRect, displayFlag bool, animateFlag bool) {
	o.ID.Send(selSetFrameDisplayAnimate, frameRect, displayFlag, animateFlag)
}

// SetFrameAutosaveName calls -[NSWindow setFrameAutosaveName:].
func (o NSWindow) SetFrameAutosaveName(name string) bool {
	return objc.Send[bool](o.ID, selSetFrameAutosaveName, objcrt.NSString(name))
}

// SetFrameFromString calls -[NSWindow setFrameFromString:].
func (o NSWindow) SetFrameFromString(string_ string) {
	o.ID.Send(selSetFrameFromString, objcrt.NSString(string_))
}

// SetFrameOrigin calls -[NSWindow setFrameOrigin:].
func (o NSWindow) SetFrameOrigin(point CGPoint) {
	o.ID.Send(selSetFrameOrigin, point)
}

// SetFrameTopLeftPoint calls -[NSWindow setFrameTopLeftPoint:].
func (o NSWindow) SetFrameTopLeftPoint(point CGPoint) {
	o.ID.Send(selSetFrameTopLeftPoint, point)
}

// SetFrameUsingName calls -[NSWindow setFrameUsingName:].
func (o NSWindow) SetFrameUsingName(name string) bool {
	return objc.Send[bool](o.ID, selSetFrameUsingName, objcrt.NSString(name))
}

// SetFrameUsingNameForce calls -[NSWindow setFrameUsingName:force:].
func (o NSWindow) SetFrameUsingNameForce(name string, force bool) bool {
	return objc.Send[bool](o.ID, selSetFrameUsingNameForce, objcrt.NSString(name), force)
}

// SetIsMiniaturized calls -[NSWindow setIsMiniaturized:].
func (o NSWindow) SetIsMiniaturized(flag bool) {
	o.ID.Send(selSetIsMiniaturized, flag)
}

// SetIsVisible calls -[NSWindow setIsVisible:].
func (o NSWindow) SetIsVisible(flag bool) {
	o.ID.Send(selSetIsVisible, flag)
}

// SetIsZoomed calls -[NSWindow setIsZoomed:].
func (o NSWindow) SetIsZoomed(flag bool) {
	o.ID.Send(selSetIsZoomed, flag)
}

// SetTitleWithRepresentedFilename calls -[NSWindow setTitleWithRepresentedFilename:].
func (o NSWindow) SetTitleWithRepresentedFilename(filename string) {
	o.ID.Send(selSetTitleWithRepresentedFilename, objcrt.NSString(filename))
}

// ToggleFullScreen calls -[NSWindow toggleFullScreen:].
func (o NSWindow) ToggleFullScreen(sender objc.ID) {
	o.ID.Send(selToggleFullScreen, sender)
}

// ToggleTabBar calls -[NSWindow toggleTabBar:].
func (o NSWindow) ToggleTabBar(sender objc.ID) {
	o.ID.Send(selToggleTabBar, sender)
}

// ToggleTabOverview calls -[NSWindow toggleTabOverview:].
func (o NSWindow) ToggleTabOverview(sender objc.ID) {
	o.ID.Send(selToggleTabOverview, sender)
}

// ToggleToolbarShown calls -[NSWindow toggleToolbarShown:].
func (o NSWindow) ToggleToolbarShown(sender objc.ID) {
	o.ID.Send(selToggleToolbarShown, sender)
}

// TransferWindowSharingToWindowCompletionHandler calls -[NSWindow transferWindowSharingToWindow:completionHandler:].
func (o NSWindow) TransferWindowSharingToWindowCompletionHandler(window NSWindow, completionHandler func(error)) {
	blockCompletionHandler := objc.NewBlock(func(_ objc.Block, a0 objc.ID) {
		completionHandler(objcrt.GoError(a0))
	})
	defer blockCompletionHandler.Release()
	o.ID.Send(selTransferWindowSharingToWindowCompletionHandler, window.ID, blockCompletionHandler)
}

// TryToPerformWith calls -[NSWindow tryToPerform:with:].
func (o NSWindow) TryToPerformWith(action objc.SEL, object objc.ID) bool {
	return objc.Send[bool](o.ID, selTryToPerformWith, action, object)
}

// UnregisterDraggedTypes calls -[NSWindow unregisterDraggedTypes].
func (o NSWindow) UnregisterDraggedTypes() {
	o.ID.Send(selUnregisterDraggedTypes)
}

// Update calls -[NSWindow update].
func (o NSWindow) Update() {
	o.ID.Send(selUpdate)
}

// UpdateConstraintsIfNeeded calls -[NSWindow updateConstraintsIfNeeded].
func (o NSWindow) UpdateConstraintsIfNeeded() {
	o.ID.Send(selUpdateConstraintsIfNeeded)
}

// UseOptimizedDrawing calls -[NSWindow useOptimizedDrawing:].
func (o NSWindow) UseOptimizedDrawing(flag bool) {
	o.ID.Send(selUseOptimizedDrawing, flag)
}

// UserSpaceScaleFactor calls -[NSWindow userSpaceScaleFactor].
func (o NSWindow) UserSpaceScaleFactor() float64 {
	return objc.Send[float64](o.ID, selUserSpaceScaleFactor)
}

// ValidRequestorForSendTypeReturnType calls -[NSWindow validRequestorForSendType:returnType:].
func (o NSWindow) ValidRequestorForSendTypeReturnType(sendType string, returnType string) objc.ID {
	return o.ID.Send(selValidRequestorForSendTypeReturnType, objcrt.NSString(sendType), objcrt.NSString(returnType))
}

// VisualizeConstraints calls -[NSWindow visualizeConstraints:].
func (o NSWindow) VisualizeConstraints(constraints NSArray) {
	o.ID.Send(selVisualizeConstraints, constraints.ID)
}

// Zoom calls -[NSWindow zoom:].
func (o NSWindow) Zoom(sender objc.ID) {
	o.ID.Send(selZoom, sender)
}

// ContentRectForFrameRectStyleMask calls +[NSWindow contentRectForFrameRect:styleMask:].
func (c NSWindowClass) ContentRectForFrameRectStyleMask(fRect CGRect, style NSWindowStyleMask) CGRect {
	return objc.Send[CGRect](objc.ID(c.Class), selContentRectForFrameRectStyleMask, fRect, uint(style))
}

// FrameRectForContentRectStyleMask calls +[NSWindow frameRectForContentRect:styleMask:].
func (c NSWindowClass) FrameRectForContentRectStyleMask(cRect CGRect, style NSWindowStyleMask) CGRect {
	return objc.Send[CGRect](objc.ID(c.Class), selFrameRectForContentRectStyleMask, cRect, uint(style))
}

// MinFrameWidthWithTitleStyleMask calls +[NSWindow minFrameWidthWithTitle:styleMask:].
func (c NSWindowClass) MinFrameWidthWithTitleStyleMask(title string, style NSWindowStyleMask) float64 {
	return objc.Send[float64](objc.ID(c.Class), selMinFrameWidthWithTitleStyleMask, objcrt.NSString(title), uint(style))
}

// RemoveFrameUsingName calls +[NSWindow removeFrameUsingName:].
func (c NSWindowClass) RemoveFrameUsingName(name string) {
	objc.ID(c.Class).Send(selRemoveFrameUsingName, objcrt.NSString(name))
}

// WindowNumberAtPointBelowWindowWithWindowNumber calls +[NSWindow windowNumberAtPoint:belowWindowWithWindowNumber:].
func (c NSWindowClass) WindowNumberAtPointBelowWindowWithWindowNumber(point CGPoint, windowNumber int) int {
	return objc.Send[int](objc.ID(c.Class), selWindowNumberAtPointBelowWindowWithWindowNumber, point, windowNumber)
}
