// Code generated by tools/bindgen. DO NOT EDIT.
//
// Source: MacOSX26.2.sdk (Xcode 26.2), target arm64-apple-macos26.0
// Frameworks: Foundation, AppKit
//
// Regenerate with: tools/bindgen/regen.sh

//go:build darwin

package appkit

// CGPoint — Points.
type CGPoint struct {
	X float64
	Y float64
}

// CGRect — Rectangles.
type CGRect struct {
	Origin CGPoint
	Size   CGSize
}

// CGSize — Sizes.
type CGSize struct {
	Width  float64
	Height float64
}
