// Code generated by tools/bindgen. DO NOT EDIT.
//
// Source: iPhoneSimulator26.2.sdk (Xcode 26.2), target arm64-apple-ios26.2-simulator
// Frameworks: Foundation, UIKit, AVFAudio, PushToTalk
//
// Regenerate with: tools/bindgen/regen.sh

//go:build darwin

package appleptt

import "github.com/ebitengine/purego/objc"

// AVAudioSession an opaque handle for the ObjC class AVAudioSession (NSObject subclass).
// Only the identity crosses: no method of AVAudioSession is on the allowlist.
type AVAudioSession struct{ objc.ID }

// AVAudioSessionClass is the class object of AVAudioSession.
type AVAudioSessionClass struct{ objc.Class }

// GetAVAudioSessionClass looks the class up in the ObjC runtime.
func GetAVAudioSessionClass() AVAudioSessionClass {
	return AVAudioSessionClass{objc.GetClass("AVAudioSession")}
}
