// Code generated by tools/bindgen. DO NOT EDIT.
//
// Source: iPhoneSimulator26.2.sdk (Xcode 26.2), target arm64-apple-ios26.2-simulator
// Frameworks: Foundation, UIKit, AVFAudio, PushToTalk
//
// Regenerate with: tools/bindgen/regen.sh

//go:build darwin

package appleptt

import "github.com/adriaanm/wata/go-pkgs/appleptt/objcrt"

// IncomingBlockVoid is an ObjC block received by a callback, copied
// (_Block_copy) so it can be invoked after the callback returns — from any
// goroutine. Release it exactly once when done: a second Release, or a Call
// after Release, panics. Call may repeat while the handle is live.
type IncomingBlockVoid struct{ h *objcrt.BlockHandle }

// Call invokes the block through its own invoke pointer.
func (b IncomingBlockVoid) Call() { b.h.Invoke() }

// Release frees the copied block (_Block_release).
func (b IncomingBlockVoid) Release() { b.h.Release() }
