// Code generated by tools/bindgen. DO NOT EDIT.
//
// Source: iPhoneSimulator26.2.sdk (Xcode 26.2), target arm64-apple-ios26.2-simulator
// Frameworks: Foundation, UIKit, AVFAudio, PushToTalk
//
// Regenerate with: tools/bindgen/regen.sh

//go:build darwin

package appleptt

import "github.com/ebitengine/purego/objc"

// NSData — Immutable Data		***************
// Only the identity crosses: no method of NSData is on the allowlist.
type NSData struct{ objc.ID }

// NSDataClass is the class object of NSData.
type NSDataClass struct{ objc.Class }

// GetNSDataClass looks the class up in the ObjC runtime.
func GetNSDataClass() NSDataClass { return NSDataClass{objc.GetClass("NSData")} }
