// Code generated by tools/bindgen. DO NOT EDIT.
//
// Source: iPhoneSimulator26.2.sdk (Xcode 26.2), target arm64-apple-ios26.2-simulator
// Frameworks: Foundation, UIKit, AVFAudio, PushToTalk
//
// Regenerate with: tools/bindgen/regen.sh

//go:build darwin

package appleptt

import "github.com/ebitengine/purego/objc"

// NSDictionary an opaque handle for the ObjC class NSDictionary (NSObject subclass).
// Only the identity crosses: no method of NSDictionary is on the allowlist.
type NSDictionary struct{ objc.ID }

// NSDictionaryClass is the class object of NSDictionary.
type NSDictionaryClass struct{ objc.Class }

// GetNSDictionaryClass looks the class up in the ObjC runtime.
func GetNSDictionaryClass() NSDictionaryClass {
	return NSDictionaryClass{objc.GetClass("NSDictionary")}
}
