// Code generated by tools/bindgen. DO NOT EDIT.
//
// Source: iPhoneSimulator26.2.sdk (Xcode 26.2), target arm64-apple-ios26.2-simulator
// Frameworks: Foundation, UIKit, AVFAudio, PushToTalk
//
// Regenerate with: tools/bindgen/regen.sh

//go:build darwin

package appleptt

import (
	"github.com/adriaanm/wata/go-pkgs/appleptt/objcrt"
	"github.com/ebitengine/purego/objc"
)

// PTChannelManager wraps the ObjC class PTChannelManager (NSObject subclass).
type PTChannelManager struct{ objc.ID }

// PTChannelManagerClass is the class object of PTChannelManager.
type PTChannelManagerClass struct{ objc.Class }

// GetPTChannelManagerClass looks the class up in the ObjC runtime.
func GetPTChannelManagerClass() PTChannelManagerClass {
	return PTChannelManagerClass{objc.GetClass("PTChannelManager")}
}

// Alloc allocates an uninitialized PTChannelManager (-[NSObject alloc]).
func (c PTChannelManagerClass) Alloc() PTChannelManager {
	return PTChannelManager{objc.ID(c.Class).Send(selAlloc)}
}

// ActiveChannelUUID — Only one channel can be active at a time -- this is the channel that will handle user events
// This being nonnull reflects whether the user can see this channel is active in the user interface
// The ephemeral push token is only usable when this is nonnull.
func (o PTChannelManager) ActiveChannelUUID() NSUUID {
	return NSUUID{o.ID.Send(selActiveChannelUUID)}
}

// LeaveChannelWithUUID — If successful, you will receive the delegate callback channelManager:channelUUID:didLeaveChannelWithUUID:reason: with reason PTChannelLeaveReasonProgrammaticRequest, Otherwise, the delegate callback channelManager:failedToLeaveChannelWithUUID:error: will be invoked if implemented. Generally, this should always succeed so long as you are already joined to a channel.
func (o PTChannelManager) LeaveChannelWithUUID(channelUUID NSUUID) {
	o.ID.Send(selLeaveChannelWithUUID, channelUUID.ID)
}

// RequestBeginTransmittingWithChannelUUID — If successful, you will receive the delegate callback channelManager:channelUUID:didBeginTransmittingFromSource: with PTChannelTransmitRequestSourceProgrammaticRequest. Otherwise, the delegate callback channelManager:failedToBeginTransmittingInChannelWithUUID:error: will be invoked if implemented.
func (o PTChannelManager) RequestBeginTransmittingWithChannelUUID(channelUUID NSUUID) {
	o.ID.Send(selRequestBeginTransmittingWithChannelUUID, channelUUID.ID)
}

// RequestJoinChannelWithUUIDDescriptor — You may only join a channel in the foreground. If successful, you will receive the delegate callback channelManager:didJoinChannelWithUUID:reason: with reason PTChannelJoinReasonProgrammaticRequest. Otherwise, the delegate callback channelManager:failedToJoinChannelWithUUID:error: will be invoked if implemented.
func (o PTChannelManager) RequestJoinChannelWithUUIDDescriptor(channelUUID NSUUID, descriptor PTChannelDescriptor) {
	o.ID.Send(selRequestJoinChannelWithUUIDDescriptor, channelUUID.ID, descriptor.ID)
}

// SetAccessoryButtonEventsEnabledForChannelUUIDCompletionHandler — The default channel behavior is to map supported accessory button events to begin/end transmission actions. If your application does not wish to map these button events to transmission actions you can disable them by setting the enabled value to false.
func (o PTChannelManager) SetAccessoryButtonEventsEnabledForChannelUUIDCompletionHandler(enabled bool, channelUUID NSUUID, completionHandler func(error)) {
	blockCompletionHandler := objc.NewBlock(func(_ objc.Block, a0 objc.ID) {
		completionHandler(objcrt.GoError(a0))
	})
	defer blockCompletionHandler.Release()
	o.ID.Send(selSetAccessoryButtonEventsEnabledForChannelUUIDCompletionHandler, enabled, channelUUID.ID, blockCompletionHandler)
}

// SetActiveRemoteParticipantForChannelUUIDCompletionHandler — When receiving incoming audio from a remote participant, set the participant to a nonnull value, which will update the system user interface and block transmitting. When the user has stopped speaking, set the participant to nil.
func (o PTChannelManager) SetActiveRemoteParticipantForChannelUUIDCompletionHandler(participant PTParticipant, channelUUID NSUUID, completionHandler func(error)) {
	blockCompletionHandler := objc.NewBlock(func(_ objc.Block, a0 objc.ID) {
		completionHandler(objcrt.GoError(a0))
	})
	defer blockCompletionHandler.Release()
	o.ID.Send(selSetActiveRemoteParticipantForChannelUUIDCompletionHandler, participant.ID, channelUUID.ID, blockCompletionHandler)
}

// SetChannelDescriptorForChannelUUIDCompletionHandler — Updates the channel descriptor
func (o PTChannelManager) SetChannelDescriptorForChannelUUIDCompletionHandler(channelDescriptor PTChannelDescriptor, channelUUID NSUUID, completionHandler func(error)) {
	blockCompletionHandler := objc.NewBlock(func(_ objc.Block, a0 objc.ID) {
		completionHandler(objcrt.GoError(a0))
	})
	defer blockCompletionHandler.Release()
	o.ID.Send(selSetChannelDescriptorForChannelUUIDCompletionHandler, channelDescriptor.ID, channelUUID.ID, blockCompletionHandler)
}

// SetServiceStatusForChannelUUIDCompletionHandler — The default value for service status is PTServiceStatusReady. If your underlying network connection is experiencing issues, set the appropriate service status. The service status will be reflected in the system user interface.
func (o PTChannelManager) SetServiceStatusForChannelUUIDCompletionHandler(status PTServiceStatus, channelUUID NSUUID, completionHandler func(error)) {
	blockCompletionHandler := objc.NewBlock(func(_ objc.Block, a0 objc.ID) {
		completionHandler(objcrt.GoError(a0))
	})
	defer blockCompletionHandler.Release()
	o.ID.Send(selSetServiceStatusForChannelUUIDCompletionHandler, int(status), channelUUID.ID, blockCompletionHandler)
}

// SetTransmissionModeForChannelUUIDCompletionHandler — The default value for transmission mode is PTTransmissionModeHalfDuplex. If your application support one of the other transmission modes set it using this function. The system user interface will be updated to reflect the transmission mode.
func (o PTChannelManager) SetTransmissionModeForChannelUUIDCompletionHandler(transmissionMode PTTransmissionMode, channelUUID NSUUID, completionHandler func(error)) {
	blockCompletionHandler := objc.NewBlock(func(_ objc.Block, a0 objc.ID) {
		completionHandler(objcrt.GoError(a0))
	})
	defer blockCompletionHandler.Release()
	o.ID.Send(selSetTransmissionModeForChannelUUIDCompletionHandler, int(transmissionMode), channelUUID.ID, blockCompletionHandler)
}

// StopTransmittingWithChannelUUID — If successful, you will receive the delegate callback channelManager:channelUUID:didEndTransmittingFromSource with request source PTChannelTransmitRequestSourceProgrammaticRequest. Otherwise, the delegate callback channelManager:failedToStopTransmittingInChannelWithUUID:error: will be invoked if implemented. Generally, this should always succeed, unless you are not currently transmitting or are not joined to a channel.
func (o PTChannelManager) StopTransmittingWithChannelUUID(channelUUID NSUUID) {
	o.ID.Send(selStopTransmittingWithChannelUUID, channelUUID.ID)
}

// ChannelManagerWithDelegateRestorationDelegateCompletionHandler — You must instantiate a channel manager upon launching your app, otherwise the system will tear down channels and their ability to receive pushes. By providing a restoration delegate, you can decide whether to rejoin or leave any previously active channels that the system knows about. Once the channel restoration process is completed, you will be given the PTChannelManager instance.
func (c PTChannelManagerClass) ChannelManagerWithDelegateRestorationDelegateCompletionHandler(delegate objc.ID, restorationDelegate objc.ID, completionHandler func(PTChannelManager, error)) {
	blockCompletionHandler := objc.NewBlock(func(_ objc.Block, a0 objc.ID, a1 objc.ID) {
		completionHandler(PTChannelManager{a0}, objcrt.GoError(a1))
	})
	defer blockCompletionHandler.Release()
	objc.ID(c.Class).Send(selChannelManagerWithDelegateRestorationDelegateCompletionHandler, delegate, restorationDelegate, blockCompletionHandler)
}
