// Code generated by tools/bindgen. DO NOT EDIT.
//
// Source: iPhoneSimulator26.2.sdk (Xcode 26.2), target arm64-apple-ios26.2-simulator
// Frameworks: Foundation, UIKit, AVFAudio, PushToTalk
//
// Regenerate with: tools/bindgen/regen.sh

//go:build darwin

package appleptt

import (
	"github.com/adriaanm/wata/go-pkgs/appleptt/objcrt"
	"github.com/ebitengine/purego/objc"
)

// PTChannelRestorationDelegate is the Go side of the ObjC protocol PTChannelRestorationDelegate.
//
// A nil field is not installed on the synthesized class, which is exactly
// ObjC's optional-method semantics: -respondsToSelector: answers NO for it.
type PTChannelRestorationDelegate struct {
	// If the system had been tracking a channel previously, this method will be called.
	// -[PTChannelRestorationDelegate channelDescriptorForRestoredChannelUUID:]
	ChannelDescriptorForRestoredChannelUUID func(channelUUID NSUUID) PTChannelDescriptor
}

// NewPTChannelRestorationDelegate synthesizes an ObjC object conforming to PTChannelRestorationDelegate
// that forwards to d's non-nil funcs. The object is retained forever: the
// ObjC runtime cannot unregister a class.
func NewPTChannelRestorationDelegate(d PTChannelRestorationDelegate) objc.ID {
	var ms []objcrt.Method
	if d.ChannelDescriptorForRestoredChannelUUID != nil {
		ms = append(ms, objcrt.Method{
			Sel: "channelDescriptorForRestoredChannelUUID:",
			Fn: func(_ objc.ID, _ objc.SEL, a0 objc.ID) objc.ID {
				return d.ChannelDescriptorForRestoredChannelUUID(NSUUID{a0}).ID
			},
		})
	}
	return objcrt.NewDelegate("WataPTChannelRestorationDelegate", []string{"PTChannelRestorationDelegate"}, ms)
}
