// Code generated by tools/bindgen. DO NOT EDIT.
//
// Source: iPhoneSimulator26.2.sdk (Xcode 26.2), target arm64-apple-ios26.2-simulator
// Frameworks: Foundation, UIKit, AVFAudio, PushToTalk
//
// Regenerate with: tools/bindgen/regen.sh

//go:build darwin

package appleptt

import (
	"github.com/adriaanm/wata/go-pkgs/appleptt/objcrt"
	"github.com/ebitengine/purego/objc"
)

// PTChannelManagerDelegate is the Go side of the ObjC protocol PTChannelManagerDelegate.
//
// A nil field is not installed on the synthesized class, which is exactly
// ObjC's optional-method semantics: -respondsToSelector: answers NO for it.
type PTChannelManagerDelegate struct {
	// This method is called when the user begins pressing the Talk button in the system user interface,  when a programmatic transmit start request succeeds, or transmitting began due to a hands-free accessory button press.
	// -[PTChannelManagerDelegate channelManager:channelUUID:didBeginTransmittingFromSource:]
	ChannelManagerChannelUUIDDidBeginTransmittingFromSource func(channelManager PTChannelManager, channelUUID NSUUID, source PTChannelTransmitRequestSource)
	// This method is called when the user stops pressing the Talk button in the system user interface,  when a programmatic transmit stop request succeeds, or transmitting ends due to a hands-free accessory button press.
	// -[PTChannelManagerDelegate channelManager:channelUUID:didEndTransmittingFromSource:]
	ChannelManagerChannelUUIDDidEndTransmittingFromSource func(channelManager PTChannelManager, channelUUID NSUUID, source PTChannelTransmitRequestSource)
	// -[PTChannelManagerDelegate channelManager:didActivateAudioSession:]
	ChannelManagerDidActivateAudioSession func(channelManager PTChannelManager, audioSession AVAudioSession)
	// -[PTChannelManagerDelegate channelManager:didDeactivateAudioSession:]
	ChannelManagerDidDeactivateAudioSession func(channelManager PTChannelManager, audioSession AVAudioSession)
	// This method is called when your channel becomes active in the system user interface
	// -[PTChannelManagerDelegate channelManager:didJoinChannelWithUUID:reason:]
	ChannelManagerDidJoinChannelWithUUIDReason func(channelManager PTChannelManager, channelUUID NSUUID, reason PTChannelJoinReason)
	// This method is called once your channel is ended
	// -[PTChannelManagerDelegate channelManager:didLeaveChannelWithUUID:reason:]
	ChannelManagerDidLeaveChannelWithUUIDReason func(channelManager PTChannelManager, channelUUID NSUUID, reason PTChannelLeaveReason)
	// -[PTChannelManagerDelegate channelManager:failedToBeginTransmittingInChannelWithUUID:error:]
	ChannelManagerFailedToBeginTransmittingInChannelWithUUIDError func(channelManager PTChannelManager, channelUUID NSUUID, error_ error)
	// -[PTChannelManagerDelegate channelManager:failedToJoinChannelWithUUID:error:]
	ChannelManagerFailedToJoinChannelWithUUIDError func(channelManager PTChannelManager, channelUUID NSUUID, error_ error)
	// -[PTChannelManagerDelegate channelManager:failedToLeaveChannelWithUUID:error:]
	ChannelManagerFailedToLeaveChannelWithUUIDError func(channelManager PTChannelManager, channelUUID NSUUID, error_ error)
	// -[PTChannelManagerDelegate channelManager:failedToStopTransmittingInChannelWithUUID:error:]
	ChannelManagerFailedToStopTransmittingInChannelWithUUIDError func(channelManager PTChannelManager, channelUUID NSUUID, error_ error)
	// -[PTChannelManagerDelegate channelManager:receivedEphemeralPushToken:]
	ChannelManagerReceivedEphemeralPushToken func(channelManager PTChannelManager, pushToken NSData)
	// -[PTChannelManagerDelegate incomingPushResultForChannelManager:channelUUID:pushPayload:]
	IncomingPushResultForChannelManagerChannelUUIDPushPayload func(channelManager PTChannelManager, channelUUID NSUUID, pushPayload NSDictionary) PTPushResult
	// -[PTChannelManagerDelegate incomingServiceUpdatePushForChannelManager:channelUUID:pushPayload:isHighPriority:remainingHighPriorityBudget:withCompletionHandler:]
	IncomingServiceUpdatePushForChannelManagerChannelUUIDPushPayloadIsHighPriorityRemainingHighPriorityBudgetWithCompletionHandler func(channelManager PTChannelManager, channelUUID NSUUID, pushPayload NSDictionary, isHighPriority bool, remainingHighPriorityBudget int, completion IncomingBlockVoid)
}

// NewPTChannelManagerDelegate synthesizes an ObjC object conforming to PTChannelManagerDelegate
// that forwards to d's non-nil funcs. The object is retained forever: the
// ObjC runtime cannot unregister a class.
func NewPTChannelManagerDelegate(d PTChannelManagerDelegate) objc.ID {
	var ms []objcrt.Method
	if d.ChannelManagerChannelUUIDDidBeginTransmittingFromSource != nil {
		ms = append(ms, objcrt.Method{
			Sel: "channelManager:channelUUID:didBeginTransmittingFromSource:",
			Fn: func(_ objc.ID, _ objc.SEL, a0 objc.ID, a1 objc.ID, a2 int) {
				d.ChannelManagerChannelUUIDDidBeginTransmittingFromSource(PTChannelManager{a0}, NSUUID{a1}, PTChannelTransmitRequestSource(a2))
			},
		})
	}
	if d.ChannelManagerChannelUUIDDidEndTransmittingFromSource != nil {
		ms = append(ms, objcrt.Method{
			Sel: "channelManager:channelUUID:didEndTransmittingFromSource:",
			Fn: func(_ objc.ID, _ objc.SEL, a0 objc.ID, a1 objc.ID, a2 int) {
				d.ChannelManagerChannelUUIDDidEndTransmittingFromSource(PTChannelManager{a0}, NSUUID{a1}, PTChannelTransmitRequestSource(a2))
			},
		})
	}
	if d.ChannelManagerDidActivateAudioSession != nil {
		ms = append(ms, objcrt.Method{
			Sel: "channelManager:didActivateAudioSession:",
			Fn: func(_ objc.ID, _ objc.SEL, a0 objc.ID, a1 objc.ID) {
				d.ChannelManagerDidActivateAudioSession(PTChannelManager{a0}, AVAudioSession{a1})
			},
		})
	}
	if d.ChannelManagerDidDeactivateAudioSession != nil {
		ms = append(ms, objcrt.Method{
			Sel: "channelManager:didDeactivateAudioSession:",
			Fn: func(_ objc.ID, _ objc.SEL, a0 objc.ID, a1 objc.ID) {
				d.ChannelManagerDidDeactivateAudioSession(PTChannelManager{a0}, AVAudioSession{a1})
			},
		})
	}
	if d.ChannelManagerDidJoinChannelWithUUIDReason != nil {
		ms = append(ms, objcrt.Method{
			Sel: "channelManager:didJoinChannelWithUUID:reason:",
			Fn: func(_ objc.ID, _ objc.SEL, a0 objc.ID, a1 objc.ID, a2 int) {
				d.ChannelManagerDidJoinChannelWithUUIDReason(PTChannelManager{a0}, NSUUID{a1}, PTChannelJoinReason(a2))
			},
		})
	}
	if d.ChannelManagerDidLeaveChannelWithUUIDReason != nil {
		ms = append(ms, objcrt.Method{
			Sel: "channelManager:didLeaveChannelWithUUID:reason:",
			Fn: func(_ objc.ID, _ objc.SEL, a0 objc.ID, a1 objc.ID, a2 int) {
				d.ChannelManagerDidLeaveChannelWithUUIDReason(PTChannelManager{a0}, NSUUID{a1}, PTChannelLeaveReason(a2))
			},
		})
	}
	if d.ChannelManagerFailedToBeginTransmittingInChannelWithUUIDError != nil {
		ms = append(ms, objcrt.Method{
			Sel: "channelManager:failedToBeginTransmittingInChannelWithUUID:error:",
			Fn: func(_ objc.ID, _ objc.SEL, a0 objc.ID, a1 objc.ID, a2 objc.ID) {
				d.ChannelManagerFailedToBeginTransmittingInChannelWithUUIDError(PTChannelManager{a0}, NSUUID{a1}, objcrt.GoError(a2))
			},
		})
	}
	if d.ChannelManagerFailedToJoinChannelWithUUIDError != nil {
		ms = append(ms, objcrt.Method{
			Sel: "channelManager:failedToJoinChannelWithUUID:error:",
			Fn: func(_ objc.ID, _ objc.SEL, a0 objc.ID, a1 objc.ID, a2 objc.ID) {
				d.ChannelManagerFailedToJoinChannelWithUUIDError(PTChannelManager{a0}, NSUUID{a1}, objcrt.GoError(a2))
			},
		})
	}
	if d.ChannelManagerFailedToLeaveChannelWithUUIDError != nil {
		ms = append(ms, objcrt.Method{
			Sel: "channelManager:failedToLeaveChannelWithUUID:error:",
			Fn: func(_ objc.ID, _ objc.SEL, a0 objc.ID, a1 objc.ID, a2 objc.ID) {
				d.ChannelManagerFailedToLeaveChannelWithUUIDError(PTChannelManager{a0}, NSUUID{a1}, objcrt.GoError(a2))
			},
		})
	}
	if d.ChannelManagerFailedToStopTransmittingInChannelWithUUIDError != nil {
		ms = append(ms, objcrt.Method{
			Sel: "channelManager:failedToStopTransmittingInChannelWithUUID:error:",
			Fn: func(_ objc.ID, _ objc.SEL, a0 objc.ID, a1 objc.ID, a2 objc.ID) {
				d.ChannelManagerFailedToStopTransmittingInChannelWithUUIDError(PTChannelManager{a0}, NSUUID{a1}, objcrt.GoError(a2))
			},
		})
	}
	if d.ChannelManagerReceivedEphemeralPushToken != nil {
		ms = append(ms, objcrt.Method{
			Sel: "channelManager:receivedEphemeralPushToken:",
			Fn: func(_ objc.ID, _ objc.SEL, a0 objc.ID, a1 objc.ID) {
				d.ChannelManagerReceivedEphemeralPushToken(PTChannelManager{a0}, NSData{a1})
			},
		})
	}
	if d.IncomingPushResultForChannelManagerChannelUUIDPushPayload != nil {
		ms = append(ms, objcrt.Method{
			Sel: "incomingPushResultForChannelManager:channelUUID:pushPayload:",
			Fn: func(_ objc.ID, _ objc.SEL, a0 objc.ID, a1 objc.ID, a2 objc.ID) objc.ID {
				return d.IncomingPushResultForChannelManagerChannelUUIDPushPayload(PTChannelManager{a0}, NSUUID{a1}, NSDictionary{a2}).ID
			},
		})
	}
	if d.IncomingServiceUpdatePushForChannelManagerChannelUUIDPushPayloadIsHighPriorityRemainingHighPriorityBudgetWithCompletionHandler != nil {
		ms = append(ms, objcrt.Method{
			Sel: "incomingServiceUpdatePushForChannelManager:channelUUID:pushPayload:isHighPriority:remainingHighPriorityBudget:withCompletionHandler:",
			Fn: func(_ objc.ID, _ objc.SEL, a0 objc.ID, a1 objc.ID, a2 objc.ID, a3 bool, a4 int, a5 objc.Block) {
				d.IncomingServiceUpdatePushForChannelManagerChannelUUIDPushPayloadIsHighPriorityRemainingHighPriorityBudgetWithCompletionHandler(PTChannelManager{a0}, NSUUID{a1}, NSDictionary{a2}, a3, a4, IncomingBlockVoid{objcrt.CopyBlock(a5)})
			},
		})
	}
	return objcrt.NewDelegate("WataPTChannelManagerDelegate", []string{"PTChannelManagerDelegate"}, ms)
}
