// Code generated by tools/bindgen. DO NOT EDIT.
//
// Source: iPhoneSimulator26.2.sdk (Xcode 26.2), target arm64-apple-ios26.2-simulator
// Frameworks: Foundation, UIKit, AVFAudio, PushToTalk
//
// Regenerate with: tools/bindgen/regen.sh

//go:build darwin

package appleptt

import (
	"github.com/adriaanm/wata/go-pkgs/appleptt/objcrt"
	"github.com/ebitengine/purego/objc"
)

// PTChannelDescriptor wraps the ObjC class PTChannelDescriptor (NSObject subclass).
type PTChannelDescriptor struct{ objc.ID }

// PTChannelDescriptorClass is the class object of PTChannelDescriptor.
type PTChannelDescriptorClass struct{ objc.Class }

// GetPTChannelDescriptorClass looks the class up in the ObjC runtime.
func GetPTChannelDescriptorClass() PTChannelDescriptorClass {
	return PTChannelDescriptorClass{objc.GetClass("PTChannelDescriptor")}
}

// Alloc allocates an uninitialized PTChannelDescriptor (-[NSObject alloc]).
func (c PTChannelDescriptorClass) Alloc() PTChannelDescriptor {
	return PTChannelDescriptor{objc.ID(c.Class).Send(selAlloc)}
}

// Image — The channel's "group photo" presented in the system user interface. This image is shown while nobody else is speaking.
func (o PTChannelDescriptor) Image() UIImage {
	return UIImage{o.ID.Send(selImage)}
}

// Name — The channel's "group name" shown in system user interface. (This is shown while nobody else is speaking.)
func (o PTChannelDescriptor) Name() string {
	return objcrt.GoString(o.ID.Send(selName))
}

// InitWithNameImage calls -[PTChannelDescriptor initWithName:image:].
func (o PTChannelDescriptor) InitWithNameImage(name string, image UIImage) PTChannelDescriptor {
	return PTChannelDescriptor{o.ID.Send(selInitWithNameImage, objcrt.NSString(name), image.ID)}
}
