// Code generated by tools/bindgen. DO NOT EDIT.
//
// Source: iPhoneSimulator26.2.sdk (Xcode 26.2), target arm64-apple-ios26.2-simulator
// Frameworks: Foundation, UIKit, AVFAudio, PushToTalk
//
// Regenerate with: tools/bindgen/regen.sh

//go:build darwin

package appleptt

import (
	"github.com/adriaanm/wata/go-pkgs/appleptt/objcrt"
	"github.com/ebitengine/purego/objc"
)

// PTParticipant wraps the ObjC class PTParticipant (NSObject subclass).
type PTParticipant struct{ objc.ID }

// PTParticipantClass is the class object of PTParticipant.
type PTParticipantClass struct{ objc.Class }

// GetPTParticipantClass looks the class up in the ObjC runtime.
func GetPTParticipantClass() PTParticipantClass {
	return PTParticipantClass{objc.GetClass("PTParticipant")}
}

// Alloc allocates an uninitialized PTParticipant (-[NSObject alloc]).
func (c PTParticipantClass) Alloc() PTParticipant {
	return PTParticipant{objc.ID(c.Class).Send(selAlloc)}
}

// Image reads the PTParticipant property image.
func (o PTParticipant) Image() UIImage {
	return UIImage{o.ID.Send(selImage)}
}

// Name reads the PTParticipant property name.
func (o PTParticipant) Name() string {
	return objcrt.GoString(o.ID.Send(selName))
}

// InitWithNameImage — The name length must be greater than 0.
func (o PTParticipant) InitWithNameImage(name string, image UIImage) PTParticipant {
	return PTParticipant{o.ID.Send(selInitWithNameImage, objcrt.NSString(name), image.ID)}
}
