// Code generated by tools/bindgen. DO NOT EDIT.
//
// Source: iPhoneSimulator26.2.sdk (Xcode 26.2), target arm64-apple-ios26.2-simulator
// Frameworks: Foundation, UIKit, AVFAudio, PushToTalk
//
// Regenerate with: tools/bindgen/regen.sh

//go:build darwin

package appleptt

import "github.com/ebitengine/purego/objc"

// PTPushResult wraps the ObjC class PTPushResult (NSObject subclass).
type PTPushResult struct{ objc.ID }

// PTPushResultClass is the class object of PTPushResult.
type PTPushResultClass struct{ objc.Class }

// GetPTPushResultClass looks the class up in the ObjC runtime.
func GetPTPushResultClass() PTPushResultClass {
	return PTPushResultClass{objc.GetClass("PTPushResult")}
}

// Alloc allocates an uninitialized PTPushResult (-[NSObject alloc]).
func (c PTPushResultClass) Alloc() PTPushResult { return PTPushResult{objc.ID(c.Class).Send(selAlloc)} }

// LeaveChannelPushResult — Use this if the push is a result of the user leaving the channel
func (c PTPushResultClass) LeaveChannelPushResult() PTPushResult {
	return PTPushResult{objc.ID(c.Class).Send(selLeaveChannelPushResult)}
}

// PushResultForActiveRemoteParticipant — Use this to report the active remote participant that started speaking
func (c PTPushResultClass) PushResultForActiveRemoteParticipant(participant PTParticipant) PTPushResult {
	return PTPushResult{objc.ID(c.Class).Send(selPushResultForActiveRemoteParticipant, participant.ID)}
}
