// Code generated by tools/bindgen. DO NOT EDIT.
//
// Source: iPhoneSimulator26.2.sdk (Xcode 26.2), target arm64-apple-ios26.2-simulator
// Frameworks: Foundation, UIKit, AVFAudio, PushToTalk
//
// Regenerate with: tools/bindgen/regen.sh

//go:build darwin

package appleptt

import "github.com/ebitengine/purego/objc"

// Selectors, registered once at package init.
var (
	selUUID                                                           = objc.RegisterName("UUID")
	selUUIDString                                                     = objc.RegisterName("UUIDString")
	selActiveChannelUUID                                              = objc.RegisterName("activeChannelUUID")
	selAlloc                                                          = objc.RegisterName("alloc")
	selChannelManagerWithDelegateRestorationDelegateCompletionHandler = objc.RegisterName("channelManagerWithDelegate:restorationDelegate:completionHandler:")
	selImage                                                          = objc.RegisterName("image")
	selInit                                                           = objc.RegisterName("init")
	selInitWithNameImage                                              = objc.RegisterName("initWithName:image:")
	selInitWithUUIDString                                             = objc.RegisterName("initWithUUIDString:")
	selLeaveChannelPushResult                                         = objc.RegisterName("leaveChannelPushResult")
	selLeaveChannelWithUUID                                           = objc.RegisterName("leaveChannelWithUUID:")
	selName                                                           = objc.RegisterName("name")
	selPushResultForActiveRemoteParticipant                           = objc.RegisterName("pushResultForActiveRemoteParticipant:")
	selRequestBeginTransmittingWithChannelUUID                        = objc.RegisterName("requestBeginTransmittingWithChannelUUID:")
	selRequestJoinChannelWithUUIDDescriptor                           = objc.RegisterName("requestJoinChannelWithUUID:descriptor:")
	selSetAccessoryButtonEventsEnabledForChannelUUIDCompletionHandler = objc.RegisterName("setAccessoryButtonEventsEnabled:forChannelUUID:completionHandler:")
	selSetActiveRemoteParticipantForChannelUUIDCompletionHandler      = objc.RegisterName("setActiveRemoteParticipant:forChannelUUID:completionHandler:")
	selSetChannelDescriptorForChannelUUIDCompletionHandler            = objc.RegisterName("setChannelDescriptor:forChannelUUID:completionHandler:")
	selSetServiceStatusForChannelUUIDCompletionHandler                = objc.RegisterName("setServiceStatus:forChannelUUID:completionHandler:")
	selSetTransmissionModeForChannelUUIDCompletionHandler             = objc.RegisterName("setTransmissionMode:forChannelUUID:completionHandler:")
	selStopTransmittingWithChannelUUID                                = objc.RegisterName("stopTransmittingWithChannelUUID:")
)
