// Code generated by tools/bindgen. DO NOT EDIT.
//
// Source: iPhoneSimulator26.2.sdk (Xcode 26.2), target arm64-apple-ios26.2-simulator
// Frameworks: Foundation, UIKit, AVFAudio, PushToTalk
//
// Regenerate with: tools/bindgen/regen.sh

//go:build darwin

package appleptt

import "github.com/ebitengine/purego/objc"

// UIImage an opaque handle for the ObjC class UIImage (NSObject subclass).
// Only the identity crosses: no method of UIImage is on the allowlist.
type UIImage struct{ objc.ID }

// UIImageClass is the class object of UIImage.
type UIImageClass struct{ objc.Class }

// GetUIImageClass looks the class up in the ObjC runtime.
func GetUIImageClass() UIImageClass { return UIImageClass{objc.GetClass("UIImage")} }
