// Code generated by tools/bindgen. DO NOT EDIT.
//
// Source: tools/bindgen/fixtures
//
// Regenerate with: tools/bindgen/regen.sh

//go:build darwin

package fixture

import "github.com/adriaanm/wata/go-pkgs/appleptt/objcrt"

// IncomingBlockFloat64String is an ObjC block received by a callback, copied
// (_Block_copy) so it can be invoked after the callback returns — from any
// goroutine. Release it exactly once when done: a second Release, or a Call
// after Release, panics. Call may repeat while the handle is live.
type IncomingBlockFloat64String struct{ h *objcrt.BlockHandle }

// Call invokes the block through its own invoke pointer.
func (b IncomingBlockFloat64String) Call(a0 float64, a1 string) { b.h.Invoke(a0, objcrt.NSString(a1)) }

// Release frees the copied block (_Block_release).
func (b IncomingBlockFloat64String) Release() { b.h.Release() }

// IncomingBlockVoid is an ObjC block received by a callback, copied
// (_Block_copy) so it can be invoked after the callback returns — from any
// goroutine. Release it exactly once when done: a second Release, or a Call
// after Release, panics. Call may repeat while the handle is live.
type IncomingBlockVoid struct{ h *objcrt.BlockHandle }

// Call invokes the block through its own invoke pointer.
func (b IncomingBlockVoid) Call() { b.h.Invoke() }

// Release frees the copied block (_Block_release).
func (b IncomingBlockVoid) Release() { b.h.Release() }
