// Code generated by tools/bindgen. DO NOT EDIT.
//
// Source: tools/bindgen/fixtures
//
// Regenerate with: tools/bindgen/regen.sh

//go:build darwin

package fixture

// WFJoinReason is the ObjC enum WFJoinReason (long).
type WFJoinReason int

const (
	WFJoinReasonRequested WFJoinReason = 0
	WFJoinReasonRestored  WFJoinReason = 1
)
