// Code generated by tools/bindgen. DO NOT EDIT.
//
// Source: tools/bindgen/fixtures
//
// Regenerate with: tools/bindgen/regen.sh

//go:build darwin

package fixture

import "github.com/ebitengine/purego/objc"

// WFSession wraps the ObjC class WFSession (NSObject subclass).
type WFSession struct{ objc.ID }

// WFSessionClass is the class object of WFSession.
type WFSessionClass struct{ objc.Class }

// GetWFSessionClass looks the class up in the ObjC runtime.
func GetWFSessionClass() WFSessionClass { return WFSessionClass{objc.GetClass("WFSession")} }

// Alloc allocates an uninitialized WFSession (-[NSObject alloc]).
func (c WFSessionClass) Alloc() WFSession { return WFSession{objc.ID(c.Class).Send(selAlloc)} }
