// Code generated by tools/bindgen. DO NOT EDIT.
//
// Source: tools/bindgen/fixtures
//
// Regenerate with: tools/bindgen/regen.sh

//go:build darwin

package fixture

import (
	"github.com/adriaanm/wata/go-pkgs/appleptt/objcrt"
	"github.com/ebitengine/purego/objc"
)

// WFSessionDelegate — What a session tells its owner.
//
// A nil field is not installed on the synthesized class, which is exactly
// ObjC's optional-method semantics: -respondsToSelector: answers NO for it.
type WFSessionDelegate struct {
	// A callback with a return value.
	// -[WFSessionDelegate replacementForSession:]
	ReplacementForSession func(session WFSession) WFSession
	// The session joined.
	// -[WFSessionDelegate session:didJoin:reason:]
	SessionDidJoinReason func(session WFSession, name string, reason WFJoinReason)
	// -[WFSessionDelegate session:failedWithError:]
	SessionFailedWithError func(session WFSession, error_ error)
	// A callback handed a block: the block is copied into a handle that outlives the call.
	// -[WFSessionDelegate session:handle:]
	SessionHandle func(session WFSession, done IncomingBlockVoid)
	// An incoming block with arguments: the handle's Call is typed.
	// -[WFSessionDelegate session:progress:]
	SessionProgress func(session WFSession, report IncomingBlockFloat64String)
}

// NewWFSessionDelegate synthesizes an ObjC object conforming to WFSessionDelegate
// that forwards to d's non-nil funcs. The object is retained forever: the
// ObjC runtime cannot unregister a class.
func NewWFSessionDelegate(d WFSessionDelegate) objc.ID {
	var ms []objcrt.Method
	if d.ReplacementForSession != nil {
		ms = append(ms, objcrt.Method{
			Sel: "replacementForSession:",
			Fn: func(_ objc.ID, _ objc.SEL, a0 objc.ID) objc.ID {
				return d.ReplacementForSession(WFSession{a0}).ID
			},
		})
	}
	if d.SessionDidJoinReason != nil {
		ms = append(ms, objcrt.Method{
			Sel: "session:didJoin:reason:",
			Fn: func(_ objc.ID, _ objc.SEL, a0 objc.ID, a1 objc.ID, a2 int) {
				d.SessionDidJoinReason(WFSession{a0}, objcrt.GoString(a1), WFJoinReason(a2))
			},
		})
	}
	if d.SessionFailedWithError != nil {
		ms = append(ms, objcrt.Method{
			Sel: "session:failedWithError:",
			Fn: func(_ objc.ID, _ objc.SEL, a0 objc.ID, a1 objc.ID) {
				d.SessionFailedWithError(WFSession{a0}, objcrt.GoError(a1))
			},
		})
	}
	if d.SessionHandle != nil {
		ms = append(ms, objcrt.Method{
			Sel: "session:handle:",
			Fn: func(_ objc.ID, _ objc.SEL, a0 objc.ID, a1 objc.Block) {
				d.SessionHandle(WFSession{a0}, IncomingBlockVoid{objcrt.CopyBlock(a1)})
			},
		})
	}
	if d.SessionProgress != nil {
		ms = append(ms, objcrt.Method{
			Sel: "session:progress:",
			Fn: func(_ objc.ID, _ objc.SEL, a0 objc.ID, a1 objc.Block) {
				d.SessionProgress(WFSession{a0}, IncomingBlockFloat64String{objcrt.CopyBlock(a1)})
			},
		})
	}
	return objcrt.NewDelegate("WataWFSessionDelegate", []string{"WFSessionDelegate"}, ms)
}
