// Code generated by tools/bindgen. DO NOT EDIT.
//
// Source: tools/bindgen/fixtures
//
// Regenerate with: tools/bindgen/regen.sh

//go:build darwin

package fixture

import (
	"github.com/adriaanm/wata/go-pkgs/appleptt/objcrt"
	"github.com/ebitengine/purego/objc"
)

// WFBlob — A class whose API is spread over categories, the way Foundation's is.
type WFBlob struct{ objc.ID }

// WFBlobClass is the class object of WFBlob.
type WFBlobClass struct{ objc.Class }

// GetWFBlobClass looks the class up in the ObjC runtime.
func GetWFBlobClass() WFBlobClass { return WFBlobClass{objc.GetClass("WFBlob")} }

// Alloc allocates an uninitialized WFBlob (-[NSObject alloc]).
func (c WFBlobClass) Alloc() WFBlob { return WFBlob{objc.ID(c.Class).Send(selAlloc)} }

// Label reads the WFBlob property label.
func (o WFBlob) Label() string {
	return objcrt.GoString(o.ID.Send(selLabel))
}

// DescribeBlob — A loose node: its category did not match the dump filter, so clang printed the method on its own. mangledName is what attributes it.
func (o WFBlob) DescribeBlob() string {
	return objcrt.GoString(o.ID.Send(selDescribeBlob))
}

// Length calls -[WFBlob length].
func (o WFBlob) Length() uint {
	return objc.Send[uint](o.ID, selLength)
}

// BlobWithName — A category's class method.
func (c WFBlobClass) BlobWithName(name string) WFBlob {
	return WFBlob{objc.ID(c.Class).Send(selBlobWithName, objcrt.NSString(name))}
}
