// Code generated by tools/bindgen. DO NOT EDIT.
//
// Source: tools/bindgen/fixtures
//
// Regenerate with: tools/bindgen/regen.sh

//go:build darwin

package fixture

// WFChannelOptions — NS_OPTIONS: an unsigned bitmask written as shifts.
type WFChannelOptions uint

const (
	WFChannelOptionNone       WFChannelOptions = 0
	WFChannelOptionDuplex     WFChannelOptions = 1
	WFChannelOptionListenOnly WFChannelOptions = 2
)

// WFServiceStatus — NS_ENUM: implicit values, one after another.
type WFServiceStatus int

const (
	// Ready for use.
	WFServiceStatusReady      WFServiceStatus = 0
	WFServiceStatusConnecting WFServiceStatus = 1
	WFServiceStatusFailed     WFServiceStatus = 17
	WFServiceStatusGone       WFServiceStatus = 18
)
