// Code generated by tools/bindgen. DO NOT EDIT.
//
// Source: MacOSX26.2.sdk (Xcode 26.2), target arm64-apple-macos26.0
// Frameworks: Foundation
//
// Regenerate with: tools/bindgen/regen.sh

//go:build darwin

package foundation

import "github.com/adriaanm/wata/go-pkgs/appleptt/objcrt"

// IncomingBlockNSURLSessionResponseDisposition is an ObjC block received by a callback, copied
// (_Block_copy) so it can be invoked after the callback returns — from any
// goroutine. Release it exactly once when done: a second Release, or a Call
// after Release, panics. Call may repeat while the handle is live.
type IncomingBlockNSURLSessionResponseDisposition struct{ h *objcrt.BlockHandle }

// Call invokes the block through its own invoke pointer.
func (b IncomingBlockNSURLSessionResponseDisposition) Call(a0 NSURLSessionResponseDisposition) {
	b.h.Invoke(int(a0))
}

// Release frees the copied block (_Block_release).
func (b IncomingBlockNSURLSessionResponseDisposition) Release() { b.h.Release() }
