// Code generated by tools/bindgen. DO NOT EDIT.
//
// Source: MacOSX26.2.sdk (Xcode 26.2), target arm64-apple-macos26.0
// Frameworks: Foundation
//
// Regenerate with: tools/bindgen/regen.sh

//go:build darwin

package foundation

// NSDataReadingOptions is the ObjC enum NSDataReadingOptions (unsigned long).
type NSDataReadingOptions uint

const (
	NSDataReadingMappedIfSafe NSDataReadingOptions = 1
	NSDataReadingUncached     NSDataReadingOptions = 2
	NSDataReadingMappedAlways NSDataReadingOptions = 8
	NSDataReadingMapped       NSDataReadingOptions = 1
	NSMappedRead              NSDataReadingOptions = 1
	NSUncachedRead            NSDataReadingOptions = 2
)

// NSDataWritingOptions is the ObjC enum NSDataWritingOptions (unsigned long).
type NSDataWritingOptions uint

const (
	NSDataWritingAtomic                                             NSDataWritingOptions = 1
	NSDataWritingWithoutOverwriting                                 NSDataWritingOptions = 2
	NSDataWritingFileProtectionNone                                 NSDataWritingOptions = 268435456
	NSDataWritingFileProtectionComplete                             NSDataWritingOptions = 536870912
	NSDataWritingFileProtectionCompleteUnlessOpen                   NSDataWritingOptions = 805306368
	NSDataWritingFileProtectionCompleteUntilFirstUserAuthentication NSDataWritingOptions = 1073741824
	NSDataWritingFileProtectionCompleteWhenUserInactive             NSDataWritingOptions = 1342177280
	NSDataWritingFileProtectionMask                                 NSDataWritingOptions = 4026531840
	NSAtomicWrite                                                   NSDataWritingOptions = 1
)

// NSURLSessionResponseDisposition is the ObjC enum NSURLSessionResponseDisposition (long).
type NSURLSessionResponseDisposition int

const (
	NSURLSessionResponseCancel         NSURLSessionResponseDisposition = 0
	NSURLSessionResponseAllow          NSURLSessionResponseDisposition = 1
	NSURLSessionResponseBecomeDownload NSURLSessionResponseDisposition = 2
	NSURLSessionResponseBecomeStream   NSURLSessionResponseDisposition = 3
)

// NSXMLParserError is the ObjC enum NSXMLParserError (long).
type NSXMLParserError int

const (
	NSXMLParserInternalError                         NSXMLParserError = 1
	NSXMLParserOutOfMemoryError                      NSXMLParserError = 2
	NSXMLParserDocumentStartError                    NSXMLParserError = 3
	NSXMLParserEmptyDocumentError                    NSXMLParserError = 4
	NSXMLParserPrematureDocumentEndError             NSXMLParserError = 5
	NSXMLParserInvalidHexCharacterRefError           NSXMLParserError = 6
	NSXMLParserInvalidDecimalCharacterRefError       NSXMLParserError = 7
	NSXMLParserInvalidCharacterRefError              NSXMLParserError = 8
	NSXMLParserInvalidCharacterError                 NSXMLParserError = 9
	NSXMLParserCharacterRefAtEOFError                NSXMLParserError = 10
	NSXMLParserCharacterRefInPrologError             NSXMLParserError = 11
	NSXMLParserCharacterRefInEpilogError             NSXMLParserError = 12
	NSXMLParserCharacterRefInDTDError                NSXMLParserError = 13
	NSXMLParserEntityRefAtEOFError                   NSXMLParserError = 14
	NSXMLParserEntityRefInPrologError                NSXMLParserError = 15
	NSXMLParserEntityRefInEpilogError                NSXMLParserError = 16
	NSXMLParserEntityRefInDTDError                   NSXMLParserError = 17
	NSXMLParserParsedEntityRefAtEOFError             NSXMLParserError = 18
	NSXMLParserParsedEntityRefInPrologError          NSXMLParserError = 19
	NSXMLParserParsedEntityRefInEpilogError          NSXMLParserError = 20
	NSXMLParserParsedEntityRefInInternalSubsetError  NSXMLParserError = 21
	NSXMLParserEntityReferenceWithoutNameError       NSXMLParserError = 22
	NSXMLParserEntityReferenceMissingSemiError       NSXMLParserError = 23
	NSXMLParserParsedEntityRefNoNameError            NSXMLParserError = 24
	NSXMLParserParsedEntityRefMissingSemiError       NSXMLParserError = 25
	NSXMLParserUndeclaredEntityError                 NSXMLParserError = 26
	NSXMLParserUnparsedEntityError                   NSXMLParserError = 28
	NSXMLParserEntityIsExternalError                 NSXMLParserError = 29
	NSXMLParserEntityIsParameterError                NSXMLParserError = 30
	NSXMLParserUnknownEncodingError                  NSXMLParserError = 31
	NSXMLParserEncodingNotSupportedError             NSXMLParserError = 32
	NSXMLParserStringNotStartedError                 NSXMLParserError = 33
	NSXMLParserStringNotClosedError                  NSXMLParserError = 34
	NSXMLParserNamespaceDeclarationError             NSXMLParserError = 35
	NSXMLParserEntityNotStartedError                 NSXMLParserError = 36
	NSXMLParserEntityNotFinishedError                NSXMLParserError = 37
	NSXMLParserLessThanSymbolInAttributeError        NSXMLParserError = 38
	NSXMLParserAttributeNotStartedError              NSXMLParserError = 39
	NSXMLParserAttributeNotFinishedError             NSXMLParserError = 40
	NSXMLParserAttributeHasNoValueError              NSXMLParserError = 41
	NSXMLParserAttributeRedefinedError               NSXMLParserError = 42
	NSXMLParserLiteralNotStartedError                NSXMLParserError = 43
	NSXMLParserLiteralNotFinishedError               NSXMLParserError = 44
	NSXMLParserCommentNotFinishedError               NSXMLParserError = 45
	NSXMLParserProcessingInstructionNotStartedError  NSXMLParserError = 46
	NSXMLParserProcessingInstructionNotFinishedError NSXMLParserError = 47
	NSXMLParserNotationNotStartedError               NSXMLParserError = 48
	NSXMLParserNotationNotFinishedError              NSXMLParserError = 49
	NSXMLParserAttributeListNotStartedError          NSXMLParserError = 50
	NSXMLParserAttributeListNotFinishedError         NSXMLParserError = 51
	NSXMLParserMixedContentDeclNotStartedError       NSXMLParserError = 52
	NSXMLParserMixedContentDeclNotFinishedError      NSXMLParserError = 53
	NSXMLParserElementContentDeclNotStartedError     NSXMLParserError = 54
	NSXMLParserElementContentDeclNotFinishedError    NSXMLParserError = 55
	NSXMLParserXMLDeclNotStartedError                NSXMLParserError = 56
	NSXMLParserXMLDeclNotFinishedError               NSXMLParserError = 57
	NSXMLParserConditionalSectionNotStartedError     NSXMLParserError = 58
	NSXMLParserConditionalSectionNotFinishedError    NSXMLParserError = 59
	NSXMLParserExternalSubsetNotFinishedError        NSXMLParserError = 60
	NSXMLParserDOCTYPEDeclNotFinishedError           NSXMLParserError = 61
	NSXMLParserMisplacedCDATAEndStringError          NSXMLParserError = 62
	NSXMLParserCDATANotFinishedError                 NSXMLParserError = 63
	NSXMLParserMisplacedXMLDeclarationError          NSXMLParserError = 64
	NSXMLParserSpaceRequiredError                    NSXMLParserError = 65
	NSXMLParserSeparatorRequiredError                NSXMLParserError = 66
	NSXMLParserNMTOKENRequiredError                  NSXMLParserError = 67
	NSXMLParserNAMERequiredError                     NSXMLParserError = 68
	NSXMLParserPCDATARequiredError                   NSXMLParserError = 69
	NSXMLParserURIRequiredError                      NSXMLParserError = 70
	NSXMLParserPublicIdentifierRequiredError         NSXMLParserError = 71
	NSXMLParserLTRequiredError                       NSXMLParserError = 72
	NSXMLParserGTRequiredError                       NSXMLParserError = 73
	NSXMLParserLTSlashRequiredError                  NSXMLParserError = 74
	NSXMLParserEqualExpectedError                    NSXMLParserError = 75
	NSXMLParserTagNameMismatchError                  NSXMLParserError = 76
	NSXMLParserUnfinishedTagError                    NSXMLParserError = 77
	NSXMLParserStandaloneValueError                  NSXMLParserError = 78
	NSXMLParserInvalidEncodingNameError              NSXMLParserError = 79
	NSXMLParserCommentContainsDoubleHyphenError      NSXMLParserError = 80
	NSXMLParserInvalidEncodingError                  NSXMLParserError = 81
	NSXMLParserExternalStandaloneEntityError         NSXMLParserError = 82
	NSXMLParserInvalidConditionalSectionError        NSXMLParserError = 83
	NSXMLParserEntityValueRequiredError              NSXMLParserError = 84
	NSXMLParserNotWellBalancedError                  NSXMLParserError = 85
	NSXMLParserExtraContentError                     NSXMLParserError = 86
	NSXMLParserInvalidCharacterInEntityError         NSXMLParserError = 87
	NSXMLParserParsedEntityRefInInternalError        NSXMLParserError = 88
	NSXMLParserEntityRefLoopError                    NSXMLParserError = 89
	NSXMLParserEntityBoundaryError                   NSXMLParserError = 90
	NSXMLParserInvalidURIError                       NSXMLParserError = 91
	NSXMLParserURIFragmentError                      NSXMLParserError = 92
	NSXMLParserNoDTDError                            NSXMLParserError = 94
	NSXMLParserDelegateAbortedParseError             NSXMLParserError = 512
)
