// Code generated by tools/bindgen. DO NOT EDIT.
//
// Source: MacOSX26.2.sdk (Xcode 26.2), target arm64-apple-macos26.0
// Frameworks: Foundation
//
// Regenerate with: tools/bindgen/regen.sh

//go:build darwin

package foundation

import "github.com/ebitengine/purego/objc"

// NSArray — NSOrderedCollectionDifference.h
// Copyright (c) 2017-2019, Apple Inc. All rights reserved.
// Only the identity crosses: no method of NSArray is on the allowlist.
type NSArray struct{ objc.ID }

// NSArrayClass is the class object of NSArray.
type NSArrayClass struct{ objc.Class }

// GetNSArrayClass looks the class up in the ObjC runtime.
func GetNSArrayClass() NSArrayClass { return NSArrayClass{objc.GetClass("NSArray")} }
