// Code generated by tools/bindgen. DO NOT EDIT.
//
// Source: MacOSX26.2.sdk (Xcode 26.2), target arm64-apple-macos26.0
// Frameworks: Foundation
//
// Regenerate with: tools/bindgen/regen.sh

//go:build darwin

package foundation

import (
	"github.com/adriaanm/wata/go-pkgs/appleptt/objcrt"
	"github.com/ebitengine/purego/objc"
)

// NSNotificationCenter wraps the ObjC class NSNotificationCenter (NSObject subclass).
type NSNotificationCenter struct{ objc.ID }

// NSNotificationCenterClass is the class object of NSNotificationCenter.
type NSNotificationCenterClass struct{ objc.Class }

// GetNSNotificationCenterClass looks the class up in the ObjC runtime.
func GetNSNotificationCenterClass() NSNotificationCenterClass {
	return NSNotificationCenterClass{objc.GetClass("NSNotificationCenter")}
}

// Alloc allocates an uninitialized NSNotificationCenter (-[NSObject alloc]).
func (c NSNotificationCenterClass) Alloc() NSNotificationCenter {
	return NSNotificationCenter{objc.ID(c.Class).Send(selAlloc)}
}

// DefaultCenter reads the NSNotificationCenter class property defaultCenter.
func (c NSNotificationCenterClass) DefaultCenter() NSNotificationCenter {
	return NSNotificationCenter{objc.ID(c.Class).Send(selDefaultCenter)}
}

// AddObserverSelectorNameObject calls -[NSNotificationCenter addObserver:selector:name:object:].
func (o NSNotificationCenter) AddObserverSelectorNameObject(observer objc.ID, aSelector objc.SEL, aName string, anObject objc.ID) {
	o.ID.Send(selAddObserverSelectorNameObject, observer, aSelector, objcrt.NSString(aName), anObject)
}

// AddObserverForNameObjectQueueUsingBlock calls -[NSNotificationCenter addObserverForName:object:queue:usingBlock:].
func (o NSNotificationCenter) AddObserverForNameObjectQueueUsingBlock(name string, obj objc.ID, queue NSOperationQueue, block func(NSNotification)) objc.ID {
	blockBlock := objc.NewBlock(func(_ objc.Block, a0 objc.ID) {
		block(NSNotification{a0})
	})
	defer blockBlock.Release()
	return o.ID.Send(selAddObserverForNameObjectQueueUsingBlock, objcrt.NSString(name), obj, queue.ID, blockBlock)
}

// PostNotification calls -[NSNotificationCenter postNotification:].
func (o NSNotificationCenter) PostNotification(notification NSNotification) {
	o.ID.Send(selPostNotification, notification.ID)
}

// PostNotificationNameObject calls -[NSNotificationCenter postNotificationName:object:].
func (o NSNotificationCenter) PostNotificationNameObject(aName string, anObject objc.ID) {
	o.ID.Send(selPostNotificationNameObject, objcrt.NSString(aName), anObject)
}

// PostNotificationNameObjectUserInfo calls -[NSNotificationCenter postNotificationName:object:userInfo:].
func (o NSNotificationCenter) PostNotificationNameObjectUserInfo(aName string, anObject objc.ID, aUserInfo NSDictionary) {
	o.ID.Send(selPostNotificationNameObjectUserInfo, objcrt.NSString(aName), anObject, aUserInfo.ID)
}

// RemoveObserver calls -[NSNotificationCenter removeObserver:].
func (o NSNotificationCenter) RemoveObserver(observer objc.ID) {
	o.ID.Send(selRemoveObserver, observer)
}

// RemoveObserverNameObject calls -[NSNotificationCenter removeObserver:name:object:].
func (o NSNotificationCenter) RemoveObserverNameObject(observer objc.ID, aName string, anObject objc.ID) {
	o.ID.Send(selRemoveObserverNameObject, observer, objcrt.NSString(aName), anObject)
}
