// Code generated by tools/bindgen. DO NOT EDIT.
//
// Source: MacOSX26.2.sdk (Xcode 26.2), target arm64-apple-macos26.0
// Frameworks: Foundation
//
// Regenerate with: tools/bindgen/regen.sh

//go:build darwin

package foundation

import (
	"github.com/adriaanm/wata/go-pkgs/appleptt/objcrt"
	"github.com/ebitengine/purego/objc"
)

// NSNotification — Notifications	***************
type NSNotification struct{ objc.ID }

// NSNotificationClass is the class object of NSNotification.
type NSNotificationClass struct{ objc.Class }

// GetNSNotificationClass looks the class up in the ObjC runtime.
func GetNSNotificationClass() NSNotificationClass {
	return NSNotificationClass{objc.GetClass("NSNotification")}
}

// Alloc allocates an uninitialized NSNotification (-[NSObject alloc]).
func (c NSNotificationClass) Alloc() NSNotification {
	return NSNotification{objc.ID(c.Class).Send(selAlloc)}
}

// Name reads the NSNotification property name.
func (o NSNotification) Name() string {
	return objcrt.GoString(o.ID.Send(selName))
}

// Object reads the NSNotification property object.
func (o NSNotification) Object() objc.ID {
	return o.ID.Send(selObject)
}

// UserInfo reads the NSNotification property userInfo.
func (o NSNotification) UserInfo() NSDictionary {
	return NSDictionary{o.ID.Send(selUserInfo)}
}

// Init calls -[NSNotification init].
func (o NSNotification) Init() NSNotification {
	return NSNotification{o.ID.Send(selInit)}
}

// InitWithNameObjectUserInfo calls -[NSNotification initWithName:object:userInfo:].
func (o NSNotification) InitWithNameObjectUserInfo(name string, object objc.ID, userInfo NSDictionary) NSNotification {
	return NSNotification{o.ID.Send(selInitWithNameObjectUserInfo, objcrt.NSString(name), object, userInfo.ID)}
}

// NotificationWithNameObject calls +[NSNotification notificationWithName:object:].
func (c NSNotificationClass) NotificationWithNameObject(aName string, anObject objc.ID) NSNotification {
	return NSNotification{objc.ID(c.Class).Send(selNotificationWithNameObject, objcrt.NSString(aName), anObject)}
}

// NotificationWithNameObjectUserInfo calls +[NSNotification notificationWithName:object:userInfo:].
func (c NSNotificationClass) NotificationWithNameObjectUserInfo(aName string, anObject objc.ID, aUserInfo NSDictionary) NSNotification {
	return NSNotification{objc.ID(c.Class).Send(selNotificationWithNameObjectUserInfo, objcrt.NSString(aName), anObject, aUserInfo.ID)}
}
