// Code generated by tools/bindgen. DO NOT EDIT.
//
// Source: MacOSX26.2.sdk (Xcode 26.2), target arm64-apple-macos26.0
// Frameworks: Foundation
//
// Regenerate with: tools/bindgen/regen.sh

//go:build darwin

package foundation

import "github.com/ebitengine/purego/objc"

// NSOperationQueue an opaque handle for the ObjC class NSOperationQueue (NSObject subclass).
// Only the identity crosses: no method of NSOperationQueue is on the allowlist.
type NSOperationQueue struct{ objc.ID }

// NSOperationQueueClass is the class object of NSOperationQueue.
type NSOperationQueueClass struct{ objc.Class }

// GetNSOperationQueueClass looks the class up in the ObjC runtime.
func GetNSOperationQueueClass() NSOperationQueueClass {
	return NSOperationQueueClass{objc.GetClass("NSOperationQueue")}
}
