// Code generated by tools/bindgen. DO NOT EDIT.
//
// Source: MacOSX26.2.sdk (Xcode 26.2), target arm64-apple-macos26.0
// Frameworks: Foundation
//
// Regenerate with: tools/bindgen/regen.sh

//go:build darwin

package foundation

import (
	"github.com/adriaanm/wata/go-pkgs/appleptt/objcrt"
	"github.com/ebitengine/purego/objc"
)

// NSProcessInfo wraps the ObjC class NSProcessInfo (NSObject subclass).
type NSProcessInfo struct{ objc.ID }

// NSProcessInfoClass is the class object of NSProcessInfo.
type NSProcessInfoClass struct{ objc.Class }

// GetNSProcessInfoClass looks the class up in the ObjC runtime.
func GetNSProcessInfoClass() NSProcessInfoClass {
	return NSProcessInfoClass{objc.GetClass("NSProcessInfo")}
}

// Alloc allocates an uninitialized NSProcessInfo (-[NSObject alloc]).
func (c NSProcessInfoClass) Alloc() NSProcessInfo {
	return NSProcessInfo{objc.ID(c.Class).Send(selAlloc)}
}

// ActiveProcessorCount reads the NSProcessInfo property activeProcessorCount.
func (o NSProcessInfo) ActiveProcessorCount() uint {
	return objc.Send[uint](o.ID, selActiveProcessorCount)
}

// Arguments reads the NSProcessInfo property arguments.
func (o NSProcessInfo) Arguments() NSArray {
	return NSArray{o.ID.Send(selArguments)}
}

// AutomaticTerminationSupportEnabled — Marks the calling app as supporting automatic termination. Without calling this or setting the equivalent Info.plist key (NSSupportsAutomaticTermination), the above methods (disableAutomaticTermination:/enableAutomaticTermination:) have no effect,
// although the counter tracking automatic termination opt-outs is still kept up to date to ensure correctness if this is called later. Currently, passing NO has no effect.
// This should be called during -applicationDidFinishLaunching or earlier.
func (o NSProcessInfo) AutomaticTerminationSupportEnabled() bool {
	return objc.Send[bool](o.ID, selAutomaticTerminationSupportEnabled)
}

// SetAutomaticTerminationSupportEnabled writes the NSProcessInfo property automaticTerminationSupportEnabled.
func (o NSProcessInfo) SetAutomaticTerminationSupportEnabled(v bool) {
	o.ID.Send(selSetAutomaticTerminationSupportEnabled, v)
}

// Environment reads the NSProcessInfo property environment.
func (o NSProcessInfo) Environment() NSDictionary {
	return NSDictionary{o.ID.Send(selEnvironment)}
}

// GloballyUniqueString reads the NSProcessInfo property globallyUniqueString.
func (o NSProcessInfo) GloballyUniqueString() string {
	return objcrt.GoString(o.ID.Send(selGloballyUniqueString))
}

// HostName reads the NSProcessInfo property hostName.
func (o NSProcessInfo) HostName() string {
	return objcrt.GoString(o.ID.Send(selHostName))
}

// IOSAppOnMac reads the NSProcessInfo property iOSAppOnMac.
func (o NSProcessInfo) IOSAppOnMac() bool {
	return objc.Send[bool](o.ID, selIsiOSAppOnMac)
}

// IOSAppOnVision reads the NSProcessInfo property iOSAppOnVision.
func (o NSProcessInfo) IOSAppOnVision() bool {
	return objc.Send[bool](o.ID, selIsiOSAppOnVision)
}

// LowPowerModeEnabled reads the NSProcessInfo property lowPowerModeEnabled.
func (o NSProcessInfo) LowPowerModeEnabled() bool {
	return objc.Send[bool](o.ID, selIsLowPowerModeEnabled)
}

// MacCatalystApp reads the NSProcessInfo property macCatalystApp.
func (o NSProcessInfo) MacCatalystApp() bool {
	return objc.Send[bool](o.ID, selIsMacCatalystApp)
}

// OperatingSystemVersion reads the NSProcessInfo property operatingSystemVersion.
func (o NSProcessInfo) OperatingSystemVersion() NSOperatingSystemVersion {
	return objc.Send[NSOperatingSystemVersion](o.ID, selOperatingSystemVersion)
}

// OperatingSystemVersionString — Human readable, localized; appropriate for displaying to user or using in bug emails and such; NOT appropriate for parsing
func (o NSProcessInfo) OperatingSystemVersionString() string {
	return objcrt.GoString(o.ID.Send(selOperatingSystemVersionString))
}

// PhysicalMemory reads the NSProcessInfo property physicalMemory.
func (o NSProcessInfo) PhysicalMemory() uint64 {
	return objc.Send[uint64](o.ID, selPhysicalMemory)
}

// ProcessIdentifier reads the NSProcessInfo property processIdentifier.
func (o NSProcessInfo) ProcessIdentifier() int32 {
	return objc.Send[int32](o.ID, selProcessIdentifier)
}

// ProcessName reads the NSProcessInfo property processName.
func (o NSProcessInfo) ProcessName() string {
	return objcrt.GoString(o.ID.Send(selProcessName))
}

// SetProcessName writes the NSProcessInfo property processName.
func (o NSProcessInfo) SetProcessName(v string) {
	o.ID.Send(selSetProcessName, objcrt.NSString(v))
}

// ProcessorCount reads the NSProcessInfo property processorCount.
func (o NSProcessInfo) ProcessorCount() uint {
	return objc.Send[uint](o.ID, selProcessorCount)
}

// SystemUptime reads the NSProcessInfo property systemUptime.
func (o NSProcessInfo) SystemUptime() float64 {
	return objc.Send[float64](o.ID, selSystemUptime)
}

// ProcessInfo reads the NSProcessInfo class property processInfo.
func (c NSProcessInfoClass) ProcessInfo() NSProcessInfo {
	return NSProcessInfo{objc.ID(c.Class).Send(selProcessInfo)}
}

// DisableAutomaticTermination — Increment or decrement the counter tracking the number of automatic quit opt-out requests. When this counter is greater than zero, the app will be considered 'active' and ineligible for automatic termination.
// An example of using this would be disabling autoquitting when the user of an instant messaging application signs on, due to it requiring a background connection to be maintained even if the app is otherwise inactive.
// Each pair of calls should have a matching "reason" argument, which can be used to easily track why an application is or is not automatically terminable.
// A given reason can be used more than once at the same time (for example: two files are transferring over the network, each one disables automatic termination with the reason @"file transfer in progress")
func (o NSProcessInfo) DisableAutomaticTermination(reason string) {
	o.ID.Send(selDisableAutomaticTermination, objcrt.NSString(reason))
}

// DisableSuddenTermination — Disable or reenable the ability to be quickly killed. The default implementations of these methods increment or decrement, respectively, a counter whose value is 1 when the process is first created. When the counter's value is 0 the application is considered to be safely killable and may be killed by the operating system without any notification or event being sent to the process first. If an application's Info.plist has an NSSupportsSuddenTermination entry whose value is true then NSApplication invokes -enableSuddenTermination automatically during application launch, which typically renders the process killable right away. You can also manually invoke -enableSuddenTermination right away in, for example, agents or daemons that don't depend on AppKit. After that, you can invoke these methods whenever the process has work it must do before it terminates. For example:
// - NSUserDefaults uses these to prevent process killing between the time at which a default has been set and the time at which the preferences file including that default has been written to disk.
// - NSDocument uses these to prevent process killing between the time at which the user has made a change to a document and the time at which the user's change has been written to disk.
// - You can use these whenever your application defers work that must be done before the application terminates. If for example your application ever defers writing something to disk, and it has an NSSupportsSuddenTermination entry in its Info.plist so as not to contribute to user-visible delays at logout or shutdown time, it must invoke -disableSuddenTermination when the writing is first deferred and -enableSuddenTermination after the writing is actually done.
func (o NSProcessInfo) DisableSuddenTermination() {
	o.ID.Send(selDisableSuddenTermination)
}

// EnableAutomaticTermination calls -[NSProcessInfo enableAutomaticTermination:].
func (o NSProcessInfo) EnableAutomaticTermination(reason string) {
	o.ID.Send(selEnableAutomaticTermination, objcrt.NSString(reason))
}

// EnableSuddenTermination calls -[NSProcessInfo enableSuddenTermination].
func (o NSProcessInfo) EnableSuddenTermination() {
	o.ID.Send(selEnableSuddenTermination)
}

// EndActivity calls -[NSProcessInfo endActivity:].
func (o NSProcessInfo) EndActivity(activity objc.ID) {
	o.ID.Send(selEndActivity, activity)
}

// IsOperatingSystemAtLeastVersion calls -[NSProcessInfo isOperatingSystemAtLeastVersion:].
func (o NSProcessInfo) IsOperatingSystemAtLeastVersion(version NSOperatingSystemVersion) bool {
	return objc.Send[bool](o.ID, selIsOperatingSystemAtLeastVersion, version)
}

// OperatingSystem calls -[NSProcessInfo operatingSystem].
func (o NSProcessInfo) OperatingSystem() uint {
	return objc.Send[uint](o.ID, selOperatingSystem)
}

// OperatingSystemName calls -[NSProcessInfo operatingSystemName].
func (o NSProcessInfo) OperatingSystemName() string {
	return objcrt.GoString(o.ID.Send(selOperatingSystemName))
}

// PerformExpiringActivityWithReasonUsingBlock calls -[NSProcessInfo performExpiringActivityWithReason:usingBlock:].
func (o NSProcessInfo) PerformExpiringActivityWithReasonUsingBlock(reason string, block func(bool)) {
	blockBlock := objc.NewBlock(func(_ objc.Block, a0 bool) {
		block(a0)
	})
	defer blockBlock.Release()
	o.ID.Send(selPerformExpiringActivityWithReasonUsingBlock, objcrt.NSString(reason), blockBlock)
}
