// Code generated by tools/bindgen. DO NOT EDIT.
//
// Source: MacOSX26.2.sdk (Xcode 26.2), target arm64-apple-macos26.0
// Frameworks: Foundation
//
// Regenerate with: tools/bindgen/regen.sh

//go:build darwin

package foundation

import "github.com/ebitengine/purego/objc"

// NSURL — NSURLHandle has been deprecated; please use NSURLConnection instead.
// Only the identity crosses: no method of NSURL is on the allowlist.
type NSURL struct{ objc.ID }

// NSURLClass is the class object of NSURL.
type NSURLClass struct{ objc.Class }

// GetNSURLClass looks the class up in the ObjC runtime.
func GetNSURLClass() NSURLClass { return NSURLClass{objc.GetClass("NSURL")} }
