// Code generated by tools/bindgen. DO NOT EDIT.
//
// Source: MacOSX26.2.sdk (Xcode 26.2), target arm64-apple-macos26.0
// Frameworks: Foundation
//
// Regenerate with: tools/bindgen/regen.sh

//go:build darwin

package foundation

import (
	"github.com/adriaanm/wata/go-pkgs/appleptt/objcrt"
	"github.com/ebitengine/purego/objc"
)

// NSURLSessionDataDelegate is the Go side of the ObjC protocol NSURLSessionDataDelegate.
//
// A nil field is not installed on the synthesized class, which is exactly
// ObjC's optional-method semantics: -respondsToSelector: answers NO for it.
type NSURLSessionDataDelegate struct {
	// Sent when data is available for the delegate to consume.  As the
	// data may be discontiguous, you should use
	// [NSData enumerateByteRangesUsingBlock:] to access it.
	// -[NSURLSessionDataDelegate URLSession:dataTask:didReceiveData:]
	URLSessionDataTaskDidReceiveData func(session NSURLSession, dataTask NSURLSessionDataTask, data NSData)
	// The task has received a response and no further messages will be
	// received until the completion block is called. The disposition
	// allows you to cancel a request or to turn a data task into a
	// download task. This delegate message is optional - if you do not
	// implement it, you can get the response as a property of the task.
	// This method will not be called for background upload tasks (which cannot be converted to download tasks).
	// -[NSURLSessionDataDelegate URLSession:dataTask:didReceiveResponse:completionHandler:]
	URLSessionDataTaskDidReceiveResponseCompletionHandler func(session NSURLSession, dataTask NSURLSessionDataTask, response NSURLResponse, completionHandler IncomingBlockNSURLSessionResponseDisposition)
}

// NewNSURLSessionDataDelegate synthesizes an ObjC object conforming to NSURLSessionDataDelegate
// that forwards to d's non-nil funcs. The object is retained forever: the
// ObjC runtime cannot unregister a class.
func NewNSURLSessionDataDelegate(d NSURLSessionDataDelegate) objc.ID {
	var ms []objcrt.Method
	if d.URLSessionDataTaskDidReceiveData != nil {
		ms = append(ms, objcrt.Method{
			Sel: "URLSession:dataTask:didReceiveData:",
			Fn: func(_ objc.ID, _ objc.SEL, a0 objc.ID, a1 objc.ID, a2 objc.ID) {
				d.URLSessionDataTaskDidReceiveData(NSURLSession{a0}, NSURLSessionDataTask{a1}, NSData{a2})
			},
		})
	}
	if d.URLSessionDataTaskDidReceiveResponseCompletionHandler != nil {
		ms = append(ms, objcrt.Method{
			Sel: "URLSession:dataTask:didReceiveResponse:completionHandler:",
			Fn: func(_ objc.ID, _ objc.SEL, a0 objc.ID, a1 objc.ID, a2 objc.ID, a3 objc.Block) {
				d.URLSessionDataTaskDidReceiveResponseCompletionHandler(NSURLSession{a0}, NSURLSessionDataTask{a1}, NSURLResponse{a2}, IncomingBlockNSURLSessionResponseDisposition{objcrt.CopyBlock(a3)})
			},
		})
	}
	return objcrt.NewDelegate("WataNSURLSessionDataDelegate", []string{"NSURLSessionDataDelegate"}, ms)
}
