// Code generated by tools/bindgen. DO NOT EDIT.
//
// Source: MacOSX26.2.sdk (Xcode 26.2), target arm64-apple-macos26.0
// Frameworks: Foundation
//
// Regenerate with: tools/bindgen/regen.sh

//go:build darwin

package foundation

import "github.com/ebitengine/purego/objc"

// NSURLResponse an opaque handle for the ObjC class NSURLResponse (NSObject subclass).
// Only the identity crosses: no method of NSURLResponse is on the allowlist.
type NSURLResponse struct{ objc.ID }

// NSURLResponseClass is the class object of NSURLResponse.
type NSURLResponseClass struct{ objc.Class }

// GetNSURLResponseClass looks the class up in the ObjC runtime.
func GetNSURLResponseClass() NSURLResponseClass {
	return NSURLResponseClass{objc.GetClass("NSURLResponse")}
}
