// Code generated by tools/bindgen. DO NOT EDIT.
//
// Source: MacOSX26.2.sdk (Xcode 26.2), target arm64-apple-macos26.0
// Frameworks: Foundation
//
// Regenerate with: tools/bindgen/regen.sh

//go:build darwin

package foundation

import "github.com/ebitengine/purego/objc"

// NSURLSessionConfiguration — WebSocket objects perform a WebSocket handshake with the server and can be used to send and receive WebSocket messages
// Only the identity crosses: no method of NSURLSessionConfiguration is on the allowlist.
type NSURLSessionConfiguration struct{ objc.ID }

// NSURLSessionConfigurationClass is the class object of NSURLSessionConfiguration.
type NSURLSessionConfigurationClass struct{ objc.Class }

// GetNSURLSessionConfigurationClass looks the class up in the ObjC runtime.
func GetNSURLSessionConfigurationClass() NSURLSessionConfigurationClass {
	return NSURLSessionConfigurationClass{objc.GetClass("NSURLSessionConfiguration")}
}
