// Code generated by tools/bindgen. DO NOT EDIT.
//
// Source: MacOSX26.2.sdk (Xcode 26.2), target arm64-apple-macos26.0
// Frameworks: Foundation
//
// Regenerate with: tools/bindgen/regen.sh

//go:build darwin

package foundation

import (
	"github.com/adriaanm/wata/go-pkgs/appleptt/objcrt"
	"github.com/ebitengine/purego/objc"
)

// NSXMLParserDelegate is the Go side of the ObjC protocol NSXMLParserDelegate.
//
// A nil field is not installed on the synthesized class, which is exactly
// ObjC's optional-method semantics: -respondsToSelector: answers NO for it.
type NSXMLParserDelegate struct {
	// -[NSXMLParserDelegate parser:didEndElement:namespaceURI:qualifiedName:]
	ParserDidEndElementNamespaceURIQualifiedName func(parser NSXMLParser, elementName string, namespaceURI string, qName string)
	// -[NSXMLParserDelegate parser:didEndMappingPrefix:]
	ParserDidEndMappingPrefix func(parser NSXMLParser, prefix string)
	// -[NSXMLParserDelegate parser:didStartElement:namespaceURI:qualifiedName:attributes:]
	ParserDidStartElementNamespaceURIQualifiedNameAttributes func(parser NSXMLParser, elementName string, namespaceURI string, qName string, attributeDict NSDictionary)
	// -[NSXMLParserDelegate parser:didStartMappingPrefix:toURI:]
	ParserDidStartMappingPrefixToURI func(parser NSXMLParser, prefix string, namespaceURI string)
	// -[NSXMLParserDelegate parser:foundAttributeDeclarationWithName:forElement:type:defaultValue:]
	ParserFoundAttributeDeclarationWithNameForElementTypeDefaultValue func(parser NSXMLParser, attributeName string, elementName string, type_ string, defaultValue string)
	// -[NSXMLParserDelegate parser:foundCDATA:]
	ParserFoundCDATA func(parser NSXMLParser, cDATABlock NSData)
	// -[NSXMLParserDelegate parser:foundCharacters:]
	ParserFoundCharacters func(parser NSXMLParser, string_ string)
	// -[NSXMLParserDelegate parser:foundComment:]
	ParserFoundComment func(parser NSXMLParser, comment string)
	// -[NSXMLParserDelegate parser:foundElementDeclarationWithName:model:]
	ParserFoundElementDeclarationWithNameModel func(parser NSXMLParser, elementName string, model string)
	// -[NSXMLParserDelegate parser:foundExternalEntityDeclarationWithName:publicID:systemID:]
	ParserFoundExternalEntityDeclarationWithNamePublicIDSystemID func(parser NSXMLParser, name string, publicID string, systemID string)
	// -[NSXMLParserDelegate parser:foundIgnorableWhitespace:]
	ParserFoundIgnorableWhitespace func(parser NSXMLParser, whitespaceString string)
	// -[NSXMLParserDelegate parser:foundInternalEntityDeclarationWithName:value:]
	ParserFoundInternalEntityDeclarationWithNameValue func(parser NSXMLParser, name string, value string)
	// -[NSXMLParserDelegate parser:foundNotationDeclarationWithName:publicID:systemID:]
	ParserFoundNotationDeclarationWithNamePublicIDSystemID func(parser NSXMLParser, name string, publicID string, systemID string)
	// -[NSXMLParserDelegate parser:foundProcessingInstructionWithTarget:data:]
	ParserFoundProcessingInstructionWithTargetData func(parser NSXMLParser, target string, data string)
	// -[NSXMLParserDelegate parser:foundUnparsedEntityDeclarationWithName:publicID:systemID:notationName:]
	ParserFoundUnparsedEntityDeclarationWithNamePublicIDSystemIDNotationName func(parser NSXMLParser, name string, publicID string, systemID string, notationName string)
	// -[NSXMLParserDelegate parser:parseErrorOccurred:]
	ParserParseErrorOccurred func(parser NSXMLParser, parseError error)
	// -[NSXMLParserDelegate parser:resolveExternalEntityName:systemID:]
	ParserResolveExternalEntityNameSystemID func(parser NSXMLParser, name string, systemID string) NSData
	// -[NSXMLParserDelegate parser:validationErrorOccurred:]
	ParserValidationErrorOccurred func(parser NSXMLParser, validationError error)
	// -[NSXMLParserDelegate parserDidEndDocument:]
	ParserDidEndDocument func(parser NSXMLParser)
	// -[NSXMLParserDelegate parserDidStartDocument:]
	ParserDidStartDocument func(parser NSXMLParser)
}

// NewNSXMLParserDelegate synthesizes an ObjC object conforming to NSXMLParserDelegate
// that forwards to d's non-nil funcs. The object is retained forever: the
// ObjC runtime cannot unregister a class.
func NewNSXMLParserDelegate(d NSXMLParserDelegate) objc.ID {
	var ms []objcrt.Method
	if d.ParserDidEndElementNamespaceURIQualifiedName != nil {
		ms = append(ms, objcrt.Method{
			Sel: "parser:didEndElement:namespaceURI:qualifiedName:",
			Fn: func(_ objc.ID, _ objc.SEL, a0 objc.ID, a1 objc.ID, a2 objc.ID, a3 objc.ID) {
				d.ParserDidEndElementNamespaceURIQualifiedName(NSXMLParser{a0}, objcrt.GoString(a1), objcrt.GoString(a2), objcrt.GoString(a3))
			},
		})
	}
	if d.ParserDidEndMappingPrefix != nil {
		ms = append(ms, objcrt.Method{
			Sel: "parser:didEndMappingPrefix:",
			Fn: func(_ objc.ID, _ objc.SEL, a0 objc.ID, a1 objc.ID) {
				d.ParserDidEndMappingPrefix(NSXMLParser{a0}, objcrt.GoString(a1))
			},
		})
	}
	if d.ParserDidStartElementNamespaceURIQualifiedNameAttributes != nil {
		ms = append(ms, objcrt.Method{
			Sel: "parser:didStartElement:namespaceURI:qualifiedName:attributes:",
			Fn: func(_ objc.ID, _ objc.SEL, a0 objc.ID, a1 objc.ID, a2 objc.ID, a3 objc.ID, a4 objc.ID) {
				d.ParserDidStartElementNamespaceURIQualifiedNameAttributes(NSXMLParser{a0}, objcrt.GoString(a1), objcrt.GoString(a2), objcrt.GoString(a3), NSDictionary{a4})
			},
		})
	}
	if d.ParserDidStartMappingPrefixToURI != nil {
		ms = append(ms, objcrt.Method{
			Sel: "parser:didStartMappingPrefix:toURI:",
			Fn: func(_ objc.ID, _ objc.SEL, a0 objc.ID, a1 objc.ID, a2 objc.ID) {
				d.ParserDidStartMappingPrefixToURI(NSXMLParser{a0}, objcrt.GoString(a1), objcrt.GoString(a2))
			},
		})
	}
	if d.ParserFoundAttributeDeclarationWithNameForElementTypeDefaultValue != nil {
		ms = append(ms, objcrt.Method{
			Sel: "parser:foundAttributeDeclarationWithName:forElement:type:defaultValue:",
			Fn: func(_ objc.ID, _ objc.SEL, a0 objc.ID, a1 objc.ID, a2 objc.ID, a3 objc.ID, a4 objc.ID) {
				d.ParserFoundAttributeDeclarationWithNameForElementTypeDefaultValue(NSXMLParser{a0}, objcrt.GoString(a1), objcrt.GoString(a2), objcrt.GoString(a3), objcrt.GoString(a4))
			},
		})
	}
	if d.ParserFoundCDATA != nil {
		ms = append(ms, objcrt.Method{
			Sel: "parser:foundCDATA:",
			Fn: func(_ objc.ID, _ objc.SEL, a0 objc.ID, a1 objc.ID) {
				d.ParserFoundCDATA(NSXMLParser{a0}, NSData{a1})
			},
		})
	}
	if d.ParserFoundCharacters != nil {
		ms = append(ms, objcrt.Method{
			Sel: "parser:foundCharacters:",
			Fn: func(_ objc.ID, _ objc.SEL, a0 objc.ID, a1 objc.ID) {
				d.ParserFoundCharacters(NSXMLParser{a0}, objcrt.GoString(a1))
			},
		})
	}
	if d.ParserFoundComment != nil {
		ms = append(ms, objcrt.Method{
			Sel: "parser:foundComment:",
			Fn: func(_ objc.ID, _ objc.SEL, a0 objc.ID, a1 objc.ID) {
				d.ParserFoundComment(NSXMLParser{a0}, objcrt.GoString(a1))
			},
		})
	}
	if d.ParserFoundElementDeclarationWithNameModel != nil {
		ms = append(ms, objcrt.Method{
			Sel: "parser:foundElementDeclarationWithName:model:",
			Fn: func(_ objc.ID, _ objc.SEL, a0 objc.ID, a1 objc.ID, a2 objc.ID) {
				d.ParserFoundElementDeclarationWithNameModel(NSXMLParser{a0}, objcrt.GoString(a1), objcrt.GoString(a2))
			},
		})
	}
	if d.ParserFoundExternalEntityDeclarationWithNamePublicIDSystemID != nil {
		ms = append(ms, objcrt.Method{
			Sel: "parser:foundExternalEntityDeclarationWithName:publicID:systemID:",
			Fn: func(_ objc.ID, _ objc.SEL, a0 objc.ID, a1 objc.ID, a2 objc.ID, a3 objc.ID) {
				d.ParserFoundExternalEntityDeclarationWithNamePublicIDSystemID(NSXMLParser{a0}, objcrt.GoString(a1), objcrt.GoString(a2), objcrt.GoString(a3))
			},
		})
	}
	if d.ParserFoundIgnorableWhitespace != nil {
		ms = append(ms, objcrt.Method{
			Sel: "parser:foundIgnorableWhitespace:",
			Fn: func(_ objc.ID, _ objc.SEL, a0 objc.ID, a1 objc.ID) {
				d.ParserFoundIgnorableWhitespace(NSXMLParser{a0}, objcrt.GoString(a1))
			},
		})
	}
	if d.ParserFoundInternalEntityDeclarationWithNameValue != nil {
		ms = append(ms, objcrt.Method{
			Sel: "parser:foundInternalEntityDeclarationWithName:value:",
			Fn: func(_ objc.ID, _ objc.SEL, a0 objc.ID, a1 objc.ID, a2 objc.ID) {
				d.ParserFoundInternalEntityDeclarationWithNameValue(NSXMLParser{a0}, objcrt.GoString(a1), objcrt.GoString(a2))
			},
		})
	}
	if d.ParserFoundNotationDeclarationWithNamePublicIDSystemID != nil {
		ms = append(ms, objcrt.Method{
			Sel: "parser:foundNotationDeclarationWithName:publicID:systemID:",
			Fn: func(_ objc.ID, _ objc.SEL, a0 objc.ID, a1 objc.ID, a2 objc.ID, a3 objc.ID) {
				d.ParserFoundNotationDeclarationWithNamePublicIDSystemID(NSXMLParser{a0}, objcrt.GoString(a1), objcrt.GoString(a2), objcrt.GoString(a3))
			},
		})
	}
	if d.ParserFoundProcessingInstructionWithTargetData != nil {
		ms = append(ms, objcrt.Method{
			Sel: "parser:foundProcessingInstructionWithTarget:data:",
			Fn: func(_ objc.ID, _ objc.SEL, a0 objc.ID, a1 objc.ID, a2 objc.ID) {
				d.ParserFoundProcessingInstructionWithTargetData(NSXMLParser{a0}, objcrt.GoString(a1), objcrt.GoString(a2))
			},
		})
	}
	if d.ParserFoundUnparsedEntityDeclarationWithNamePublicIDSystemIDNotationName != nil {
		ms = append(ms, objcrt.Method{
			Sel: "parser:foundUnparsedEntityDeclarationWithName:publicID:systemID:notationName:",
			Fn: func(_ objc.ID, _ objc.SEL, a0 objc.ID, a1 objc.ID, a2 objc.ID, a3 objc.ID, a4 objc.ID) {
				d.ParserFoundUnparsedEntityDeclarationWithNamePublicIDSystemIDNotationName(NSXMLParser{a0}, objcrt.GoString(a1), objcrt.GoString(a2), objcrt.GoString(a3), objcrt.GoString(a4))
			},
		})
	}
	if d.ParserParseErrorOccurred != nil {
		ms = append(ms, objcrt.Method{
			Sel: "parser:parseErrorOccurred:",
			Fn: func(_ objc.ID, _ objc.SEL, a0 objc.ID, a1 objc.ID) {
				d.ParserParseErrorOccurred(NSXMLParser{a0}, objcrt.GoError(a1))
			},
		})
	}
	if d.ParserResolveExternalEntityNameSystemID != nil {
		ms = append(ms, objcrt.Method{
			Sel: "parser:resolveExternalEntityName:systemID:",
			Fn: func(_ objc.ID, _ objc.SEL, a0 objc.ID, a1 objc.ID, a2 objc.ID) objc.ID {
				return d.ParserResolveExternalEntityNameSystemID(NSXMLParser{a0}, objcrt.GoString(a1), objcrt.GoString(a2)).ID
			},
		})
	}
	if d.ParserValidationErrorOccurred != nil {
		ms = append(ms, objcrt.Method{
			Sel: "parser:validationErrorOccurred:",
			Fn: func(_ objc.ID, _ objc.SEL, a0 objc.ID, a1 objc.ID) {
				d.ParserValidationErrorOccurred(NSXMLParser{a0}, objcrt.GoError(a1))
			},
		})
	}
	if d.ParserDidEndDocument != nil {
		ms = append(ms, objcrt.Method{
			Sel: "parserDidEndDocument:",
			Fn: func(_ objc.ID, _ objc.SEL, a0 objc.ID) {
				d.ParserDidEndDocument(NSXMLParser{a0})
			},
		})
	}
	if d.ParserDidStartDocument != nil {
		ms = append(ms, objcrt.Method{
			Sel: "parserDidStartDocument:",
			Fn: func(_ objc.ID, _ objc.SEL, a0 objc.ID) {
				d.ParserDidStartDocument(NSXMLParser{a0})
			},
		})
	}
	return objcrt.NewDelegate("WataNSXMLParserDelegate", []string{"NSXMLParserDelegate"}, ms)
}
