// Code generated by tools/bindgen. DO NOT EDIT.
//
// Source: MacOSX26.2.sdk (Xcode 26.2), target arm64-apple-macos26.0
// Frameworks: Foundation
//
// Regenerate with: tools/bindgen/regen.sh

//go:build darwin

package foundation

// NSOperatingSystemVersion is the C struct NSOperatingSystemVersion (struct NSOperatingSystemVersion), by value.
type NSOperatingSystemVersion struct {
	MajorVersion int
	MinorVersion int
	PatchVersion int
}

// NSRange is the C struct NSRange (struct _NSRange), by value.
type NSRange struct {
	Location uint
	Length   uint
}
