// Code generated by tools/bindgen. DO NOT EDIT.
//
// Source: tools/bindgen/fixtures
//
// Regenerate with: tools/bindgen/regen.sh

//go:build darwin

package fixture

import (
	"github.com/adriaanm/wata/go-pkgs/appleptt/objcrt"
	"github.com/ebitengine/purego/objc"
)

// WFStore wraps the ObjC class WFStore (NSObject subclass).
type WFStore struct{ objc.ID }

// WFStoreClass is the class object of WFStore.
type WFStoreClass struct{ objc.Class }

// GetWFStoreClass looks the class up in the ObjC runtime.
func GetWFStoreClass() WFStoreClass { return WFStoreClass{objc.GetClass("WFStore")} }

// Alloc allocates an uninitialized WFStore (-[NSObject alloc]).
func (c WFStoreClass) Alloc() WFStore { return WFStore{objc.ID(c.Class).Send(selAlloc)} }

// ReportError — An NSError * parameter is an ordinary Go error, not an out-parameter.
func (o WFStore) ReportError(error_ error) {
	o.ID.Send(selReportError, objcrt.NSErrorID(error_))
}

// SyncWithError calls -[WFStore syncWithError:].
func (o WFStore) SyncWithError() error {
	var errOut objcrt.ErrOut
	o.ID.Send(selSyncWithError, errOut.Ptr())
	return errOut.Err()
}

// WriteToPathError — Writes, or reports why it could not.
func (o WFStore) WriteToPathError(path string) (bool, error) {
	var errOut objcrt.ErrOut
	ret := objc.Send[bool](o.ID, selWriteToPathError, objcrt.NSString(path), errOut.Ptr())
	return ret, errOut.Err()
}

// LoadFromPathError calls +[WFStore loadFromPath:error:].
func (c WFStoreClass) LoadFromPathError(path string) (WFStore, error) {
	var errOut objcrt.ErrOut
	ret := objc.ID(c.Class).Send(selLoadFromPathError, objcrt.NSString(path), errOut.Ptr())
	return WFStore{ret}, errOut.Err()
}
